import { Banknote, CalendarDays, ChevronDown, FileText, History, Landmark, LoaderCircle, MessageSquarePlus, Search, Settings2, UserRound } from 'lucide-react';
import { type FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ApiError } from '../../../../services/api/client';
import { activityFieldLabel, activityValueLabel } from '../../expedienteFormatters';
import { expedientesService } from '../../expedientes.service';
import type { ExpedienteActivityCategory, ExpedienteActivityItem, ExpedienteDetail } from '../../expedientes.types';
import styles from './ActivityTab.module.css';

const categoryOptions: Array<{ value: ExpedienteActivityCategory; label: string }> = [
  { value: 'TODO', label: 'Todo' }, { value: 'OPERACION', label: 'Operación' }, { value: 'DOCUMENTOS', label: 'Documentos' }, { value: 'FINANZAS', label: 'Finanzas' }, { value: 'SISTEMA', label: 'Sistema' },
];
const sectionLabels: Record<ExpedienteActivityItem['related_section'], string> = { resumen: 'Resumen', actos: 'Actos', comparecientes: 'Comparecientes', predios: 'Predios / Inmuebles', documentos: 'Documentos', seguimiento: 'Seguimiento', plantillas: 'Plantillas y formatos', presupuesto: 'Presupuesto', finanzas: 'Finanzas', isr: 'Cálculo ISR', cumplimiento: 'Cumplimiento', actividad: 'Actividad' };
const categoryLabels = { OPERACION: 'Operación', DOCUMENTOS: 'Documentos', FINANZAS: 'Finanzas', SISTEMA: 'Sistema' } as const;
const dayKey = (value: string) => new Date(value).toLocaleDateString('en-CA', { timeZone: 'America/Mexico_City' });
const dayLabel = (value: string) => { const date = new Date(value); const today = dayKey(new Date().toISOString()); const yesterdayDate = new Date(); yesterdayDate.setDate(yesterdayDate.getDate() - 1); const yesterday = dayKey(yesterdayDate.toISOString()); const key = dayKey(value); if (key === today) return 'Hoy'; if (key === yesterday) return 'Ayer'; return new Intl.DateTimeFormat('es-MX', { weekday: 'long', day: 'numeric', month: 'long', year: date.getFullYear() === new Date().getFullYear() ? undefined : 'numeric', timeZone: 'America/Mexico_City' }).format(date); };
const time = (value: string) => new Intl.DateTimeFormat('es-MX', { hour: '2-digit', minute: '2-digit', timeZone: 'America/Mexico_City' }).format(new Date(value));
const dateTime = (value: string) => new Intl.DateTimeFormat('es-MX', { dateStyle: 'long', timeStyle: 'short', timeZone: 'America/Mexico_City' }).format(new Date(value));
const actorName = (item: ExpedienteActivityItem) => `${item.actor.nombre} ${item.actor.apellido}`.trim();
const displayValue = (value: unknown) => value === null || value === undefined || value === '' ? 'Sin dato' : typeof value === 'boolean' ? value ? 'Sí' : 'No' : typeof value === 'object' ? 'Información actualizada' : typeof value === 'string' ? activityValueLabel(value) : String(value);
const fixtureItems: ExpedienteActivityItem[] = [
  { id: 'exp009-event-1', type: 'CAMBIO_ESTATUS', category: 'OPERACION', title: 'Firma registrada', description: 'La firma del instrumento quedó confirmada.', occurred_at: '2026-08-29T18:00:00.000Z', actor: { id: 'fixture-user', nombre: 'Andrea', apellido: 'Ruiz' }, manual_note: false, previous_values: { estado: 'EN_PROCESO' }, new_values: { estado: 'FIRMADO' }, related_section: 'seguimiento', related_entity: 'Expediente', related_entity_id: null },
  { id: 'exp009-event-2', type: 'DOCUMENTO', category: 'DOCUMENTOS', title: 'Proyecto de escritura sustituido', description: 'Se incorporó una versión vigente conservando el documento anterior.', occurred_at: '2026-08-29T16:35:00.000Z', actor: { id: 'fixture-user', nombre: 'Andrea', apellido: 'Ruiz' }, manual_note: false, previous_values: null, new_values: null, related_section: 'documentos', related_entity: 'ExpedienteDocumento', related_entity_id: null },
  { id: 'exp009-event-3', type: 'PAGO', category: 'FINANZAS', title: 'Ingreso aplicado al expediente', description: 'El anticipo fue validado y aplicado al saldo del presupuesto.', occurred_at: '2026-08-28T20:10:00.000Z', actor: { id: 'fixture-admin', nombre: 'Elena', apellido: 'Vázquez' }, manual_note: false, previous_values: { estado: 'PENDIENTE' }, new_values: { estado: 'APLICADO' }, related_section: 'finanzas', related_entity: 'ExpedienteIngresoReportado', related_entity_id: null },
  { id: 'exp009-event-4', type: 'COMPARECIENTE', category: 'OPERACION', title: 'Compareciente vinculado', description: 'Se agregó la parte compradora al acto de compraventa.', occurred_at: '2026-08-27T19:45:00.000Z', actor: { id: 'fixture-user', nombre: 'Andrea', apellido: 'Ruiz' }, manual_note: false, previous_values: null, new_values: null, related_section: 'comparecientes', related_entity: 'ExpedienteCompareciente', related_entity_id: null },
  { id: 'exp009-event-5', type: 'AUDITORIA', category: 'SISTEMA', title: 'Expediente creado desde cotización', description: 'La cotización aceptada originó este expediente.', occurred_at: '2026-08-26T15:20:00.000Z', actor: { id: 'fixture-admin', nombre: 'Elena', apellido: 'Vázquez' }, manual_note: false, previous_values: null, new_values: null, related_section: 'resumen', related_entity: 'Expediente', related_entity_id: null },
];

function ActivityIcon({ item }: { item: ExpedienteActivityItem }) {
  if (item.manual_note) return <MessageSquarePlus />;
  if (item.category === 'DOCUMENTOS') return <FileText />;
  if (item.category === 'FINANZAS') return <Banknote />;
  if (item.category === 'SISTEMA') return <Settings2 />;
  return <History />;
}

export function ActivityTab({ expediente, fixture = false }: { expediente: ExpedienteDetail; fixture?: boolean }) {
  const navigate = useNavigate();
  const [items, setItems] = useState<ExpedienteActivityItem[]>([]); const [cursor, setCursor] = useState<string | null>(null);
  const [category, setCategory] = useState<ExpedienteActivityCategory>('TODO'); const [searchDraft, setSearchDraft] = useState(''); const [search, setSearch] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState('');
  const [selected, setSelected] = useState<string | null>(null); const [note, setNote] = useState(''); const [status, setStatus] = useState<'loading' | 'ready' | 'more' | 'saving'>('loading'); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = useCallback(async (nextCursor: string | null, append: boolean, signal?: AbortSignal) => {
    setStatus(append ? 'more' : 'loading'); setError('');
    try { const response = fixture ? { data: fixtureItems.filter((item) => (category === 'TODO' || item.category === category) && (!search || `${item.title} ${item.description}`.toLocaleLowerCase('es-MX').includes(search.toLocaleLowerCase('es-MX'))) && (!from || item.occurred_at.slice(0, 10) >= from) && (!to || item.occurred_at.slice(0, 10) <= to)), next_cursor: null } : await expedientesService.activity(expediente.id, { category, search, from, to, cursor: nextCursor, limit: 30 }, signal); setItems((current) => append ? [...current, ...response.data] : response.data); setCursor(response.next_cursor); if (!append) setSelected(response.data[0]?.id || null); setStatus('ready'); }
    catch (caught) { if (!(caught instanceof DOMException && caught.name === 'AbortError')) { setStatus('ready'); setError(caught instanceof ApiError ? caught.message : 'No pudimos cargar la actividad.'); } }
  }, [category, expediente.id, fixture, from, search, to]);
  useEffect(() => { const controller = new AbortController(); void load(null, false, controller.signal); return () => controller.abort(); }, [load]);
  const selectedItem = items.find((item) => item.id === selected) || null;
  const groups = useMemo(() => { const map = new Map<string, ExpedienteActivityItem[]>(); items.forEach((item) => { const key = dayKey(item.occurred_at); map.set(key, [...(map.get(key) || []), item]); }); return [...map.entries()].map(([key, entries]) => ({ key, label: dayLabel(entries[0].occurred_at), entries })); }, [items]);
  const applyFilters = (event: FormEvent) => { event.preventDefault(); setSearch(searchDraft.trim()); };
  const addNote = async (event: FormEvent) => { event.preventDefault(); const value = note.trim(); if (!value) return; setStatus('saving'); setError(''); setNotice(''); try { const result = fixture ? { item: { ...fixtureItems[0], id: crypto.randomUUID(), type: 'NOTA', title: 'Nota operativa', description: value, occurred_at: new Date().toISOString(), manual_note: true, previous_values: null, new_values: null, related_section: 'actividad' as const }, idempotent: false } : await expedientesService.addActivityNote(expediente.id, value, crypto.randomUUID()); setNote(''); setNotice(result.idempotent ? 'La nota ya estaba registrada.' : 'Nota agregada a la actividad.'); setItems((current) => [result.item, ...current.filter((item) => item.id !== result.item.id)]); setSelected(result.item.id); setStatus('ready'); } catch (caught) { setStatus('ready'); setError(caught instanceof ApiError ? caught.message : 'No pudimos guardar la nota.'); } };

  return <section className={styles.activity} aria-labelledby="exp009-title">
    <header className={styles.heading}><div><span>EXP-009</span><h2 id="exp009-title">Actividad del expediente</h2><p>Historia operativa relevante: qué ocurrió, cuándo y quién lo realizó.</p></div><div className={styles.separation}><Landmark /><span>Seguimiento muestra lo pendiente.<br />Actividad conserva lo ocurrido.</span></div></header>
    <form className={styles.filters} onSubmit={applyFilters} aria-label="Filtros de actividad"><label className={styles.search}><span className={styles.srOnly}>Buscar en actividad</span><Search /><input value={searchDraft} onChange={(event) => setSearchDraft(event.target.value)} placeholder="Buscar en actividad" maxLength={120} /><button type="submit">Buscar</button></label><div className={styles.categoryFilters} role="group" aria-label="Categoría">{categoryOptions.map((option) => <button key={option.value} type="button" aria-pressed={category === option.value} onClick={() => setCategory(option.value)}>{option.label}</button>)}</div><div className={styles.dateFilters}><label><span>Desde</span><input type="date" value={from} max={to || undefined} onChange={(event) => setFrom(event.target.value)} /></label><label><span>Hasta</span><input type="date" value={to} min={from || undefined} onChange={(event) => setTo(event.target.value)} /></label></div></form>
    {expediente.capabilities.canWrite && <form className={styles.noteComposer} onSubmit={addNote}><div><MessageSquarePlus /><span><strong>Agregar nota</strong><small>Se registrará con tu nombre y fecha. No crea tareas ni modifica Seguimiento.</small></span></div><textarea aria-label="Nota para la actividad" value={note} onChange={(event) => setNote(event.target.value)} maxLength={2000} rows={3} placeholder="Escribe una observación operativa relevante…" /><footer><span>{note.length}/2000</span><button type="submit" disabled={!note.trim() || status === 'saving'}>{status === 'saving' ? <LoaderCircle className={styles.spin} /> : <MessageSquarePlus />}Guardar nota</button></footer></form>}
    {error && <div className={styles.error} role="alert">{error}<button type="button" onClick={() => void load(null, false)}>Reintentar</button></div>}{notice && <div className={styles.notice} role="status">{notice}</div>}
    <div className={styles.content}><div className={styles.timeline} aria-busy={status === 'loading'}>{status === 'loading' ? <div className={styles.loading} role="status"><LoaderCircle className={styles.spin} />Cargando actividad…</div> : groups.length ? groups.map((group) => <section key={group.key} className={styles.dayGroup} aria-labelledby={`activity-day-${group.key}`}><h3 id={`activity-day-${group.key}`}>{group.label}</h3><ol>{group.entries.map((item) => <li key={item.id}><time dateTime={item.occurred_at}>{time(item.occurred_at)}</time><button type="button" className={selected === item.id ? styles.eventSelected : styles.event} aria-expanded={selected === item.id} aria-controls="activity-detail" onClick={() => setSelected(item.id)}><span className={styles.eventIcon} data-category={item.category}><ActivityIcon item={item} /></span><span className={styles.eventCopy}><span><strong>{item.title}</strong><em>{categoryLabels[item.category]}</em></span><small>{item.description}</small><span className={styles.actor}><UserRound />{actorName(item)}</span></span><ChevronDown className={styles.eventChevron} /></button></li>)}</ol></section>) : <div className={styles.empty}><History /><strong>No hay actividad para estos filtros.</strong><span>Prueba otra categoría o rango de fechas.</span></div>}{cursor && <button type="button" className={styles.loadMore} disabled={status === 'more'} onClick={() => void load(cursor, true)}>{status === 'more' && <LoaderCircle className={styles.spin} />}Cargar más</button>}</div>
      <aside id="activity-detail" className={styles.detail} aria-live="polite">{selectedItem ? <><header><span className={styles.eventIcon} data-category={selectedItem.category}><ActivityIcon item={selectedItem} /></span><div><small>{categoryLabels[selectedItem.category]}</small><h3>{selectedItem.title}</h3></div></header><p>{selectedItem.description}</p><dl className={styles.facts}><div><dt>Cuándo</dt><dd><CalendarDays />{dateTime(selectedItem.occurred_at)}</dd></div><div><dt>Quién</dt><dd><UserRound />{actorName(selectedItem)}</dd></div></dl><ChangeDetails item={selectedItem} />{selectedItem.related_section !== 'actividad' && <button type="button" className={styles.related} onClick={() => navigate({ hash: selectedItem.related_section })}>Abrir {sectionLabels[selectedItem.related_section]}<span aria-hidden="true">→</span></button>}</> : <div className={styles.detailEmpty}><History /><span>Selecciona un evento para ver su detalle.</span></div>}</aside>
    </div>
  </section>;
}

function ChangeDetails({ item }: { item: ExpedienteActivityItem }) {
  const keys = [...new Set([...Object.keys(item.previous_values || {}), ...Object.keys(item.new_values || {})])];
  if (!keys.length) return null;
  return <section className={styles.changes}><h4>Cambios</h4>{keys.map((key) => <div key={key}><span>{activityFieldLabel(key)}</span><p><del>{displayValue(item.previous_values?.[key])}</del><b aria-hidden="true">→</b><ins>{displayValue(item.new_values?.[key])}</ins></p></div>)}</section>;
}
