import { ArrowDownLeft, ArrowUpRight, Bot, BriefcaseBusiness, CheckCircle2, FileCheck2, FileText, FileWarning, HandCoins, Landmark, Plus, ReceiptText, Upload, WalletCards, X } from 'lucide-react';
import { FormEvent, useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { MovementDetail } from '../../../finance/components/MovementDetail';
import { NewMovementFlow } from '../../../finance/components/NewMovementFlow';
import { financeService } from '../../../finance/finance.service';
import type { FinanceCatalogs, FinanceMovement } from '../../../finance/finance.types';
import { financeDate, statusLabel } from '../../../finance/finance.utils';
import { expedienteFinanceService, type Exp008AIProposal, type Exp008Data, type Exp008Income, type Exp008Request } from '../../expedienteFinance.service';
import type { ExpedienteDetail } from '../../expedientes.types';
import styles from '../../Expedientes.module.css';

type Props = { expediente: ExpedienteDetail; onChanged(): void };
type Panel = 'income'|'request'|'review'|'apply'|'pay'|null;
const money = (value: unknown) => new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(value||0));
const date = (value?:string|null) => value ? new Intl.DateTimeFormat('es-MX',{dateStyle:'medium'}).format(new Date(value)) : '—';
const key = () => crypto.randomUUID();

export function FinanceTab({ expediente, onChanged }: Props) {
  const [data,setData]=useState<Exp008Data|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [notice,setNotice]=useState('');
  const [panel,setPanel]=useState<Panel>(null); const [selectedIncome,setSelectedIncome]=useState<Exp008Income|null>(null); const [selectedRequest,setSelectedRequest]=useState<Exp008Request|null>(null); const [busy,setBusy]=useState(false);
  const [proposal,setProposal]=useState<Exp008AIProposal|null>(null);
  const [catalogs,setCatalogs]=useState<FinanceCatalogs|null>(null); const [createOpen,setCreateOpen]=useState(false); const [selectedMovement,setSelectedMovement]=useState<FinanceMovement|null>(null);
  const drawerRef=useRef<HTMLElement|null>(null);
  const load=()=>{setLoading(true);setError('');const c=new AbortController();expedienteFinanceService.read(expediente.id,c.signal).then(setData).catch(()=>{if(!c.signal.aborted)setError('No pudimos cargar las finanzas del expediente.');}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();};
  useEffect(load,[expediente.id]);
  useEffect(()=>{if(!expediente.capabilities.canWriteFinance)return;const c=new AbortController();financeService.catalogs(c.signal).then(setCatalogs).catch(()=>undefined);return()=>c.abort();},[expediente.capabilities.canWriteFinance]);
  useEffect(()=>{if(!panel)return;const previous=document.activeElement instanceof HTMLElement?document.activeElement:null;const drawer=drawerRef.current;const focusable=()=>Array.from(drawer?.querySelectorAll<HTMLElement>('button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [href], [tabindex]:not([tabindex="-1"])')||[]);focusable()[0]?.focus();const onKeyDown=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();setPanel(null);return;}if(event.key!=='Tab')return;const items=focusable();if(!items.length)return;const first=items[0];const last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}};document.addEventListener('keydown',onKeyDown);return()=>{document.removeEventListener('keydown',onKeyDown);previous?.focus();};},[panel]);
  const operationalSummary=useMemo(()=>{const incomes=data?.ingresosReportados||[];const requests=data?.solicitudesPago||[];return{income:incomes.filter(x=>x.estado==='APLICADO').reduce((sum,x)=>sum+Number(x.monto_validado||0),0),pendingIncome:incomes.filter(x=>x.estado==='PENDIENTE_APLICACION').length,expenses:requests.filter(x=>x.estado==='PAGADA').reduce((sum,x)=>sum+Number(x.importe),0),pendingRequests:requests.filter(x=>x.estado==='PENDIENTE').length};},[data]);
  const canonicalSummary=expediente.financialSummary||{ingresos_recibidos:0,honorarios_generados:0,honorarios_cobrados:0,honorarios_por_cobrar:0,fondos_terceros:0,otros_destinos:0,fondos_terceros_pendientes:0,egresos:0};
  const movements=(expediente.movimientosFinancieros||[]) as FinanceMovement[];
  const done=(message:string)=>{setNotice(message);setPanel(null);setSelectedIncome(null);setSelectedRequest(null);setProposal(null);load();onChanged();};
  const submit=async(action:()=>Promise<unknown>,message:string)=>{setBusy(true);setError('');try{await action();done(message);}catch(e:any){setError(e?.message||'No pudimos completar la operación.');}finally{setBusy(false);}};
  const analyze=async(action:()=>Promise<{item:Exp008AIProposal}>)=>{setBusy(true);setError('');try{const result=await action();setProposal(result.item);setPanel('review');}catch(e:any){setError(e?.message||'No pudimos analizar el documento.');}finally{setBusy(false);}};
  if(loading)return <div className={styles.caseFinanceLoading} role="status">Cargando finanzas del expediente…</div>;
  if(!data)return <p className={styles.sectionError} role="alert">{error||'Las finanzas no están disponibles.'}</p>;
  return <div className={styles.tabStack}>
    <section className={styles.caseFinanceMetrics} aria-label="Resumen financiero del expediente">
      <article data-tone="gold"><span><BriefcaseBusiness/></span><small>Honorarios generados</small><strong>{money(canonicalSummary.honorarios_generados)}</strong></article>
      <article data-tone="green"><span><ArrowDownLeft/></span><small>Honorarios cobrados</small><strong>{money(canonicalSummary.honorarios_cobrados)}</strong></article>
      <article data-tone="orange"><span><HandCoins/></span><small>Por cobrar</small><strong>{money(canonicalSummary.honorarios_por_cobrar)}</strong></article>
      <article><span><Landmark/></span><small>Recursos no propios</small><strong>{money(canonicalSummary.fondos_terceros)}</strong></article>
      <article data-tone="orange"><span><ReceiptText/></span><small>Por aplicar</small><strong>{operationalSummary.pendingIncome}</strong></article>
      <article data-tone="red"><span><ArrowUpRight/></span><small>Egresos registrados</small><strong>{money(operationalSummary.expenses)}</strong></article>
      <article><span><HandCoins/></span><small>Solicitudes pendientes</small><strong>{operationalSummary.pendingRequests}</strong></article>
      <article data-tone="gold"><span><WalletCards/></span><small>Presupuesto vigente</small><strong>{money(data.presupuesto?.total)}</strong></article>
    </section>
    {notice&&<div className={styles.caseFinanceSuccess} role="status"><CheckCircle2/> {notice}</div>}{error&&<p className={styles.sectionError} role="alert">{error}</p>}
    {(data.capabilities.canReport||data.capabilities.canCreateRequest)&&<section className={styles.caseFinanceActions} aria-label="Acciones financieras"><div><strong>Operación interna</strong><span>Reporta evidencia o crea una solicitud sin alterar el ledger.</span></div>{data.capabilities.canReport&&<button className={styles.secondaryButton} onClick={()=>setPanel('income')}><Upload size={16}/>Reportar ingreso</button>}{data.capabilities.canCreateRequest&&<button className={styles.primaryButton} onClick={()=>setPanel('request')}><Plus size={16}/>Solicitar pago</button>}</section>}
    <section className={styles.sectionCard}><header><div><h2>Anticipos e ingresos</h2><p>La carga queda pendiente hasta que Administración revise y aplique.</p></div></header>
      <div className={styles.caseFinanceOperationalList}>{data.ingresosReportados.length?data.ingresosReportados.map(item=><IncomeRow key={item.id} item={item} canApply={data.capabilities.canApply} canAI={data.capabilities.canUseAI} onOpenDocument={(linkId)=>void expedienteFinanceService.openDocument(expediente.id,linkId)} onAI={()=>void analyze(async()=>{const link=item.documentos[0];if(!link)throw new Error('No hay evidencia disponible.');setSelectedIncome(item);setSelectedRequest(null);return expedienteFinanceService.proposeAI(expediente.id,{documento_id:link.documento.id,ingreso_reportado_id:item.id,operation_id:key()});})} onApply={()=>{setSelectedIncome(item);setPanel('apply');}}/>):<Empty icon={<ReceiptText/>} text="No hay comprobantes reportados."/>}</div>
    </section>
    <section className={styles.sectionCard}><header><div><h2>Solicitudes de pago</h2><p>La ficha origen, el comprobante de pago y el documento fiscal conservan roles distintos.</p></div></header>
      <div className={styles.caseFinanceOperationalList}>{data.solicitudesPago.length?data.solicitudesPago.map(item=><RequestRow key={item.id} item={item} canApply={data.capabilities.canApply} canAI={data.capabilities.canUseAI} onOpenDocument={(linkId)=>void expedienteFinanceService.openDocument(expediente.id,linkId)} onAI={()=>void analyze(async()=>{const link=item.documentos.find(x=>x.tipo==='SOLICITUD_ORIGEN');if(!link)throw new Error('Esta solicitud no tiene ficha externa para analizar.');setSelectedRequest(item);setSelectedIncome(null);return expedienteFinanceService.proposeAI(expediente.id,{documento_id:link.documento.id,solicitud_pago_id:item.id,operation_id:key()});})} onPay={()=>{setSelectedRequest(item);setPanel('pay');}} onReceipt={()=>item.movimiento_id&&void submit(()=>expedienteFinanceService.generateReceipt(expediente.id,item.movimiento_id!),'Comprobante PRAVIA generado y vinculado.')}/>):<Empty icon={<FileText/>} text="No hay solicitudes de pago."/>}</div>
    </section>
    <section className={styles.sectionCard}><header className={styles.caseFinanceHeader}><div><h2>Movimientos del expediente</h2><p>Una sola fuente de verdad, compartida con Finanzas central.</p></div>{expediente.capabilities.canWriteFinance&&<button type="button" className={styles.primaryButton} disabled={!catalogs} onClick={()=>setCreateOpen(true)}><Plus size={16}/>Registrar movimiento</button>}</header>{movements.length?<div className={styles.caseMovementList}>{movements.map(item=>{const evidence=item.movimientoDocumentos||[];return <button type="button" key={item.id} onClick={()=>setSelectedMovement(item)}><span className={item.naturaleza==='INGRESO'?styles.income:styles.expense}>{item.naturaleza==='INGRESO'?<ArrowDownLeft/>:<ArrowUpRight/>}</span><div><strong>{item.concepto}</strong><small>{financeDate(item.fecha_movimiento)} · {statusLabel(item.estatus)}</small></div><span className={evidence.length?styles.caseReceiptOk:styles.caseReceiptMissing}>{evidence.length?<FileCheck2/>:<FileWarning/>}{evidence.length?'Con comprobante':'Sin comprobante'}</span><b>{money(item.monto)}</b></button>;})}</div>:<Empty icon={<WalletCards/>} text="No hay movimientos aplicados en este expediente."/>}</section>
    {expediente.capabilities.canReadFinance&&<section className={styles.caseFinanceLedgerNote}><FileCheck2/><div><strong>Ledger canónico conectado</strong><span>Los ingresos aplicados y egresos pagados aparecen también en Finanzas central. No se concilian automáticamente.</span></div></section>}
    {panel&&<div className={styles.caseFinanceOverlay} role="presentation"><section ref={drawerRef} className={styles.caseFinanceDrawer} role="dialog" aria-modal="true" aria-labelledby="exp008-dialog-title"><header><div><small>EXP-008</small><h2 id="exp008-dialog-title">{panel==='income'?'Reportar ingreso':panel==='request'?'Nueva solicitud de pago':panel==='review'?'Revisar propuesta de IA':panel==='apply'?'Aplicar ingreso':'Registrar pago'}</h2></div><button type="button" aria-label="Cerrar" onClick={()=>setPanel(null)}><X/></button></header>{panel==='income'&&<IncomeForm busy={busy} onSubmit={(values,file)=>void submit(()=>expedienteFinanceService.reportIncome(expediente.id,{...values,idempotency_key:key()},file),'Comprobante reportado; pendiente de aplicación.')}/>} {panel==='request'&&<RequestForm busy={busy} onSubmit={(values,file)=>void submit(()=>file?expedienteFinanceService.createExternalRequest(expediente.id,{...values,idempotency_key:key()},file):expedienteFinanceService.createInternalRequest(expediente.id,{...values,idempotency_key:key()}),'Solicitud creada y pendiente de pago.')}/>} {panel==='review'&&proposal&&<AIReviewForm busy={busy} proposal={proposal} onSubmit={(decision,accepted_fields)=>void submit(()=>expedienteFinanceService.validateAI(expediente.id,proposal.id,{decision,accepted_fields}),decision==='REJECT'?'Propuesta rechazada; no se modificó el registro.':'Propuesta validada por una persona; aún no se aplicó ningún movimiento.')}/>} {panel==='apply'&&selectedIncome&&<ApplyForm busy={busy} data={data} item={selectedIncome} onSubmit={(values)=>void submit(()=>expedienteFinanceService.applyIncome(expediente.id,selectedIncome.id,{...values,idempotency_key:key()}),'Ingreso aplicado al ledger canónico.')}/>} {panel==='pay'&&selectedRequest&&<PayForm busy={busy} data={data} item={selectedRequest} onSubmit={(values,payment,fiscal)=>void submit(()=>expedienteFinanceService.payRequest(expediente.id,selectedRequest.id,{...values,idempotency_key:key()},payment,fiscal),'Solicitud pagada y egreso registrado.')}/>}</section></div>}
    {createOpen&&catalogs&&<NewMovementFlow catalogs={catalogs} initialExpedienteId={expediente.id} lockExpediente onClose={()=>setCreateOpen(false)} onSaved={onChanged}/>}
    {selectedMovement&&<MovementDetail movement={selectedMovement} permissions={catalogs?.permisos||{escribir:false,aplicar:false,conciliar:false,expedientesLeer:true,documentosLeer:expediente.capabilities.canReadDocuments,documentosEscribir:false,documentosEliminar:false}} onChanged={onChanged} onClose={()=>setSelectedMovement(null)}/>}
  </div>;
}

function IncomeRow({item,canApply,canAI,onOpenDocument,onAI,onApply}:{item:Exp008Income;canApply:boolean;canAI:boolean;onOpenDocument(id:string):void;onAI():void;onApply():void}){return <article><div className={styles.caseFinanceRowIcon}><ArrowDownLeft/></div><div className={styles.caseFinanceRowMain}><span className={item.estado==='APLICADO'?styles.caseStatusDone:item.estado==='ANULADO'?styles.caseStatusVoid:styles.caseStatusPending}>{item.estado==='PENDIENTE_APLICACION'?'Pendiente de aplicación':item.estado==='APLICADO'?'Aplicado':'Anulado'}</span><strong>{item.concepto_contexto||'Ingreso reportado'}</strong><small>Reportado por {item.reportadoPor?.nombre||'Usuario'} · {date(item.created_at)}</small><div className={styles.caseFinanceDocChips}>{item.documentos.map(link=><button key={link.id} onClick={()=>onOpenDocument(link.id)}><FileText/> {link.documento.nombre_original}</button>)}</div></div><b>{item.monto_validado?money(item.monto_validado):item.monto_reportado?money(item.monto_reportado):'Por validar'}</b><div className={styles.caseFinanceRowActions}>{canAI&&item.estado==='PENDIENTE_APLICACION'&&<button onClick={onAI}><Bot/>Analizar</button>}{canApply&&item.estado==='PENDIENTE_APLICACION'&&<button className={styles.primaryButton} onClick={onApply}>Aplicar</button>}</div></article>}
function RequestRow({item,canApply,canAI,onOpenDocument,onAI,onPay,onReceipt}:{item:Exp008Request;canApply:boolean;canAI:boolean;onOpenDocument(id:string):void;onAI():void;onPay():void;onReceipt():void}){return <article><div className={styles.caseFinanceRowIcon}><HandCoins/></div><div className={styles.caseFinanceRowMain}><span className={item.estado==='PAGADA'?styles.caseStatusDone:item.estado==='ANULADA'?styles.caseStatusVoid:styles.caseStatusPending}>{item.estado==='PENDIENTE'?'Pendiente':item.estado==='PAGADA'?'Pagada':'Anulada'}</span><strong>{item.concepto}</strong><small>{item.via==='INTERNA'?'Captura interna':'Documento externo'} · {item.creadoPor?.nombre||'Usuario'} · {date(item.created_at)}</small><div className={styles.caseFinanceDocChips}>{item.documentos.map(link=><button key={link.id} onClick={()=>onOpenDocument(link.id)} title={link.tipo.replaceAll('_',' ')}><FileText/> {link.documento.nombre_original}</button>)}</div></div><b>{money(item.importe)}</b><div className={styles.caseFinanceRowActions}>{canAI&&item.estado==='PENDIENTE'&&item.via==='DOCUMENTO_EXTERNO'&&<button onClick={onAI}><Bot/>Analizar</button>}{canApply&&item.estado==='PENDIENTE'&&<button className={styles.primaryButton} onClick={onPay}>Registrar pago</button>}{canApply&&item.estado==='PAGADA'&&item.movimiento_id&&<button onClick={onReceipt}><ReceiptText/>Comprobante PRAVIA</button>}</div></article>}
const Empty=({icon,text}:{icon:ReactNode;text:string})=><div className={styles.caseFinanceEmpty}>{icon}<strong>{text}</strong><p>Los registros aparecerán aquí con su estado y siguiente acción.</p></div>;
function Field({label,name,type='text',required=false,defaultValue}:{label:string;name:string;type?:string;required?:boolean;defaultValue?:string}){return <label><span>{label}</span><input name={name} type={type} required={required} defaultValue={defaultValue} step={type==='number'?'0.01':undefined} min={type==='number'?'0':undefined}/></label>}
function IncomeForm({busy,onSubmit}:{busy:boolean;onSubmit(v:Record<string,string>,f:File):void}){const send=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);const file=form.get('file');if(file instanceof File&&file.size)onSubmit(Object.fromEntries([...form.entries()].filter(([k])=>k!=='file')) as Record<string,string>,file);};return <form className={styles.caseFinanceForm} onSubmit={send}><p>Subir evidencia no aplica ningún movimiento.</p><Field label="Concepto o contexto" name="concepto_contexto" required/><Field label="Monto reportado (opcional)" name="monto_reportado" type="number"/><label><span>Comprobante</span><input name="file" type="file" accept="application/pdf,image/png,image/jpeg" required/></label><button className={styles.primaryButton} disabled={busy}>{busy?'Guardando…':'Reportar comprobante'}</button></form>}
function RequestForm({busy,onSubmit}:{busy:boolean;onSubmit(v:Record<string,string>,f?:File):void}){const send=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);const file=form.get('file');onSubmit(Object.fromEntries([...form.entries()].filter(([k])=>k!=='file')) as Record<string,string>,file instanceof File&&file.size?file:undefined);};return <form className={styles.caseFinanceForm} onSubmit={send}><Field label="Concepto" name="concepto" required/><Field label="Importe" name="importe" type="number" required/><Field label="Beneficiario" name="beneficiario"/><Field label="Dependencia" name="dependencia"/><Field label="Referencia" name="referencia"/><label><span>Ficha externa (opcional)</span><input name="file" type="file" accept="application/pdf,image/png,image/jpeg,.docx"/><small>Sin archivo se genera la ficha interna conforme a Configuración.</small></label><button className={styles.primaryButton} disabled={busy}>{busy?'Guardando…':'Crear solicitud'}</button></form>}
function AIReviewForm({busy,proposal,onSubmit}:{busy:boolean;proposal:Exp008AIProposal;onSubmit(decision:'ACCEPT'|'REJECT',fields:Record<string,string>):void}){const fields=Object.entries(proposal.propuesta||{});const send=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();onSubmit('ACCEPT',Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>);};return <form className={styles.caseFinanceForm} onSubmit={send}><div className={styles.caseFinanceGuard}><strong>La IA sólo propone</strong><span>Revisa cada dato. Validar actualiza la captura, pero no aplica ni paga ningún movimiento.</span></div>{fields.length?fields.map(([name,value])=><Field key={name} label={name.replaceAll('_',' ')} name={name} defaultValue={value==null?'':String(value)}/>):<p>No se extrajeron datos; revisa el documento manualmente.</p>}<section className={styles.caseFinanceAITrace} aria-label="Procedencia de la propuesta"><strong>Fuente y procedencia</strong>{proposal.provenance?.map((source,index)=><div key={`${source.campo}-${index}`}><span>{source.campo.replaceAll('_',' ')}</span><small>{source.documento}{source.pagina?` · página ${source.pagina}`:''}</small></div>)}{proposal.conflictos?.length?<p role="alert">Conflictos detectados: {proposal.conflictos.length}. Debes resolverlos antes de continuar.</p>:null}{proposal.faltantes?.length?<p>Campos no encontrados: {proposal.faltantes.join(', ')}.</p>:null}</section><div className={styles.caseFinanceReviewActions}><button type="button" className={styles.secondaryButton} disabled={busy} onClick={()=>onSubmit('REJECT',{})}>Rechazar propuesta</button><button className={styles.primaryButton} disabled={busy||!fields.length}>{busy?'Guardando revisión…':'Validar datos revisados'}</button></div></form>}
function ApplyForm({busy,data,item,onSubmit}:{busy:boolean;data:Exp008Data;item:Exp008Income;onSubmit(v:Record<string,string>):void}){const send=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();onSubmit(Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>);};return <form className={styles.caseFinanceForm} onSubmit={send}><div className={styles.caseFinanceGuard}><strong>Revisión humana obligatoria</strong><span>Confirma el monto y su aplicación general.</span></div><Field label="Monto validado" name="monto_validado" type="number" required defaultValue={String(item.monto_reportado||'')}/><Field label="Honorarios" name="honorarios" type="number" required/><Field label="Impuestos y derechos" name="impuestos_derechos" type="number" required/><Field label="Concepto" name="concepto" defaultValue={item.concepto_contexto||''}/><label><span>Cuenta</span><select name="cuenta_id" required><option value="">Seleccionar</option>{data.catalogs.accounts.map(x=><option key={x.id} value={x.id}>{x.institucion} · {x.alias}</option>)}</select></label><Field label="Forma de pago" name="forma_pago"/><Field label="Referencia" name="referencia"/><button className={styles.primaryButton} disabled={busy}>{busy?'Aplicando…':'Validar y aplicar'}</button></form>}
function PayForm({busy,data,item,onSubmit}:{busy:boolean;data:Exp008Data;item:Exp008Request;onSubmit(v:Record<string,string>,p?:File,f?:File):void}){const send=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);const payment=form.get('payment');const fiscal=form.get('fiscal');onSubmit(Object.fromEntries([...form.entries()].filter(([k])=>!['payment','fiscal'].includes(k))) as Record<string,string>,payment instanceof File&&payment.size?payment:undefined,fiscal instanceof File&&fiscal.size?fiscal:undefined);};return <form className={styles.caseFinanceForm} onSubmit={send}><div className={styles.caseFinanceGuard}><strong>{item.concepto}</strong><span>{money(item.importe)} · registrar no concilia banco.</span></div><label><span>Cuenta</span><select name="cuenta_id" required><option value="">Seleccionar</option>{data.catalogs.accounts.map(x=><option key={x.id} value={x.id}>{x.institucion} · {x.alias}</option>)}</select></label><label><span>Categoría de egreso</span><select name="categoria_id" required><option value="">Seleccionar</option>{data.catalogs.categories.filter(x=>x.direccion!=='INGRESO').map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></label><Field label="Forma de pago" name="forma_pago"/><Field label="Referencia" name="referencia"/><label><span>Comprobante de pago (opcional)</span><input name="payment" type="file" accept="application/pdf,image/png,image/jpeg"/></label><label><span>Factura / comprobante fiscal (opcional)</span><input name="fiscal" type="file" accept="application/pdf,image/png,image/jpeg"/></label><button className={styles.primaryButton} disabled={busy}>{busy?'Registrando…':'Confirmar pago'}</button></form>}
