import { ArrowDownLeft, ArrowUpRight, Bot, BriefcaseBusiness, CheckCircle2, FileCheck2, FileText, FileWarning, HandCoins, Landmark, Plus, ReceiptText, Upload, WalletCards, X } from 'lucide-react';
import { FormEvent, useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { MovementDetail } from '../../../finance/components/MovementDetail';
import { NewMovementFlow } from '../../../finance/components/NewMovementFlow';
import { financeService } from '../../../finance/finance.service';
import type { FinanceCatalogs, FinanceMovement } from '../../../finance/finance.types';
import { financeDate, statusLabel } from '../../../finance/finance.utils';
import { expedienteFinanceService, type Exp008AIProposal, type Exp008Data, type Exp008Income, type Exp008Request } from '../../expedienteFinance.service';
import type { ExpedienteDetail } from '../../expedientes.types';
import styles from '../../Expedientes.module.css';

type Props = { expediente: ExpedienteDetail; onChanged(): void };
type Panel = 'income'|'request'|'review'|'apply'|'pay'|'invoice'|null;
const money = (value: unknown) => new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(value||0));
const date = (value?:string|null) => value ? new Intl.DateTimeFormat('es-MX',{dateStyle:'medium'}).format(new Date(value)) : '—';
const key = () => crypto.randomUUID();
const uploadedFile = (form: HTMLFormElement, name: string) =>
  (form.elements.namedItem(name) as HTMLInputElement | null)?.files?.[0];

export function FinanceTab({ expediente, onChanged }: Props) {
  const [data,setData]=useState<Exp008Data|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [notice,setNotice]=useState('');
  const [panel,setPanel]=useState<Panel>(null); const [selectedIncome,setSelectedIncome]=useState<Exp008Income|null>(null); const [selectedRequest,setSelectedRequest]=useState<Exp008Request|null>(null); const [busy,setBusy]=useState(false);
  const [proposal,setProposal]=useState<Exp008AIProposal|null>(null);
  const [statementBusy,setStatementBusy]=useState(false);
  const [catalogs,setCatalogs]=useState<FinanceCatalogs|null>(null); const [createOpen,setCreateOpen]=useState(false); const [selectedMovement,setSelectedMovement]=useState<FinanceMovement|null>(null);
  const drawerRef=useRef<HTMLElement|null>(null);
  const load=()=>{setLoading(true);setError('');const c=new AbortController();expedienteFinanceService.read(expediente.id,c.signal).then(setData).catch(()=>{if(!c.signal.aborted)setError('No pudimos cargar las finanzas del expediente.');}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();};
  useEffect(load,[expediente.id]);
  useEffect(()=>{if(!expediente.capabilities.canWriteFinance)return;const c=new AbortController();financeService.catalogs(c.signal).then(setCatalogs).catch(()=>undefined);return()=>c.abort();},[expediente.capabilities.canWriteFinance]);
  useEffect(()=>{if(panel)setError('');},[panel]);
  useEffect(()=>{if(!panel)return;const previous=document.activeElement instanceof HTMLElement?document.activeElement:null;const drawer=drawerRef.current;const focusable=()=>Array.from(drawer?.querySelectorAll<HTMLElement>('button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [href], [tabindex]:not([tabindex="-1"])')||[]);focusable()[0]?.focus();const onKeyDown=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();setPanel(null);return;}if(event.key!=='Tab')return;const items=focusable();if(!items.length)return;const first=items[0];const last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}};document.addEventListener('keydown',onKeyDown);return()=>{document.removeEventListener('keydown',onKeyDown);previous?.focus();};},[panel]);
  const operationalSummary=useMemo(()=>{const incomes=data?.ingresosReportados||[];const requests=data?.solicitudesPago||[];return{income:incomes.filter(x=>x.estado==='APLICADO').reduce((sum,x)=>sum+Number(x.monto_validado||0),0),pendingIncome:incomes.filter(x=>x.estado==='PENDIENTE_APLICACION').length,expenses:requests.filter(x=>x.estado==='PAGADA').reduce((sum,x)=>sum+Number(x.importe),0),pendingRequests:requests.filter(x=>x.estado==='PENDIENTE').length};},[data]);
  const canonicalSummary=expediente.financialSummary||{ingresos_recibidos:0,honorarios_generados:0,honorarios_cobrados:0,honorarios_por_cobrar:0,fondos_terceros:0,otros_destinos:0,fondos_terceros_pendientes:0,egresos:0};
  const movements=(expediente.movimientosFinancieros||[]) as FinanceMovement[];
  const done=(message:string)=>{setNotice(message);setPanel(null);setSelectedIncome(null);setSelectedRequest(null);setProposal(null);load();onChanged();};
  const submit=async(action:()=>Promise<unknown>,message:string)=>{setBusy(true);setError('');try{await action();done(message);}catch(e:any){setError(e?.message||'No pudimos completar la operación.');}finally{setBusy(false);}};
  const analyze=async(action:()=>Promise<{item:Exp008AIProposal}>)=>{setBusy(true);setError('');try{const result=await action();setProposal(result.item);setPanel('review');}catch(e:any){setError(e?.message||'No pudimos analizar el documento.');}finally{setBusy(false);}};
  const generateStatement=async()=>{setStatementBusy(true);setError('');try{const result=await expedienteFinanceService.generateAccountStatement(expediente.id);window.open(result.url,'_blank','noopener,noreferrer');setNotice(result.idempotent?'El estado de cuenta ya estaba generado; abrimos el documento vigente.':'Estado de cuenta generado con datos vigentes.');onChanged();}catch(e:any){setError(e?.message||'No pudimos generar el estado de cuenta.');}finally{setStatementBusy(false);}};
  if(loading)return <div className={styles.caseFinanceLoading} role="status">Cargando finanzas del expediente…</div>;
  if(!data)return <p className={styles.sectionError} role="alert">{error||'Las finanzas no están disponibles.'}</p>;
  return <div className={styles.tabStack}>
    <section className={styles.caseFinanceMetrics} aria-label="Resumen financiero del expediente">
      <article data-tone="gold"><span><BriefcaseBusiness/></span><small>Honorarios generados</small><strong>{money(canonicalSummary.honorarios_generados)}</strong></article>
      <article data-tone="green"><span><ArrowDownLeft/></span><small>Honorarios cobrados</small><strong>{money(canonicalSummary.honorarios_cobrados)}</strong></article>
      <article data-tone="orange"><span><HandCoins/></span><small>Por cobrar</small><strong>{money(canonicalSummary.honorarios_por_cobrar)}</strong></article>
      <article><span><Landmark/></span><small>Recursos no propios</small><strong>{money(canonicalSummary.fondos_terceros)}</strong></article>
      <article data-tone="orange"><span><ReceiptText/></span><small>Por aplicar</small><strong>{operationalSummary.pendingIncome}</strong></article>
      <article data-tone="red"><span><ArrowUpRight/></span><small>Egresos registrados</small><strong>{money(operationalSummary.expenses)}</strong></article>
      <article><span><HandCoins/></span><small>Solicitudes pendientes</small><strong>{operationalSummary.pendingRequests}</strong></article>
      <article data-tone="gold"><span><WalletCards/></span><small>Presupuesto vigente</small><strong>{money(data.presupuesto?.total)}</strong></article>
    </section>
    {notice&&<div className={styles.caseFinanceSuccess} role="status"><CheckCircle2/> {notice}</div>}{error&&!panel&&<p className={styles.sectionError} role="alert">{error}</p>}
    {(data.capabilities.canReport||data.capabilities.canCreateRequest)&&<section className={styles.caseFinanceActions} aria-label="Acciones financieras"><div><strong>Operación interna</strong><span>Reporta evidencia o crea una solicitud sin alterar el ledger.</span></div>{data.capabilities.canReport&&<button className={styles.secondaryButton} onClick={()=>setPanel('income')}><Upload size={16}/>Reportar ingreso</button>}{data.capabilities.canCreateRequest&&<button className={styles.primaryButton} onClick={()=>setPanel('request')}><Plus size={16}/>Solicitar pago</button>}</section>}
    <section className={styles.sectionCard} aria-label="Estado de cuenta del expediente"><header className={styles.caseFinanceHeader}><div><h2>Estado de cuenta</h2><p>Presupuesto vigente contra cobros y aplicaciones del ledger canónico.</p></div>{data.accountStatement&&data.capabilities.canReadDocuments&&<button type="button" className={styles.primaryButton} disabled={statementBusy} onClick={()=>void generateStatement()}><FileText size={16}/>{statementBusy?'Generando…':'Generar estado de cuenta'}</button>}</header>{data.accountStatement?<><div className={styles.caseAccountStatement} role="table" aria-label="Detalle del estado de cuenta"><div role="row" className={styles.caseAccountStatementHeader}><span role="columnheader">Concepto</span><span role="columnheader">Presupuestado</span><span role="columnheader">Cobrado / aplicado</span><span role="columnheader">Pendiente</span></div>{data.accountStatement.sections.map(row=><div role="row" key={row.key}><strong role="cell">{row.label}</strong><span role="cell">{money(row.budgeted)}</span><span role="cell">{money(row.collected)}</span><span role="cell">{money(row.pending)}</span></div>)}</div><div className={styles.caseAccountTotals}><span><small>Presupuesto vigente</small><b>{money(data.accountStatement.totals.budget)}</b></span><span><small>Total cobrado</small><b>{money(data.accountStatement.totals.collected)}</b></span><span><small>Total pendiente</small><b>{money(data.accountStatement.totals.pending)}</b></span><span><small>Recursos pendientes de entregar / aplicar</small><b>{money(data.accountStatement.totals.thirdPartyPendingApplication)}</b></span></div><p className={styles.caseAccountSource}>Fuente: {data.accountStatement.canonicalSource} · Presupuesto v{data.accountStatement.budget.version}</p></>:<Empty icon={<FileText/>} text="El expediente todavía no tiene presupuesto vigente."/>}</section>
    <section className={styles.sectionCard}><header><div><h2>Anticipos e ingresos</h2><p>La carga queda pendiente hasta que Administración revise y aplique.</p></div></header>
      <div className={styles.caseFinanceOperationalList}>{data.ingresosReportados.length?data.ingresosReportados.map(item=><IncomeRow key={item.id} item={item} canApply={data.capabilities.canApply} canCompleteInvoice={data.capabilities.canCompleteInvoice} canAI={data.capabilities.canUseAI} onOpenDocument={(linkId)=>void expedienteFinanceService.openDocument(expediente.id,linkId)} onAI={()=>void analyze(async()=>{const link=item.documentos.find(x=>x.tipo==='COMPROBANTE_INGRESO');if(!link)throw new Error('No hay evidencia disponible.');setSelectedIncome(item);setSelectedRequest(null);return expedienteFinanceService.proposeAI(expediente.id,{documento_id:link.documento.id,ingreso_reportado_id:item.id,operation_id:key()});})} onApply={()=>{setSelectedIncome(item);setPanel('apply');}} onInvoice={()=>{setSelectedIncome(item);setPanel('invoice');}}/>):<Empty icon={<ReceiptText/>} text="No hay comprobantes reportados."/>}</div>
    </section>
    <section className={styles.sectionCard}><header><div><h2>Solicitudes de pago</h2><p>La ficha origen, el comprobante de pago y el documento fiscal conservan roles distintos.</p></div></header>
      <div className={styles.caseFinanceOperationalList}>{data.solicitudesPago.length?data.solicitudesPago.map(item=><RequestRow key={item.id} item={item} canApply={data.capabilities.canApply} canAI={data.capabilities.canUseAI} onOpenDocument={(linkId)=>void expedienteFinanceService.openDocument(expediente.id,linkId)} onAI={()=>void analyze(async()=>{const link=item.documentos.find(x=>x.tipo==='SOLICITUD_ORIGEN');if(!link)throw new Error('Esta solicitud no tiene ficha externa para analizar.');setSelectedRequest(item);setSelectedIncome(null);return expedienteFinanceService.proposeAI(expediente.id,{documento_id:link.documento.id,solicitud_pago_id:item.id,operation_id:key()});})} onPay={()=>{setSelectedRequest(item);setPanel('pay');}} onReceipt={()=>item.movimiento_id&&void submit(()=>expedienteFinanceService.generateReceipt(expediente.id,item.movimiento_id!),'Comprobante PRAVIA generado y vinculado.')}/>):<Empty icon={<FileText/>} text="No hay solicitudes de pago."/>}</div>
    </section>
    <section className={styles.sectionCard}><header className={styles.caseFinanceHeader}><div><h2>Movimientos del expediente</h2><p>Una sola fuente de verdad, compartida con Finanzas central.</p></div>{expediente.capabilities.canWriteFinance&&<button type="button" className={styles.primaryButton} disabled={!catalogs} onClick={()=>setCreateOpen(true)}><Plus size={16}/>Registrar movimiento</button>}</header>{movements.length?<div className={styles.caseMovementList}>{movements.map(item=>{const evidence=item.movimientoDocumentos||[];return <button type="button" key={item.id} onClick={()=>setSelectedMovement(item)}><span className={item.naturaleza==='INGRESO'?styles.income:styles.expense}>{item.naturaleza==='INGRESO'?<ArrowDownLeft/>:<ArrowUpRight/>}</span><div><strong>{item.concepto}</strong><small>{financeDate(item.fecha_movimiento)} · {statusLabel(item.estatus)}</small></div><span className={evidence.length?styles.caseReceiptOk:styles.caseReceiptMissing}>{evidence.length?<FileCheck2/>:<FileWarning/>}{evidence.length?'Con comprobante':'Sin comprobante'}</span><b>{money(item.monto)}</b></button>;})}</div>:<Empty icon={<WalletCards/>} text="No hay movimientos aplicados en este expediente."/>}</section>
    {expediente.capabilities.canReadFinance&&<section className={styles.caseFinanceLedgerNote}><FileCheck2/><div><strong>Ledger canónico conectado</strong><span>Los ingresos aplicados y egresos pagados aparecen también en Finanzas central. No se concilian automáticamente.</span></div></section>}
    {panel&&<div className={styles.caseFinanceOverlay} role="presentation"><section ref={drawerRef} className={styles.caseFinanceDrawer} role="dialog" aria-modal="true" aria-labelledby="exp008-dialog-title" aria-busy={busy}><header><div><small>EXP-008</small><h2 id="exp008-dialog-title">{panel==='income'?'Reportar ingreso':panel==='request'?'Nueva solicitud de pago':panel==='review'?'Revisar propuesta de IA':panel==='apply'?'Aplicar ingreso':panel==='invoice'?'Agregar factura':'Registrar pago'}</h2></div><button type="button" aria-label="Cerrar" onClick={()=>setPanel(null)}><X/></button></header>{error&&<p className={styles.caseFinanceDrawerError} role="alert">{error}</p>}{panel==='income'&&<IncomeForm busy={busy} data={data} expedienteId={expediente.id} onSubmit={(values,files)=>void submit(()=>expedienteFinanceService.reportIncome(expediente.id,{...values,idempotency_key:key()},files),values.factura_pendiente==='true'?'Ingreso guardado con factura pendiente.':'Ingreso guardado con factura PDF y XML.')}/>} {panel==='request'&&<RequestForm busy={busy} onSubmit={(values,file)=>void submit(()=>file?expedienteFinanceService.createExternalRequest(expediente.id,{...values,idempotency_key:key()},file):expedienteFinanceService.createInternalRequest(expediente.id,{...values,idempotency_key:key()}),'Solicitud creada y pendiente de pago.')}/>} {panel==='review'&&proposal&&<AIReviewForm busy={busy} proposal={proposal} onSubmit={(decision,accepted_fields)=>void submit(()=>expedienteFinanceService.validateAI(expediente.id,proposal.id,{decision,accepted_fields}),decision==='REJECT'?'Propuesta rechazada; no se modificó el registro.':'Propuesta validada por una persona; aún no se aplicó ningún movimiento.')}/>} {panel==='apply'&&selectedIncome&&<ApplyForm busy={busy} data={data} item={selectedIncome} onSubmit={(values)=>void submit(()=>expedienteFinanceService.applyIncome(expediente.id,selectedIncome.id,{...values,idempotency_key:key()}),'Ingreso aplicado al ledger canónico.')}/>} {panel==='invoice'&&selectedIncome&&<InvoiceForm busy={busy} item={selectedIncome} onSubmit={(files)=>void submit(()=>expedienteFinanceService.completeInvoice(expediente.id,selectedIncome.id,{idempotency_key:key()},files),'Documentos fiscales guardados.')}/>} {panel==='pay'&&selectedRequest&&<PayForm busy={busy} data={data} item={selectedRequest} onSubmit={(values,payment,fiscal)=>void submit(()=>expedienteFinanceService.payRequest(expediente.id,selectedRequest.id,{...values,idempotency_key:key()},payment,fiscal),'Solicitud pagada y egreso registrado.')}/>}</section></div>}
    {createOpen&&catalogs&&<NewMovementFlow catalogs={catalogs} initialExpedienteId={expediente.id} lockExpediente onClose={()=>setCreateOpen(false)} onSaved={onChanged}/>}
    {selectedMovement&&<MovementDetail movement={selectedMovement} permissions={catalogs?.permisos||{escribir:false,aplicar:false,conciliar:false,expedientesLeer:true,documentosLeer:expediente.capabilities.canReadDocuments,documentosEscribir:false,documentosEliminar:false}} onChanged={onChanged} onClose={()=>setSelectedMovement(null)}/>}
  </div>;
}

function IncomeRow({item,canApply,canCompleteInvoice,canAI,onOpenDocument,onAI,onApply,onInvoice}:{item:Exp008Income;canApply:boolean;canCompleteInvoice:boolean;canAI:boolean;onOpenDocument(id:string):void;onAI():void;onApply():void;onInvoice():void}){return <article><div className={styles.caseFinanceRowIcon}><ArrowDownLeft/></div><div className={styles.caseFinanceRowMain}><div className={styles.caseFinanceStatusLine}><span className={item.estado==='APLICADO'?styles.caseStatusDone:item.estado==='ANULADO'?styles.caseStatusVoid:styles.caseStatusPending}>{item.estado==='PENDIENTE_APLICACION'?'Pendiente de aplicación':item.estado==='APLICADO'?'Aplicado':'Anulado'}</span>{item.factura_estado&&<span className={item.factura_estado==='CARGADA'?styles.caseStatusDone:styles.caseStatusPending}>{item.factura_estado==='CARGADA'?'Factura cargada':'Factura pendiente'}</span>}</div><strong>{item.concepto_contexto||'Ingreso reportado'}</strong><small>Facturar a: {item.facturarAVinculo?.compareciente.nombre_busqueda||'Sin asignar'} · {item.forma_pago==='OTRO'?item.forma_pago_detalle:item.forma_pago?.toLocaleLowerCase('es-MX')||'Forma no registrada'}</small><small>Reportado por {item.reportadoPor?.nombre||'Usuario'} · {date(item.created_at)}</small><div className={styles.caseFinanceDocChips}>{item.documentos.map(link=><button key={link.id} onClick={()=>onOpenDocument(link.id)}><FileText/> {link.documento.nombre_original}</button>)}</div></div><b>{item.monto_validado?money(item.monto_validado):item.monto_reportado?money(item.monto_reportado):'Por validar'}</b><div className={styles.caseFinanceRowActions}>{canCompleteInvoice&&item.factura_estado==='PENDIENTE'&&<button className={styles.primaryButton} onClick={onInvoice}><Upload/>Agregar factura</button>}{canAI&&item.estado==='PENDIENTE_APLICACION'&&<button onClick={onAI}><Bot/>Analizar</button>}{canApply&&item.estado==='PENDIENTE_APLICACION'&&<button className={styles.primaryButton} onClick={onApply}>Aplicar</button>}</div></article>}
function RequestRow({item,canApply,canAI,onOpenDocument,onAI,onPay,onReceipt}:{item:Exp008Request;canApply:boolean;canAI:boolean;onOpenDocument(id:string):void;onAI():void;onPay():void;onReceipt():void}){return <article><div className={styles.caseFinanceRowIcon}><HandCoins/></div><div className={styles.caseFinanceRowMain}><span className={item.estado==='PAGADA'?styles.caseStatusDone:item.estado==='ANULADA'?styles.caseStatusVoid:styles.caseStatusPending}>{item.estado==='PENDIENTE'?'Pendiente':item.estado==='PAGADA'?'Pagada':'Anulada'}</span><strong>{item.concepto}</strong><small>{item.via==='INTERNA'?'Captura interna':'Documento externo'} · {item.creadoPor?.nombre||'Usuario'} · {date(item.created_at)}</small><div className={styles.caseFinanceDocChips}>{item.documentos.map(link=><button key={link.id} onClick={()=>onOpenDocument(link.id)} title={link.tipo.replaceAll('_',' ')}><FileText/> {link.documento.nombre_original}</button>)}</div></div><b>{money(item.importe)}</b><div className={styles.caseFinanceRowActions}>{canAI&&item.estado==='PENDIENTE'&&item.via==='DOCUMENTO_EXTERNO'&&<button onClick={onAI}><Bot/>Analizar</button>}{canApply&&item.estado==='PENDIENTE'&&<button className={styles.primaryButton} onClick={onPay}>Registrar pago</button>}{canApply&&item.estado==='PAGADA'&&item.movimiento_id&&<button onClick={onReceipt}><ReceiptText/>Comprobante PRAVIA</button>}</div></article>}
const Empty=({icon,text}:{icon:ReactNode;text:string})=><div className={styles.caseFinanceEmpty}>{icon}<strong>{text}</strong><p>Los registros aparecerán aquí con su estado y siguiente acción.</p></div>;
function Field({label,name,type='text',required=false,defaultValue}:{label:string;name:string;type?:string;required?:boolean;defaultValue?:string}){return <label><span>{label}</span><input name={name} type={type} required={required} defaultValue={defaultValue} step={type==='number'?'0.01':undefined} min={type==='number'?'0':undefined}/></label>}
function IncomeForm({busy,data,expedienteId,onSubmit}:{busy:boolean;data:Exp008Data;expedienteId:string;onSubmit(v:Record<string,string>,f:{receipt:File;invoicePdf?:File;invoiceXml?:File}):void}){
  const [pending,setPending]=useState(true);
  const [method,setMethod]=useState('');
  const [concept,setConcept]=useState('');
  const [amount,setAmount]=useState('');
  const [aiBusy,setAiBusy]=useState(false);
  const [aiMessage,setAiMessage]=useState('');
  const [aiError,setAiError]=useState(false);
  const formRef=useRef<HTMLFormElement|null>(null);
  const fillWithAI=async()=>{
    const receipt=formRef.current&&uploadedFile(formRef.current,'file');
    if(!receipt){setAiError(true);setAiMessage('Selecciona primero el comprobante del ingreso.');return;}
    setAiBusy(true);setAiError(false);setAiMessage('Leyendo el comprobante…');
    try{
      const suggestion=await expedienteFinanceService.previewIncomeAI(expedienteId,receipt);
      if(suggestion.monto_reportado)setAmount(current=>current||suggestion.monto_reportado||'');
      if(suggestion.concepto_contexto)setConcept(current=>current||suggestion.concepto_contexto||'');
      setAiMessage(suggestion.monto_reportado||suggestion.concepto_contexto
        ?'La IA sugirió datos del comprobante. Revisa y corrige los campos antes de registrar.'
        :'No encontramos datos suficientemente claros. Puedes completar el ingreso manualmente.');
    }catch(error){setAiError(true);setAiMessage(error instanceof Error?error.message:'No pudimos leer el comprobante. Puedes completar el ingreso manualmente.');}
    finally{setAiBusy(false);}
  };
  const send=(event:FormEvent<HTMLFormElement>)=>{
    event.preventDefault();
    const form=new FormData(event.currentTarget);
    const receipt=uploadedFile(event.currentTarget,'file');
    const pdf=uploadedFile(event.currentTarget,'invoice_pdf');
    const xml=uploadedFile(event.currentTarget,'invoice_xml');
    if(!receipt)return;
    onSubmit({...Object.fromEntries([...form.entries()].filter(([name])=>!['file','invoice_pdf','invoice_xml','factura_pendiente'].includes(name))) as Record<string,string>,factura_pendiente:String(pending)},{receipt,invoicePdf:pdf,invoiceXml:xml});
  };
  return <form ref={formRef} className={styles.caseFinanceForm} onSubmit={send}>
    <p>Registrar evidencia no aplica ningún movimiento financiero.</p>
    <label><span>Concepto o contexto</span><input name="concepto_contexto" required value={concept} onChange={event=>setConcept(event.target.value)}/></label>
    <label><span>Monto reportado (opcional)</span><input name="monto_reportado" type="number" step="0.01" min="0" value={amount} onChange={event=>setAmount(event.target.value)}/></label>
    <label><span>¿A quién se va a facturar?</span><select name="facturar_a_vinculo_id" required><option value="">Seleccionar compareciente</option>{data.catalogs.parties.map(item=><option key={item.id} value={item.id}>{item.compareciente.nombre_busqueda} · {item.caracter.nombre}</option>)}</select></label>
    <PaymentMethodFields method={method} onChange={setMethod}/>
    <label><span>Comprobante del ingreso</span><input name="file" type="file" accept=".pdf,.png,.jpg,.jpeg,.bmp,.webp,.doc,.docx,.xml,.zip" required onChange={()=>{setAiMessage('');setAiError(false);}}/></label>
    {data.capabilities.canPrefillAI&&<div className={styles.caseFinanceAIAction}><button type="button" className={styles.secondaryButton} disabled={busy||aiBusy} onClick={()=>void fillWithAI()}><Bot size={16}/>{aiBusy?'Leyendo comprobante…':'Llenar con IA'}</button><small>PDF, JPG, PNG o DOCX. La sugerencia no registra el ingreso.</small></div>}
    {aiMessage&&<div className={styles.caseFinanceAIMessage} role={aiError?'alert':'status'}>{aiMessage}</div>}
    <label className={styles.caseFinanceCheckbox}><input type="checkbox" checked={pending} onChange={event=>setPending(event.target.checked)}/><span>Factura pendiente</span></label>
    {!pending&&<div className={styles.caseFinanceFiscalPair}><label><span>Factura PDF</span><input name="invoice_pdf" type="file" accept="application/pdf,.pdf" required/></label><label><span>Factura XML</span><input name="invoice_xml" type="file" accept="application/xml,text/xml,.xml" required/></label></div>}
    <button className={styles.primaryButton} disabled={busy||aiBusy||!data.catalogs.parties.length}>{busy?'Guardando ingreso…':'Registrar ingreso'}</button>
    {!data.catalogs.parties.length&&<small role="alert">Agrega al menos un compareciente al expediente antes de registrar el ingreso.</small>}
  </form>;
}
function RequestForm({busy,onSubmit}:{busy:boolean;onSubmit(v:Record<string,string>,f?:File):void}){const send=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);const file=uploadedFile(e.currentTarget,'file');onSubmit(Object.fromEntries([...form.entries()].filter(([k])=>k!=='file')) as Record<string,string>,file);};return <form className={styles.caseFinanceForm} onSubmit={send}><Field label="Concepto" name="concepto" required/><Field label="Importe" name="importe" type="number" required/><Field label="Beneficiario" name="beneficiario"/><Field label="Dependencia" name="dependencia"/><Field label="Referencia" name="referencia"/><label><span>Ficha externa (opcional)</span><input name="file" type="file" accept=".pdf,.png,.jpg,.jpeg,.bmp,.webp,.doc,.docx,.xml,.zip"/><small>Sin archivo se genera la ficha interna conforme a Configuración.</small></label><button className={styles.primaryButton} disabled={busy}>{busy?'Guardando…':'Crear solicitud'}</button></form>}
function AIReviewForm({busy,proposal,onSubmit}:{busy:boolean;proposal:Exp008AIProposal;onSubmit(decision:'ACCEPT'|'REJECT',fields:Record<string,string>):void}){const fields=Object.entries(proposal.propuesta||{});const send=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();onSubmit('ACCEPT',Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>);};return <form className={styles.caseFinanceForm} onSubmit={send}><div className={styles.caseFinanceGuard}><strong>La IA sólo propone</strong><span>Revisa cada dato. Validar actualiza la captura, pero no aplica ni paga ningún movimiento.</span></div>{fields.length?fields.map(([name,value])=><Field key={name} label={name.replaceAll('_',' ')} name={name} defaultValue={value==null?'':String(value)}/>):<p>No se extrajeron datos; revisa el documento manualmente.</p>}<section className={styles.caseFinanceAITrace} aria-label="Procedencia de la propuesta"><strong>Fuente y procedencia</strong>{proposal.provenance?.map((source,index)=><div key={`${source.campo}-${index}`}><span>{source.campo.replaceAll('_',' ')}</span><small>{source.documento}{source.pagina?` · página ${source.pagina}`:''}</small></div>)}{proposal.conflictos?.length?<p role="alert">Conflictos detectados: {proposal.conflictos.length}. Debes resolverlos antes de continuar.</p>:null}{proposal.faltantes?.length?<p>Campos no encontrados: {proposal.faltantes.join(', ')}.</p>:null}</section><div className={styles.caseFinanceReviewActions}><button type="button" className={styles.secondaryButton} disabled={busy} onClick={()=>onSubmit('REJECT',{})}>Rechazar propuesta</button><button className={styles.primaryButton} disabled={busy||!fields.length}>{busy?'Guardando revisión…':'Validar datos revisados'}</button></div></form>}
function PaymentMethodFields({method,onChange,defaultValue}:{method:string;onChange(value:string):void;defaultValue?:string|null}){return <><label><span>Forma de pago</span><select name="forma_pago" required value={method||defaultValue||''} onChange={(event)=>onChange(event.target.value)}><option value="">Seleccionar forma de pago</option><option value="CHEQUE">Cheque</option><option value="EFECTIVO">Efectivo</option><option value="TRANSFERENCIA">Transferencia</option><option value="OTRO">Otro</option></select></label>{(method||defaultValue)==='OTRO'&&<Field label="Especificar forma de pago" name="forma_pago_detalle" required/>}</>}
function ApplyForm({busy,data,item,onSubmit}:{busy:boolean;data:Exp008Data;item:Exp008Income;onSubmit(v:Record<string,string>):void}){const[method,setMethod]=useState(item.forma_pago||'');const send=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();onSubmit(Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>);};return <form className={styles.caseFinanceForm} onSubmit={send}><div className={styles.caseFinanceGuard}><strong>Revisión humana obligatoria</strong><span>Confirma el monto y su aplicación general.</span></div><Field label="Monto validado" name="monto_validado" type="number" required defaultValue={String(item.monto_reportado||'')}/><Field label="Honorarios" name="honorarios" type="number" required/><Field label="Impuestos y derechos" name="impuestos_derechos" type="number" required/><Field label="Concepto" name="concepto" defaultValue={item.concepto_contexto||''}/><label><span>Cuenta</span><select name="cuenta_id" required><option value="">Seleccionar</option>{data.catalogs.accounts.map(x=><option key={x.id} value={x.id}>{x.institucion} · {x.alias}</option>)}</select></label><PaymentMethodFields method={method} onChange={setMethod}/><Field label="Referencia" name="referencia"/><button className={styles.primaryButton} disabled={busy}>{busy?'Aplicando…':'Validar y aplicar'}</button></form>}
function InvoiceForm({busy,item,onSubmit}:{busy:boolean;item:Exp008Income;onSubmit(files:{invoicePdf?:File;invoiceXml?:File}):void}){const hasPdf=item.documentos.some(x=>x.tipo==='COMPROBANTE_FISCAL'&&(x.documento.mime_type==='application/pdf'||x.documento.nombre_original.toLowerCase().endsWith('.pdf')));const hasXml=item.documentos.some(x=>x.tipo==='COMPROBANTE_FISCAL'&&(['application/xml','text/xml'].includes(x.documento.mime_type)||x.documento.nombre_original.toLowerCase().endsWith('.xml')));const send=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();onSubmit({invoicePdf:uploadedFile(e.currentTarget,'invoice_pdf'),invoiceXml:uploadedFile(e.currentTarget,'invoice_xml')});};return <form className={styles.caseFinanceForm} onSubmit={send}><div className={styles.caseFinanceGuard}><strong>Factura pendiente</strong><span>Facturar a {item.facturarAVinculo?.compareciente.nombre_busqueda||'compareciente del expediente'}. La factura quedará cargada únicamente al conservar PDF y XML.</span></div><div className={styles.caseFinanceFiscalPair}>{!hasPdf&&<label><span>Factura PDF</span><input name="invoice_pdf" type="file" accept="application/pdf,.pdf" required={hasXml}/></label>}{!hasXml&&<label><span>Factura XML</span><input name="invoice_xml" type="file" accept="application/xml,text/xml,.xml" required={hasPdf}/></label>}</div><small>Componentes existentes: PDF {hasPdf?'cargado':'pendiente'} · XML {hasXml?'cargado':'pendiente'}.</small><button className={styles.primaryButton} disabled={busy}>{busy?'Guardando factura…':'Agregar factura'}</button></form>}
function PayForm({busy,data,item,onSubmit}:{busy:boolean;data:Exp008Data;item:Exp008Request;onSubmit(v:Record<string,string>,p?:File,f?:{pdf?:File;xml?:File}):void}){
  const[method,setMethod]=useState('');
  const send=(e:FormEvent<HTMLFormElement>)=>{
    e.preventDefault();
    const form=new FormData(e.currentTarget);
    onSubmit(Object.fromEntries([...form.entries()].filter(([k])=>!['payment','fiscal_pdf','fiscal_xml'].includes(k))) as Record<string,string>,uploadedFile(e.currentTarget,'payment'),{pdf:uploadedFile(e.currentTarget,'fiscal_pdf'),xml:uploadedFile(e.currentTarget,'fiscal_xml')});
  };
  return <form className={styles.caseFinanceForm} onSubmit={send}><div className={styles.caseFinanceGuard}><strong>{item.concepto}</strong><span>{money(item.importe)} · registrar no concilia banco.</span></div><label><span>Cuenta</span><select name="cuenta_id" required><option value="">Seleccionar</option>{data.catalogs.accounts.map(x=><option key={x.id} value={x.id}>{x.institucion} · {x.alias}</option>)}</select></label><label><span>Categoría de egreso</span><select name="categoria_id" required><option value="">Seleccionar</option>{data.catalogs.categories.filter(x=>x.direccion!=='INGRESO').map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></label><PaymentMethodFields method={method} onChange={setMethod}/><Field label="Referencia" name="referencia"/><label><span>Comprobante de pago (opcional)</span><input name="payment" type="file" accept=".pdf,.png,.jpg,.jpeg,.bmp,.webp,.doc,.docx,.xml,.zip"/></label><fieldset className={styles.caseFinanceFiscalPair}><legend>Factura / comprobante fiscal (opcional)</legend><label><span>XML fiscal</span><input name="fiscal_xml" type="file" accept="application/xml,text/xml,.xml"/></label><label><span>PDF fiscal</span><input name="fiscal_pdf" type="file" accept="application/pdf,.pdf"/></label></fieldset><button className={styles.primaryButton} disabled={busy}>{busy?'Registrando…':'Confirmar pago'}</button></form>;
}
