import { AlertTriangle, Building2, LoaderCircle, Pencil, Plus, Search, Trash2, X } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../../../auth/AuthProvider';
import { propertiesService } from '../../../properties/properties.service';
import { expedienteReturnParams } from '../../expedienteNavigation';
import { expedientesService } from '../../expedientes.service';
import type { ExpedienteDetail, ExpedientePredioCatalogs, ExpedientePredioCommand, ExpedientePredioPreview, ExpedientePredioRelation, PredioSummary } from '../../expedientes.types';
import styles from './PropertiesTab.module.css';

type DialogState = { operation: 'LINK' | 'UPDATE' | 'UNLINK'; current?: ExpedientePredioRelation };
const title = (property: PredioSummary) => property.apodo || property.ubicacion_texto || [property.calle, property.numero_exterior].filter(Boolean).join(' ') || property.clave_catastral || property.folio_real || 'Inmueble sin apodo';
const subtitle = (property: PredioSummary) => [property.clave_catastral && `Clave ${property.clave_catastral}`, property.cuenta_predial && `Cuenta ${property.cuenta_predial}`, property.folio_real && `Folio ${property.folio_real}`, property.municipio, property.estado].filter(Boolean).join(' · ') || 'Sin identificadores registrales capturados';

export function PropertiesTab({ expediente, onChanged = () => undefined }: { expediente: ExpedienteDetail; onChanged?: () => void }) {
  const location = useLocation(); const navigate = useNavigate(); const { user } = useAuth(); const returned = location.state as { prd001NewPredioId?: string } | null; const canWrite = Boolean(user?.permissions?.includes('expedientes.write'));
  const [relations, setRelations] = useState<ExpedientePredioRelation[]>(expediente.predios || []); const [catalogs, setCatalogs] = useState<ExpedientePredioCatalogs | null>(null); const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading');
  const [dialog, setDialog] = useState<DialogState | null>(null); const [search, setSearch] = useState(''); const [options, setOptions] = useState<PredioSummary[]>([]); const [property, setProperty] = useState<PredioSummary | null>(null); const [actIds, setActIds] = useState<string[]>([]); const [reason, setReason] = useState(''); const [preview, setPreview] = useState<ExpedientePredioPreview | null>(null); const [confirmed, setConfirmed] = useState(false); const [working, setWorking] = useState(false); const [message, setMessage] = useState(''); const [idempotencyKey, setIdempotencyKey] = useState('');
  const load = useCallback(async (signal?: AbortSignal) => { try { const [links, catalogData] = await Promise.all([expedientesService.listProperties(expediente.id, signal), expedientesService.propertyCatalogs(expediente.id, signal)]); setRelations(links.data); setCatalogs(catalogData); setStatus('ready'); } catch { setStatus('error'); } }, [expediente.id]);
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort(); }, [load]);
  const reset = () => { setSearch(''); setOptions([]); setProperty(null); setActIds([]); setReason(''); setPreview(null); setConfirmed(false); setMessage(''); setIdempotencyKey(crypto.randomUUID()); };
  const open = (operation: DialogState['operation'], current?: ExpedientePredioRelation, selected?: PredioSummary) => { reset(); setDialog({ operation, current }); if (current) { setProperty(current.predio); setActIds(current.actos.map((item) => item.expediente_acto_id)); } if (selected) setProperty(selected); };
  useEffect(() => { if (status !== 'ready' || !returned?.prd001NewPredioId) return; propertiesService.get(returned.prd001NewPredioId).then((data) => open('LINK', undefined, data)).catch(() => setMessage('El inmueble se guardó, pero no fue posible preparar el vínculo.')); navigate({ pathname: location.pathname, hash: '#predios' }, { replace: true, state: null }); }, [status, returned?.prd001NewPredioId]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { if (!dialog || dialog.operation !== 'LINK' || property) return; const controller = new AbortController(); const timer = window.setTimeout(() => { expedientesService.searchProperties(expediente.id, search, controller.signal).then((result) => { setOptions(result.data); setMessage(''); }).catch(() => { if (!controller.signal.aborted) setMessage('No pudimos buscar en el maestro inmobiliario.'); }); }, 180); return () => { window.clearTimeout(timer); controller.abort(); }; }, [dialog, expediente.id, property, search]);
  const command = (): ExpedientePredioCommand => ({ operation: dialog!.operation, relation_id: dialog?.current?.id, predio_id: property?.id, expediente_acto_ids: actIds, reason: reason || undefined, idempotency_key: idempotencyKey });
  const requestPreview = async () => { setWorking(true); setMessage(''); try { setPreview(await expedientesService.previewProperty(expediente.id, command())); } catch (error) { setMessage(error instanceof Error ? error.message : 'No fue posible calcular el impacto.'); } finally { setWorking(false); } };
  const apply = async () => { if (!preview) return; setWorking(true); setMessage(''); try { await expedientesService.applyProperty(expediente.id, { ...command(), preview_fingerprint: preview.fingerprint, confirm_protected_work: confirmed }); setDialog(null); await load(); onChanged(); } catch (error) { setMessage(error instanceof Error ? error.message : 'No fue posible aplicar el vínculo.'); } finally { setWorking(false); } };
  const selectedActs = useMemo(() => new Set(actIds), [actIds]); const toggleAct = (id: string) => setActIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  if (status === 'loading') return <div className={styles.state}><LoaderCircle className={styles.spin} />Cargando inmuebles…</div>;
  if (status === 'error') return <div className={styles.state} role="alert"><AlertTriangle />No pudimos cargar las relaciones inmobiliarias.<button onClick={() => void load()}>Reintentar</button></div>;
  return <section className={styles.section}><header><div><h2>Predios / Inmuebles</h2><p>Maestros reutilizables relacionados con los actos de este expediente.</p></div>{canWrite && <div className={styles.headerActions}><button type="button" className={styles.secondary} onClick={() => navigate(`/predios/nuevo?${expedienteReturnParams(expediente.id, 'predios')}`)}><Plus size={17} />Crear nuevo</button><button type="button" className={styles.primary} onClick={() => open('LINK')}><Search size={17} />Vincular existente</button></div>}</header>
    {message && !dialog && <div className={styles.notice} role="status">{message}</div>}
    <div className={styles.list}>{relations.map((relation) => <article key={relation.id} className={styles.propertyCard}><div className={styles.propertyIcon}><Building2 /></div><div className={styles.propertyBody}><h3>{title(relation.predio)}</h3><p>{subtitle(relation.predio)}</p><div className={styles.acts} aria-label="Actos relacionados">{relation.actos.map((item) => <span key={item.id}>{item.expedienteActo.tipo_acto.nombre}</span>)}</div></div><div className={styles.actions}><button type="button" onClick={() => navigate(`/predios/${relation.predio.id}?${expedienteReturnParams(expediente.id, 'predios')}`)}>Ver ficha</button>{canWrite && <><button type="button" aria-label={`Editar actos de ${title(relation.predio)}`} onClick={() => open('UPDATE', relation)}><Pencil size={16} /></button><button type="button" aria-label={`Desvincular ${title(relation.predio)}`} onClick={() => open('UNLINK', relation)}><Trash2 size={16} /></button></>}</div></article>)}{!relations.length && <div className={styles.empty}><Building2 /><strong>No hay inmuebles vinculados.</strong><span>Vincula un maestro existente o crea una ficha completa.</span></div>}</div>
    {dialog && <div className={styles.backdrop}><section className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby="property-link-title"><header><div><h2 id="property-link-title">{dialog.operation === 'LINK' ? 'Vincular inmueble' : dialog.operation === 'UPDATE' ? 'Actualizar actos del inmueble' : 'Desvincular inmueble'}</h2><p>{dialog.operation === 'UNLINK' ? 'Se retirará sólo la relación; la ficha maestra y sus documentos se conservan.' : 'Selecciona los actos en los que participa este mismo inmueble.'}</p></div><button type="button" className={styles.iconButton} aria-label="Cerrar" onClick={() => setDialog(null)}><X /></button></header><div className={styles.dialogBody}>
      {dialog.operation === 'LINK' && !property && <><label className={styles.search}><span>Buscar en el maestro</span><div><Search size={17} /><input autoFocus value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Apodo, clave, cuenta, folio o domicilio" /></div></label><div className={styles.options}>{options.map((option) => <button type="button" key={option.id} onClick={() => setProperty(option)}><strong>{title(option)}</strong><span>{subtitle(option)}</span></button>)}{!options.length && <p>Escribe para buscar inmuebles autorizados de esta organización.</p>}</div></>}
      {property && <div className={styles.selected}><Building2 /><div><strong>{title(property)}</strong><span>{subtitle(property)}</span></div>{dialog.operation === 'LINK' && <button type="button" onClick={() => { setProperty(null); setPreview(null); }}>Cambiar</button>}</div>}
      {dialog.operation !== 'UNLINK' && property && <fieldset className={styles.actSelector}><legend>Actos correspondientes</legend>{catalogs?.acts.map((act) => <label key={act.id}><input type="checkbox" checked={selectedActs.has(act.id)} onChange={() => { toggleAct(act.id); setPreview(null); }} /><span>{act.tipo_acto.nombre}</span></label>)}</fieldset>}
      {dialog.operation === 'UNLINK' && <label className={styles.reason}><span>Motivo de desvinculación</span><textarea rows={3} value={reason} onChange={(event) => { setReason(event.target.value); setPreview(null); }} /></label>}
      {!preview && <button type="button" className={styles.secondary} disabled={working || !property || (dialog.operation !== 'UNLINK' && !actIds.length)} onClick={() => void requestPreview()}>{working ? 'Calculando…' : 'Revisar impacto'}</button>}
      {preview && <div className={`${styles.preview} ${styles[preview.classification.toLowerCase()]}`}><strong>{preview.classification === 'SAFE' ? 'Cambio seguro' : preview.classification === 'REVIEW_REQUIRED' ? 'Revisión requerida' : 'Cambio bloqueado'}</strong><p>CFG-002 reevaluado: {preview.impact.added.length} aplicabilidades nuevas, {preview.impact.removed_or_no_longer_applicable.length} retiradas y {preview.impact.retained.length} conservadas. No se generará ningún documento automáticamente.</p>{preview.impact.protected_work.count > 0 && <p>Trabajo protegido relacionado: {preview.impact.protected_work.count} elementos.</p>}{preview.classification === 'REVIEW_REQUIRED' && <label><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} />Confirmo que revisé el impacto sobre el trabajo existente.</label>}</div>}
      {message && <div className={styles.notice} role="alert">{message}</div>}
    </div><footer><button type="button" className={styles.secondary} onClick={() => setDialog(null)}>Cancelar</button><button type="button" className={styles.primary} disabled={!preview || preview.classification === 'BLOCKED' || working || (preview.classification === 'REVIEW_REQUIRED' && !confirmed)} onClick={() => void apply()}>{working ? 'Aplicando…' : dialog.operation === 'UNLINK' ? 'Desvincular relación' : 'Guardar relación'}</button></footer></section></div>}
  </section>;
}
