import { CheckCircle2, ClipboardList, LoaderCircle, RefreshCw, Save } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { expedientesService } from '../../expedientes.service';
import type { ExpedienteDetail, ExpedienteQuestionnaireInstance } from '../../expedientes.types';
import type { QuestionnaireQuestion } from '../../../settings/catalogs/catalogs.types';
import styles from '../../Expedientes.module.css';

const answerValue = (value: unknown) => value === undefined || value === null ? '' : String(value);
function AnswerField({ question, value, onChange }: { question: QuestionnaireQuestion; value: unknown; onChange: (value: unknown) => void }) {
  if (question.type === 'BOOLEAN') return <select value={answerValue(value)} onChange={(event) => onChange(event.target.value === '' ? '' : event.target.value === 'true')}><option value="">Pendiente</option><option value="true">Sí</option><option value="false">No</option></select>;
  if (question.type === 'CHOICE') return <select value={answerValue(value)} onChange={(event) => onChange(event.target.value)}><option value="">Selecciona…</option>{(question.options || []).map((option) => <option key={option.code} value={option.code}>{option.label}</option>)}</select>;
  if (question.type === 'MULTI_CHOICE') return <fieldset className={styles.questionnaireMulti}>{(question.options || []).map((option) => <label key={option.code}><input type="checkbox" checked={Array.isArray(value) && value.includes(option.code)} onChange={(event) => { const current = Array.isArray(value) ? value : []; onChange(event.target.checked ? [...current, option.code] : current.filter((item) => item !== option.code)); }} />{option.label}</label>)}</fieldset>;
  const type = question.type === 'DATE' ? 'date' : question.type === 'NUMBER' ? 'number' : 'text';
  return <input type={type} value={answerValue(value)} onChange={(event) => onChange(type === 'number' && event.target.value !== '' ? Number(event.target.value) : event.target.value)} />;
}

export function QuestionnairesTab({ expediente }: { expediente: ExpedienteDetail }) {
  const [instances, setInstances] = useState<ExpedienteQuestionnaireInstance[]>([]); const [answers, setAnswers] = useState<Record<string, Record<string, unknown>>>({});
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(''); const [message, setMessage] = useState('');
  const load = useCallback(async () => { setLoading(true); setMessage(''); try { const data = await expedientesService.questionnaires(expediente.id); setInstances(data); setAnswers(Object.fromEntries(data.map((item) => [item.assessmentId, { ...(item.latestResponse?.answers_json || {}) }]))); } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'No pudimos cargar los cuestionarios aplicables.'); } finally { setLoading(false); } }, [expediente.id]);
  useEffect(() => { void load(); }, [load]);
  const ensure = async () => { setBusy('ensure'); setMessage(''); try { await expedientesService.ensureQuestionnaires(expediente.id); await load(); } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'No fue posible actualizar la aplicabilidad.'); } finally { setBusy(''); } };
  const save = async (item: ExpedienteQuestionnaireInstance, finalize: boolean) => { setBusy(item.assessmentId); setMessage(''); try { if (!item.latestResponse?.base_fingerprint) throw new Error('Recarga el cuestionario antes de guardar.'); await expedientesService.saveQuestionnaire(expediente.id, { assessmentId: item.assessmentId, baseFingerprint: item.latestResponse.base_fingerprint, answers: answers[item.assessmentId] || {}, finalize, idempotencyKey: crypto.randomUUID() }); await load(); setMessage(finalize ? 'Cuestionario finalizado y registrado.' : 'Borrador guardado.'); } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'No fue posible guardar las respuestas.'); } finally { setBusy(''); } };
  if (loading) return <section className={styles.sectionCard}><div className={styles.inlineState} role="status"><LoaderCircle className={styles.spin} />Consultando la aplicabilidad de Cumplimiento…</div></section>;
  return <div className={styles.tabStack}><section className={styles.sectionCard}><header><div><h2>Cuestionarios</h2><p>Dos bancos globales: uno por persona y uno por cada acto aplicable. Cumplimiento PLD/UIF es la única autoridad de aplicabilidad.</p></div>{expediente.capabilities.canWrite && <button type="button" className={styles.secondaryButton} disabled={busy === 'ensure'} onClick={() => void ensure()}><RefreshCw size={15} />Actualizar desde Cumplimiento</button>}</header>{message && <div className={styles.sectionError} role="status">{message}</div>}{instances.length === 0 ? <p className={styles.sectionEmpty}>Cumplimiento no determinó cuestionarios aplicables para la revisión vigente.</p> : <div className={styles.questionnaireInstances}>{instances.map((item) => { const current = answers[item.assessmentId] || {}; const finalized = item.latestResponse?.estado === 'FINALIZADO'; return <article key={item.assessmentId} className={styles.questionnaireInstance}><header><span><ClipboardList size={18} /></span><div><small>{item.bank === 'PERSONAL' ? 'PERSONAL' : 'ACTO / OPERACIÓN'} · v{item.version.number}</small><h3>{item.artifact.name}</h3><p>{item.subject.label}</p></div>{finalized && <em><CheckCircle2 size={14} />Finalizado</em>}</header>{item.definition.sections.map((section) => <fieldset key={section.id} disabled={finalized}><legend>{section.label}</legend>{(section.questions || []).filter((question) => question.active !== false).map((question) => <label key={question.id}><span>{question.label}{question.required && <b aria-label="Obligatoria"> *</b>}</span><AnswerField question={question} value={current[question.id]} onChange={(value) => setAnswers((state) => ({ ...state, [item.assessmentId]: { ...(state[item.assessmentId] || {}), [question.id]: value } }))} /></label>)}</fieldset>)}{expediente.capabilities.canWrite && !finalized && <footer><button type="button" className={styles.secondaryButton} disabled={busy === item.assessmentId} onClick={() => void save(item, false)}><Save size={15} />Guardar borrador</button><button type="button" className={styles.primaryButton} disabled={busy === item.assessmentId} onClick={() => void save(item, true)}>{busy === item.assessmentId && <LoaderCircle className={styles.spin} size={15} />}Finalizar cuestionario</button></footer>}</article>; })}</div>}</section></div>;
}
