import { CalendarDays, CheckSquare2, Clock3, FileWarning } from 'lucide-react';
import type { ExpedienteDetail } from '../../expedientes.types';
import { dateTime, statusLabels } from '../../expedienteFormatters';
import { ExpedienteNextStep } from '../ExpedienteNextStep';
import { ExpedienteReadiness } from '../ExpedienteReadiness';
import { PostfirmaPanel } from '../PostfirmaPanel';
import { DeliveryPanel } from '../DeliveryPanel';
import styles from '../../Expedientes.module.css';
export function SummaryTab({ expediente, onChanged }: { expediente: ExpedienteDetail; onChanged(): void }) { const pendingTasks = (expediente.tareas || []).filter((item) => item.estatus !== 'COMPLETADA'); const pendingReqs = (expediente.requisitos_docs || []).filter((item) => item.obligatorio && !['VALIDADO', 'OMITIDO_JUSTIFICADO'].includes(item.estatus)); return <div className={styles.tabStack}><ExpedienteNextStep expediente={expediente} /><ExpedienteReadiness readiness={expediente.readiness} /><DeliveryPanel expediente={expediente} onChanged={onChanged} /><section className={styles.summaryGrid}><article><span><Clock3 size={18} /></span><small>Estado actual</small><strong>{statusLabels[expediente.estatus]}</strong><p>{expediente.etapaActual?.nombre_snapshot || expediente.etapa_actual_nombre || 'Sin etapa configurada'}</p></article><article><span><FileWarning size={18} /></span><small>Requisitos pendientes</small><strong>{pendingReqs.length}</strong><p>{pendingReqs[0]?.nombre || 'Sin requisitos obligatorios pendientes'}</p></article><article><span><CheckSquare2 size={18} /></span><small>Tareas abiertas</small><strong>{pendingTasks.length}</strong><p>{pendingTasks[0]?.titulo || 'Sin tareas abiertas'}</p></article><article><span><CalendarDays size={18} /></span><small>Firma</small><strong>{expediente.fecha_real_firma ? 'Realizada' : expediente.fecha_estimada_firma ? 'Programada' : 'Sin programar'}</strong><p>{dateTime(expediente.fecha_real_firma || expediente.fecha_estimada_firma)}</p></article></section><PostfirmaPanel expediente={expediente} onChanged={onChanged} /></div>; }
