import { AlertTriangle, CalendarClock, Check, Circle, Clock3, Download, FileCog, LoaderCircle, LockKeyhole, Play, Plus, RotateCcw, Settings2, UserRound } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { expedientesService } from '../../expedientes.service';
import type { ExpedienteDetail, ExpedienteSeguimiento, ExpedienteTransition, SeguimientoActivity, SeguimientoEstado } from '../../expedientes.types';
import { dateTime, macroLabels } from '../../expedienteFormatters';
import styles from '../../Expedientes.module.css';
import { complianceService } from '../../../compliance/compliance.service';

const stateClass: Record<SeguimientoEstado, string> = {
  NO_INICIADO: 'trackingStateNeutral', EN_PROCESO: 'trackingStateProgress', EN_ESPERA_EXTERNA: 'trackingStateWaiting',
  COMPLETADO: 'trackingStateDone', BLOQUEADO: 'trackingStateBlocked', NO_APLICA: 'trackingStateMuted',
};

export function WorkflowTab({ expediente, onChanged }: { expediente: ExpedienteDetail; onChanged(): void }) {
  const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const [dialog, setDialog] = useState<'scheduled' | 'effective' | null>(null); const [documentRevision, setDocumentRevision] = useState('');
  const [signaturePreflight, setSignaturePreflight] = useState<{ ready: boolean; ready_label: string; count: number; hash: string; missing: Array<{ id: string; label: string; source: string; action: string; status: string }> } | null>(null);
  const [signatureKey, setSignatureKey] = useState('');
  const completed = new Map((expediente.etapas || []).map((item: any) => [item.clave_snapshot, item]));
  const stages = expediente.workflow.stages || [];
  const transition = expediente.estatus === 'FIRMA_PROGRAMADA' ? expediente.workflow.transitions.find((item) => item.status === 'FIRMADO') || expediente.workflow.transitions[0] : expediente.workflow.transitions[0];
  const advance = async (target: ExpedienteTransition, data?: { date: string; place?: string }) => { setSaving(true); setError(''); try { await expedientesService.transition(expediente.id, { expected_version: expediente.version, nuevo_estatus: target.status, ...(target.stage?.clave ? { nueva_etapa_clave: target.stage.clave } : {}), ...(target.requires_signature_data && data ? { datos_firma: { fecha_firma: data.date, lugar: data.place || '' } } : {}), ...(target.requires_effective_date && data ? { fecha_efectiva: data.date } : {}), ...(target.status === 'FIRMADO' ? { document_revision: documentRevision, mode: 'CONFIRM', preflight_hash: signaturePreflight?.hash, idempotency_key: signatureKey } : {}) }); setDialog(null); setSignaturePreflight(null); onChanged(); } catch { setError('No fue posible avanzar. Revisa los requisitos pendientes y vuelve a confirmar.'); } finally { setSaving(false); } };
  const startTransition = async () => { if (!transition) return; if (transition.status === 'FIRMADO') { setSaving(true); setError(''); try { const [appendix, preview] = await Promise.all([expedientesService.documentAppendix(expediente.id), expedientesService.signaturePreflight(expediente.id, expediente.version)]); setDocumentRevision(appendix.revision); setSignaturePreflight(preview.preflight); setSignatureKey(crypto.randomUUID()); setDialog('effective'); } catch { setError('No pudimos revisar la preparación documental antes de firmar.'); } finally { setSaving(false); } return; } if (transition.requires_signature_data) setDialog('scheduled'); else if (transition.requires_effective_date) setDialog('effective'); else void advance(transition); };
  const actionable = expediente.capabilities.canWrite && transition && !transition.requires_notes && transition.status !== 'ENTREGADO';
  const generatePending = async () => { setSaving(true); setError(''); try { await complianceService.h6GeneratePending(expediente.id); setError('Los formatos disponibles quedaron reconciliados. Los generados aún requieren revisión y firma.'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible generar los formatos pendientes.'); } finally { setSaving(false); } };
  const downloadPackage = async () => { setSaving(true); setError(''); try { const { blob } = await complianceService.h6SignaturePackage(expediente.id); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `paquete-firma-${expediente.numero_pravia}.${blob.type === 'application/pdf' ? 'pdf' : 'zip'}`; link.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible preparar el paquete de firma.'); } finally { setSaving(false); } };
  return <div className={styles.tabStack}>
    <OperationalFollowup expediente={expediente} />
    <section className={styles.sectionCard}><header><div><h2>Hitos contractuales</h2><p>Transición canónica del expediente y snapshot documental de EXP-004. Versión {expediente.flujoVersion?.version ?? '—'} congelada.</p></div><div className={styles.complianceDocumentHeaderActions}>{transition?.status === 'FIRMADO' && expediente.capabilities.canWrite && <button type="button" disabled={saving} onClick={() => void generatePending()}><FileCog />Generar formatos pendientes</button>}<button type="button" disabled={saving} onClick={() => void downloadPackage()}><Download />Descargar paquete</button>{actionable && <button type="button" className={styles.primaryButton} disabled={saving} onClick={startTransition}>{saving ? <LoaderCircle className={styles.spin} size={16} /> : <Play size={16} />}{transition.label}</button>}</div></header>{error && <div className={styles.inlineError} role="status">{error}</div>}<div className={styles.workflowSummary}><span>{macroLabels[expediente.macrofase]}</span><strong>{expediente.etapaActual?.nombre_snapshot || expediente.etapa_actual_nombre || 'Sin etapa'}</strong><small>{expediente.workflow.current_status_label}</small></div>{stages.length ? <ol className={styles.timeline}>{stages.map((stage: any) => { const instance: any = completed.get(stage.clave); const current = stage.clave === expediente.etapaActual?.clave_snapshot; const done = Boolean(instance?.completada); return <li key={stage.clave} className={current ? styles.timelineCurrent : done ? styles.timelineDone : ''}><span>{done ? <Check size={14} /> : <Circle size={12} />}</span><div><strong>{stage.nombre}</strong><small>{stage.estado_general_relacionado?.replaceAll('_', ' ').toLocaleLowerCase('es-MX')}{stage.obligatoria ? ' · Obligatoria' : ' · Opcional'}</small></div><time>{instance?.fecha_fin ? dateTime(instance.fecha_fin) : current ? 'En curso' : 'Próxima'}</time></li>; })}</ol> : <p className={styles.sectionEmpty}>Este expediente no tiene hitos macro configurados.</p>}{dialog && transition && <TransitionDateDialog mode={dialog} preflight={signaturePreflight} onClose={() => { setDialog(null); setSignaturePreflight(null); }} onGoToCompliance={() => { window.location.hash = 'cumplimiento'; }} onSave={(data) => void advance(transition, data)} saving={saving} />}</section>
  </div>;
}

function OperationalFollowup({ expediente }: { expediente: ExpedienteDetail }) {
  const [data, setData] = useState<ExpedienteSeguimiento | null>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [saving, setSaving] = useState('');
  const [reopen, setReopen] = useState<SeguimientoActivity | null>(null); const [reason, setReason] = useState('');
  const [adjust, setAdjust] = useState<SeguimientoActivity | null>(null);
  const [creatingExtraordinary, setCreatingExtraordinary] = useState(false);
  const [extraordinary, setExtraordinary] = useState({ expediente_acto_id: '', nombre: '', descripcion: '', duracion_estimada: '1', tipo_dias: 'HABILES', margen_seguridad: '0' });
  const [adjustment, setAdjustment] = useState({ duration: '', margin: '', dayType: 'HABILES' as 'HABILES' | 'NATURALES', reason: '' });
  const load = useCallback(async () => { setLoading(true); setError(''); try { setData(await expedientesService.seguimiento(expediente.id)); } catch { setError('No pudimos cargar el seguimiento operativo.'); } finally { setLoading(false); } }, [expediente.id]);
  useEffect(() => { void load(); }, [load]);
  const update = async (activity: SeguimientoActivity, estado: SeguimientoEstado) => { setSaving(activity.id); setError(''); try { await expedientesService.updateSeguimientoActivity(expediente.id, activity.id, { expected_version: activity.version, estado }); await load(); } catch { setError('La actividad cambió o sus dependencias siguen pendientes. Recarga e inténtalo de nuevo.'); } finally { setSaving(''); } };
  const assign = async (activity: SeguimientoActivity, responsibleId: string) => { setSaving(activity.id); setError(''); try { await expedientesService.updateSeguimientoActivity(expediente.id, activity.id, { expected_version: activity.version, responsable_id: responsibleId || null, razon: 'Responsable operativo actualizado.' }); await load(); } catch { setError('No pudimos actualizar el responsable.'); } finally { setSaving(''); } };
  const materialize = async () => { setSaving('materialize'); setError(''); try { await expedientesService.materializeSeguimiento(expediente.id); await load(); } catch { setError('No pudimos preparar el seguimiento desde la configuración vigente.'); } finally { setSaving(''); } };
  const confirmReopen = async () => { if (!reopen || !reason.trim()) return; setSaving(reopen.id); setError(''); try { await expedientesService.reopenSeguimientoActivity(expediente.id, reopen.id, { expected_version: reopen.version, razon: reason }); setReopen(null); setReason(''); await load(); } catch { setError('La actividad cambió. Recarga antes de reabrir.'); } finally { setSaving(''); } };
  const openAdjustment = (activity: SeguimientoActivity) => { const current = activity.excepcion_operativa; setAdjust(activity); setAdjustment({ duration: current?.duracion_estimada === undefined ? String(activity.tiempo.estimado) : String(current.duracion_estimada), margin: current?.margen_seguridad === undefined ? String(activity.tiempo.margen) : String(current.margen_seguridad), dayType: current?.tipo_dias || activity.tiempo.tipo_dias, reason: current?.motivo || '' }); };
  const confirmAdjustment = async () => { if (!adjust || !adjustment.reason.trim()) return; const duration = Number(adjustment.duration); const margin = Number(adjustment.margin); if (!Number.isInteger(duration) || duration < 0 || !Number.isInteger(margin) || margin < 0) { setError('La duración y el margen deben ser enteros iguales o mayores a cero.'); return; } setSaving(adjust.id); setError(''); try { await expedientesService.updateSeguimientoActivity(expediente.id, adjust.id, { expected_version: adjust.version, excepcion_operativa: { duracion_estimada: duration, margen_seguridad: margin, tipo_dias: adjustment.dayType, motivo: adjustment.reason.trim() }, razon: adjustment.reason.trim() }); setAdjust(null); await load(); } catch { setError('La actividad cambió. Recarga antes de guardar el ajuste.'); } finally { setSaving(''); } };
  const createExtraordinary = async () => { if (!extraordinary.expediente_acto_id || !extraordinary.nombre.trim()) return; setSaving('extraordinary'); setError(''); try { await expedientesService.createSeguimientoExtraordinary(expediente.id, { ...extraordinary, duracion_estimada: Number(extraordinary.duracion_estimada), margen_seguridad: Number(extraordinary.margen_seguridad), razon: 'Actividad extraordinaria agregada desde Seguimiento.' }); setCreatingExtraordinary(false); setExtraordinary({ expediente_acto_id: '', nombre: '', descripcion: '', duracion_estimada: '1', tipo_dias: 'HABILES', margen_seguridad: '0' }); await load(); } catch { setError('No pudimos agregar la actividad extraordinaria.'); } finally { setSaving(''); } };
  if (loading) return <section className={styles.sectionCard}><div className={styles.inlineState} role="status"><LoaderCircle className={styles.spin} />Cargando seguimiento…</div></section>;
  return <section className={styles.sectionCard} aria-labelledby="operational-followup-title">
    <header><div><h2 id="operational-followup-title">Seguimiento operativo</h2><p>Copias operativas de CFG-001 por acto. La configuración maestra no se modifica.</p></div><div className={styles.complianceDocumentHeaderActions}>{expediente.capabilities.canWrite && Boolean(data?.actos.length) && <button type="button" onClick={() => setCreatingExtraordinary(true)}><Plus size={15} />Actividad extraordinaria</button>}{expediente.capabilities.canWrite && !data?.actos.length && <button type="button" className={styles.primaryButton} disabled={saving === 'materialize'} onClick={() => void materialize()}>{saving === 'materialize' && <LoaderCircle className={styles.spin} size={15} />}Preparar seguimiento</button>}</div></header>
    {error && <div className={styles.inlineError} role="alert">{error}</div>}
    {data?.proyeccion && <div className={styles.operationalProjection} aria-label="Proyección operativa"><div><small>Ruta crítica restante</small><strong>{data.proyeccion.dias_restantes_ruta_critica} días</strong></div><div><small>Fecha final estimada</small><strong>{data.proyeccion.fecha_final_estimada ? dateTime(data.proyeccion.fecha_final_estimada) : 'Sin actividades'}</strong></div><span>Ramas paralelas: máximo, no suma</span></div>}
    {data?.fecha_firma_manual && <div className={styles.signatureSignal}><CalendarClock size={18} /><div><small>Fecha de firma manual</small><strong>{dateTime(data.fecha_firma_manual)}</strong></div><span>{data.firma.efectiva ? 'Firma realizada · Postfirma activa' : 'Prefirma en curso'}</span></div>}
    {data?.actos.length ? <div className={styles.trackingActs}>{data.actos.map((act, actIndex) => <section key={act.expediente_acto_id} className={styles.trackingAct} aria-labelledby={`tracking-act-${act.expediente_acto_id}`}><header><div><small>Acto {actIndex + 1}</small><h3 id={`tracking-act-${act.expediente_acto_id}`}>{act.nombre}</h3></div><span>{act.estatus === 'ACTIVO' ? 'Activo' : 'Referencia histórica'}</span></header>{act.etapas.map((stage) => <section key={`${act.expediente_acto_id}-${stage.orden}`} className={styles.trackingStage}><header><h4>{stage.nombre}</h4><span>{stage.actividades.filter((item) => item.estado_efectivo === 'COMPLETADO').length}/{stage.actividades.length} completadas</span></header><div className={styles.trackingGrid}>{stage.actividades.map((activity) => <TrackingActivityCard key={activity.id} activity={activity} canWrite={expediente.capabilities.canWrite} responsibleOptions={data.responsables} saving={saving === activity.id} onState={(state) => void update(activity, state)} onAssign={(id) => void assign(activity, id)} onAdjust={() => openAdjustment(activity)} onReopen={() => { setReopen(activity); setReason(''); }} />)}</div></section>)}</section>)}</div> : <div className={styles.sectionEmpty}>No hay actividades operativas materializadas. Prepararlas no inventa avance ni fechas históricas.</div>}
    {data?.entrega.completada && <div className={styles.deliveryMilestone} role="status"><Check size={18} /><div><strong>Entregado al cliente</strong><small>{dateTime(data.entrega.fecha)} · Las alertas operativas normales están detenidas; el historial permanece.</small></div></div>}
    {reopen && <div className={styles.dialogBackdrop}><section className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby="reopen-title"><header><div><h2 id="reopen-title">Reabrir actividad</h2><p>El avance downstream se reevaluará sin borrar trabajo existente.</p></div></header><div className={styles.dialogBody}><label>Motivo<textarea autoFocus rows={3} value={reason} onChange={(event) => setReason(event.target.value)} /></label></div><footer><button type="button" className={styles.secondaryButton} onClick={() => setReopen(null)}>Cancelar</button><button type="button" className={styles.primaryButton} disabled={!reason.trim() || saving === reopen.id} onClick={() => void confirmReopen()}>Reabrir y reevaluar</button></footer></section></div>}
    {adjust && <div className={styles.dialogBackdrop}><section className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby="adjustment-title"><header><div><h2 id="adjustment-title">Ajuste particular</h2><p>Solo modifica esta copia operativa. CFG-001 permanece intacto.</p></div></header><div className={styles.dialogBody}><div className={styles.inlineFields}><label>Duración estimada<input type="number" min="0" step="1" value={adjustment.duration} onChange={(event) => setAdjustment((value) => ({ ...value, duration: event.target.value }))} /></label><label>Margen de seguridad<input type="number" min="0" step="1" value={adjustment.margin} onChange={(event) => setAdjustment((value) => ({ ...value, margin: event.target.value }))} /></label></div><label>Tipo de días<select value={adjustment.dayType} onChange={(event) => setAdjustment((value) => ({ ...value, dayType: event.target.value as 'HABILES' | 'NATURALES' }))}><option value="HABILES">Hábiles</option><option value="NATURALES">Naturales</option></select></label><label>Motivo del ajuste<textarea autoFocus rows={3} value={adjustment.reason} onChange={(event) => setAdjustment((value) => ({ ...value, reason: event.target.value }))} /></label></div><footer><button type="button" className={styles.secondaryButton} onClick={() => setAdjust(null)}>Cancelar</button><button type="button" className={styles.primaryButton} disabled={!adjustment.reason.trim() || saving === adjust.id} onClick={() => void confirmAdjustment()}>Guardar ajuste particular</button></footer></section></div>}
    {creatingExtraordinary && <div className={styles.dialogBackdrop}><section className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby="extraordinary-title"><header><div><h2 id="extraordinary-title">Actividad extraordinaria</h2><p>Se agrega sólo a este expediente y nunca modifica CFG-001.</p></div></header><div className={styles.dialogBody}><label>Acto<select value={extraordinary.expediente_acto_id} onChange={(event) => setExtraordinary({ ...extraordinary, expediente_acto_id: event.target.value })}><option value="">Selecciona</option>{data?.actos.map((act) => <option key={act.expediente_acto_id} value={act.expediente_acto_id}>{act.nombre}</option>)}</select></label><label>Nombre<input value={extraordinary.nombre} onChange={(event) => setExtraordinary({ ...extraordinary, nombre: event.target.value })} /></label><label>Descripción<textarea rows={2} value={extraordinary.descripcion} onChange={(event) => setExtraordinary({ ...extraordinary, descripcion: event.target.value })} /></label><div className={styles.inlineFields}><label>Duración<input type="number" min="0" value={extraordinary.duracion_estimada} onChange={(event) => setExtraordinary({ ...extraordinary, duracion_estimada: event.target.value })} /></label><label>Margen<input type="number" min="0" value={extraordinary.margen_seguridad} onChange={(event) => setExtraordinary({ ...extraordinary, margen_seguridad: event.target.value })} /></label></div></div><footer><button type="button" className={styles.secondaryButton} onClick={() => setCreatingExtraordinary(false)}>Cancelar</button><button type="button" className={styles.primaryButton} disabled={!extraordinary.expediente_acto_id || !extraordinary.nombre.trim() || saving === 'extraordinary'} onClick={() => void createExtraordinary()}>Agregar actividad</button></footer></section></div>}
  </section>;
}

function TrackingActivityCard({ activity, canWrite, responsibleOptions, saving, onState, onAssign, onAdjust, onReopen }: { activity: SeguimientoActivity; canWrite: boolean; responsibleOptions: Array<{ id: string; nombre: string; apellido?: string | null }>; saving: boolean; onState(state: SeguimientoEstado): void; onAssign(id: string): void; onAdjust(): void; onReopen(): void }) {
  const blocked = activity.estado_efectivo === 'BLOQUEADO';
  const actions: Array<{ state: SeguimientoEstado; label: string }> = activity.estado_operativo === 'NO_INICIADO' || activity.estado_operativo === 'BLOQUEADO' ? [{ state: 'EN_PROCESO', label: 'Iniciar' }, { state: 'NO_APLICA', label: 'No aplica' }] : activity.estado_operativo === 'EN_PROCESO' ? [{ state: 'EN_ESPERA_EXTERNA', label: 'Espera externa' }, { state: 'COMPLETADO', label: 'Completar' }, { state: 'NO_APLICA', label: 'No aplica' }] : activity.estado_operativo === 'EN_ESPERA_EXTERNA' ? [{ state: 'EN_PROCESO', label: 'Retomar' }, { state: 'COMPLETADO', label: 'Completar' }] : [];
  return <article className={styles.trackingActivity} data-state={activity.estado_efectivo} aria-label={`${activity.actividad_nombre_snapshot}: ${activity.estado_label}`}><header><span className={`${styles.trackingState} ${styles[stateClass[activity.estado_efectivo]]}`}>{activity.estado_efectivo === 'BLOQUEADO' ? <LockKeyhole size={13} /> : activity.estado_efectivo === 'COMPLETADO' ? <Check size={13} /> : activity.estado_efectivo === 'EN_PROCESO' ? <Play size={13} /> : <Clock3 size={13} />}{activity.estado_label}</span>{activity.tiempo.atrasada && <span className={styles.delayBadge}><AlertTriangle size={13} />Atrasada</span>}</header><h5>{activity.actividad_nombre_snapshot}</h5>{activity.actividad_descripcion_snapshot && <p>{activity.actividad_descripcion_snapshot}</p>}<dl><div><dt>Estimado</dt><dd>{activity.tiempo.estimado} días {activity.tiempo.tipo_dias === 'HABILES' ? 'hábiles' : 'naturales'}</dd></div><div><dt>Margen</dt><dd>{activity.tiempo.margen} días</dd></div><div><dt>Transcurrido</dt><dd>{activity.primera_fecha_inicio ? `${activity.tiempo.transcurrido} días` : 'Sin iniciar'}</dd></div></dl>{activity.excepcion_operativa && <div className={styles.operationalAdjustment}><Settings2 size={14} /><span><strong>Ajuste particular:</strong> {activity.excepcion_operativa.motivo}</span></div>}{activity.bloqueada_por.length > 0 && <div className={styles.blockingCause}><LockKeyhole size={14} /><span><strong>Bloqueada por:</strong> {activity.bloqueada_por.map((item) => item.nombre).join(', ')}</span></div>}{activity.dependencias.length > 0 && <details><summary>Dependencias ({activity.dependencias.length})</summary><ul>{activity.dependencias.map((dep) => <li key={dep.id}>{dep.nombre} · {String(dep.estado).replaceAll('_', ' ').toLocaleLowerCase('es-MX')}</li>)}</ul></details>}{activity.requiere_revision && <div className={styles.reviewSignal} role="status"><AlertTriangle size={14} />{activity.motivo_revision}</div>}<label className={styles.trackingResponsible}><UserRound size={14} /><span>Responsable</span><select aria-label={`Responsable de ${activity.actividad_nombre_snapshot}`} value={activity.responsable_id || ''} disabled={!canWrite || saving} onChange={(event) => onAssign(event.target.value)}><option value="">Sin asignar</option>{responsibleOptions.map((person) => <option key={person.id} value={person.id}>{person.nombre} {person.apellido || ''}</option>)}</select></label>{canWrite && <footer>{saving && <LoaderCircle className={styles.spin} size={15} />}<button type="button" disabled={saving} onClick={onAdjust}><Settings2 size={14} />Ajustar</button>{actions.map((action) => <button key={action.state} type="button" disabled={saving || (blocked && action.state !== 'NO_APLICA')} onClick={() => onState(action.state)}>{action.label}</button>)}{['COMPLETADO', 'NO_APLICA'].includes(activity.estado_operativo) && <button type="button" disabled={saving} onClick={onReopen}><RotateCcw size={14} />Reabrir</button>}</footer>}</article>;
}

function TransitionDateDialog({ mode, preflight, onClose, onGoToCompliance, onSave, saving }: { mode: 'scheduled' | 'effective'; preflight?: { ready: boolean; ready_label: string; count: number; missing: Array<{ id: string; label: string }> } | null; onClose(): void; onGoToCompliance(): void; onSave(data: { date: string; place?: string }): void; saving: boolean }) {
  const [date, setDate] = useState(''); const [place, setPlace] = useState(''); const scheduled = mode === 'scheduled';
  return <div className={styles.dialogBackdrop}><section className={styles.dialog} role="dialog" aria-modal="true" aria-label={scheduled ? 'Programar firma' : 'Registrar firma efectiva'}><header><div><h2>{scheduled ? 'Programar firma' : 'Registrar firma efectiva'}</h2><p>{scheduled ? 'Registra manualmente la fecha prevista y el lugar.' : 'Al confirmar, el apéndice documental revisado quedará congelado. Si cambió, PRAVIA bloqueará la firma.'}</p></div></header><div className={styles.dialogBody}>{!scheduled && preflight && <div className={preflight.ready ? styles.inlineSuccess : styles.inlineError} role="status"><strong>{preflight.ready_label}</strong>{preflight.missing.length > 0 && <ul>{preflight.missing.map((item) => <li key={item.id}>{item.label}</li>)}</ul>}</div>}<label>{scheduled ? 'Fecha y hora programada' : 'Fecha y hora efectiva'}<input type="datetime-local" value={date} onChange={(event) => setDate(event.target.value)} /></label>{scheduled && <label>Lugar<input value={place} onChange={(event) => setPlace(event.target.value)} placeholder="Notaría o ubicación" /></label>}</div><footer>{!scheduled && preflight?.ready === false ? <><button type="button" className={styles.secondaryButton} onClick={onClose}>Continuar</button><button type="button" className={styles.primaryButton} onClick={onGoToCompliance}>Ir a Cumplimiento</button></> : <><button type="button" className={styles.secondaryButton} onClick={onClose}>Cancelar</button><button type="button" className={styles.primaryButton} disabled={!date || (scheduled && !place) || saving} onClick={() => onSave({ date, place })}>{saving && <LoaderCircle className={styles.spin} size={15} />}{scheduled ? 'Guardar programación' : 'Registrar firma y congelar apéndice'}</button></>}</footer></section></div>;
}
