import { apiRequest } from '../../services/api/client';

export type Exp008Document = { id: string; tipo: string; documento: { id: string; nombre_original: string; mime_type: string } };
export type Exp008Income = { id: string; estado: 'PENDIENTE_APLICACION'|'APLICADO'|'ANULADO'; concepto_contexto?: string|null; monto_reportado?: string|null; monto_validado?: string|null; honorarios_aplicados?: string|null; impuestos_derechos_aplicados?: string|null; created_at: string; aplicado_at?: string|null; movimiento_id?: string|null; documentos: Exp008Document[]; reportadoPor?: { nombre:string;apellido?:string|null } };
export type Exp008Request = { id:string;via:'INTERNA'|'DOCUMENTO_EXTERNO';estado:'PENDIENTE'|'PAGADA'|'ANULADA';concepto:string;importe:string;dependencia?:string|null;beneficiario?:string|null;created_at:string;pagado_at?:string|null;movimiento_id?:string|null;documentos:Exp008Document[];creadoPor?:{nombre:string;apellido?:string|null} };
export type Exp008AIProposal = { id:string;estado:'PENDIENTE'|'CONFLICTO'|'VALIDADA'|'RECHAZADA';propuesta:Record<string,string|number|null>;provenance:Array<{campo:string;documento_id:string;documento:string;pagina?:number|null;fragmento?:string|null;confianza?:number|null}>;conflictos?:Array<string|Record<string,unknown>>|null;faltantes?:string[]|null;modelo:string };
export type Exp008Data = { expediente:{id:string;numero_pravia:string};ingresosReportados:Exp008Income[];solicitudesPago:Exp008Request[];presupuesto?:{subtotal_honorarios:string;subtotal_impuestos_derechos:string;total:string;version:number}|null;catalogs:{accounts:Array<{id:string;institucion:string;alias:string;ultimos_cuatro?:string|null;moneda:string}>;categories:Array<{id:string;clave:string;nombre:string;direccion:string}>};capabilities:{canRead:boolean;canReport:boolean;canCreateRequest:boolean;canApply:boolean;canUseAI:boolean;canReadDocuments:boolean;canRetireDocuments:boolean} };

export const exp008VisualFixture: Exp008Data = { expediente:{id:'exp-isr-fixture',numero_pravia:'EXP-2026-00318'}, ingresosReportados:[{id:'income-pending',estado:'PENDIENTE_APLICACION',concepto_contexto:'Anticipo de honorarios y gastos',monto_reportado:'25000.00',created_at:'2026-08-29T15:20:00.000Z',reportadoPor:{nombre:'Carlos',apellido:'Mendoza'},documentos:[{id:'income-link',tipo:'COMPROBANTE_INGRESO',documento:{id:'income-document',nombre_original:'transferencia-anticipo.pdf',mime_type:'application/pdf'}}]},{id:'income-applied',estado:'APLICADO',concepto_contexto:'Primer anticipo',monto_reportado:'40000.00',monto_validado:'40000.00',honorarios_aplicados:'30000.00',impuestos_derechos_aplicados:'10000.00',created_at:'2026-08-25T14:00:00.000Z',aplicado_at:'2026-08-26T17:30:00.000Z',movimiento_id:'movement-fixture',reportadoPor:{nombre:'Andrea',apellido:'Ruiz'},documentos:[{id:'applied-link',tipo:'COMPROBANTE_INGRESO',documento:{id:'applied-document',nombre_original:'comprobante-validado.pdf',mime_type:'application/pdf'}}]}], solicitudesPago:[{id:'request-pending',via:'DOCUMENTO_EXTERNO',estado:'PENDIENTE',concepto:'Derechos de inscripción RPP',importe:'18500.00',dependencia:'Registro Público de la Propiedad',beneficiario:'Gobierno del Estado',created_at:'2026-08-29T16:10:00.000Z',creadoPor:{nombre:'Carlos',apellido:'Mendoza'},documentos:[{id:'request-source-link',tipo:'SOLICITUD_ORIGEN',documento:{id:'request-source-document',nombre_original:'ficha-pago-rpp.pdf',mime_type:'application/pdf'}}]},{id:'request-paid',via:'INTERNA',estado:'PAGADA',concepto:'Certificado de libertad de gravamen',importe:'450.00',created_at:'2026-08-24T13:00:00.000Z',pagado_at:'2026-08-25T19:00:00.000Z',movimiento_id:'expense-fixture',creadoPor:{nombre:'Andrea',apellido:'Ruiz'},documentos:[{id:'payment-link',tipo:'COMPROBANTE_PAGO',documento:{id:'payment-document',nombre_original:'comprobante-pago.pdf',mime_type:'application/pdf'}},{id:'fiscal-link',tipo:'COMPROBANTE_FISCAL',documento:{id:'fiscal-document',nombre_original:'factura-servicio.pdf',mime_type:'application/pdf'}}]}], presupuesto:{subtotal_honorarios:'100000.00',subtotal_impuestos_derechos:'18500.00',total:'118500.00',version:1}, catalogs:{accounts:[{id:'account-1',institucion:'BBVA',alias:'Operativa',ultimos_cuatro:'2048',moneda:'MXN'}],categories:[{id:'category-income',clave:'HONORARIOS',nombre:'Honorarios',direccion:'INGRESO'},{id:'category-expense',clave:'DERECHOS',nombre:'Impuestos y derechos',direccion:'EGRESO'}]}, capabilities:{canRead:true,canReport:true,canCreateRequest:true,canApply:true,canUseAI:true,canReadDocuments:true,canRetireDocuments:true} };

const form = (values:Record<string,unknown>, files:Record<string,File|undefined>={}) => { const body=new FormData(); Object.entries(values).forEach(([key,value])=>{if(value!==undefined&&value!==null)body.append(key,String(value));}); Object.entries(files).forEach(([key,value])=>{if(value)body.append(key,value);}); return body; };
const root = (id:string) => `/expedientes/${encodeURIComponent(id)}/finanzas-operativas`;
export const expedienteFinanceService = {
  read(id:string,signal?:AbortSignal){if(import.meta.env.DEV&&new URLSearchParams(window.location.search).get('fixture')==='exp008')return Promise.resolve(exp008VisualFixture);return apiRequest<Exp008Data>(root(id),{signal});},
  reportIncome(id:string,input:Record<string,unknown>,file:File){return apiRequest(`${root(id)}/ingresos`,{method:'POST',body:form(input,{file})});},
  createInternalRequest(id:string,input:Record<string,unknown>){return apiRequest(`${root(id)}/solicitudes/interna`,{method:'POST',body:JSON.stringify(input)});},
  createExternalRequest(id:string,input:Record<string,unknown>,file:File){return apiRequest(`${root(id)}/solicitudes/externa`,{method:'POST',body:form(input,{file})});},
  applyIncome(id:string,incomeId:string,input:Record<string,unknown>){return apiRequest(`${root(id)}/ingresos/${encodeURIComponent(incomeId)}/aplicar`,{method:'POST',body:JSON.stringify(input)});},
  payRequest(id:string,requestId:string,input:Record<string,unknown>,payment?:File,fiscal?:File){return apiRequest(`${root(id)}/solicitudes/${encodeURIComponent(requestId)}/pagar`,{method:'POST',body:form(input,{payment_proof:payment,fiscal_document:fiscal})});},
  proposeAI(id:string,input:Record<string,unknown>){return apiRequest<{item:Exp008AIProposal;idempotent:boolean}>(`${root(id)}/ia/proponer`,{method:'POST',body:JSON.stringify(input)});},
  validateAI(id:string,proposalId:string,input:Record<string,unknown>){return apiRequest(`${root(id)}/ia/propuestas/${encodeURIComponent(proposalId)}/validar`,{method:'POST',body:JSON.stringify(input)});},
  generateReceipt(id:string,movementId:string){return apiRequest(`${root(id)}/movimientos/${encodeURIComponent(movementId)}/comprobante-pravia`,{method:'POST',body:JSON.stringify({idempotency_key:crypto.randomUUID()})});},
  documentUrl(id:string,linkId:string){return apiRequest<{url:string}>(`${root(id)}/documentos/${encodeURIComponent(linkId)}/url`);},
  async openDocument(id:string,linkId:string){const {url}=await this.documentUrl(id,linkId);window.open(url,'_blank','noopener,noreferrer');},
};
