import type { AgendaEvent } from '../agenda.types';
import { addDays, dateKey, dateKeyInZone, eventDurationMinutes, layoutOverlaps, sameDay, startOfWeek, zonedParts } from '../agenda.utils';
import { CalendarEvent } from './CalendarEvent';
import styles from '../Agenda.module.css';

const START_HOUR=8; const END_HOUR=18; const HOUR_HEIGHT=58;
export function WeekCalendar({ date, events, timezone, onOpen }: { date: Date; events: AgendaEvent[]; timezone: string; onOpen(event: AgendaEvent): void }) {
  const start=startOfWeek(date); const days=Array.from({length:7},(_,index)=>addDays(start,index)); const hours=Array.from({length:END_HOUR-START_HOUR+1},(_,index)=>START_HOUR+index); const now=new Date(); const nowParts=zonedParts(now,timezone);
  return <section className={styles.weekCalendar} aria-label="Calendario semanal"><div className={styles.weekHeader}><span/><div>{days.map((day)=><strong key={dateKey(day)} data-today={sameDay(day,now)}><small>{new Intl.DateTimeFormat('es-MX',{weekday:'short'}).format(day)}</small><b>{day.getDate()}</b></strong>)}</div></div><div className={styles.weekScroll}><div className={styles.timeLabels}>{hours.map((hour)=><span key={hour} style={{top:(hour-START_HOUR)*HOUR_HEIGHT}}>{String(hour).padStart(2,'0')}:00</span>)}</div><div className={styles.weekGrid} style={{height:(END_HOUR-START_HOUR)*HOUR_HEIGHT}}>{days.map((day)=>{const dayEvents=events.filter((event)=>dateKeyInZone(event.fecha_inicio,timezone)===dateKey(day));const placed=layoutOverlaps(dayEvents);return <div className={styles.dayColumn} key={dateKey(day)}>{hours.slice(0,-1).map((hour)=><i key={hour} style={{top:(hour-START_HOUR)*HOUR_HEIGHT}}/>)}{placed.map(({event,lane,lanes})=>{const part=zonedParts(event.fecha_inicio,timezone);const top=Math.max(0,((part.hour-START_HOUR)*60+part.minute)*(HOUR_HEIGHT/60));const height=Math.max(32,eventDurationMinutes(event)*(HOUR_HEIGHT/60));return <CalendarEvent key={event.id} event={event} timezone={timezone} compact={height<52} onOpen={onOpen} style={{top,height,left:`calc(${lane} * (100% / ${lanes}))`,width:`calc(100% / ${lanes} - 3px)`}}/>})}{sameDay(day,now)&&nowParts.hour>=START_HOUR&&nowParts.hour<END_HOUR&&<span className={styles.currentLine} style={{top:((nowParts.hour-START_HOUR)*60+nowParts.minute)*(HOUR_HEIGHT/60)}}><b>{String(nowParts.hour).padStart(2,'0')}:{String(nowParts.minute).padStart(2,'0')}</b></span>}</div>})}</div></div></section>;
}

