import { useState, type FormEvent } from 'react';
import { LoaderCircle, Plus, Trash2 } from 'lucide-react';
import { conceptsFromVersion, money } from '../quoteFormatters';
import { quotesService } from '../quotes.service';
import type { Quote, QuoteConcept, QuoteConceptCategory, QuoteVersion } from '../quotes.types';
import { QuoteDrawer } from './QuoteDrawer';
import styles from '../Quotes.module.css';

const categories: QuoteConceptCategory[] = ['HONORARIOS', 'DERECHOS', 'IMPUESTOS', 'GASTOS', 'OTROS'];
export function EditQuoteVersionDrawer({ quote, onClose, onCreated }: { quote: Quote; onClose: () => void; onCreated: (version: QuoteVersion) => void }) {
  const latest = quote.versiones[0]; const initial = conceptsFromVersion(latest);
  const [concepts, setConcepts] = useState<QuoteConcept[]>(initial.length ? initial : [{ categoria: 'HONORARIOS', concepto: '', monto: 0 }]);
  const [fee, setFee] = useState(Number(latest?.honorarios_pravia ?? quote.honorarios_pravia ?? 0)); const [notes, setNotes] = useState(latest?.notas ?? ''); const [approve, setApprove] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const total = concepts.reduce((sum, item) => sum + Number(item.monto || 0), 0);
  const update = (index: number, field: keyof QuoteConcept, value: string) => setConcepts((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: field === 'monto' ? Number(value) : value } as QuoteConcept : item));
  const submit = async (event: FormEvent) => { event.preventDefault(); if (concepts.some((item) => !item.concepto.trim() || item.monto <= 0)) return setError('Completa todos los conceptos con importes mayores que cero.'); if (fee < 0 || fee > total) return setError('La participación PRAVIA no puede superar el total.'); setSaving(true); setError(''); try { const result = await quotesService.createVersion(quote.id, { desglose_notaria: { rubros: concepts }, desglose_pravia: { participacion_pravia: fee }, total_notaria: total, honorarios_pravia: fee, notas: notes || undefined, aprobada: approve }); onCreated(result.version); } catch { setError('No pudimos crear la nueva versión.'); setSaving(false); } };
  return <QuoteDrawer title={`Nueva versión · v${quote.version_actual + 1}`} subtitle="La versión anterior se conservará en el historial." onClose={onClose} footer={<><button type="button" className={styles.secondaryButton} onClick={onClose}>Cancelar</button><button type="submit" form="edit-quote-version" className={styles.primaryButton} disabled={saving}>{saving && <LoaderCircle size={17} className={styles.spin} />}Crear versión</button></>}><form id="edit-quote-version" className={styles.quoteForm} onSubmit={submit}><fieldset><legend>Conceptos</legend>{error && <div className={styles.formError} role="alert">{error}</div>}<div className={styles.conceptHeader}><span>Categoría</span><span>Concepto</span><span>Importe MXN</span><span /></div>{concepts.map((item, index) => <div className={styles.conceptRow} key={index}><select aria-label={`Categoría concepto ${index + 1}`} value={item.categoria} onChange={(event) => update(index, 'categoria', event.target.value)}>{categories.map((category) => <option key={category}>{category}</option>)}</select><input aria-label={`Descripción concepto ${index + 1}`} value={item.concepto} onChange={(event) => update(index, 'concepto', event.target.value)} /><input aria-label={`Importe concepto ${index + 1}`} type="number" min="0" step=".01" value={item.monto || ''} onChange={(event) => update(index, 'monto', event.target.value)} /><button type="button" aria-label={`Eliminar concepto ${index + 1}`} disabled={concepts.length === 1} onClick={() => setConcepts((current) => current.filter((_, itemIndex) => itemIndex !== index))}><Trash2 size={17} /></button></div>)}<button type="button" className={styles.addConcept} onClick={() => setConcepts((current) => [...current, { categoria: 'OTROS', concepto: '', monto: 0 }])}><Plus size={16} />Agregar concepto</button><div className={styles.totalsBox}><label><span>Participación interna PRAVIA</span><input type="number" min="0" step=".01" value={fee || ''} onChange={(event) => setFee(Number(event.target.value))} /></label><dl><div><dt>Total cliente</dt><dd>{money(total)}</dd></div></dl></div><label className={styles.textareaLabel}><span>Notas de versión</span><textarea rows={4} value={notes} onChange={(event) => setNotes(event.target.value)} /></label><label className={styles.checkboxLabel}><input type="checkbox" checked={approve} onChange={(event) => setApprove(event.target.checked)} /><span><strong>Marcar como versión vigente</strong><small>La versión aprobada anterior conservará su contenido, pero dejará de ser la vigente.</small></span></label></fieldset></form></QuoteDrawer>;
}
