import { act, render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { OwnershipStructureEditor } from '../features/comparecientes/components/OwnershipStructureEditor';

const api=vi.hoisted(()=>({ownershipStructure:vi.fn(),saveOwnershipStructure:vi.fn(),previewOwnershipLinks:vi.fn(),previewOwnershipReconciliation:vi.fn(),searchMaster:vi.fn(),decideOwnershipReconciliation:vi.fn(),proposeOwnershipAi:vi.fn(),decideOwnershipAi:vi.fn()}));
vi.mock('../features/comparecientes/comparecientes.service',()=>({comparecientesService:api}));

const structure={configured:true,root_node_id:'root',revision:2,fingerprint:'a'.repeat(64),expanded_fingerprint:'b'.repeat(64),incomplete_markers:['UNKNOWN_PERCENTAGE:e1'],reconciliations:[],nodes:[{id:'root',party_kind:'PM',identity_mode:'LINKED',linked_compareciente_id:'party-1',canonical_label:'Sociedad sintética',metadata:{}},{id:'owner',party_kind:'PF',identity_mode:'STRUCTURED_ONLY',display_name:'Persona sintética',incomplete:false,metadata:{}}],edges:[{id:'e1',owner_node_id:'owner',owned_node_id:'root',percentage:null,evidence_document_id:null}],controls:[]};
const renderEditor=(props:Partial<React.ComponentProps<typeof OwnershipStructureEditor>>={})=>render(<OwnershipStructureEditor comparecienteId="party-1" name="Sociedad sintética" canWrite documents={[]} {...props}/>);

describe('H4 CUM-BC-001 frontend',()=>{
  beforeEach(()=>{vi.clearAllMocks();api.ownershipStructure.mockResolvedValue(structure);api.previewOwnershipLinks.mockResolvedValue([]);api.saveOwnershipStructure.mockResolvedValue({...structure,revision:3});api.searchMaster.mockResolvedValue([]);api.decideOwnershipReconciliation.mockResolvedValue({});api.decideOwnershipAi.mockResolvedValue({})});

  it('presents current facts, unknown percentage and human review state without a false legal conclusion',async()=>{renderEditor();expect(await screen.findByRole('heading',{name:'Estructura de propiedad y control'})).toBeInTheDocument();expect(screen.getByText('Estructura incompleta')).toBeInTheDocument();expect(screen.getByRole('spinbutton',{name:'Porcentaje de propiedad'})).toHaveValue(null);expect(screen.queryByText(/es beneficiario controlador/i)).not.toBeInTheDocument();expect(screen.getByText('Vista derivada de la estructura')).toBeInTheDocument()});

  it('saves through explicit root, optimistic revision and idempotency without an AI call',async()=>{const user=userEvent.setup();renderEditor();const percentage=await screen.findByRole('spinbutton',{name:'Porcentaje de propiedad'});await user.type(percentage,'40');await user.click(screen.getByRole('button',{name:'Guardar estructura'}));await waitFor(()=>expect(api.saveOwnershipStructure).toHaveBeenCalledWith('party-1',expect.objectContaining({root_node_id:'root',expected_revision:2,idempotency_key:expect.any(String)})));expect(api.proposeOwnershipAi).not.toHaveBeenCalled()});

  it('uses the searchable canonical selector and requires identity confirmation before linking',async()=>{const user=userEvent.setup();api.searchMaster.mockResolvedValue([{id:'linked-1',nombre:'Ana Sintética',rfc:'SYN010101AA1',tipo_persona:'FISICA'}]);api.previewOwnershipLinks.mockResolvedValue([{node_id:'owner',before:null,canonical_identity:{id:'linked-1',nombre:'Ana Sintética',tipo_persona:'FISICA'},target_structure_revision:0,target_fingerprint:null,confirmation:'confirm-1'}]);renderEditor();await screen.findByRole('heading',{name:'Estructura de propiedad y control'});await user.selectOptions(screen.getAllByRole('combobox',{name:'Identidad'})[1],'LINKED');const search=screen.getByRole('textbox',{name:'Buscar compareciente canónico'});await user.type(search,'Ana');await act(async()=>{await new Promise(resolve=>window.setTimeout(resolve,220))});const list=await screen.findByRole('listbox',{name:'Comparecientes disponibles'});await user.click(within(list).getByRole('option',{name:/Ana Sintética/}));await user.click(screen.getByRole('button',{name:'Guardar estructura'}));expect(await screen.findByRole('heading',{name:'Confirma las identidades canónicas'})).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Confirmar y guardar'}));await waitFor(()=>expect(api.saveOwnershipStructure).toHaveBeenCalledWith('party-1',expect.objectContaining({identity_confirmations:{owner:'confirm-1'}})))});

  it('offers canonical creation as an explicit human action',async()=>{const user=userEvent.setup();renderEditor();await screen.findByRole('heading',{name:'Estructura de propiedad y control'});await user.selectOptions(screen.getAllByRole('combobox',{name:'Identidad'})[1],'LINKED');const link=screen.getByRole('link',{name:'Crear compareciente en una nueva pestaña'});expect(link).toHaveAttribute('href','/comparecientes/nuevo');expect(link).toHaveAttribute('target','_blank')});

  it('supports evidence for ownership and qualitative control with human confirmation',async()=>{const user=userEvent.setup();renderEditor({documents:[{id:'doc-1',name:'Acta sintética.pdf'}]});await screen.findByRole('heading',{name:'Estructura de propiedad y control'});await user.selectOptions(screen.getByRole('combobox',{name:'Documento de evidencia de propiedad'}),'doc-1');await user.click(screen.getByRole('button',{name:'Hecho'}));await user.selectOptions(screen.getByRole('combobox',{name:'Documento de evidencia del control'}),'doc-1');expect(screen.getByRole('checkbox',{name:'Confirmado por una persona'})).toBeChecked();await user.click(screen.getByRole('button',{name:'Guardar estructura'}));await waitFor(()=>expect(api.saveOwnershipStructure).toHaveBeenCalledWith('party-1',expect.objectContaining({edges:[expect.objectContaining({evidence_document_id:'doc-1'})],controls:[expect.objectContaining({evidence_document_id:'doc-1',human_confirmed:true})]})))});

  it('keeps AI prepare-only until a person confirms or rejects the proposal',async()=>{const user=userEvent.setup();const proposal={id:'proposal-1',status:'PENDING',source_document_id:'doc-1',source_pages:[1],base_revision:2,base_fingerprint:structure.fingerprint,proposed_changes:{graph:{root_node_id:'root',nodes:structure.nodes,edges:structure.edges,controls:[],incomplete_markers:[]}}};api.proposeOwnershipAi.mockResolvedValue(proposal);renderEditor({canUseAi:true,documents:[{id:'doc-1',name:'Acta sintética.pdf'}]});await screen.findByRole('heading',{name:'Propuesta asistida desde documento'});await user.selectOptions(screen.getByRole('combobox',{name:'Documento fuente para propuesta IA'}),'doc-1');await user.click(screen.getByRole('button',{name:'Preparar propuesta'}));expect(await screen.findByText('Propuesta pendiente de revisión humana')).toBeInTheDocument();expect(api.saveOwnershipStructure).not.toHaveBeenCalled();await user.click(screen.getByRole('button',{name:'Rechazar'}));await waitFor(()=>expect(api.decideOwnershipAi).toHaveBeenCalledWith('party-1','proposal-1',{decision:'REJECTED',graph:undefined}))});

  it('exposes pending PM reconciliation as a human decision',async()=>{const user=userEvent.setup();api.ownershipStructure.mockResolvedValue({...structure,nodes:[structure.nodes[0],{...structure.nodes[1],identity_mode:'LINKED',linked_compareciente_id:'linked-pm',canonical_label:'PM vinculada',party_kind:'PM'}],reconciliations:[{id:'rec-1',status:'PENDING',source_node_id:'owner',target_revision:4,canonical_fingerprint:'c'.repeat(64)}]});renderEditor();expect(await screen.findByRole('heading',{name:'Conciliaciones pendientes'})).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Descartar'}));await waitFor(()=>expect(api.decideOwnershipReconciliation).toHaveBeenCalledWith('party-1','rec-1',{decision:'REJECTED',graph:undefined}))});

  it('read-only mode exposes no mutation controls',async()=>{renderEditor({canWrite:false});await screen.findByRole('heading',{name:'Estructura de propiedad y control'});expect(screen.getByText(/Vista de solo lectura/)).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Guardar estructura'})).not.toBeInTheDocument();expect(screen.getByRole('spinbutton',{name:'Porcentaje de propiedad'})).toHaveAttribute('readonly')});

  it('F006 previews source/current/proposed changes and submits the reviewed replacement, not the current destination',async()=>{
    const user=userEvent.setup();const proposed={...structure,edges:[{...structure.edges[0],percentage:'73'}]};
    api.ownershipStructure.mockResolvedValue({...structure,reconciliations:[{id:'rec-1',status:'PENDING',source_node_id:'owner',target_revision:2}]});
    api.previewOwnershipReconciliation.mockResolvedValue({local:proposed,current:structure,proposed,review_token:'review-1',identity_confirmations:{}});
    renderEditor();const confirm=await screen.findByRole('button',{name:'Confirmar cambios e incorporar'});expect(confirm).toBeDisabled();
    await user.click(screen.getByRole('button',{name:'Revisar cambios'}));const diff=await screen.findByRole('region',{name:'Cambios propuestos para confirmar'});expect(within(diff).getByText(/Actualizar:.*73%/)).toBeVisible();
    expect(screen.getByRole('region',{name:'Rama local de origen'})).toBeVisible();expect(screen.getByRole('region',{name:'Destino canónico actual'})).toBeVisible();
    await user.click(confirm);await waitFor(()=>expect(api.decideOwnershipReconciliation).toHaveBeenCalledWith('party-1','rec-1',{decision:'ACCEPTED',graph:proposed,review_token:'review-1'}));
  });

  it('F006 shows previous PF facts before canonical confirmation',async()=>{const user=userEvent.setup();api.previewOwnershipLinks.mockResolvedValue([{node_id:'owner',before:structure.nodes[1],canonical_identity:{id:'person-new',nombre:'Identidad canónica sintética',tipo_persona:'FISICA'},target_structure_revision:0,confirmation:'c'}]);renderEditor();await user.click(await screen.findByRole('button',{name:'Guardar estructura'}));expect(await screen.findByText('Identidad local anterior: Persona sintética')).toBeVisible();expect(screen.getByText('Identidad canónica: Identidad canónica sintética')).toBeVisible();expect(api.saveOwnershipStructure).not.toHaveBeenCalled();});

  it('F007 shows identities, 73%, control and source before enabling exact AI confirmation',async()=>{
    const user=userEvent.setup();const graph={...structure,edges:[{...structure.edges[0],percentage:'73',evidence_document_id:'doc-1',evidence_document_version:'v-test',evidence_document_checksum:'abc'}],controls:[{id:'c1',subject_node_id:'owner',kind:'VOTE',description:'Voto contractual sintético',human_confirmed:false,evidence_document_id:'doc-1'}]};
    api.proposeOwnershipAi.mockResolvedValue({id:'ai-1',review_token:'exact-review',source_pages:[2],proposed_changes:{graph}});renderEditor({canUseAi:true,documents:[{id:'doc-1',name:'Soporte sintético.pdf'}]});
    await user.selectOptions(await screen.findByRole('combobox',{name:'Documento fuente para propuesta IA'}),'doc-1');await user.click(screen.getByRole('button',{name:'Preparar propuesta'}));
    const region=await screen.findByRole('region',{name:'Hechos propuestos por IA'});expect(within(region).getByText(/73%/)).toBeVisible();expect(within(region).getByText('Voto contractual sintético')).toBeVisible();expect(within(region).getByText(/v-test/)).toBeVisible();expect(within(region).getByText(/Sin cambios: Persona sintética/)).toBeVisible();
    const confirm=screen.getByRole('button',{name:'Confirmar propuesta'});expect(confirm).toBeDisabled();expect(api.decideOwnershipAi).not.toHaveBeenCalled();await user.click(screen.getByRole('checkbox',{name:/He revisado identidades/}));await user.click(confirm);
    await waitFor(()=>expect(api.decideOwnershipAi).toHaveBeenCalledWith('party-1','ai-1',{decision:'CONFIRMED',graph,review_token:'exact-review'}));
  });

  it('F007 routes corrections to the same editor without a write',async()=>{const user=userEvent.setup();const graph={...structure,edges:[{...structure.edges[0],percentage:'73'}]};api.proposeOwnershipAi.mockResolvedValue({id:'ai-2',review_token:'review',source_pages:[],proposed_changes:{graph}});renderEditor({canUseAi:true,documents:[{id:'doc-1',name:'Sintético.pdf'}]});await user.selectOptions(await screen.findByRole('combobox',{name:'Documento fuente para propuesta IA'}),'doc-1');await user.click(screen.getByRole('button',{name:'Preparar propuesta'}));await user.click(await screen.findByRole('button',{name:'Corregir en editor'}));expect(screen.getByRole('spinbutton',{name:'Porcentaje de propiedad'})).toHaveValue(73);expect(api.decideOwnershipAi).not.toHaveBeenCalled();expect(api.saveOwnershipStructure).not.toHaveBeenCalled();});

  it('F008 renders canonical expanded participants and relationships exactly once in the projection',async()=>{const user=userEvent.setup();const nested={...structure,nodes:[structure.nodes[0],{id:'pm-b',party_kind:'PM',identity_mode:'LINKED',linked_compareciente_id:'b',canonical_label:'PM B'},{id:'p1',party_kind:'PF',identity_mode:'STRUCTURED_ONLY',display_name:'P1 expandida'},{id:'p2',party_kind:'PF',identity_mode:'STRUCTURED_ONLY',display_name:'P2 expandida'}],edges:[{id:'be',owner_node_id:'pm-b',owned_node_id:'root',percentage:'100'},{id:'p1e',owner_node_id:'p1',owned_node_id:'pm-b',percentage:'40'},{id:'p2e',owner_node_id:'p2',owned_node_id:'pm-b',percentage:'60'}],incomplete_markers:['CANONICAL_BRANCH_REQUIRES_REVIEW:pm-b']};api.ownershipStructure.mockResolvedValue({...structure,expanded:nested});renderEditor();await screen.findByRole('heading',{name:'Estructura de propiedad y control'});await user.click(screen.getByText('Vista derivada de la estructura'));const graph=screen.getByRole('region',{name:'Expansión canónica'});expect(within(graph).getAllByText('P1 expandida')).toHaveLength(1);expect(within(graph).getAllByText('P2 expandida')).toHaveLength(1);expect(within(graph).getByText(/P1 expandida → PM B · 40%/)).toBeVisible();expect(within(graph).getByRole('note')).toHaveTextContent('ciclos');expect(api.saveOwnershipStructure).not.toHaveBeenCalled();});

  it.each([390,320])('keeps accessible named controls at %ipx without a duplicate persisted diagram',async width=>{Object.defineProperty(window,'innerWidth',{configurable:true,value:width});window.dispatchEvent(new Event('resize'));renderEditor();await screen.findByRole('heading',{name:'Estructura de propiedad y control'});expect(screen.getByRole('button',{name:'Guardar estructura'})).toBeEnabled();expect(screen.getByRole('combobox',{name:'Documento de evidencia de propiedad'})).toBeInTheDocument();expect(screen.getAllByText('Vista derivada de la estructura')).toHaveLength(1)});
});
