import {render,screen,within,waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {MemoryRouter} from 'react-router-dom';
import {beforeEach,describe,expect,it,vi} from 'vitest';
import {ComplianceTab} from '../features/cases/components/tabs/ComplianceTab';
const api=vi.hoisted(()=>({documentStructure:vi.fn(),beneficialController:vi.fn(),evaluateLegalCase:vi.fn()}));
vi.mock('../features/compliance/compliance.service',()=>({complianceService:api}));
vi.mock('../features/auth/AuthProvider',()=>({useAuth:()=>({user:{permissions:['compliance.read','compliance.write','documentos.read']}})}));
const evaluation:any={id:'bc-1',review_id:'r-current',regime:'LFPIORPI',status:'EVALUATED',legal_date:'2026-09-01',rule_set_checksum:'verified-synthetic',snapshot:{id:'snapshot-1',structure_revision:2,incomplete_markers:[]},structure_path:'/comparecientes/pm-1',target_name:'PM sintética',results:[{id:'p1',determination:'IDENTIFIED',subject_compareciente_id:'party-1',subject_name:'Persona autorizada',subject_path:'/comparecientes/party-1'},{id:'p2',determination:'IDENTIFIED',subject_name:'Identidad estructurada sintética'}],supports:[{document_id:'doc-1',label:'Soporte autorizado.pdf',path:'/comparecientes/pm-1'}]};
const summary=(evaluations:any[]= [evaluation],history:any[]=[])=>({current_review_id:'r-current',evaluations,history,configured_legal_rules:true});
const renderTab=()=>render(<MemoryRouter><ComplianceTab expediente={{id:'exp-h4',numero_pravia:'EXP-0001-2026',complianceReviews:[]} as any}/></MemoryRouter>);
beforeEach(()=>{vi.clearAllMocks();api.documentStructure.mockResolvedValue({vulnerable:false,groups:[],requirements:[],missing:[]});api.beneficialController.mockResolvedValue(summary());api.evaluateLegalCase.mockResolvedValue({});});
describe('F009 BC case consumer',()=>{
 it('shows authorized linked/structured subjects and support through the canonical document workspace',async()=>{renderTab();expect(await screen.findByRole('link',{name:'Persona autorizada'})).toHaveAttribute('href','/comparecientes/party-1');expect(screen.getByText('Identidad estructurada sintética')).toBeVisible();expect(screen.getByRole('link',{name:'Ver soporte en ficha documental: Soporte autorizado.pdf'})).toHaveAttribute('href','/comparecientes/pm-1');});
 it('does not invent an evidence action when the authorized projection has no support',async()=>{api.beneficialController.mockResolvedValue(summary([{...evaluation,supports:[]}]));renderTab();await screen.findByText('Persona autorizada');expect(screen.queryByRole('link',{name:/Ver soporte/})).not.toBeInTheDocument();});
 it('requires explicit dated confirmation before reevaluating through the existing authority',async()=>{api.beneficialController.mockResolvedValue(summary([{...evaluation,reevaluation_required:true}]));renderTab();const user=userEvent.setup();await user.click(await screen.findByRole('button',{name:'Reevaluar cumplimiento'}));expect(api.evaluateLegalCase).not.toHaveBeenCalled();const panel=screen.getByRole('region',{name:'Confirmar reevaluación'});expect(within(panel).getByLabelText('Fecha jurídica de reevaluación')).toHaveValue('2026-09-01');await user.click(within(panel).getByRole('button',{name:'Confirmar y reevaluar'}));await waitFor(()=>expect(api.evaluateLegalCase).toHaveBeenCalledWith('exp-h4',{idempotency_key:expect.any(String),fecha_juridica_confirmada:'2026-09-01'}));});
 it('hides verified CFF N/A without hiding unconfigured CFF',async()=>{api.beneficialController.mockResolvedValue(summary([{...evaluation,id:'cff-na',regime:'CFF_RMF',status:'NOT_APPLICABLE',target_name:'CFF no aplicable'},{...evaluation,id:'cff-pending',regime:'CFF_RMF',status:'NOT_CONFIGURED',rule_set_checksum:null,target_name:'CFF por configurar',results:[]}]));renderTab();expect(await screen.findByText('CFF / RMF · CFF por configurar')).toBeVisible();expect(screen.queryByText('CFF / RMF · CFF no aplicable')).not.toBeInTheDocument();expect(screen.getByText(/Regla jurídica no configurada/)).toBeVisible();});
 it('keeps historical results in a separate disclosure without actionable reevaluation',async()=>{api.beneficialController.mockResolvedValue(summary([evaluation],[{...evaluation,id:'old',target_name:'PM histórica',review_id:'r-old',reevaluation_required:true}]));renderTab();await screen.findByText('LFPIORPI · PM sintética');const disclosure=screen.getByText('Ver historial de evaluaciones (1)');await userEvent.click(disclosure);expect(screen.getByText('LFPIORPI · PM histórica')).toBeVisible();expect(screen.queryByRole('button',{name:'Reevaluar cumplimiento'})).not.toBeInTheDocument();});
});
