import { render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { App } from '../app/App';
import { getAssistantActions, resolveAssistantContext } from '../features/assistant/assistantContext';

const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}});
const permissions=['cumplimiento.read','cumplimiento.write','cumplimiento.confirm','expedientes.read','documentos.read','ai.use','ai.cumplimiento.read'];
const alert={codigo:'BC-04',mensaje:'Falta confirmar beneficiario controlador o recabar la declaración aplicable.',regla:'Artículo 17, fracción XII',dato:'beneficiario_controlador_identificado = no',fuente:'Respuesta de la revisión; no existe maestro independiente',accion:'Completar la declaración y adjuntar evidencia.'};
const review:any={id:'review-1',tipo:'UIF',estatus:'PENDIENTE_REVISION',fecha_operacion:'2026-08-12T00:00:00.000Z',rule_version_snapshot:'LFPIORPI-2025-07-16+UMA-2026-02-01',snapshot_captured_at:'2026-08-12T16:00:00.000Z',created_at:'2026-08-12T16:00:00.000Z',updated_at:'2026-08-12T17:00:00.000Z',master_data_changed:true,cuestionario_json:{tipo_acto_uif:'TRANSMISION_DERECHOS_REALES_INMUEBLES',precio_pactado:1200000,pep_declarada:'PENDIENTE',beneficiario_controlador_identificado:false},resultado_json:{clasificacion:'REQUIERE_AVISO',requiere_aviso:true,acto:'TRANSMISION_DERECHOS_REALES_INMUEBLES',monto_base_mxn:1200000,umbral_mxn:938480,alertas:[alert],faltantes:['Origen de recursos'],disclaimer:'Resultado de apoyo operativo; requiere revisión humana.'},rule_snapshot:{nombre:'Actividades vulnerables en actos notariales',version:'LFPIORPI-2025-07-16+UMA-2026-02-01',fuente_nombre:'LFPIORPI e INEGI',fuente_url:'https://example.test/lfpiorpi.pdf',parametros:{acumulacion_meses:6,reglas:{TRANSMISION_DERECHOS_REALES_INMUEBLES:{fundamento:'Artículo 17'}}},cuestionario:[{clave:'tipo_acto_uif',etiqueta:'Supuesto legal del acto',tipo:'SELECT',requerido:true},{clave:'beneficiario_controlador_identificado',etiqueta:'Beneficiario controlador identificado',tipo:'BOOLEAN',requerido:true},{clave:'origen_recursos_documentado',etiqueta:'Origen de recursos documentado',tipo:'BOOLEAN',requerido:true},{clave:'pep_declarada',etiqueta:'Condición PEP declarada',tipo:'SELECT',requerido:true}]},master_snapshot:{expediente:{id:'exp-1',numero_pravia:'EXP-2026-0141',version:3,valor_operacion_mxn:1200000},comparecientes:[{id:'party-1',version:2,tipo_persona:'FISICA',nombre:'María Fernanda López',rfc:'LORM900101AA1',pep_estado:'PENDIENTE',identificaciones:[]}]},expediente:{id:'exp-1',numero_pravia:'EXP-2026-0141',cliente_alias:'María Fernanda López',tipo_acto:{nombre:'Compraventa'},notaria:{numero_notaria:'12',nombre:'Notaría 12'},abogado:{id:'u1',nombre:'Andrea',apellido:'Ruiz'},comparecientes:[{compareciente:{id:'party-1'}}]},ruleSet:{nombre:'Actividades vulnerables',version:'2026.1'},creado_por:{nombre:'Andrea',apellido:'Ruiz'},revisado_por:null,evidencias:[{id:'ev-1',tipo_evidencia:'IDENTIDAD',created_at:'2026-08-12T16:30:00.000Z',documento:{id:'doc-1',nombre_original:'INE_Maria.pdf',tipo:'IDENTIFICACION',estatus:'VIGENTE'},agregado_por:{nombre:'Andrea',apellido:'Ruiz'}}],decisiones:[]};
const catalogs={reglas:[{id:'rule-1',tipo:'UIF',nombre:'Actividades vulnerables',version:'2026.1'}],expedientes:[{id:'exp-1',numero_pravia:'EXP-2026-0141',tipo_acto:{nombre:'Compraventa'}}],usuarios:[{id:'u1',nombre:'Andrea',apellido:'Ruiz'}],documentos:[{id:'doc-1',nombre_original:'INE_Maria.pdf',expediente_id:'exp-1'}]};

function mockApi(options:{empty?:boolean;fail?:boolean;permissions?:string[]}={}){vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{const url=String(input);if(url.endsWith('/auth/me'))return json({user:{id:'u1',name:'Andrea Ruiz',role:'ADMINISTRACION',permissions:options.permissions??permissions}});if(url.includes('/cumplimiento/catalogos'))return json({success:true,...catalogs});if(url.match(/\/cumplimiento\/revisiones\/review-1$/)){if(options.fail)return json({error:'No disponible'},500);return json({success:true,revision:review,historial:[{...review,id:'review-0',estatus:'CONFIRMADO',created_at:'2026-02-02T12:00:00.000Z',resultado_json:{...review.resultado_json,clasificacion:'INCOMPLETO'}}]});}if(url.includes('/cumplimiento/revisiones?')){if(options.fail)return json({error:'No disponible'},500);const rows=options.empty?[]:[review];return json({success:true,revisiones:rows,meta:{page:url.includes('page=2')?2:1,pageSize:12,total:rows.length,totalPages:1},metrics:{requieren_revision:rows.length,pendientes:rows.length,observaciones:0,confirmadas:0}});}if(url.includes('/evaluar')&&init?.method==='POST')return json({success:true,revision:review});if(url.includes('/evidencias')&&init?.method==='POST')return json({success:true,evidencia:{id:'ev-2'}},201);return json({success:true});}));}
const renderAt=(path:string)=>render(<MemoryRouter initialEntries={[path]}><App/></MemoryRouter>);

describe('Riesgos / UIF',()=>{beforeEach(()=>vi.restoreAllMocks());
 it('muestra KPIs reales, filtros y cola server-side',async()=>{mockApi();renderAt('/riesgos?search=0141');expect(await screen.findByRole('heading',{name:'Riesgos / UIF'})).toBeInTheDocument();expect((await screen.findAllByText('EXP-2026-0141')).length).toBeGreaterThan(0);expect(screen.getAllByText('Requiere acción UIF').length).toBeGreaterThan(0);await waitFor(()=>expect(vi.mocked(fetch).mock.calls.some(([url])=>String(url).includes('search=0141'))).toBe(true));});
 it('abre workstation con checklist, RuleSet, UIF y master vs snapshot',async()=>{mockApi();renderAt('/riesgos/revisiones/review-1');expect(await screen.findByRole('heading',{name:'EXP-2026-0141'})).toBeInTheDocument();expect(screen.getByText(/Datos actualizados desde la última revisión/)).toBeInTheDocument();expect(screen.getByText('Checklist estructurado')).toBeInTheDocument();expect(screen.getByText(/no existe un registro maestro independiente/i)).toBeInTheDocument();expect(screen.getByText('Requiere acción UIF')).toBeInTheDocument();});
 it('explica alertas con regla, dato, fuente y acción',async()=>{mockApi();const user=userEvent.setup();renderAt('/riesgos/revisiones/review-1');const item=await screen.findByRole('button',{name:/Falta confirmar beneficiario/});await user.click(item);const dialog=screen.getByRole('dialog');expect(within(dialog).getByText('Artículo 17, fracción XII')).toBeInTheDocument();expect(within(dialog).getByText(/no existe maestro independiente/)).toBeInTheDocument();expect(within(dialog).getByText(/Completar la declaración/)).toBeInTheDocument();});
 it('vincula evidencia existente sin crear storage paralelo',async()=>{mockApi();const user=userEvent.setup();renderAt('/riesgos/revisiones/review-1');await screen.findByText('Evidencia vinculada');await user.click(screen.getByRole('button',{name:'Vincular'}));await user.selectOptions(screen.getByLabelText('Documento de evidencia'),'doc-1');await user.click(screen.getByRole('button',{name:'Confirmar vínculo'}));await waitFor(()=>expect(vi.mocked(fetch).mock.calls.some(([url,init])=>String(url).includes('/evidencias')&&init?.method==='POST')).toBe(true));});
 it('respeta permisos de lectura y confirmación',async()=>{mockApi({permissions:['cumplimiento.read','expedientes.read']});renderAt('/riesgos/revisiones/review-1');expect(await screen.findByText('Checklist estructurado')).toBeInTheDocument();expect(screen.queryByRole('button',{name:/Confirmar revisión/})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:/Ejecutar evaluación/})).not.toBeInTheDocument();});
 it('presenta historial read-only y diferencia resultado previo',async()=>{mockApi();const user=userEvent.setup();renderAt('/riesgos/revisiones/review-1');await screen.findByText('Checklist estructurado');await user.click(screen.getByRole('button',{name:'Historial'}));expect(await screen.findByText('Revisiones anteriores')).toBeInTheDocument();expect(screen.getByText(/Requiere información/)).toBeInTheDocument();});
 it('muestra estados empty y error sin detalles técnicos',async()=>{mockApi({empty:true});const first=renderAt('/riesgos');expect(await screen.findByText('No hay revisiones pendientes dentro de tu alcance.')).toBeInTheDocument();first.unmount();mockApi({fail:true});renderAt('/riesgos');expect(await screen.findByText('No pudimos cargar las revisiones.')).toBeInTheDocument();expect(screen.queryByText(/HTTP|Prisma|endpoint/i)).not.toBeInTheDocument();});
 it('expone contexto IA compliance con id real y lenguaje trazable',()=>{const context=resolveAssistantContext({pathname:'/riesgos/revisiones/review-1',hash:''});expect(context).toMatchObject({module:'compliance',entityType:'complianceReview',entityId:'review-1'});expect(getAssistantActions(context).map(x=>x.label)).toContain('¿Por qué esta alerta?');});
});
