import { render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { App } from '../app/App';
import { getAssistantActions, resolveAssistantContext } from '../features/assistant/assistantContext';

const response = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } });
const session = { user: { id: 'user-1', name: 'Andrea Ruiz', role: 'ADMINISTRACION', permissions: ['comparecientes.read','comparecientes.write','documentos.read','documentos.write','expedientes.read'] } };
const row = { id: 'party-1', tipo_persona: 'FISICA', nombre: 'María Fernanda López Ramírez', rfc: 'LORM900101AA1', curp: 'LORM900101MNLPZR08', expedientes_vinculados: 3, identidad: 'VERIFICADA', documentos: { total: 3, vigentes: 2, con_observacion: 0 }, cumplimiento: 'COMPLETO', updated_at: '2026-08-12T17:00:00.000Z' };
const list = { success: true, data: [row], metrics: { total: 1, verified: 1, pending: 0, observed: 0 }, meta: { total: 1, page: 1, limit: 20, pageSize: 20, totalPages: 1, hasPreviousPage: false, hasNextPage: false }, definitions: { documents: 'Conteo descriptivo' } };
const detail: any = { ...row, nombre_busqueda: 'MARIA FERNANDA LOPEZ RAMIREZ', estatus: 'ACTIVO', created_at: '2026-07-01T10:00:00.000Z', updated_at_material: row.updated_at, creado_por: { id: 'user-1', nombre: 'Andrea', apellido: 'Ruiz' }, personaFisica: { nombre_completo_calculado: row.nombre, nacionalidad: 'Mexicana', pep_estado: 'PENDIENTE' }, personaMoral: null, domicilios: [{ id: 'address-1', tipo: 'PARTICULAR', principal: true, vigente: true, comprobado: true, calle: 'Av. México', exterior: '120', colonia: 'Centro', municipio: 'Tepic', estado: 'Nayarit', codigo_postal: '63000', documentoComprobante: { id: 'doc-2', nombre_original: 'Comprobante.pdf', estatus: 'VIGENTE' } }], contactos: [{ id: 'contact-1', tipo: 'CORREO', valor: 'maria@example.mx', validado: true }], identificaciones: [{ id: 'identity-1', tipo_identificacion: 'INE', numero: '****4401', estatus: 'VIGENTE', validado_at: '2026-08-01T10:00:00.000Z', fecha_vencimiento: '2030-12-31T00:00:00.000Z', documento: { id: 'doc-1', nombre_original: 'INE.pdf', estatus: 'VIGENTE' } }], documentos: [{ id: 'link-1', categoria: 'IDENTIFICACION', fecha_validacion: '2026-08-01T10:00:00.000Z', documento: { id: 'doc-1', nombre_original: 'INE.pdf', mime_type: 'application/pdf', size_bytes: 22000, fecha_carga: '2026-08-01T10:00:00.000Z', estatus: 'VIGENTE' } }], datosFuente: [{ id: 'source-1', campo: 'rfc', valor_detectado: row.rfc, valor_confirmado: row.rfc, estado: 'CONFIRMADO', confirmado_at: '2026-08-01T10:00:00.000Z', documento: { id: 'doc-3', nombre_original: 'Constancia Fiscal.pdf' }, pagina: 1 }], expedientes: [{ id: 'link-exp-1', caracter: { nombre: 'Compradora' }, expediente: { id: 'exp-1', numero_pravia: 'EXP-2026-0041', estatus: 'EN_PROCESO', numero_notaria: '12', tipo_acto: { nombre: 'Compraventa' }, notaria: { nombre: 'Notaría 12' }, abogado: { nombre: 'Andrea', apellido: 'Ruiz' }, complianceReviews: [] } }], representacionesComoRepresentante: [], representacionesComoRepresentado: [], complianceSnapshots: [], actividad: [{ id: 'audit-1', accion: 'CREAR_PERSONA_FISICA', created_at: '2026-07-01T10:00:00.000Z', detalles: { modulo: 'COMPARECIENTES' }, usuario: { nombre: 'Andrea', apellido: 'Ruiz' } }], health: [{ key: 'IDENTIDAD', label: 'Identidad', state: 'COMPLETO' }, { key: 'FISCAL', label: 'Fiscal', state: 'COMPLETO' }, { key: 'DOMICILIO', label: 'Domicilio', state: 'COMPLETO' }, { key: 'REPRESENTACION', label: 'Representación', state: 'NO_APLICA' }, { key: 'CUMPLIMIENTO', label: 'Cumplimiento', state: 'COMPLETO' }, { key: 'DOCUMENTOS', label: 'Documentos', state: 'COMPLETO' }], capabilities: { canUploadDocuments: true, canArchive: true, allowsSoftDuplicateOverride: true, blocksExactIdentityDuplicate: true } };

const mockApi = (options: { empty?: boolean; fail?: boolean; duplicate?: 'soft'|'exact'; grants?: string[] } = {}) => vi.stubGlobal('fetch', vi.fn(async (input: RequestInfo | URL, init?: RequestInit) => { const url = String(input);
  if (url.endsWith('/auth/me')) return response(options.grants ? { user: { ...session.user, permissions: options.grants } } : session);
  if (url.includes('/comparecientes/duplicados?')) return response({ success: true, data: options.duplicate ? [{ id: 'party-2', tipo_persona: 'FISICA', nombre: 'María López', rfc: options.duplicate === 'exact' ? 'LORM900101AA1' : null, curp: null, razones: [options.duplicate === 'exact' ? 'RFC_EXACTO' : 'NOMBRE_SIMILAR'], bloqueo_alta: options.duplicate === 'exact', updated_at: row.updated_at }] : [] });
  if (url.includes('/comparecientes?')) return options.fail ? response({ error: 'No disponible' }, 500) : response(options.empty ? { ...list, data: [], metrics: { total: 0, verified: 0, pending: 0, observed: 0 }, meta: { ...list.meta, total: 0 } } : list);
  if (url.endsWith('/comparecientes/persona-fisica') && init?.method === 'POST') return response({ success: true, data: { compareciente: { id: 'created-party' } } }, 201);
  if (url.endsWith('/comparecientes/persona-moral') && init?.method === 'POST') return response({ success: true, data: { compareciente: { id: 'created-company' } } }, 201);
  if (url.endsWith('/comparecientes/party-1')) return response({ success: true, data: detail });
  if (url.endsWith('/comparecientes/party-1/documentos') && init?.method === 'POST') return response({ success: true, data: {} }, 201);
  return response({}, 204);
}));

async function reachReview(user: ReturnType<typeof userEvent.setup>, type: 'FISICA'|'MORAL' = 'FISICA') {
  await user.click(screen.getByRole('button', { name: 'Nuevo compareciente' }));
  await user.click(screen.getByRole('button', { name: type === 'FISICA' ? /Persona física/ : /Persona moral/ }));
  const label = type === 'FISICA' ? 'Nombre *' : 'Razón social *'; await user.type(screen.getByLabelText(label), type === 'FISICA' ? 'María' : 'Horizonte, S.A. de C.V.');
  for (let index = 0; index < 4; index += 1) await user.click(screen.getByRole('button', { name: 'Siguiente' }));
}

describe('Comparecientes', () => {
  beforeEach(() => { vi.restoreAllMocks(); window.localStorage.clear(); });
  it('renderiza tarjetas compactas por defecto y permite una lista persistente', async () => { mockApi(); const user = userEvent.setup(); render(<MemoryRouter initialEntries={['/comparecientes']}><App /></MemoryRouter>); expect(await screen.findByRole('heading', { name: 'Comparecientes' })).toBeInTheDocument(); expect(await screen.findByRole('link', { name: `Abrir ficha de ${row.nombre}` })).toBeInTheDocument(); expect(screen.getByText('Identidad verificada')).toBeInTheDocument(); await user.click(screen.getByRole('button', { name: 'Lista' })); expect(await screen.findByRole('table')).toBeInTheDocument(); expect(window.localStorage.getItem('pravia:comparecientes:view')).toBe('list'); });
  it('envía búsqueda, filtros, sort y paginación al servidor', async () => { mockApi(); const user = userEvent.setup(); render(<MemoryRouter initialEntries={['/comparecientes']}><App /></MemoryRouter>); await screen.findByLabelText('Vista de tarjetas de comparecientes'); await user.type(screen.getByPlaceholderText(/Nombre, razón social/), 'López'); await waitFor(() => expect(fetch).toHaveBeenCalledWith(expect.stringContaining('search=L%C3%B3pez'), expect.anything())); await user.selectOptions(screen.getByLabelText('Estatus de identidad'), 'OBSERVACION'); await waitFor(() => expect(fetch).toHaveBeenCalledWith(expect.stringContaining('identidad=OBSERVACION'), expect.anything())); await user.selectOptions(screen.getByLabelText('Ordenar'), 'nombre:asc'); await waitFor(() => expect(fetch).toHaveBeenCalledWith(expect.stringContaining('sort=nombre%3Aasc'), expect.anything())); });
  it('respeta permisos de solo lectura', async () => { mockApi({ grants: ['comparecientes.read'] }); render(<MemoryRouter initialEntries={['/comparecientes']}><App /></MemoryRouter>); await screen.findByLabelText('Vista de tarjetas de comparecientes'); expect(screen.queryByRole('button', { name: 'Nuevo compareciente' })).not.toBeInTheDocument(); });
  it('crea persona física mediante el flujo progresivo', async () => { mockApi(); const user = userEvent.setup(); render(<MemoryRouter initialEntries={['/comparecientes']}><App /></MemoryRouter>); await screen.findByLabelText('Vista de tarjetas de comparecientes'); await reachReview(user, 'FISICA'); await user.click(screen.getByRole('button', { name: 'Crear compareciente' })); await waitFor(() => expect(vi.mocked(fetch).mock.calls.some(([url, init]) => String(url).endsWith('/persona-fisica') && init?.method === 'POST')).toBe(true)); });
  it('crea persona moral mediante el flujo progresivo', async () => { mockApi(); const user = userEvent.setup(); render(<MemoryRouter initialEntries={['/comparecientes']}><App /></MemoryRouter>); await screen.findByLabelText('Vista de tarjetas de comparecientes'); await reachReview(user, 'MORAL'); await user.click(screen.getByRole('button', { name: 'Crear compareciente' })); await waitFor(() => expect(vi.mocked(fetch).mock.calls.some(([url, init]) => String(url).endsWith('/persona-moral') && init?.method === 'POST')).toBe(true)); });
  it('advierte coincidencias blandas y bloquea RFC/CURP exactos', async () => { mockApi({ duplicate: 'soft' }); const user = userEvent.setup(); const first = render(<MemoryRouter initialEntries={['/comparecientes']}><App /></MemoryRouter>); await screen.findByLabelText('Vista de tarjetas de comparecientes'); await reachReview(user); await user.click(screen.getByRole('button', { name: 'Crear compareciente' })); const dialog = await screen.findByRole('alertdialog'); expect(within(dialog).getByText(/podría corresponder/)).toBeInTheDocument(); expect(within(dialog).getByRole('button', { name: 'Continuar de todos modos' })).toBeInTheDocument(); first.unmount(); mockApi({ duplicate: 'exact' }); render(<MemoryRouter initialEntries={['/comparecientes']}><App /></MemoryRouter>); await screen.findByLabelText('Vista de tarjetas de comparecientes'); await reachReview(userEvent.setup()); await userEvent.click(screen.getByRole('button', { name: 'Crear compareciente' })); const blocked = await screen.findByRole('alertdialog'); expect(within(blocked).queryByRole('button', { name: 'Continuar de todos modos' })).not.toBeInTheDocument(); expect(screen.getByText(/bloquea el alta/)).toBeInTheDocument(); });
  it('abre workspace con información y documentos simultáneos, procedencia y relaciones', async () => { mockApi(); const user = userEvent.setup(); render(<MemoryRouter initialEntries={['/comparecientes/party-1']}><App /></MemoryRouter>); expect(await screen.findByRole('heading', { name: row.nombre })).toBeInTheDocument(); expect(screen.getByRole('heading', { name: 'Información' })).toBeInTheDocument(); expect(screen.getByRole('heading', { name: 'Archivo documental' })).toBeInTheDocument(); const identity = screen.getByRole('tab', { name: 'Identidad y fiscal' }); await user.click(identity); expect(identity).toHaveAttribute('aria-selected', 'true'); expect(await screen.findByText(/Constancia Fiscal\.pdf/)).toBeInTheDocument(); await user.click(screen.getByRole('tab', { name: 'Expedientes' })); expect(await screen.findByText('EXP-2026-0041')).toBeInTheDocument(); expect(screen.getByText('INE.pdf')).toBeInTheDocument(); });
  it('carga documentos por endpoint autenticado del compareciente con categoría y metadatos', async () => { mockApi(); const user = userEvent.setup(); render(<MemoryRouter initialEntries={['/comparecientes/party-1#documentos']}><App /></MemoryRouter>); await screen.findByText('INE.pdf'); await user.click(screen.getAllByRole('button', { name: 'Agregar documento' })[0]); const dialog = await screen.findByRole('dialog', { name: 'Agregar documento' }); const input = within(dialog).getByLabelText(/Arrastra un archivo/) as HTMLInputElement; await user.upload(input, new File(['contenido'], 'nuevo.pdf', { type: 'application/pdf' })); await user.click(within(dialog).getByRole('button', { name: 'Agregar documento' })); await waitFor(() => expect(vi.mocked(fetch).mock.calls.some(([url, init]) => String(url).endsWith('/comparecientes/party-1/documentos') && init?.method === 'POST')).toBe(true)); });
  it('muestra empty y error humanos', async () => { mockApi({ empty: true }); const first = render(<MemoryRouter initialEntries={['/comparecientes']}><App /></MemoryRouter>); expect(await screen.findByText('No hay comparecientes.')).toBeInTheDocument(); first.unmount(); mockApi({ fail: true }); render(<MemoryRouter initialEntries={['/comparecientes']}><App /></MemoryRouter>); expect(await screen.findByText('No pudimos cargar los comparecientes.')).toBeInTheDocument(); });
  it('expone contexto IA diferente en lista y entidad real', () => { const listContext = resolveAssistantContext({ pathname: '/comparecientes', hash: '' }); const detailContext = resolveAssistantContext({ pathname: '/comparecientes/party-1', hash: '#documentos' }); expect(getAssistantActions(listContext).map((action) => action.label)).toContain('Duplicados posibles'); expect(detailContext).toMatchObject({ module: 'comparecientes', entityType: 'compareciente', entityId: 'party-1', subview: 'documentos' }); expect(getAssistantActions(detailContext).map((action) => action.label)).toContain('¿Qué falta?'); });
});
