import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { FinanceTab } from '../features/cases/components/tabs/FinanceTab';
import type { ExpedienteDetail } from '../features/cases/expedientes.types';

const api = vi.hoisted(()=>({read:vi.fn(),reportIncome:vi.fn(),createInternalRequest:vi.fn(),createExternalRequest:vi.fn(),applyIncome:vi.fn(),payRequest:vi.fn(),proposeAI:vi.fn(),validateAI:vi.fn(),generateReceipt:vi.fn(),openDocument:vi.fn()}));
vi.mock('../features/cases/expedienteFinance.service',()=>({expedienteFinanceService:api}));

const fixture=()=>({expediente:{id:'exp-a',numero_pravia:'EXP-0001-2026'},ingresosReportados:[{id:'income-a',estado:'PENDIENTE_APLICACION',concepto_contexto:'Anticipo inicial',monto_reportado:'1000.00',created_at:'2026-08-29T12:00:00Z',reportadoPor:{nombre:'Andrea'},documentos:[{id:'link-income',tipo:'COMPROBANTE_INGRESO',documento:{id:'doc-income',nombre_original:'transferencia.pdf',mime_type:'application/pdf'}}]}],solicitudesPago:[{id:'request-a',via:'DOCUMENTO_EXTERNO',estado:'PENDIENTE',concepto:'Derechos RPP',importe:'450.00',created_at:'2026-08-29T12:00:00Z',creadoPor:{nombre:'Andrea'},documentos:[{id:'link-request',tipo:'SOLICITUD_ORIGEN',documento:{id:'doc-request',nombre_original:'ficha-rpp.pdf',mime_type:'application/pdf'}}]}],presupuesto:{subtotal_honorarios:'1000.00',subtotal_impuestos_derechos:'500.00',total:'1500.00',version:1},catalogs:{accounts:[{id:'account-a',institucion:'Banco',alias:'Operativa',moneda:'MXN'}],categories:[{id:'category-a',clave:'DERECHOS',nombre:'Derechos',direccion:'EGRESO'}]},capabilities:{canRead:true,canReport:true,canCreateRequest:true,canApply:true,canUseAI:true,canReadDocuments:true,canRetireDocuments:true}});
const expediente={id:'exp-a',numero_pravia:'EXP-0001-2026',capabilities:{canReadFinance:true,canWriteFinance:true,canReadCaseFinance:true,canReportCaseFinance:true,canApplyCaseFinance:true,canWrite:true,canDeliver:false,canManagePostfirma:false,canReadProject:true,canUploadDocuments:true,canReadDocuments:true,canDeleteDocuments:true}} as unknown as ExpedienteDetail;

describe('EXP-008 · Finanzas del expediente UI',()=>{
  beforeEach(()=>{vi.clearAllMocks();api.read.mockResolvedValue(fixture());api.reportIncome.mockResolvedValue({});api.createInternalRequest.mockResolvedValue({});api.createExternalRequest.mockResolvedValue({});api.applyIncome.mockResolvedValue({});api.payRequest.mockResolvedValue({});api.proposeAI.mockResolvedValue({item:{id:'proposal-a',estado:'PENDIENTE',propuesta:{monto:'1000.00',referencia:'ABC'},provenance:[{campo:'monto',documento_id:'doc-income',documento:'transferencia.pdf',pagina:1}],conflictos:[],faltantes:['fecha'],modelo:'document-model'},idempotent:false});api.validateAI.mockResolvedValue({});api.generateReceipt.mockResolvedValue({});});
  it('muestra resumen, ingresos y solicitudes con estados inequívocos',async()=>{render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);expect(await screen.findByText('Anticipo inicial')).toBeInTheDocument();expect(screen.getByText('Pendiente de aplicación')).toBeInTheDocument();expect(screen.getByText('Derechos RPP')).toBeInTheDocument();expect(screen.getByText('Pendiente')).toBeInTheDocument();});
  it('separa el documento origen del comprobante reportado',async()=>{render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);expect(await screen.findByText('transferencia.pdf')).toBeInTheDocument();expect(screen.getByText('ficha-rpp.pdf')).toBeInTheDocument();});
  it('abre captura de ingreso y advierte que no auto-aplica',async()=>{render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);await userEvent.click(await screen.findByRole('button',{name:/Reportar ingreso/}));expect(screen.getByRole('dialog')).toBeInTheDocument();expect(screen.getByText('Subir evidencia no aplica ningún movimiento.')).toBeInTheDocument();});
  it('gestiona foco, Escape y retorno al activador del drawer',async()=>{const user=userEvent.setup();render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);const trigger=await screen.findByRole('button',{name:/Reportar ingreso/});await user.click(trigger);expect(screen.getByRole('button',{name:'Cerrar'})).toHaveFocus();await user.keyboard('{Escape}');expect(screen.queryByRole('dialog')).not.toBeInTheDocument();expect(trigger).toHaveFocus();});
  it('crea solicitud interna cuando no se adjunta ficha externa',async()=>{render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);await userEvent.click(await screen.findByRole('button',{name:/Solicitar pago/}));await userEvent.type(screen.getByLabelText('Concepto'),'Pago municipal');await userEvent.type(screen.getByLabelText('Importe'),'300');await userEvent.click(screen.getByRole('button',{name:'Crear solicitud'}));await waitFor(()=>expect(api.createInternalRequest).toHaveBeenCalledWith('exp-a',expect.objectContaining({concepto:'Pago municipal',importe:'300'})));});
  it('sólo expone aplicar cuando capability administrativa está presente',async()=>{api.read.mockResolvedValueOnce({...fixture(),capabilities:{...fixture().capabilities,canApply:false,canUseAI:false}});render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);await screen.findByText('Anticipo inicial');expect(screen.queryByRole('button',{name:'Aplicar'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Registrar pago'})).not.toBeInTheDocument();});
  it('muestra aplicación general Honorarios + Impuestos y derechos',async()=>{render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);await userEvent.click(await screen.findByRole('button',{name:'Aplicar'}));expect(screen.getByLabelText('Honorarios')).toBeInTheDocument();expect(screen.getByLabelText('Impuestos y derechos')).toBeInTheDocument();expect(screen.queryByText(/concepto por concepto/i)).not.toBeInTheDocument();});
  it('muestra documentos de pago y fiscales como campos separados',async()=>{render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);await userEvent.click(await screen.findByRole('button',{name:'Registrar pago'}));expect(screen.getByLabelText('Comprobante de pago (opcional)')).toBeInTheDocument();expect(screen.getByLabelText('Factura / comprobante fiscal (opcional)')).toBeInTheDocument();});
  it('envía sólo el documento autorizado al análisis IA',async()=>{render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);const buttons=await screen.findAllByRole('button',{name:/Analizar/});await userEvent.click(buttons[0]);await waitFor(()=>expect(api.proposeAI).toHaveBeenCalledWith('exp-a',expect.objectContaining({documento_id:'doc-income',ingreso_reportado_id:'income-a'})));});
  it('exige revisión humana visible y no aplica silenciosamente la propuesta IA',async()=>{render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);const buttons=await screen.findAllByRole('button',{name:/Analizar/});await userEvent.click(buttons[0]);expect(await screen.findByRole('heading',{name:'Revisar propuesta de IA'})).toBeInTheDocument();expect(screen.getByText('transferencia.pdf · página 1')).toBeInTheDocument();expect(api.applyIncome).not.toHaveBeenCalled();await userEvent.click(screen.getByRole('button',{name:'Validar datos revisados'}));await waitFor(()=>expect(api.validateAI).toHaveBeenCalledWith('exp-a','proposal-a',expect.objectContaining({decision:'ACCEPT',accepted_fields:expect.objectContaining({monto:'1000.00'})})));expect(api.applyIncome).not.toHaveBeenCalled();});
});
