import { render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
// Preload the two production lazy-route modules used by this integration file.
// This keeps global-suite worker/module transformation contention out of the
// behavioral assertions without changing the application's lazy-loading path.
import '../features/cases/ExpedienteWorkspace';
import '../features/cases/ExpedientesPage';
import { App } from '../app/App';
import { getAssistantActions, resolveAssistantContext } from '../features/assistant/assistantContext';
import type { ExpedienteDetail, ExpedienteListResult } from '../features/cases/expedientes.types';

const response = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } });
const waitForExpedienteWorkspace = () => waitFor(() => {
  expect(screen.queryByText('Cargando módulo…')).not.toBeInTheDocument();
  expect(screen.getByRole('heading', { name: 'Información del expediente' })).toBeInTheDocument();
}, { timeout: 10_000 });
const permissions = ['expedientes.read', 'expedientes.write', 'expedientes.project.read', 'documentos.read', 'documentos.write', 'comparecientes.read', 'comparecientes.write', 'notarias.read', 'usuarios.read', 'compliance.read'];
const session = (grants = permissions) => ({ user: { id: 'user-1', name: 'Andrea Ruiz', role: 'ADMINISTRACION', permissions: grants } });
const item = { id: 'exp-1', numero_pravia: 'EXP-0041-2026', numero_notaria: null, cliente_alias: 'Cliente Real', cliente_principal: 'Cliente Real', comparecientes_adicionales: 0, estatus: 'EN_INTEGRACION', macrofase: 'INTEGRACION', version: 2, etapa_actual_nombre: 'Validación documental', proxima_accion: 'Integrar documentos', fecha_limite_accion: null, fecha_estimada_firma: null, updated_at: '2026-08-12T17:30:00.000Z', tipo_acto: { id: 'act-1', nombre: 'Compraventa' }, abogado: { id: 'user-1', nombre: 'Andrea', apellido: 'Ruiz', rol: 'ADMINISTRACION' }, notaria: { id: 'notary-1', nombre: 'Notaría del Centro', numero_notaria: '12', municipio: 'Tepic' }, etapaActual: { id: 'stage-1', clave_snapshot: 'INTEGRACION', nombre_snapshot: 'Validación documental', orden_snapshot: 2, fecha_inicio: '2026-08-10T10:00:00.000Z' }, riesgo: { label: 'Sin evaluar', requires_attention: false, review_id: null }, vulnerable: { value: null, label: 'Sin evaluar' }, cumplimiento: { state: 'PENDIENTE', label: 'Pendiente', pending_count: 1 } } as const;
const list: ExpedienteListResult = { data: [item as any], metrics: [{ key: 'INTEGRACION', label: 'Integración', value: 1, percentage: 100 }, { key: 'PROYECTO', label: 'Proyecto', value: 0, percentage: 0 }, { key: 'FIRMA', label: 'Firma', value: 0, percentage: 0 }, { key: 'POSTFIRMA', label: 'Postfirma', value: 0, percentage: 0 }, { key: 'ENTREGADO', label: 'Entregado', value: 0, percentage: 0 }, { key: 'TOTAL', label: 'Total expedientes', value: 1, percentage: null }], meta: { total: 1, page: 1, pageSize: 20, limit: 20, totalPages: 1, hasPreviousPage: false, hasNextPage: false }, facets: { actTypes: [{ id: 'act-1', nombre: 'Compraventa', descripcion: 'Transmisión de propiedad', configuracionesOperativas: [{ id: 'cfg-1', clasificacion: 'TRASLATIVOS', familia: 'TRANSMISIÓN DE PROPIEDAD', nombre_personalizado: 'Compraventa', descripcion_personalizada: 'Transmisión de propiedad', revision: 4 }], tipoActoCaracteresCompareciente: [{ caracter_id: 'char-1', sugerido: true, caracter: { id: 'char-1', nombre: 'Comprador' } }] }, { id: 'act-2', nombre: 'Poder', descripcion: 'Representación', configuracionesOperativas: [{ id: 'cfg-2', clasificacion: 'NO_TRASLATIVOS', familia: 'REPRESENTACIÓN', nombre_personalizado: 'Poder', descripcion_personalizada: 'Representación voluntaria', revision: 2 }], tipoActoCaracteresCompareciente: [] }], responsibles: [{ id: 'user-1', nombre: 'Andrea', apellido: 'Ruiz', rol: 'ADMINISTRACION' }], notaries: [{ id: 'notary-1', nombre: 'Notaría del Centro', numero_notaria: '12', municipio: 'Tepic' }], stages: ['Validación documental'] } };
const actLinks=[{id:'exp-act-1',expediente_id:'exp-1',tipo_acto_id:'act-1',origen:'COTIZACION',estatus:'ACTIVO',created_at:'2026-08-01T10:00:00.000Z',tipo_acto:{id:'act-1',nombre:'Compraventa',descripcion:'Transmisión de propiedad'}},{id:'exp-act-2',expediente_id:'exp-1',tipo_acto_id:'act-1',origen:'ADICIONAL',estatus:'ACTIVO',created_at:'2026-08-02T10:00:00.000Z',tipo_acto:{id:'act-1',nombre:'Compraventa',descripcion:'Segunda instancia intencional'}}] as any;
const partyRelations=[{id:'party-link-1',expediente_id:'exp-1',expediente_acto_id:'exp-act-1',compareciente_id:'party-1',caracter_id:'char-1',forma_comparecencia:'PROPIO_DERECHO',participacion_porcentaje:'50',datos_validados:false,estatus:'ACTIVO',expedienteActo:actLinks[0],caracter:{id:'char-1',nombre:'Comprador'},compareciente:{id:'party-1',nombre_busqueda:'CLIENTE REAL',tipo_persona:'FISICA',personaFisica:{nombre_completo_calculado:'Cliente Real'},personaMoral:null},representacionesComoRepresentante:[]},{id:'party-link-2',expediente_id:'exp-1',expediente_acto_id:'exp-act-2',compareciente_id:'party-1',caracter_id:'char-2',forma_comparecencia:'PROPIO_DERECHO',participacion_porcentaje:null,datos_validados:false,estatus:'ACTIVO',expedienteActo:actLinks[1],caracter:{id:'char-2',nombre:'Fideicomitente'},compareciente:{id:'party-1',nombre_busqueda:'CLIENTE REAL',tipo_persona:'FISICA',personaFisica:{nombre_completo_calculado:'Cliente Real'},personaMoral:null},representacionesComoRepresentante:[]}] as any;
const detail: ExpedienteDetail = { ...(item as any), descripcion: null, created_at: '2026-08-01T10:00:00.000Z', fecha_apertura: '2026-08-01T10:00:00.000Z', fecha_escritura: null, numero_escritura: null, folio_desde: null, folio_hasta: null, creador: { id: 'user-1', nombre: 'Andrea', apellido: 'Ruiz' }, abogado: item.abogado, header_options: { responsibles: list.facets.responsibles }, flujoVersion: { id: 'flow-1', version: 3 }, actos: actLinks, comparecientes: [{ id: 'link-1', datos_validados: false, forma_comparecencia: 'PROPIO_DERECHO', caracter: { nombre: 'Comprador' }, compareciente: { personaFisica: { nombre_completo_calculado: 'Cliente Real' } } }], expedienteRepresentaciones: [], requisitos_docs: [{ id: 'req-1', nombre: 'Identificación oficial', obligatorio: true, estatus: 'PENDIENTE' }], expedienteDocumentos: [], etapas: [{ id: 'stage-1', clave_snapshot: 'INTEGRACION', nombre_snapshot: 'Validación documental', completada: false, fecha_inicio: '2026-08-10T10:00:00.000Z' }], tareas: [], tareas_externas: [], movimientosFinancieros: [], actividades: [{ id: 'activity-1', tipo: 'CAMBIO_ESTATUS', titulo: 'Apertura de expediente', descripcion: 'Expediente creado.', created_at: '2026-08-01T10:00:00.000Z', usuario: { nombre: 'Andrea', apellido: 'Ruiz' } }], complianceReviews: [], workflow: { current_status_label: 'En integración', transitions: [{ status: 'EN_PROCESO', label: 'En proceso', stage: { clave: 'PROYECTO', nombre: 'Elaboración de proyecto', orden: 3 }, requires_signature_data: false, requires_effective_date: false, requires_notes: false }], next_stage: { clave: 'PROYECTO', nombre: 'Elaboración de proyecto', orden: 3 }, stages: [{ clave: 'INTEGRACION', nombre: 'Validación documental', orden: 2, obligatoria: true, estado_general_relacionado: 'EN_INTEGRACION' }, { clave: 'PROYECTO', nombre: 'Elaboración de proyecto', orden: 3, obligatoria: true, estado_general_relacionado: 'EN_PROCESO' }] }, progress: { documental: 0, operativo: 0, financiero: 0, general: 0, configuration: { documental: 'EN_PROGRESO', operativo: 'EN_PROGRESO', financiero: 'NO_CONFIGURADO' } }, readiness: { indicators: [{ key: 'identidad', label: 'Identidad', state: 'PENDIENTE', detail: 'Falta validar comparecientes' }, { key: 'documentos', label: 'Documentos', state: 'PENDIENTE', detail: '1 requisito pendiente' }, { key: 'proyecto', label: 'Proyecto', state: 'PENDIENTE', detail: 'Sin proyecto vigente' }], blockers: [{ type: 'REQUISITO_FALTANTE', label: 'Identificación oficial' }], complete: 0 }, capabilities: { canWrite: true, canDeliver: false, canManagePostfirma: false, canReadProject: true, canReadFinance: false, canWriteFinance: false, canUploadDocuments: true, canReadDocuments: true, canDeleteDocuments: false } };
const financeMovement = { id:'mov-1',folio:'MOV-2026-000041',naturaleza:'INGRESO',tipo_movimiento:'ABONO',concepto:'Anticipo recibido',monto:60000,fecha_movimiento:'2026-08-12T12:00:00Z',estatus:'APLICADO',forma_pago:'TRANSFERENCIA',referencia:'SPEI-41',expediente:{id:'exp-1',numero_pravia:'EXP-0041-2026',cliente_alias:'Cliente Real'},cuenta:{id:'account-1',institucion:'BBVA',alias:'Operativa',moneda:'MXN'},distribuciones:[{id:'alloc-1',categoria_id:'fees',monto:40000,categoria:{id:'fees',clave:'HONORARIOS',nombre:'Honorarios',naturaleza:'DESPACHO',direccion:'INGRESO'}},{id:'alloc-2',categoria_id:'third',monto:20000,categoria:{id:'third',clave:'TERCEROS',nombre:'Recursos de terceros',naturaleza:'TERCERO',direccion:'AMBAS'}}],comprobanteInterno:{id:'internal-1',folio:'COM-2026-000041',estado:'VIGENTE'},movimientoDocumentos:[] };
const financeCatalogs={categories:financeMovement.distribuciones.map(item=>item.categoria),accounts:[financeMovement.cuenta],expedientes:[{id:'exp-1',numero_pravia:'EXP-0041-2026',cliente_alias:'Cliente Real',notaria_id:'notary-1',abogado_id:'user-1'}],notarias:[],responsables:[],permisos:{escribir:true,aplicar:true,conciliar:true,expedientesLeer:true,documentosLeer:true,documentosEscribir:true,documentosEliminar:true},invoiceIntegration:{configured:false,status:'PENDIENTE_CONFIGURACION',message:'Pendiente'},bankImport:{configured:false,message:'Pendiente'}};
const eligibleQuote={id:'quote-eligible',numero_solicitud:'SOL-2026-0042',numero_cotizacion:'COT-2026-0042',total_cliente:185000,updated_at:'2026-08-20T12:00:00.000Z',prospecto:{id:'prospect-1',nombre:'Cliente Real',tipo_acto:'Compraventa',email:'cliente@example.test',telefono:null},notaria:{id:'notary-1',nombre:'Notaría del Centro',numero_notaria:'12',municipio:'Tepic'},creada_por:{id:'user-1',nombre:'Andrea',apellido:'Ruiz'},conversion:{eligible:true,validatedAdvanceTotal:0},workflow:{stage:'ACEPTO_ANTICIPO',version:3,stageEnteredAt:'2026-08-20T11:00:00.000Z'}};
const questionnaireInstance={assessmentId:'assessment-1',bank:'OPERACION',artifact:{id:'questionnaire-1',name:'Acto / Operación'},version:{id:'questionnaire-version-1',number:3},definition:{schema_version:1,scope:'GENERAL',sections:[{id:'section-1',label:'Cuestionario de operación',questions:[{id:'question-1',label:'¿Requiere representación?',type:'BOOLEAN',required:false,active:true,order:0}]}]},subject:{key:'OPERACION:exp-act-1',label:'Compraventa'},prefill:{},latestResponse:null,formats:[]};

const mockApi = (options: { grants?: string[]; failList?: boolean; transitionFails?: boolean; empty?: boolean; denyActs?: boolean; staleApply?: boolean; headerFails?: boolean } = {}) => vi.stubGlobal('fetch', vi.fn(async (input: RequestInfo | URL, init?: RequestInit) => { const url = String(input); const grants=options.grants??permissions; const canReadFinance=grants.includes('finanzas.read');
  if (url.endsWith('/auth/me')) return response(session(grants));
  if (url.includes('/expedientes?')) return options.failList ? response({ error: 'No disponible' }, 500) : response(options.empty ? { ...list, data: [], metrics: list.metrics.map((metric) => ({ ...metric, value: 0, percentage: metric.key === 'TOTAL' ? null : 0 })), meta: { ...list.meta, total: 0 } } : list);
  if (url.endsWith('/expedientes/tipos-acto')) return response(list.facets.actTypes);
  if (url.endsWith('/usuarios')) return response(list.facets.responsibles);
  if (url.includes('/notarias?')) return response({ data: list.facets.notaries, meta: { total: 1, page: 1, limit: 30, totalPages: 1 } });
  if (url.includes('/comparecientes?')) return response({ data: [{ id: 'party-1', nombre_busqueda: 'CLIENTE REAL', tipo_persona: 'FISICA', personaFisica: { nombre_completo_calculado: 'Cliente Real', rfc: 'XAXX010101000' } }], meta: { total: 1 } });
  if (url.endsWith('/expedientes/cotizaciones-elegibles')) return response({data:[eligibleQuote],total:1});
  if (url.endsWith('/expedientes/convertir-cotizacion') && init?.method === 'POST') return response({ ...detail, id: 'created-exp', numero_pravia: 'EXP-0042-2026', idempotent:false }, 201);
  if (url.endsWith('/expedientes') && init?.method === 'POST') return response({error:'Todo expediente nuevo debe originarse desde una cotización elegible.',code:'EXPEDIENTE_QUOTE_ORIGIN_REQUIRED'},409);
  if (url.endsWith('/expedientes/exp-1/transicion-estatus')) return options.transitionFails ? response({ error: 'Aún hay requisitos pendientes.' }, 409) : response({ ...detail, version: 3 });
  if (url.endsWith('/expedientes/exp-1/actos') && (!init?.method || init.method === 'GET')) return options.denyActs ? response({error:'Sin alcance'},403) : response({data:actLinks,canonical_source:'ExpedienteActo',legacy_tipo_acto_id_editable:false});
  if (url.endsWith('/expedientes/exp-1/actos/preview') && init?.method === 'POST') return response({fingerprint:'preview-1',classification:'SAFE',target_tipo_acto:{id:'act-1',nombre:'Compraventa'},impact:{added:[{key:'cfg001:new',id:'stage-2',name:'Firma',source:'CFG-001'}],removed_or_no_longer_applicable:[],retained:[],protected_work:{count:0,requires_human_confirmation:false},sources:{cfg001:true,cfg002:true}}});
  if (url.endsWith('/expedientes/exp-1/actos/aplicar') && init?.method === 'POST') return options.staleApply ? response({error:'Vista previa obsoleta',code:'EXPEDIENTE_ACT_PREVIEW_STALE'},409) : response({acto:actLinks[0],idempotent:false,version:3},201);
  if (url.endsWith('/expedientes/exp-1/comparecientes') && (!init?.method || init.method === 'GET')) return response({data:partyRelations,canonical_source:'ExpedienteCompareciente',legacy_pending_act_assignment:0});
  if (url.includes('/expedientes/exp-1/comparecientes/buscar')) return response({data:[{id:'party-1',nombre:'Cliente Real',tipo_persona:'FISICA',identificador:'RFC ·••••1000'},{id:'party-2',nombre:'Representada Ejemplo',tipo_persona:'MORAL',identificador:'RFC ·••••2000'}]});
  if (url.endsWith('/expedientes/exp-1/comparecientes/catalogos')) return response({data:{acts:actLinks.map((act:any)=>({...act,tipo_acto:{...act.tipo_acto,tipoActoCaracteresCompareciente:[{caracter_id:'char-1',sugerido:true,caracter:{id:'char-1',nombre:'Comprador'}},{caracter_id:'char-2',sugerido:false,caracter:{id:'char-2',nombre:'Fideicomitente'}}]}})),representationCharacters:[{id:'rep-1',clave:'APODERADO',nombre:'Apoderado'}],appearanceForms:['PROPIO_DERECHO','EN_REPRESENTACION_PERSONA_MORAL','OTRO']}});
  if (url.endsWith('/expedientes/exp-1/comparecientes/preview') && init?.method === 'POST') return response({fingerprint:'party-preview-1',classification:'SAFE',impact:{added:[],removed_or_no_longer_applicable:[],retained:[],protected_work:{count:0,requires_human_confirmation:false},sources:{cfg002:true}}});
  if (url.endsWith('/expedientes/exp-1/comparecientes/aplicar') && init?.method === 'POST') return response({relation:partyRelations[0],idempotent:false,version:3},201);
  if (url.endsWith('/expedientes/exp-1/seguimiento')) return response({
    expediente_id:'exp-1',configuracion_actual_no_reaplicada:true,fecha_firma_manual:null,
    firma:{programada:null,efectiva:null,snapshot_canonico:false},entrega:{completada:false,fecha:null,alertasI:false,alertas_operativas_activas:true},
    actos:[{expediente_acto_id:'exp-act-1',tipo_acto_id:'act-1',nombre:'Compraventa',estatus:'ACTIVO',etapas:[]}],responsables:[item.abogado],
    proyeccion:{dias_restantes_ruta_critica:12,fecha_final_estimada:'2026-09-22T12:00:00.000Z',semantica_paralelo:'MAX',altera_fecha_estimada_firma:false},
    resumen_temporal:{fuente:'SEGUIMIENTO',dias_habiles_a_firma:5,dias_habiles_a_entrega:12},signals:{prefirm:[],postfirm:[]}
  });
  if (url.endsWith('/expedientes/exp-1/cuestionarios')) return response({success:true,data:[questionnaireInstance]});
  if (url.endsWith('/expedientes/exp-1/proyecto')) return response({ vigente: null, historial: [], ultimoReporte: null });
  if (url.endsWith('/expedientes/exp-1/finanzas-operativas')) return response({expediente:{id:'exp-1',numero_pravia:'EXP-0041-2026'},ingresosReportados:[],solicitudesPago:[],presupuesto:{subtotal_honorarios:'100000',subtotal_impuestos_derechos:'20000',total:'120000',version:1},catalogs:{accounts:financeCatalogs.accounts,categories:financeCatalogs.categories},capabilities:{canRead:true,canReport:true,canCreateRequest:true,canApply:true,canUseAI:true,canReadDocuments:true,canRetireDocuments:true}});
  if (url.endsWith('/finanzas/catalogos')) return response({success:true,data:financeCatalogs});
  if (url.endsWith('/expedientes/exp-1') && init?.method === 'PATCH') return options.headerFails ? response({ error: 'El expediente cambió.', code: 'EXPEDIENTE_VERSION_CONFLICT' }, 409) : response({ ...detail, ...JSON.parse(String(init.body || '{}')), version: 3 });
  if (url.endsWith('/expedientes/exp-1')||url.endsWith('/expedientes/created-exp')) return response({ ...detail, id:url.endsWith('/created-exp')?'created-exp':'exp-1', numero_pravia:url.endsWith('/created-exp')?'EXP-0042-2026':detail.numero_pravia, movimientosFinancieros:canReadFinance?[financeMovement]:[], financialSummary:canReadFinance?{ingresos_recibidos:60000,honorarios_generados:100000,honorarios_cobrados:40000,honorarios_por_cobrar:60000,fondos_terceros:20000,otros_destinos:0,fondos_terceros_pendientes:20000,egresos:0}:null, capabilities:{...detail.capabilities,canReadFinance,canWriteFinance:grants.includes('finanzas.write'),canReadDocuments:grants.includes('documentos.read'),canUploadDocuments:grants.includes('documentos.write'),canDeleteDocuments:grants.includes('documentos.unlink')} });
  return response({}, 204);
}));

describe('Expedientes', () => {
  beforeEach(() => vi.restoreAllMocks());
  it('renderiza seis KPIs, filtros por columna, tabla compacta y folio canónico', async () => { mockApi(); render(<MemoryRouter initialEntries={['/expedientes']}><App /></MemoryRouter>); expect(await screen.findByRole('heading', { name: 'Expedientes' })).toBeInTheDocument(); expect(await screen.findByRole('table')).toBeInTheDocument(); expect(screen.getByText('Total expedientes')).toBeInTheDocument(); expect(screen.getAllByText('EXP-0041-2026').length).toBeGreaterThan(0); expect(screen.queryByLabelText('Filtros de expedientes')).not.toBeInTheDocument(); expect(screen.getByLabelText('Filtrar Folio')).toBeInTheDocument(); });
  it('combina filtros de columna, permite limpiar uno y ordena desde encabezados', async () => { mockApi(); const user = userEvent.setup(); render(<MemoryRouter initialEntries={['/expedientes']}><App /></MemoryRouter>); await screen.findByRole('table'); await user.click(screen.getByLabelText('Filtrar Folio')); await user.type(screen.getByLabelText('Filtrar por folio'), '0041'); await waitFor(() => expect(fetch).toHaveBeenCalledWith(expect.stringContaining('folio=0041'), expect.anything())); await user.click(screen.getByLabelText('Filtrar Etapa')); await user.selectOptions(screen.getByLabelText('Filtrar por etapa'), 'Validación documental'); await waitFor(() => expect(fetch).toHaveBeenCalledWith(expect.stringMatching(/folio=0041.*etapa=Validaci%C3%B3n\+documental|etapa=Validaci%C3%B3n\+documental.*folio=0041/), expect.anything())); await user.click(screen.getAllByRole('button', { name: 'Limpiar este filtro' })[0]); await waitFor(() => expect(fetch).toHaveBeenCalledWith(expect.not.stringContaining('folio=0041'), expect.anything())); await user.click(screen.getByRole('button', { name: /Ordenar Folio/ })); await waitFor(() => expect(fetch).toHaveBeenCalledWith(expect.stringContaining('sort=numero_pravia%3Aasc'), expect.anything())); });
  it('abre la ficha desde toda la fila y conserva aislado el control interno', async () => { mockApi(); const user = userEvent.setup(); render(<MemoryRouter initialEntries={['/expedientes']}><App /></MemoryRouter>); const row = await screen.findByRole('row', { name: 'Abrir expediente EXP-0041-2026' }); expect(row).toHaveAttribute('tabindex', '0'); await user.click(within(row).getByText('Compraventa')); await waitForExpedienteWorkspace(); });
  it('oculta alta sin permiso y no expone finanzas fuera de alcance', async () => { mockApi({ grants: ['expedientes.read'] }); render(<MemoryRouter initialEntries={['/expedientes']}><App /></MemoryRouter>); await screen.findByRole('table'); expect(screen.queryByRole('button', { name: 'Nuevo expediente' })).not.toBeInTheDocument(); });
  it('abre expediente únicamente desde una cotización elegible y sin recaptura', async () => { mockApi(); const user = userEvent.setup(); render(<MemoryRouter initialEntries={['/expedientes']}><App /></MemoryRouter>); await screen.findByRole('table'); await user.click(screen.getByRole('button', { name: 'Nuevo expediente' })); expect(await screen.findByRole('heading',{name:'Selecciona una cotización elegible'})).toBeInTheDocument(); expect(screen.queryByPlaceholderText('Nombre, razón social, RFC o CURP')).not.toBeInTheDocument(); await user.click(screen.getByRole('button',{name:/COT-2026-0042/})); expect(screen.getByText('Aceptó / Anticipo confirmado')).toBeInTheDocument(); await user.click(screen.getByRole('button',{name:'Convertir en expediente'})); await waitFor(()=>expect(fetch).toHaveBeenCalledWith(expect.stringContaining('/expedientes/convertir-cotizacion'),expect.objectContaining({method:'POST'}))); const call=vi.mocked(fetch).mock.calls.find(([url])=>String(url).endsWith('/expedientes/convertir-cotizacion')); expect(JSON.parse(String(call?.[1]?.body))).toMatchObject({cotizacion_id:'quote-eligible',expectedVersion:3,confirm:true}); expect(vi.mocked(fetch).mock.calls.some(([url,init])=>String(url).endsWith('/expedientes')&&init?.method==='POST')).toBe(false); await waitForExpedienteWorkspace(); }, 15_000);
  it('muestra una única cabecera editable y navega a Seguimiento sin pestaña Resumen', async () => { mockApi(); render(<MemoryRouter initialEntries={['/expedientes/exp-1']}><App /></MemoryRouter>); await waitForExpedienteWorkspace(); expect(screen.getAllByRole('heading', { name: 'Información del expediente' })).toHaveLength(1); expect(screen.queryByRole('tab', { name: 'Resumen' })).not.toBeInTheDocument(); expect(screen.getByDisplayValue('EXP-0041-2026')).toHaveAttribute('readonly'); expect(screen.getByText('Los actos adicionales se conservan y se administran en la pestaña Actos.')).toBeInTheDocument(); expect(screen.getByRole('tablist', { name: 'Secciones del expediente' })).toBeInTheDocument(); const workflowTab = screen.getByRole('tab', { name: 'Seguimiento' }); expect(workflowTab).toHaveAttribute('aria-selected', 'false'); await userEvent.click(workflowTab); expect(workflowTab).toHaveAttribute('aria-selected', 'true'); expect(await screen.findByText(/Versión 3 congelada/)).toBeInTheDocument(); });
  it('guarda todos los campos dirty y el cambio de acto mediante una sola escritura atómica', async () => { mockApi(); const user = userEvent.setup(); render(<MemoryRouter initialEntries={['/expedientes/exp-1']}><App /></MemoryRouter>); await waitForExpedienteWorkspace(); expect(screen.getAllByDisplayValue('Andrea Ruiz').some((element) => element.hasAttribute('readonly'))).toBe(true); expect(screen.getByDisplayValue('EXP-0041-2026')).toHaveAttribute('readonly'); await user.clear(screen.getByLabelText('Cliente')); await user.type(screen.getByLabelText('Cliente'), 'Cliente editado'); const actSelect = screen.getAllByRole('combobox').find((element) => element.querySelector('option[value="act-2"]'))!; await user.selectOptions(actSelect, 'act-2'); await user.type(screen.getByLabelText('Número de escritura'), 'ESC-778'); await user.type(screen.getByLabelText('Fecha estimada de firma'), '2026-10-10'); const save = screen.getByRole('button', { name: 'Guardar cambios' }); expect(save).toBeEnabled(); await user.click(save); await waitFor(() => expect(fetch).toHaveBeenCalledWith(expect.stringContaining('/expedientes/exp-1'), expect.objectContaining({ method: 'PATCH' }))); const writes = vi.mocked(fetch).mock.calls.filter(([url, init]) => String(url).endsWith('/expedientes/exp-1') && init?.method === 'PATCH'); expect(writes).toHaveLength(1); const payload = JSON.parse(String(writes[0][1]?.body)); expect(payload).toMatchObject({ cliente_alias: 'Cliente editado', numero_escritura: 'ESC-778', fecha_estimada_firma: '2026-10-10', version: 2, act_change: { operation: 'CHANGE', tipo_acto_id: 'act-2', expediente_acto_id: 'exp-act-1' } }); expect(vi.mocked(fetch).mock.calls.some(([url, init]) => String(url).endsWith('/actos/aplicar') && init?.method === 'POST')).toBe(false); });
  it('conserva los valores locales si el backend rechaza el guardado', async () => { mockApi({ headerFails: true }); const user = userEvent.setup(); render(<MemoryRouter initialEntries={['/expedientes/exp-1']}><App /></MemoryRouter>); await waitForExpedienteWorkspace(); const client = screen.getByLabelText('Cliente'); await user.clear(client); await user.type(client, 'Cambio sin perder'); await user.click(screen.getByRole('button', { name: 'Guardar cambios' })); expect(await screen.findByRole('alert')).toHaveTextContent('El expediente cambió.'); expect(client).toHaveValue('Cambio sin perder'); });
  it('captura Fecha de escritura en Seguimiento sin confundirla con Fecha de firma', async () => { mockApi(); const user = userEvent.setup(); render(<MemoryRouter initialEntries={['/expedientes/exp-1#seguimiento']}><App /></MemoryRouter>); expect(await screen.findByRole('heading', { name: 'Datos de escrituración' })).toBeInTheDocument(); const deedDate = screen.getByLabelText('Fecha de escritura'); await user.type(deedDate, '2026-10-21'); await user.click(screen.getByRole('button', { name: 'Guardar fecha' })); const write = await waitFor(() => vi.mocked(fetch).mock.calls.find(([url, init]) => String(url).endsWith('/expedientes/exp-1') && init?.method === 'PATCH')) as any; const payload = JSON.parse(String(write[1]?.body)); expect(payload).toEqual({ fecha_escritura: '2026-10-21', version: 2 }); expect(payload).not.toHaveProperty('fecha_firma'); });
  it('muestra sólo cuestionarios aplicables derivados de Cumplimiento', async () => { mockApi(); render(<MemoryRouter initialEntries={['/expedientes/exp-1#cuestionarios']}><App /></MemoryRouter>); expect(await screen.findByRole('heading',{name:'Acto / Operación'})).toBeInTheDocument(); expect(screen.getAllByText('Compraventa').length).toBeGreaterThan(0); expect(screen.getByText('¿Requiere representación?')).toBeInTheDocument(); expect(screen.queryByText(/Alimenta ADM-001/)).not.toBeInTheDocument(); });
  it('oculta Cumplimiento y neutraliza el deep-link sin compliance.read', async () => { mockApi({ grants: ['expedientes.read'] }); render(<MemoryRouter initialEntries={['/expedientes/exp-1#cumplimiento']}><App /></MemoryRouter>); expect(await screen.findByRole('heading', { name: 'Información del expediente' })).toBeInTheDocument(); expect(screen.queryByRole('tab', { name: 'Cumplimiento' })).not.toBeInTheDocument(); expect(await screen.findByRole('heading', { name: 'Actos del expediente' })).toBeInTheDocument(); });
  it('muestra dos instancias del mismo acto y exige preview desde selector jerárquico CFG-001', async () => { mockApi(); const user=userEvent.setup(); render(<MemoryRouter initialEntries={['/expedientes/exp-1#actos']}><App /></MemoryRouter>); expect(await screen.findByRole('heading',{name:'Actos del expediente'})).toBeInTheDocument(); expect((await screen.findAllByText('Compraventa')).length).toBeGreaterThanOrEqual(3); expect(screen.getByText(/Instancia 1/)).toBeInTheDocument(); expect(screen.getByText(/Instancia 2/)).toBeInTheDocument(); await user.click(screen.getByRole('button',{name:'Agregar acto'})); const dialog=screen.getByRole('dialog',{name:'Agregar acto'}); expect(within(dialog).getByLabelText('Selector CFG-001 de actos')).toBeInTheDocument(); await user.click(within(dialog).getByRole('button',{name:/Compraventa/})); expect(within(dialog).queryByRole('button',{name:'Confirmar cambio'})).not.toBeInTheDocument(); await user.click(within(dialog).getByRole('button',{name:'Revisar impacto'})); expect(await within(dialog).findByText('Cambio seguro')).toBeInTheDocument(); await user.click(within(dialog).getByRole('button',{name:'Confirmar cambio'})); await waitFor(()=>expect(fetch).toHaveBeenCalledWith(expect.stringContaining('/expedientes/exp-1/actos/aplicar'),expect.objectContaining({method:'POST'}))); });
  it('distingue permiso denegado y preview obsoleto en Actos', async () => { mockApi({denyActs:true}); const denied=render(<MemoryRouter initialEntries={['/expedientes/exp-1#actos']}><App /></MemoryRouter>); expect(await screen.findByText('No tienes permiso para consultar los actos de este expediente.')).toBeInTheDocument(); denied.unmount(); mockApi({staleApply:true}); const user=userEvent.setup(); render(<MemoryRouter initialEntries={['/expedientes/exp-1#actos']}><App /></MemoryRouter>); await screen.findByText(/Instancia 1/); await user.click(screen.getByRole('button',{name:'Agregar acto'})); const dialog=screen.getByRole('dialog',{name:'Agregar acto'}); await user.click(within(dialog).getByRole('button',{name:/Compraventa/})); await user.click(within(dialog).getByRole('button',{name:'Revisar impacto'})); await user.click(await within(dialog).findByRole('button',{name:'Confirmar cambio'})); expect(await within(dialog).findByText('La vista previa quedó obsoleta porque el expediente cambió. Revisa nuevamente el impacto.')).toBeInTheDocument(); });
  it('muestra la misma identidad en varios actos y vincula mediante preview sin mini-ficha', async()=>{mockApi();const user=userEvent.setup();render(<MemoryRouter initialEntries={['/expedientes/exp-1#comparecientes']}><App/></MemoryRouter>);expect(await screen.findByRole('heading',{name:'Comparecientes'})).toBeInTheDocument();expect(screen.getByDisplayValue('Cliente Real')).toBeInTheDocument();expect(screen.getByText('Ficha maestra única · Persona física · 2 relaciones')).toBeInTheDocument();expect(screen.getByText('Fideicomitente')).toBeInTheDocument();expect(screen.getByText('50%')).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Agregar compareciente'}));const dialog=screen.getByRole('dialog',{name:'Agregar compareciente'});expect(within(dialog).getByRole('button',{name:/Crear nuevo/})).toBeInTheDocument();expect(within(dialog).queryByLabelText('Nombre')).not.toBeInTheDocument();await user.selectOptions(within(dialog).getByLabelText('Comparecencia'),'OTRO');expect(within(dialog).queryByRole('group',{name:'Representación'})).not.toBeInTheDocument();await user.type(within(dialog).getByLabelText('Buscar persona existente'),'Cliente');await user.click(await within(dialog).findByRole('option',{name:/Cliente Real/}));await user.selectOptions(within(dialog).getByLabelText('Acto'),'exp-act-1');await user.selectOptions(within(dialog).getByLabelText('Rol / carácter'),'char-1');await user.click(within(dialog).getByRole('button',{name:'Revisar impacto'}));expect(await within(dialog).findByText('Cambio seguro')).toBeInTheDocument();await user.click(within(dialog).getByRole('button',{name:'Confirmar cambio'}));await waitFor(()=>expect(fetch).toHaveBeenCalledWith(expect.stringContaining('/expedientes/exp-1/comparecientes/aplicar'),expect.objectContaining({method:'POST'})));});
  it('consolida Finanzas dentro del expediente y bloquea el vínculo al registrar',async()=>{const grants=[...permissions,'finanzas.read','finanzas.write','finanzas.validate','documentos.unlink'];mockApi({grants});const user=userEvent.setup();render(<MemoryRouter initialEntries={['/expedientes/exp-1#finanzas']}><App/></MemoryRouter>);expect(await screen.findByText('Honorarios generados')).toBeInTheDocument();expect(screen.getByText('$100,000.00')).toBeInTheDocument();expect(screen.getByText('Honorarios cobrados')).toBeInTheDocument();expect(screen.getByText('$40,000.00')).toBeInTheDocument();expect(screen.getByText('Por cobrar')).toBeInTheDocument();expect(screen.getAllByText('$60,000.00').length).toBeGreaterThan(0);expect(screen.getByText('Recursos no propios')).toBeInTheDocument();expect(screen.getByText('Sin comprobante')).toBeInTheDocument();await user.click(await screen.findByRole('button',{name:'Registrar movimiento'}));const dialog=screen.getByRole('dialog',{name:'Registrar movimiento'});await user.click(within(dialog).getByRole('button',{name:/Continuar/}));const expedienteSelect=within(dialog).getByLabelText('Expediente');expect(expedienteSelect).toBeDisabled();expect(expedienteSelect).toHaveValue('exp-1');});
  it('muestra error humano ante transición inválida', async () => { mockApi({ transitionFails: true }); const user = userEvent.setup(); render(<MemoryRouter initialEntries={['/expedientes/exp-1#seguimiento']}><App /></MemoryRouter>); await screen.findByText(/Versión 3 congelada/); await user.click(screen.getByRole('button', { name: 'En proceso' })); expect(await screen.findByText('No fue posible avanzar. Revisa los requisitos pendientes y vuelve a confirmar.')).toBeInTheDocument(); });
  it('muestra vacío y error sin romper el shell', async () => { mockApi({ empty: true }); const first = render(<MemoryRouter initialEntries={['/expedientes']}><App /></MemoryRouter>); expect(await screen.findByText('No hay expedientes.')).toBeInTheDocument(); first.unmount(); mockApi({ failList: true }); render(<MemoryRouter initialEntries={['/expedientes']}><App /></MemoryRouter>); expect(await screen.findByText('No pudimos cargar los expedientes.')).toBeInTheDocument(); });
  it('expone contexto IA distinto para lista y expediente real', () => { const listContext = resolveAssistantContext({ pathname: '/expedientes', hash: '' }); const detailContext = resolveAssistantContext({ pathname: '/expedientes/exp-1', hash: '#documentos' }); expect(getAssistantActions(listContext).map((action) => action.label)).toContain('Expedientes bloqueados'); expect(detailContext).toMatchObject({ module: 'expedientes', entityType: 'expediente', entityId: 'exp-1', subview: 'documentos' }); expect(getAssistantActions(detailContext).map((action) => action.label)).toContain('¿Qué falta?'); });
});
