import { fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { WorkflowTab } from '../features/cases/components/tabs/WorkflowTab';
import { expedientesService } from '../features/cases/expedientes.service';
import type { ExpedienteDetail, ExpedienteSeguimiento, SeguimientoActivity } from '../features/cases/expedientes.types';

vi.mock('../features/cases/expedientes.service', () => ({ expedientesService: { seguimiento: vi.fn(), materializeSeguimiento: vi.fn(), updateSeguimientoActivity: vi.fn(), reopenSeguimientoActivity: vi.fn(), transition: vi.fn(), documentAppendix: vi.fn() } }));

const activity = (overrides: Partial<SeguimientoActivity> = {}): SeguimientoActivity => ({
  id: 'activity-1', expediente_acto_id: 'act-1', etapa_nombre_snapshot: 'Prefirma', actividad_nombre_snapshot: 'Revisar documentación',
  estado: 'NO_INICIADO', estado_operativo: 'NO_INICIADO', estado_efectivo: 'NO_INICIADO', estado_label: 'No iniciado', version: 1,
  en_alcance: true, requiere_revision: false, responsable_id: 'user-1', responsable: { id: 'user-1', nombre: 'Andrea', apellido: 'Ruiz' },
  aplica_por_defecto: true, resolucion_fuente: 'GENERAL', dependencias: [], bloqueada_por: [],
  tiempo: { estimado: 3, tipo_dias: 'HABILES', margen: 1, transcurrido: 0, atrasada: false, margen_consumido: false }, ...overrides,
});
const tracking = (activities: SeguimientoActivity[] = [activity()]): ExpedienteSeguimiento => ({
  expediente_id: 'exp-1', configuracion_actual_no_reaplicada: true, fecha_firma_manual: '2026-09-01T17:00:00Z',
  firma: { programada: '2026-09-01T17:00:00Z', efectiva: null, snapshot_canonico: false },
  entrega: { completada: false, fecha: null, alertas_operativas_activas: true },
  actos: [{ expediente_acto_id: 'act-1', tipo_acto_id: 'type-1', nombre: 'Compraventa', estatus: 'ACTIVO', etapas: [{ nombre: 'Prefirma', orden: 1, actividades: activities }] }],
  responsables: [{ id: 'user-1', nombre: 'Andrea', apellido: 'Ruiz' }], signals: { prefirm: activities, postfirm: [] },
});
const expediente = { id: 'exp-1', version: 1, estatus: 'ABIERTO', macrofase: 'APERTURA', etapas: [], workflow: { current_status_label: 'Abierto', transitions: [], stages: [] }, capabilities: { canWrite: true } } as unknown as ExpedienteDetail;

describe('EXP-005 · Seguimiento UI', () => {
  beforeEach(() => { vi.clearAllMocks(); vi.mocked(expedientesService.seguimiento).mockResolvedValue(tracking()); });
  it('muestra jerarquía Acto → Etapa → Actividad y fecha manual', async () => { render(<WorkflowTab expediente={expediente} onChanged={vi.fn()} />); expect(await screen.findByText('Compraventa')).toBeInTheDocument(); expect(screen.getByText('Prefirma')).toBeInTheDocument(); expect(screen.getByText('Revisar documentación')).toBeInTheDocument(); expect(screen.getByText('Fecha de firma manual')).toBeInTheDocument(); });
  it('explica causa de bloqueo sin depender sólo del color', async () => { vi.mocked(expedientesService.seguimiento).mockResolvedValue(tracking([activity({ estado: 'BLOQUEADO', estado_operativo: 'BLOQUEADO', estado_efectivo: 'BLOQUEADO', estado_label: 'Bloqueado', bloqueada_por: [{ id: 'a', nombre: 'Validar identidad', estado: 'EN_PROCESO' }], dependencias: [{ id: 'd', actividad_id: 'a', nombre: 'Validar identidad', estado: 'EN_PROCESO', bloqueante: true }] })])); render(<WorkflowTab expediente={expediente} onChanged={vi.fn()} />); expect(await screen.findByText(/Bloqueada por:/)).toBeInTheDocument(); expect(screen.getAllByText(/Validar identidad/).length).toBeGreaterThan(0); expect(screen.getByRole('button', { name: 'Iniciar' })).toBeDisabled(); });
  it('inicia actividad con versión optimista', async () => { vi.mocked(expedientesService.updateSeguimientoActivity).mockResolvedValue({} as any); render(<WorkflowTab expediente={expediente} onChanged={vi.fn()} />); fireEvent.click(await screen.findByRole('button', { name: 'Iniciar' })); await waitFor(() => expect(expedientesService.updateSeguimientoActivity).toHaveBeenCalledWith('exp-1', 'activity-1', { expected_version: 1, estado: 'EN_PROCESO' })); });
  it('reabre mediante diálogo accesible y motivo', async () => { vi.mocked(expedientesService.seguimiento).mockResolvedValue(tracking([activity({ estado: 'COMPLETADO', estado_operativo: 'COMPLETADO', estado_efectivo: 'COMPLETADO', estado_label: 'Completado' })])); vi.mocked(expedientesService.reopenSeguimientoActivity).mockResolvedValue({} as any); render(<WorkflowTab expediente={expediente} onChanged={vi.fn()} />); fireEvent.click(await screen.findByRole('button', { name: 'Reabrir' })); const dialog = screen.getByRole('dialog', { name: 'Reabrir actividad' }); fireEvent.change(within(dialog).getByRole('textbox', { name: 'Motivo' }), { target: { value: 'Corrección documental' } }); fireEvent.click(within(dialog).getByRole('button', { name: 'Reabrir y reevaluar' })); await waitFor(() => expect(expedientesService.reopenSeguimientoActivity).toHaveBeenCalledWith('exp-1', 'activity-1', { expected_version: 1, razon: 'Corrección documental' })); });
  it('guarda un ajuste particular sin modificar CFG-001', async () => { vi.mocked(expedientesService.updateSeguimientoActivity).mockResolvedValue({} as any); render(<WorkflowTab expediente={expediente} onChanged={vi.fn()} />); fireEvent.click(await screen.findByRole('button', { name: 'Ajustar' })); const dialog = screen.getByRole('dialog', { name: 'Ajuste particular' }); fireEvent.change(within(dialog).getByRole('spinbutton', { name: 'Duración estimada' }), { target: { value: '6' } }); fireEvent.change(within(dialog).getByRole('spinbutton', { name: 'Margen de seguridad' }), { target: { value: '2' } }); fireEvent.change(within(dialog).getByRole('combobox', { name: 'Tipo de días' }), { target: { value: 'NATURALES' } }); fireEvent.change(within(dialog).getByRole('textbox', { name: 'Motivo del ajuste' }), { target: { value: 'Plazo confirmado con la institución.' } }); fireEvent.click(within(dialog).getByRole('button', { name: 'Guardar ajuste particular' })); await waitFor(() => expect(expedientesService.updateSeguimientoActivity).toHaveBeenCalledWith('exp-1', 'activity-1', { expected_version: 1, excepcion_operativa: { duracion_estimada: 6, margen_seguridad: 2, tipo_dias: 'NATURALES', motivo: 'Plazo confirmado con la institución.' }, razon: 'Plazo confirmado con la institución.' })); });
  it('muestra entrega final sin borrar la trazabilidad', async () => { vi.mocked(expedientesService.seguimiento).mockResolvedValue({ ...tracking(), entrega: { completada: true, fecha: '2026-09-10T12:00:00Z', alertas_operativas_activas: false } }); render(<WorkflowTab expediente={expediente} onChanged={vi.fn()} />); expect(await screen.findByText('Entregado al cliente')).toBeInTheDocument(); expect(screen.getByText(/alertas operativas normales están detenidas; el historial permanece/i)).toBeInTheDocument(); });
});
