import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { App } from '../app/App';
import { getAssistantActions, resolveAssistantContext } from '../features/assistant/assistantContext';
import type { ExpedienteDetail, ExpedienteListResult } from '../features/cases/expedientes.types';

const response = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } });
const permissions = ['expedientes.read', 'expedientes.write', 'expedientes.project.read', 'documentos.read', 'documentos.write', 'comparecientes.read', 'notarias.read', 'usuarios.read', 'cumplimiento.read'];
const session = (grants = permissions) => ({ user: { id: 'user-1', name: 'Andrea Ruiz', role: 'ADMINISTRACION', permissions: grants } });
const item = { id: 'exp-1', numero_pravia: 'EXP-2026-0041', numero_notaria: null, cliente_alias: 'Cliente Real', cliente_principal: 'Cliente Real', comparecientes_adicionales: 0, estatus: 'EN_INTEGRACION', macrofase: 'INTEGRACION', version: 2, etapa_actual_nombre: 'Validación documental', proxima_accion: 'Integrar documentos', fecha_limite_accion: null, fecha_estimada_firma: null, updated_at: '2026-08-12T17:30:00.000Z', tipo_acto: { id: 'act-1', nombre: 'Compraventa' }, abogado: { id: 'user-1', nombre: 'Andrea', apellido: 'Ruiz', rol: 'ADMINISTRACION' }, notaria: { id: 'notary-1', nombre: 'Notaría del Centro', numero_notaria: '12', municipio: 'Tepic' }, etapaActual: { id: 'stage-1', clave_snapshot: 'INTEGRACION', nombre_snapshot: 'Validación documental', orden_snapshot: 2, fecha_inicio: '2026-08-10T10:00:00.000Z' }, riesgo: { label: 'Sin evaluar', requires_attention: false, review_id: null } } as const;
const list: ExpedienteListResult = { data: [item as any], metrics: [{ key: 'INTEGRACION', label: 'Integración', value: 1, percentage: 100 }, { key: 'PROYECTO', label: 'Proyecto', value: 0, percentage: 0 }, { key: 'FIRMA', label: 'Firma', value: 0, percentage: 0 }, { key: 'POSTFIRMA', label: 'Postfirma', value: 0, percentage: 0 }, { key: 'ENTREGADO', label: 'Entregado', value: 0, percentage: 0 }, { key: 'TOTAL', label: 'Total expedientes', value: 1, percentage: null }], meta: { total: 1, page: 1, pageSize: 20, limit: 20, totalPages: 1, hasPreviousPage: false, hasNextPage: false }, facets: { actTypes: [{ id: 'act-1', nombre: 'Compraventa', descripcion: 'Transmisión de propiedad', tipoActoCaracteresCompareciente: [{ caracter_id: 'char-1', sugerido: true, caracter: { id: 'char-1', nombre: 'Comprador' } }] }], responsibles: [{ id: 'user-1', nombre: 'Andrea', apellido: 'Ruiz', rol: 'ADMINISTRACION' }], notaries: [{ id: 'notary-1', nombre: 'Notaría del Centro', numero_notaria: '12', municipio: 'Tepic' }], stages: ['Validación documental'] } };
const detail: ExpedienteDetail = { ...(item as any), descripcion: null, created_at: '2026-08-01T10:00:00.000Z', fecha_apertura: '2026-08-01T10:00:00.000Z', abogado: item.abogado, flujoVersion: { id: 'flow-1', version: 3 }, comparecientes: [{ id: 'link-1', datos_validados: false, forma_comparecencia: 'PROPIO_DERECHO', caracter: { nombre: 'Comprador' }, compareciente: { personaFisica: { nombre_completo_calculado: 'Cliente Real' } } }], expedienteRepresentaciones: [], requisitos_docs: [{ id: 'req-1', nombre: 'Identificación oficial', obligatorio: true, estatus: 'PENDIENTE' }], expedienteDocumentos: [], etapas: [{ id: 'stage-1', clave_snapshot: 'INTEGRACION', nombre_snapshot: 'Validación documental', completada: false, fecha_inicio: '2026-08-10T10:00:00.000Z' }], tareas: [], tareas_externas: [], movimientosFinancieros: [], actividades: [{ id: 'activity-1', tipo: 'CAMBIO_ESTATUS', titulo: 'Apertura de expediente', descripcion: 'Expediente creado.', created_at: '2026-08-01T10:00:00.000Z', usuario: { nombre: 'Andrea', apellido: 'Ruiz' } }], complianceReviews: [], workflow: { current_status_label: 'En integración', transitions: [{ status: 'EN_PROCESO', label: 'En proceso', stage: { clave: 'PROYECTO', nombre: 'Elaboración de proyecto', orden: 3 }, requires_signature_data: false, requires_effective_date: false, requires_notes: false }], next_stage: { clave: 'PROYECTO', nombre: 'Elaboración de proyecto', orden: 3 }, stages: [{ clave: 'INTEGRACION', nombre: 'Validación documental', orden: 2, obligatoria: true, estado_general_relacionado: 'EN_INTEGRACION' }, { clave: 'PROYECTO', nombre: 'Elaboración de proyecto', orden: 3, obligatoria: true, estado_general_relacionado: 'EN_PROCESO' }] }, progress: { documental: 0, operativo: 0, financiero: 0, general: 0, configuration: { documental: 'EN_PROGRESO', operativo: 'EN_PROGRESO', financiero: 'NO_CONFIGURADO' } }, readiness: { indicators: [{ key: 'identidad', label: 'Identidad', state: 'PENDIENTE', detail: 'Falta validar comparecientes' }, { key: 'documentos', label: 'Documentos', state: 'PENDIENTE', detail: '1 requisito pendiente' }, { key: 'proyecto', label: 'Proyecto', state: 'PENDIENTE', detail: 'Sin proyecto vigente' }], blockers: [{ type: 'REQUISITO_FALTANTE', label: 'Identificación oficial' }], complete: 0 }, capabilities: { canWrite: true, canDeliver: false, canManagePostfirma: false, canReadProject: true, canReadFinance: false, canUploadDocuments: true } };

const mockApi = (options: { grants?: string[]; failList?: boolean; transitionFails?: boolean; empty?: boolean } = {}) => vi.stubGlobal('fetch', vi.fn(async (input: RequestInfo | URL, init?: RequestInit) => { const url = String(input);
  if (url.endsWith('/auth/me')) return response(session(options.grants));
  if (url.includes('/expedientes?')) return options.failList ? response({ error: 'No disponible' }, 500) : response(options.empty ? { ...list, data: [], metrics: list.metrics.map((metric) => ({ ...metric, value: 0, percentage: metric.key === 'TOTAL' ? null : 0 })), meta: { ...list.meta, total: 0 } } : list);
  if (url.endsWith('/expedientes/tipos-acto')) return response(list.facets.actTypes);
  if (url.endsWith('/usuarios')) return response(list.facets.responsibles);
  if (url.includes('/notarias?')) return response({ data: list.facets.notaries, meta: { total: 1, page: 1, limit: 30, totalPages: 1 } });
  if (url.includes('/comparecientes?')) return response({ data: [{ id: 'party-1', nombre_busqueda: 'CLIENTE REAL', tipo_persona: 'FISICA', personaFisica: { nombre_completo_calculado: 'Cliente Real', rfc: 'XAXX010101000' } }], meta: { total: 1 } });
  if (url.endsWith('/expedientes') && init?.method === 'POST') return response({ ...detail, id: 'created-exp', numero_pravia: 'EXP-2026-0042' }, 201);
  if (url.endsWith('/expedientes/exp-1/transicion-estatus')) return options.transitionFails ? response({ error: 'Aún hay requisitos pendientes.' }, 409) : response({ ...detail, version: 3 });
  if (url.endsWith('/expedientes/exp-1/proyecto')) return response({ vigente: null, historial: [], ultimoReporte: null });
  if (url.endsWith('/expedientes/exp-1')) return response(detail);
  return response({}, 204);
}));

describe('Expedientes', () => {
  beforeEach(() => vi.restoreAllMocks());
  it('renderiza seis KPIs, filtros densos, tabla y datos reales', async () => { mockApi(); render(<MemoryRouter initialEntries={['/expedientes']}><App /></MemoryRouter>); expect(await screen.findByRole('heading', { name: 'Expedientes' })).toBeInTheDocument(); expect(await screen.findByRole('table')).toBeInTheDocument(); expect(screen.getByText('Total expedientes')).toBeInTheDocument(); expect(screen.getAllByText('EXP-2026-0041').length).toBeGreaterThan(0); });
  it('envía búsqueda, filtro y paginación al servidor', async () => { mockApi(); const user = userEvent.setup(); render(<MemoryRouter initialEntries={['/expedientes']}><App /></MemoryRouter>); await screen.findByRole('table'); await user.type(screen.getByPlaceholderText('Folio, cliente, acto, notaría…'), 'Cliente'); await waitFor(() => expect(fetch).toHaveBeenCalledWith(expect.stringContaining('search=Cliente'), expect.anything())); await user.selectOptions(screen.getByLabelText('Etapa'), 'Validación documental'); await waitFor(() => expect(fetch).toHaveBeenCalledWith(expect.stringContaining('etapa=Validaci%C3%B3n+documental'), expect.anything())); });
  it('oculta alta sin permiso y no expone finanzas fuera de alcance', async () => { mockApi({ grants: ['expedientes.read'] }); render(<MemoryRouter initialEntries={['/expedientes']}><App /></MemoryRouter>); await screen.findByRole('table'); expect(screen.queryByRole('button', { name: 'Nuevo expediente' })).not.toBeInTheDocument(); });
  it('abre un expediente directo y deja el folio exclusivamente al servidor', async () => { mockApi(); const user = userEvent.setup(); render(<MemoryRouter initialEntries={['/expedientes']}><App /></MemoryRouter>); await screen.findByRole('table'); await user.click(screen.getByRole('button', { name: 'Nuevo expediente' })); await user.click(await screen.findByRole('button', { name: /Compraventa/ })); await user.click(screen.getByRole('button', { name: /Continuar/ })); await user.type(screen.getByPlaceholderText('Nombre, razón social, RFC o CURP'), 'Cliente'); await user.click(await screen.findByRole('button', { name: /Cliente Real/ })); await user.click(screen.getByRole('button', { name: /Continuar/ })); await user.click(screen.getByRole('button', { name: /Continuar/ })); const responsibleButtons = screen.getAllByRole('button', { name: /Andrea Ruiz/ }); await user.click(responsibleButtons[responsibleButtons.length - 1]); await user.click(screen.getByRole('button', { name: /Continuar/ })); await user.click(screen.getByRole('button', { name: 'Crear expediente' })); await waitFor(() => expect(vi.mocked(fetch).mock.calls.some(([url, init]) => String(url).endsWith('/expedientes') && init?.method === 'POST')).toBe(true)); const call = vi.mocked(fetch).mock.calls.find(([url, init]) => String(url).endsWith('/expedientes') && init?.method === 'POST'); const body = JSON.parse(String(call?.[1]?.body)); expect(body).toMatchObject({ tipo_acto_id: 'act-1', compareciente_id: 'party-1', abogado_id: 'user-1' }); expect(body).not.toHaveProperty('numero_pravia'); });
  it('abre workspace con readiness inequívoco, tabs accesibles y workflow congelado', async () => { mockApi(); render(<MemoryRouter initialEntries={['/expedientes/exp-1']}><App /></MemoryRouter>); expect(await screen.findByRole('heading', { name: 'Compraventa' })).toBeInTheDocument(); expect(screen.getByText('¿Está listo para avanzar?')).toBeInTheDocument(); expect(screen.getByText('0 de 3 completos')).toBeInTheDocument(); expect(screen.queryByText('0 completos')).not.toBeInTheDocument(); expect(screen.getAllByText('Identificación oficial').length).toBeGreaterThan(0); const workflowTab = screen.getByRole('tab', { name: 'Workflow' }); expect(workflowTab).toHaveAttribute('aria-selected', 'false'); await userEvent.click(workflowTab); expect(workflowTab).toHaveAttribute('aria-selected', 'true'); expect(await screen.findByText(/Versión 3 congelada/)).toBeInTheDocument(); });
  it('muestra error humano ante transición inválida', async () => { mockApi({ transitionFails: true }); const user = userEvent.setup(); render(<MemoryRouter initialEntries={['/expedientes/exp-1#workflow']}><App /></MemoryRouter>); await screen.findByText(/Versión 3 congelada/); await user.click(screen.getByRole('button', { name: 'En proceso' })); expect(await screen.findByText('No fue posible avanzar. Revisa los requisitos pendientes.')).toBeInTheDocument(); });
  it('muestra vacío y error sin romper el shell', async () => { mockApi({ empty: true }); const first = render(<MemoryRouter initialEntries={['/expedientes']}><App /></MemoryRouter>); expect(await screen.findByText('No hay expedientes.')).toBeInTheDocument(); first.unmount(); mockApi({ failList: true }); render(<MemoryRouter initialEntries={['/expedientes']}><App /></MemoryRouter>); expect(await screen.findByText('No pudimos cargar los expedientes.')).toBeInTheDocument(); });
  it('expone contexto IA distinto para lista y expediente real', () => { const listContext = resolveAssistantContext({ pathname: '/expedientes', hash: '' }); const detailContext = resolveAssistantContext({ pathname: '/expedientes/exp-1', hash: '#documentos' }); expect(getAssistantActions(listContext).map((action) => action.label)).toContain('Expedientes bloqueados'); expect(detailContext).toMatchObject({ module: 'expedientes', entityType: 'expediente', entityId: 'exp-1', subview: 'documentos' }); expect(getAssistantActions(detailContext).map((action) => action.label)).toContain('¿Qué falta?'); });
});
