import { fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { FinanceTab } from '../features/cases/components/tabs/FinanceTab';
import type { ExpedienteDetail } from '../features/cases/expedientes.types';

const api = vi.hoisted(()=>({read:vi.fn(),reportIncome:vi.fn(),previewIncomeAI:vi.fn(),completeInvoice:vi.fn(),createInternalRequest:vi.fn(),createExternalRequest:vi.fn(),applyIncome:vi.fn(),payRequest:vi.fn(),proposeAI:vi.fn(),validateAI:vi.fn(),generateReceipt:vi.fn(),generateAccountStatement:vi.fn(),openDocument:vi.fn()}));
vi.mock('../features/cases/expedienteFinance.service',()=>({expedienteFinanceService:api}));

const fixture=()=>({expediente:{id:'exp-a',numero_pravia:'EXP-0001-2026'},ingresosReportados:[{id:'income-a',estado:'PENDIENTE_APLICACION',concepto_contexto:'Anticipo inicial',monto_reportado:'1000.00',forma_pago:'TRANSFERENCIA',factura_estado:'PENDIENTE',facturarAVinculo:{id:'party-link',compareciente:{id:'party-a',nombre_busqueda:'Juan Pérez',tipo_persona:'FISICA'}},created_at:'2026-08-29T12:00:00Z',reportadoPor:{nombre:'Andrea'},documentos:[{id:'link-income',tipo:'COMPROBANTE_INGRESO',documento:{id:'doc-income',nombre_original:'transferencia.pdf',mime_type:'application/pdf'}}]}],solicitudesPago:[{id:'request-a',via:'DOCUMENTO_EXTERNO',estado:'PENDIENTE',concepto:'Derechos RPP',importe:'450.00',created_at:'2026-08-29T12:00:00Z',creadoPor:{nombre:'Andrea'},documentos:[{id:'link-request',tipo:'SOLICITUD_ORIGEN',documento:{id:'doc-request',nombre_original:'ficha-rpp.pdf',mime_type:'application/pdf'}}]}],presupuesto:{subtotal_honorarios:'1000.00',subtotal_impuestos_derechos:'500.00',total:'1500.00',version:1},catalogs:{accounts:[{id:'account-a',institucion:'Banco',alias:'Operativa',moneda:'MXN'}],categories:[{id:'category-a',clave:'DERECHOS',nombre:'Derechos',direccion:'EGRESO'}],parties:[{id:'party-link',compareciente_id:'party-a',compareciente:{nombre_busqueda:'Juan Pérez',tipo_persona:'FISICA'},caracter:{nombre:'Comprador'}}]},capabilities:{canRead:true,canReport:true,canCreateRequest:true,canApply:true,canCompleteInvoice:true,canUseAI:true,canReadDocuments:true,canRetireDocuments:true}});
const expediente={id:'exp-a',numero_pravia:'EXP-0001-2026',capabilities:{canReadFinance:true,canWriteFinance:true,canReadCaseFinance:true,canReportCaseFinance:true,canApplyCaseFinance:true,canWrite:true,canDeliver:false,canManagePostfirma:false,canReadProject:true,canUploadDocuments:true,canReadDocuments:true,canDeleteDocuments:true}} as unknown as ExpedienteDetail;

describe('EXP-008 · Finanzas del expediente UI',()=>{
  beforeEach(()=>{vi.clearAllMocks();api.read.mockResolvedValue(fixture());api.reportIncome.mockResolvedValue({});api.completeInvoice.mockResolvedValue({});api.createInternalRequest.mockResolvedValue({});api.createExternalRequest.mockResolvedValue({});api.applyIncome.mockResolvedValue({});api.payRequest.mockResolvedValue({});api.proposeAI.mockResolvedValue({item:{id:'proposal-a',estado:'PENDIENTE',propuesta:{monto:'1000.00',referencia:'ABC'},provenance:[{campo:'monto',documento_id:'doc-income',documento:'transferencia.pdf',pagina:1}],conflictos:[],faltantes:['fecha'],modelo:'document-model'},idempotent:false});api.validateAI.mockResolvedValue({});api.generateReceipt.mockResolvedValue({});});
  it('muestra resumen, ingresos y solicitudes con estados inequívocos',async()=>{render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);expect(await screen.findByText('Anticipo inicial')).toBeInTheDocument();expect(screen.getByText('Pendiente de aplicación')).toBeInTheDocument();expect(screen.getByText('Derechos RPP')).toBeInTheDocument();expect(screen.getByText('Pendiente')).toBeInTheDocument();});
  it('separa el documento origen del comprobante reportado',async()=>{render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);expect(await screen.findByText('transferencia.pdf')).toBeInTheDocument();expect(screen.getByText('ficha-rpp.pdf')).toBeInTheDocument();});
  it('abre captura de ingreso y advierte que no auto-aplica',async()=>{render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);await userEvent.click(await screen.findByRole('button',{name:/Reportar ingreso/}));expect(screen.getByRole('dialog')).toBeInTheDocument();expect(screen.getByText('Registrar evidencia no aplica ningún movimiento financiero.')).toBeInTheDocument();expect(screen.getByLabelText('¿A quién se va a facturar?')).toBeInTheDocument();expect(screen.getByLabelText('Forma de pago')).toBeInTheDocument();});
  it('acepta el conjunto documental universal en evidencias financieras no fiscales',async()=>{render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);await userEvent.click(await screen.findByRole('button',{name:/Reportar ingreso/}));expect(screen.getByLabelText('Comprobante del ingreso')).toHaveAttribute('accept','.pdf,.png,.jpg,.jpeg,.bmp,.webp,.doc,.docx,.xml,.zip');});
  it('transmite el comprobante real al reportar ingreso',async()=>{const user=userEvent.setup();render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);await user.click(await screen.findByRole('button',{name:/Reportar ingreso/}));await user.type(screen.getByLabelText('Concepto o contexto'),'Anticipo QA');await user.selectOptions(screen.getByLabelText('¿A quién se va a facturar?'),'party-link');await user.selectOptions(screen.getByLabelText('Forma de pago'),'TRANSFERENCIA');const receipt=new File(['evidencia'],'anticipo.pdf',{type:'application/pdf'});await user.upload(screen.getByLabelText('Comprobante del ingreso'),receipt);expect((screen.getByLabelText('Comprobante del ingreso') as HTMLInputElement).files?.length).toBe(1);fireEvent.submit(screen.getByRole('dialog').querySelector('form')!);await waitFor(()=>expect(api.reportIncome).toHaveBeenCalledWith('exp-a',expect.objectContaining({concepto_contexto:'Anticipo QA'}),{receipt,invoicePdf:undefined,invoiceXml:undefined}));});
  it('sugiere importe y concepto desde comprobante sin registrar ni aplicar el ingreso',async()=>{
    api.read.mockResolvedValueOnce({...fixture(),capabilities:{...fixture().capabilities,canPrefillAI:true}});
    api.previewIncomeAI.mockResolvedValueOnce({monto_reportado:'1234.50',concepto_contexto:'Anticipo documental',evidencia:[]});
    const user=userEvent.setup();render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);
    await user.click(await screen.findByRole('button',{name:/Reportar ingreso/}));
    const receipt=new File(['%PDF-1.4'],'anticipo.pdf',{type:'application/pdf'});
    await user.upload(screen.getByLabelText('Comprobante del ingreso'),receipt);
    await user.click(screen.getByRole('button',{name:'Llenar con IA'}));
    await waitFor(()=>expect(api.previewIncomeAI).toHaveBeenCalledWith('exp-a',receipt));
    expect(screen.getByLabelText('Monto reportado (opcional)')).toHaveValue(1234.5);
    expect(screen.getByLabelText('Concepto o contexto')).toHaveValue('Anticipo documental');
    expect(api.reportIncome).not.toHaveBeenCalled();expect(api.applyIncome).not.toHaveBeenCalled();
    await user.clear(screen.getByLabelText('Monto reportado (opcional)'));
    await user.type(screen.getByLabelText('Monto reportado (opcional)'),'1250');
    expect(screen.getByLabelText('Monto reportado (opcional)')).toHaveValue(1250);
  });
  it('un fallo de IA no bloquea la captura manual del ingreso',async()=>{
    api.read.mockResolvedValueOnce({...fixture(),capabilities:{...fixture().capabilities,canPrefillAI:true}});
    api.previewIncomeAI.mockRejectedValueOnce(new Error('No pudimos leer el comprobante con IA.'));
    const user=userEvent.setup();render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);
    await user.click(await screen.findByRole('button',{name:/Reportar ingreso/}));
    const receipt=new File(['%PDF-1.4'],'anticipo.pdf',{type:'application/pdf'});
    await user.upload(screen.getByLabelText('Comprobante del ingreso'),receipt);
    await user.click(screen.getByRole('button',{name:'Llenar con IA'}));
    expect(await screen.findByRole('alert')).toHaveTextContent('No pudimos leer el comprobante con IA.');
    await user.type(screen.getByLabelText('Concepto o contexto'),'Captura manual');
    await user.type(screen.getByLabelText('Monto reportado (opcional)'),'400');
    await user.selectOptions(screen.getByLabelText('¿A quién se va a facturar?'),'party-link');
    await user.selectOptions(screen.getByLabelText('Forma de pago'),'TRANSFERENCIA');
    await waitFor(()=>expect(screen.getByRole('button',{name:'Registrar ingreso'})).toBeEnabled());
    fireEvent.submit(screen.getByRole('dialog').querySelector('form')!);
    await waitFor(()=>expect(api.reportIncome).toHaveBeenCalledWith('exp-a',expect.objectContaining({monto_reportado:'400',concepto_contexto:'Captura manual'}),expect.objectContaining({receipt})));
  });
  it('no expone prellenado IA sin capability aun cuando el ingreso manual está permitido',async()=>{
    render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);
    await userEvent.click(await screen.findByRole('button',{name:/Reportar ingreso/}));
    expect(screen.queryByRole('button',{name:'Llenar con IA'})).not.toBeInTheDocument();
    expect(screen.getByRole('button',{name:'Registrar ingreso'})).toBeEnabled();
  });
  it('muestra estado pendiente y acción administrativa para completar factura',async()=>{render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);expect(await screen.findByText('Factura pendiente')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Agregar factura'}));expect(screen.getByLabelText('Factura PDF')).toBeInTheDocument();expect(screen.getByLabelText('Factura XML')).toBeInTheDocument();});
  it('transmite ambos archivos al completar una factura pendiente',async()=>{const user=userEvent.setup();render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);await user.click(await screen.findByRole('button',{name:'Agregar factura'}));const pdf=new File(['%PDF'],'factura.pdf',{type:'application/pdf'});const xml=new File(['<cfdi/>'],'factura.xml',{type:'application/xml'});await user.upload(screen.getByLabelText('Factura PDF'),pdf);await user.upload(screen.getByLabelText('Factura XML'),xml);await user.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Agregar factura'}));await waitFor(()=>expect(api.completeInvoice).toHaveBeenCalledWith('exp-a','income-a',expect.objectContaining({idempotency_key:expect.any(String)}),{invoicePdf:pdf,invoiceXml:xml}));});
  it('mantiene visible dentro del drawer un error operativo devuelto por el backend',async()=>{api.createInternalRequest.mockRejectedValueOnce(new Error('No se pudo guardar el documento en Storage.'));const user=userEvent.setup();render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);await user.click(await screen.findByRole('button',{name:/Solicitar pago/}));await user.type(screen.getByLabelText('Concepto'),'Solicitud con error');await user.type(screen.getByLabelText('Importe'),'2500');const dialog=screen.getByRole('dialog');await user.click(screen.getByRole('button',{name:'Crear solicitud'}));expect(await screen.findByRole('alert')).toHaveTextContent('No se pudo guardar el documento en Storage.');expect(dialog).toContainElement(screen.getByRole('alert'));expect(dialog).toBeInTheDocument();});
  it('gestiona foco, Escape y retorno al activador del drawer',async()=>{const user=userEvent.setup();render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);const trigger=await screen.findByRole('button',{name:/Reportar ingreso/});await user.click(trigger);expect(screen.getByRole('button',{name:'Cerrar'})).toHaveFocus();await user.keyboard('{Escape}');expect(screen.queryByRole('dialog')).not.toBeInTheDocument();expect(trigger).toHaveFocus();});
  it('crea solicitud interna cuando no se adjunta ficha externa',async()=>{render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);await userEvent.click(await screen.findByRole('button',{name:/Solicitar pago/}));await userEvent.type(screen.getByLabelText('Concepto'),'Pago municipal');await userEvent.type(screen.getByLabelText('Importe'),'300');await userEvent.click(screen.getByRole('button',{name:'Crear solicitud'}));await waitFor(()=>expect(api.createInternalRequest).toHaveBeenCalledWith('exp-a',expect.objectContaining({concepto:'Pago municipal',importe:'300'})));});
  it('transmite la ficha externa adjunta al crear una solicitud',async()=>{const user=userEvent.setup();render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);await user.click(await screen.findByRole('button',{name:/Solicitar pago/}));await user.type(screen.getByLabelText('Concepto'),'Derechos QA');await user.type(screen.getByLabelText('Importe'),'320');const file=new File(['ficha'],'ficha.pdf',{type:'application/pdf'});await user.upload(screen.getByLabelText(/Ficha externa/),file);await user.click(screen.getByRole('button',{name:'Crear solicitud'}));await waitFor(()=>expect(api.createExternalRequest).toHaveBeenCalledWith('exp-a',expect.objectContaining({concepto:'Derechos QA',importe:'320'}),file));expect(api.createInternalRequest).not.toHaveBeenCalled();});
  it('sólo expone aplicar cuando capability administrativa está presente',async()=>{api.read.mockResolvedValueOnce({...fixture(),capabilities:{...fixture().capabilities,canApply:false,canUseAI:false}});render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);await screen.findByText('Anticipo inicial');expect(screen.queryByRole('button',{name:'Aplicar'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Registrar pago'})).not.toBeInTheDocument();});
  it('muestra aplicación general Honorarios + Impuestos y derechos',async()=>{render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);await userEvent.click(await screen.findByRole('button',{name:'Aplicar'}));expect(screen.getByLabelText('Honorarios')).toBeInTheDocument();expect(screen.getByLabelText('Impuestos y derechos')).toBeInTheDocument();expect(screen.queryByText(/concepto por concepto/i)).not.toBeInTheDocument();});
  it('muestra comprobante de pago y ambos componentes fiscales como campos separados',async()=>{render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);await userEvent.click(await screen.findByRole('button',{name:'Registrar pago'}));expect(screen.getByLabelText('Comprobante de pago (opcional)')).toBeInTheDocument();expect(screen.getByRole('group',{name:'Factura / comprobante fiscal (opcional)'})).toBeInTheDocument();expect(screen.getByLabelText('XML fiscal')).toHaveAttribute('accept','application/xml,text/xml,.xml');expect(screen.getByLabelText('PDF fiscal')).toHaveAttribute('accept','application/pdf,.pdf');});
  it('envía XML y PDF fiscales juntos al pago sin sustituir el comprobante bancario',async()=>{const user=userEvent.setup();render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);await user.click(await screen.findByRole('button',{name:'Registrar pago'}));await user.selectOptions(screen.getByLabelText('Cuenta'),'account-a');await user.selectOptions(screen.getByLabelText('Categoría de egreso'),'category-a');await user.selectOptions(screen.getByLabelText('Forma de pago'),'TRANSFERENCIA');const proof=new File(['pago'],'pago.pdf',{type:'application/pdf'});const xml=new File(['<cfdi/>'],'factura.xml',{type:'application/xml'});const pdf=new File(['%PDF'],'factura.pdf',{type:'application/pdf'});await user.upload(screen.getByLabelText('Comprobante de pago (opcional)'),proof);await user.upload(screen.getByLabelText('XML fiscal'),xml);await user.upload(screen.getByLabelText('PDF fiscal'),pdf);await user.click(screen.getByRole('button',{name:'Confirmar pago'}));await waitFor(()=>expect(api.payRequest).toHaveBeenCalledWith('exp-a','request-a',expect.objectContaining({cuenta_id:'account-a',categoria_id:'category-a'}),proof,{pdf,xml}));});
  it('envía sólo el documento autorizado al análisis IA',async()=>{render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);const buttons=await screen.findAllByRole('button',{name:/Analizar/});await userEvent.click(buttons[0]);await waitFor(()=>expect(api.proposeAI).toHaveBeenCalledWith('exp-a',expect.objectContaining({documento_id:'doc-income',ingreso_reportado_id:'income-a'})));});
  it('exige revisión humana visible y no aplica silenciosamente la propuesta IA',async()=>{render(<FinanceTab expediente={expediente} onChanged={vi.fn()}/>);const buttons=await screen.findAllByRole('button',{name:/Analizar/});await userEvent.click(buttons[0]);expect(await screen.findByRole('heading',{name:'Revisar propuesta de IA'})).toBeInTheDocument();expect(screen.getByText('transferencia.pdf · página 1')).toBeInTheDocument();expect(api.applyIncome).not.toHaveBeenCalled();await userEvent.click(screen.getByRole('button',{name:'Validar datos revisados'}));await waitFor(()=>expect(api.validateAI).toHaveBeenCalledWith('exp-a','proposal-a',expect.objectContaining({decision:'ACCEPT',accepted_fields:expect.objectContaining({monto:'1000.00'})})));expect(api.applyIncome).not.toHaveBeenCalled();});
});
