import { fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { App } from '../app/App';
import { getAssistantActions, resolveAssistantContext } from '../features/assistant/assistantContext';

const response=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}});
const permissions=['finanzas.read','finanzas.write','finanzas.validate','expedientes.read','documentos.read','documentos.write','documentos.unlink'];
const session={user:{id:'user-1',name:'Andrea Ruiz',role:'ADMINISTRACION',permissions}};
const account={id:'account-1',institucion:'BBVA',alias:'Operativa principal',tipo:'CUENTA_BANCARIA',ultimos_cuatro:'1234',moneda:'MXN',activa:true,predeterminada:true,saldo_pravia:418500,_count:{movimientos:8,transaccionesBanco:4}};
const categories=[{id:'cat-fees',clave:'HONORARIOS',nombre:'Honorarios',naturaleza:'DESPACHO',direccion:'INGRESO'},{id:'cat-rights',clave:'DERECHOS',nombre:'Derechos',naturaleza:'TERCERO',direccion:'AMBAS'},{id:'cat-expense',clave:'GASTOS_DESPACHO',nombre:'Gastos del despacho',naturaleza:'EGRESO_DESPACHO',direccion:'EGRESO'}];
const catalogs={categories,accounts:[account],expedientes:[{id:'exp-1',numero_pravia:'EXP-2026-0141',cliente_alias:'Inmobiliaria del Valle',notaria_id:'notaria-1',abogado_id:'user-1',cotizacion_id:'quote-1'}],notarias:[{id:'notaria-1',nombre:'Notaría 12',numero_notaria:'12'}],responsables:[{id:'user-1',nombre:'Andrea',apellido:'Ruiz',rol:'ADMINISTRACION'}],permisos:{escribir:true,aplicar:true,conciliar:true,expedientesLeer:true,documentosLeer:true,documentosEscribir:true,documentosEliminar:true},invoiceIntegration:{configured:false,status:'PENDIENTE_CONFIGURACION',message:'Integración de facturación pendiente de configuración.'},bankImport:{configured:false,message:'Formato de importación bancaria pendiente de confirmar con el cliente.'}};
const summary={period:{from:'2026-08-01',to:'2026-08-31',key:'ESTE_MES',label:'1 ago 2026 – 31 ago 2026'},kpis:{ingresos_recibidos:830000,honorarios_generados:390000,honorarios_cobrados:312000,honorarios_por_cobrar:78000,fondos_terceros:498000,otros_destinos:20000,fondos_terceros_pendientes:126000,egresos:392000},cashFlow:[{periodo:'2026-06',ingresos:520000,honorarios:190000,egresos:250000},{periodo:'2026-07',ingresos:680000,honorarios:240000,egresos:310000},{periodo:'2026-08',ingresos:830000,honorarios:312000,egresos:392000}],allocation:{despacho:312000,terceros:498000,otros:20000}};
const evidence={id:'link-1',tipo_vinculo:'COMPROBANTE_PAGO',fecha_vinculo:'2026-08-12T12:01:00.000Z',documento:{id:'doc-1',nombre_original:'comprobante.pdf',mime_type:'application/pdf',size_bytes:2048,fecha_carga:'2026-08-12T12:01:00.000Z',estatus:'VIGENTE'}};
const movement:any={id:'mov-1',folio:'MOV-2026-000141',naturaleza:'INGRESO',tipo_movimiento:'ANTICIPO',concepto:'Anticipo de cliente',monto:100000,fecha_movimiento:'2026-08-12T12:00:00.000Z',estatus:'APLICADO',forma_pago:'TRANSFERENCIA',referencia:'SPEI-8841',expediente:{id:'exp-1',numero_pravia:'EXP-2026-0141',cliente_alias:'Inmobiliaria del Valle'},cuenta:account,distribuciones:[{id:'alloc-1',categoria_id:'cat-fees',monto:30000,categoria:categories[0]},{id:'alloc-2',categoria_id:'cat-rights',monto:70000,categoria:categories[1]}],comprobanteInterno:{id:'receipt-1',folio:'COM-2026-000141',estado:'VIGENTE'},movimientoDocumentos:[evidence]};
const receipt={id:'receipt-1',folio:'COM-2026-000141',tipo:'INGRESO',fecha:'2026-08-12T12:00:00.000Z',importe:100000,concepto:'Anticipo de cliente',persona:'Inmobiliaria del Valle',estado:'VIGENTE',movimiento:movement};
const receivable={id:'fee-1',cliente:'Inmobiliaria del Valle',expediente:{id:'exp-1',numero_pravia:'EXP-2026-0141'},cotizacion:{numero_cotizacion:'COT-2026-0041'},responsable:'Andrea Ruiz',notaria:'Notaría 12',fecha_reconocimiento:'2026-08-01',fecha_vencimiento:null,generated:100000,collected:30000,pending:70000,bucket:null,ultimo_pago:null};
const reconciliation={summary:{conciliados:2,pendientes:1,sinCoincidencia:0},rows:[{transaction:{id:'bank-1',fecha:'2026-08-12',importe:100000,descripcion:'SPEI CLIENTE',referencia:'SPEI-8841',estado:'PENDIENTE',cuenta:account},current:null,suggestion:{score:100,algorithm:'PRAVIA_RECONCILIATION_V1',reasons:['Importe exacto','Misma cuenta','Misma fecha','Referencia coincidente'],movement}}],unmatchedMovements:[]};

function mockApi(options:{grants?:string[];fail?:boolean;empty?:boolean;withoutEvidence?:boolean}={}){vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{const url=String(input);const grants=options.grants??permissions;const listedMovement=options.withoutEvidence?{...movement,movimientoDocumentos:[]}:movement;if(url==='https://signed.example/comprobante.pdf')return new Response('pdf',{status:200,headers:{'Content-Type':'application/pdf'}});if(url.endsWith('/auth/me'))return response({user:{...session.user,permissions:grants}});if(url.endsWith('/finanzas/catalogos'))return response({success:true,data:{...catalogs,permisos:{escribir:grants.includes('finanzas.write'),aplicar:grants.includes('finanzas.validate'),conciliar:grants.includes('finanzas.validate'),expedientesLeer:grants.includes('expedientes.read'),documentosLeer:grants.includes('documentos.read'),documentosEscribir:grants.includes('documentos.write'),documentosEliminar:grants.includes('documentos.unlink')}}});if(url.includes('/finanzas/resumen'))return options.fail?response({error:'No disponible'},500):response({success:true,data:summary});if(url.includes('/finanzas/movimientos?'))return response({success:true,data:{items:options.empty?[]:[listedMovement],meta:{page:1,pageSize:20,total:options.empty?0:1,totalPages:1}}});if(url.endsWith('/documentos/doc-1/url'))return response({url:'https://signed.example/comprobante.pdf'});if(url.endsWith('/documentos')&&init?.method==='POST')return response({id:'doc-new',nombre_original:'nuevo.pdf',mime_type:'application/pdf',size_bytes:4},201);if(url.includes('/finanzas/movimientos/mov-1/comprobantes/doc-1')&&init?.method==='DELETE')return response({success:true,data:{retired:true}});if(url.endsWith('/finanzas/cuentas'))return response({success:true,data:[account]});if(url.includes('/finanzas/cartera'))return response({success:true,data:{items:[receivable],meta:{page:1,pageSize:20,total:1,totalPages:1,agingAvailable:false}}});if(url.includes('/finanzas/conciliacion?'))return response({success:true,data:reconciliation});if(url.endsWith('/finanzas/movimientos')&&init?.method==='POST')return response({success:true,data:{movement:{...movement,id:'mov-created',folio:'MOV-2026-000142',estatus:'PENDIENTE_COMPROBANTE',movimientoDocumentos:[]}}},201);if(url.endsWith('/finanzas/movimientos/mov-created/comprobante')&&init?.method==='POST')return response({success:true,data:{receipt:{...receipt,folio:'COM-2026-000142'}}},201);if(url.endsWith('/finanzas/movimientos/mov-created/aplicar')&&init?.method==='POST')return response({success:true,data:{movement:{...movement,id:'mov-created'},idempotent:false}});if(url.endsWith('/finanzas/conciliacion')&&init?.method==='POST')return response({success:true,data:{id:'recon-1'}});if(url.endsWith('/finanzas/cuentas')&&init?.method==='POST')return response({success:true,data:{...account,id:'account-2'}},201);return response({success:true,data:{}});}));}
const renderFinance=(path='/finanzas')=>render(<MemoryRouter initialEntries={[path]}><App/></MemoryRouter>);

describe('Finanzas',()=>{beforeEach(()=>vi.restoreAllMocks());
  it('muestra métricas económicamente separadas y mantiene Resumen en modo lectura',async()=>{mockApi();renderFinance();expect(await screen.findByRole('heading',{name:'Finanzas'})).toBeInTheDocument();expect(await screen.findByText('Ingresos recibidos')).toBeInTheDocument();expect(screen.getByText('Honorarios cobrados')).toBeInTheDocument();expect(screen.getByText('Recursos no propios')).toBeInTheDocument();expect(screen.getByText('$20,000.00 pendientes de clasificar')).toBeInTheDocument();expect(screen.getByText('Por cobrar')).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Registrar movimiento'})).not.toBeInTheDocument();expect(screen.getByRole('img',{name:/Gráfica mensual/})).toBeInTheDocument();expect(screen.getByText('Distribución de ingresos')).toBeInTheDocument();});
  it('mantiene el periodo común al navegar entre vistas financieras',async()=>{mockApi();const user=userEvent.setup();renderFinance();await screen.findByText('Ingresos recibidos');await user.selectOptions(screen.getByLabelText('Periodo financiero'),'TRIMESTRE');await waitFor(()=>expect(vi.mocked(fetch).mock.calls.some(([url])=>String(url).includes('periodo=TRIMESTRE'))).toBe(true));await user.click(screen.getByRole('button',{name:'Movimientos'}));await screen.findByRole('table');expect(screen.getByLabelText('Periodo financiero')).toHaveValue('TRIMESTRE');expect(vi.mocked(fetch).mock.calls.some(([url])=>String(url).includes('/finanzas/movimientos?')&&String(url).includes('periodo=TRIMESTRE'))).toBe(true);});
  it('lista movimientos, usa filtros reales y abre el comprobante desde el movimiento',async()=>{mockApi();const user=userEvent.setup();renderFinance('/finanzas?view=movimientos');expect(await screen.findByRole('table')).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Más filtros'})).not.toBeInTheDocument();await user.type(screen.getByLabelText('Buscar movimientos'),'0141');await waitFor(()=>expect(vi.mocked(fetch).mock.calls.some(([url])=>String(url).includes('search=0141'))).toBe(true));await user.click(screen.getByRole('button',{name:'MOV-2026-000141'}));expect(await screen.findByRole('dialog',{name:'Anticipo de cliente'})).toBeInTheDocument();expect(screen.getByText('Distribución económica')).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Visualizar comprobante.pdf'}));expect(await screen.findByRole('dialog',{name:'comprobante.pdf'})).toBeInTheDocument();});
  it('registra un movimiento distribuido una sola vez y permite comprobante opcional',async()=>{mockApi();const user=userEvent.setup();renderFinance('/finanzas?view=movimientos');await screen.findByRole('table');await user.click(screen.getByRole('button',{name:'Registrar movimiento'}));const dialog=screen.getByRole('dialog',{name:'Registrar movimiento'});await user.click(within(dialog).getByRole('button',{name:/Continuar/}));await user.type(within(dialog).getByLabelText('Importe total (MXN)'),'100000');await user.type(within(dialog).getByLabelText('Concepto'),'Anticipo de cliente');await user.click(within(dialog).getByRole('button',{name:/Continuar/}));await user.selectOptions(within(dialog).getByLabelText('Clasificación 1'),'cat-fees');await user.type(within(dialog).getByLabelText('Importe de clasificación 1'),'100000');await user.click(within(dialog).getByRole('button',{name:/Continuar/}));expect(within(dialog).getByText('Folio interno automático')).toBeInTheDocument();await user.click(within(dialog).getByRole('button',{name:/Continuar/}));await user.click(within(dialog).getByRole('button',{name:'Registrar movimiento'}));expect(await within(dialog).findByText('COM-2026-000142')).toBeInTheDocument();expect(vi.mocked(fetch).mock.calls.filter(([url,init])=>String(url).endsWith('/finanzas/movimientos')&&init?.method==='POST')).toHaveLength(1);const apply=within(dialog).getByRole('button',{name:'Aplicar movimiento'});expect(apply).toBeDisabled();await user.click(within(dialog).getByRole('checkbox',{name:/Revisé el importe/}));await user.click(apply);expect(await within(dialog).findByText('Movimiento aplicado correctamente.')).toBeInTheDocument();});
  it('guarda una distribución parcial como borrador sin generar comprobante interno',async()=>{mockApi();const user=userEvent.setup();renderFinance('/finanzas?view=movimientos');await screen.findByRole('table');await user.click(screen.getByRole('button',{name:'Registrar movimiento'}));const dialog=screen.getByRole('dialog',{name:'Registrar movimiento'});await user.click(within(dialog).getByRole('button',{name:/Continuar/}));await user.type(within(dialog).getByLabelText('Importe total (MXN)'),'85000');await user.type(within(dialog).getByLabelText('Concepto'),'Distribución parcial');await user.click(within(dialog).getByRole('button',{name:/Continuar/}));await user.selectOptions(within(dialog).getByLabelText('Clasificación 1'),'cat-fees');await user.type(within(dialog).getByLabelText('Importe de clasificación 1'),'30000');await user.click(within(dialog).getByRole('button',{name:'Agregar clasificación'}));await user.selectOptions(within(dialog).getByLabelText('Clasificación 2'),'cat-rights');await user.type(within(dialog).getByLabelText('Importe de clasificación 2'),'40000');expect(within(dialog).getByText(/Quedan \$15,000.00 sin clasificar/)).toBeInTheDocument();await user.click(within(dialog).getByRole('button',{name:/Continuar/}));await user.click(within(dialog).getByRole('button',{name:/Continuar/}));await user.click(within(dialog).getByRole('button',{name:'Registrar movimiento'}));expect(await within(dialog).findByText('Borrador guardado')).toBeInTheDocument();expect(within(dialog).getByText(/no puede generar folio interno ni aplicarse/)).toBeInTheDocument();expect(vi.mocked(fetch).mock.calls.some(([url,init])=>String(url).endsWith('/finanzas/movimientos/mov-created/comprobante')&&init?.method==='POST')).toBe(false);});
  it('bloquea una distribución superior al importe antes de enviarla',async()=>{mockApi();const user=userEvent.setup();renderFinance('/finanzas?view=movimientos');await screen.findByRole('table');await user.click(screen.getByRole('button',{name:'Registrar movimiento'}));const dialog=screen.getByRole('dialog',{name:'Registrar movimiento'});await user.click(within(dialog).getByRole('button',{name:/Continuar/}));await user.type(within(dialog).getByLabelText('Importe total (MXN)'),'85000');await user.type(within(dialog).getByLabelText('Concepto'),'Distribución inválida');await user.click(within(dialog).getByRole('button',{name:/Continuar/}));await user.selectOptions(within(dialog).getByLabelText('Clasificación 1'),'cat-fees');await user.type(within(dialog).getByLabelText('Importe de clasificación 1'),'30000');await user.click(within(dialog).getByRole('button',{name:'Agregar clasificación'}));await user.selectOptions(within(dialog).getByLabelText('Clasificación 2'),'cat-rights');await user.type(within(dialog).getByLabelText('Importe de clasificación 2'),'70000');expect(within(dialog).getByText(/excede el movimiento por \$15,000.00/)).toBeInTheDocument();expect(within(dialog).getByRole('button',{name:/Continuar/})).toBeDisabled();expect(vi.mocked(fetch).mock.calls.some(([url,init])=>String(url).endsWith('/finanzas/movimientos')&&init?.method==='POST')).toBe(false);});
  it('elimina la pestaña separada de comprobantes y no ofrece CFDI falso',async()=>{mockApi();const first=renderFinance();await screen.findByText('Ingresos recibidos');expect(screen.queryByRole('button',{name:'Comprobantes'})).not.toBeInTheDocument();first.unmount();mockApi();renderFinance('/finanzas?view=facturacion');expect(await screen.findByText('Integración pendiente de configuración')).toBeInTheDocument();expect(screen.getByText('No se simulará el timbrado.')).toBeInTheDocument();expect(screen.queryByRole('button',{name:/Timbrar/})).not.toBeInTheDocument();});
  it('presenta cuentas con saldo calculado claramente diferenciado',async()=>{mockApi();renderFinance('/finanzas?view=cuentas');expect(await screen.findByText('Operativa principal')).toBeInTheDocument();expect(screen.getByText('Saldo calculado en PRAVIA')).toBeInTheDocument();expect(screen.getByText('No es saldo bancario oficial')).toBeInTheDocument();});
  it('explica el algoritmo determinista y requiere decisión humana para conciliar',async()=>{mockApi();const user=userEvent.setup();renderFinance('/finanzas?view=conciliacion');expect(await screen.findByText('Coincidencia exacta')).toBeInTheDocument();expect(screen.getByText('100% de similitud')).toBeInTheDocument();expect(screen.getByText(/Importe exacto · Misma cuenta · Misma fecha · Referencia coincidente/)).toBeInTheDocument();expect(screen.getByText(/nunca se concilian automáticamente/i)).toBeInTheDocument();await user.click(screen.getByRole('button',{name:/Conciliar/}));await waitFor(()=>expect(vi.mocked(fetch).mock.calls.some(([url,init])=>String(url).endsWith('/finanzas/conciliacion')&&init?.method==='POST')).toBe(true));});
  it('deriva cartera de honorarios y no inventa antigüedad',async()=>{mockApi();renderFinance('/finanzas?view=cartera');expect(await screen.findByText('Cartera')).toBeInTheDocument();expect(screen.getByText(/Antigüedad no disponible/)).toBeInTheDocument();expect(screen.getByText('Sin fecha contractual')).toBeInTheDocument();});
  it('respeta permisos financieros y oculta el módulo sin lectura',async()=>{mockApi({grants:['expedientes.read']});renderFinance();expect(await screen.findByText('Acceso financiero restringido')).toBeInTheDocument();expect(screen.queryByRole('link',{name:'Finanzas'})).not.toBeInTheDocument();});
  it('muestra comprobante ausente, permite adjuntar y respeta permiso de retiro',async()=>{mockApi({withoutEvidence:true});const user=userEvent.setup();const view=renderFinance('/finanzas?view=movimientos');await screen.findByRole('table');await user.click(screen.getByRole('button',{name:'MOV-2026-000141'}));const dialog=await screen.findByRole('dialog',{name:'Anticipo de cliente'});expect(within(dialog).getByText('Sin comprobante')).toBeInTheDocument();const input=view.container.querySelector('input[type="file"]') as HTMLInputElement;fireEvent.change(input,{target:{files:[new File(['pdf'],'nuevo.pdf',{type:'application/pdf'})]}});await waitFor(()=>expect(vi.mocked(fetch).mock.calls.some(([url,init])=>String(url).endsWith('/documentos')&&init?.method==='POST')).toBe(true));expect(await within(dialog).findByText('nuevo.pdf')).toBeInTheDocument();});
  it('no permite retirar comprobantes sin documentos.unlink',async()=>{mockApi({grants:permissions.filter(item=>item!=='documentos.unlink')});const user=userEvent.setup();renderFinance('/finanzas?view=movimientos');await screen.findByRole('table');await user.click(screen.getByRole('button',{name:'MOV-2026-000141'}));expect(await screen.findByRole('dialog',{name:'Anticipo de cliente'})).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Retirar comprobante.pdf'})).not.toBeInTheDocument();});
  it('descarga y retira el comprobante con confirmación sin eliminar el movimiento',async()=>{mockApi();vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});const user=userEvent.setup();renderFinance('/finanzas?view=movimientos');await screen.findByRole('table');await user.click(screen.getByRole('button',{name:'MOV-2026-000141'}));await user.click(await screen.findByRole('button',{name:'Descargar comprobante.pdf'}));await waitFor(()=>expect(vi.mocked(fetch).mock.calls.some(([url])=>String(url)==='https://signed.example/comprobante.pdf')).toBe(true));await user.click(screen.getByRole('button',{name:'Retirar comprobante.pdf'}));const confirm=await screen.findByRole('alertdialog',{name:'Retirar comprobante'});await user.click(within(confirm).getByRole('button',{name:'Retirar comprobante'}));await waitFor(()=>expect(vi.mocked(fetch).mock.calls.some(([url,init])=>String(url).includes('/finanzas/movimientos/mov-1/comprobantes/doc-1')&&init?.method==='DELETE')).toBe(true));expect(screen.getByRole('dialog',{name:'Anticipo de cliente'})).toBeInTheDocument();});
  it('muestra empty y error humanos',async()=>{mockApi({empty:true});const first=renderFinance('/finanzas?view=movimientos');expect(await screen.findByText('No hay movimientos registrados en este periodo.')).toBeInTheDocument();first.unmount();mockApi({fail:true});renderFinance();expect(await screen.findByText('No pudimos cargar Finanzas.')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Reintentar'})).toBeInTheDocument();});
  it('expone las cinco preguntas financieras de IA sin inventar importes',()=>{const context=resolveAssistantContext({pathname:'/finanzas',hash:''});expect(context.module).toBe('finanzas');expect(getAssistantActions(context).map(item=>item.label)).toEqual(['Cobrado este mes','Del despacho','Por cobrar','Sin comprobante','Conciliación pendiente']);});
});
