import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { App } from '../app/App';
import { getAssistantActions, resolveAssistantContext } from '../features/assistant/assistantContext';

const response = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } });
const session = { user: { id: 'user-1', name: 'Andrea Ruiz', role: 'ADMINISTRACION', permissions: ['notarias.read', 'notarias.write', 'expedientes.read'] } };
const row = { id: 'notaria-1', numero_notaria: '12', nombre: 'Notaría Pública 12', etiqueta: 'Notaría 12', titular: 'Lic. Ana Pérez', ciudad: 'Tepic', municipio: 'Tepic', entidad_federativa: 'Nayarit', demarcacion: 'Tepic', contacto: { nombre: 'Recepción', telefono: '311 555 0000', correo: 'recepcion@notaria.mx' }, expedientes_activos: 4, estatus: 'ACTIVA', predeterminada: false, updated_at: '2026-08-12T18:00:00.000Z' };
const list = { data: [row], metrics: { total: 3, active: 2, inactive: 1, withActiveCases: 2 }, distribution: { criterion: 'ENTIDAD_FEDERATIVA', total: 3, items: [{ label: 'Nayarit', value: 2, percentage: 66.7 }, { label: 'Jalisco', value: 1, percentage: 33.3 }] }, facets: { states: ['Jalisco', 'Nayarit'], cities: ['Tepic'] }, meta: { total: 1, page: 1, limit: 20, pageSize: 20, totalPages: 1, hasPreviousPage: false, hasNextPage: false }, definitions: { activeCases: 'No incluye entregados' } };
const detail: any = { ...row, direccion: 'Av. México 100, Centro', codigo_postal: '63000', telefono: '311 555 0000', whatsapp: null, correo_general: 'contacto@notaria.mx', correo_proyectos: null, pagina_web: null, contacto_principal: 'Recepción', horario: '09:00 a 17:00', dias_atencion: 'Lunes a viernes', tiempo_respuesta: '2 días', tiempo_presupuesto: null, tiempo_firma: null, instrucciones_especiales: null, observaciones_generales: 'Confirmar recepción de proyectos.', requisitos_frecuentes: null, dias_respuesta_estimados: 5, activa: true, color_identificador: '#D4AF37', tipos_acto_json: ['Compraventa'], instituciones_json: [], municipios_atendidos_json: ['Tepic'], created_at: '2026-06-01T10:00:00.000Z', contactos: [{ id: 'contact-1', nombre: 'Recepción', cargo: 'Recepción', telefono: '311 555 0000', whatsapp: null, correo: 'recepcion@notaria.mx', observaciones: null, activo: true, created_at: '2026-06-01T10:00:00.000Z' }], metrics: { activeCases: 4, historicalCases: 9, quotes: 3, upcomingSignatures: 1, lastActivity: '2026-08-12T18:00:00.000Z' }, expedientes: [], proximasFirmas: [{ id: 'exp-1', numero_pravia: 'EXP-2026-0041', fecha_estimada_firma: '2026-08-20T17:00:00.000Z', cliente_alias: 'Inmobiliaria del Valle' }], responsables: [{ id: 'user-1', nombre: 'Andrea', apellido: 'Ruiz', rol: 'ABOGADO', expedientes: 4 }], actividad: [{ id: 'audit-1', accion: 'EDITAR_NOTARIA', created_at: '2026-08-12T18:00:00.000Z', usuario: { nombre: 'Andrea', apellido: 'Ruiz' } }], definitions: {} };
const caseRow = { id: 'exp-1', numero_pravia: 'EXP-2026-0041', cliente_alias: 'Inmobiliaria del Valle', estatus: 'EN_PROCESO', etapa_actual_nombre: 'Proyecto', updated_at: '2026-08-12T18:00:00.000Z', tipo_acto: { nombre: 'Compraventa' }, abogado: { id: 'user-1', nombre: 'Andrea', apellido: 'Ruiz' }, gestor: null };

const mockApi = (options: { empty?: boolean; fail?: boolean; grants?: string[]; duplicate?: boolean } = {}) => vi.stubGlobal('fetch', vi.fn(async (input: RequestInfo | URL, init?: RequestInit) => { const url = String(input);
  if (url.endsWith('/auth/me')) return response(options.grants ? { user: { ...session.user, permissions: options.grants } } : session);
  if (url.includes('/notarias?portfolio=true')) return options.fail ? response({ error: 'No disponible' }, 500) : response(options.empty ? { ...list, data: [], metrics: { total: 0, active: 0, inactive: 0, withActiveCases: 0 }, distribution: { ...list.distribution, total: 0, items: [] }, meta: { ...list.meta, total: 0 } } : list);
  if (url.endsWith('/notarias/notaria-1/expedientes?page=1&pageSize=10&sort=updated_at%3Adesc')) return response({ data: [caseRow], meta: { total: 1, page: 1, totalPages: 1, hasPreviousPage: false, hasNextPage: false } });
  if (url.endsWith('/notarias/notaria-1')) return response(detail);
  if (url.endsWith('/notarias') && init?.method === 'POST') return options.duplicate ? response({ error: 'Ya existe la Notaría No. 12 en Nayarit' }, 400) : response({ ...detail, id: 'created-notaria' }, 201);
  if (url.endsWith('/notarias/notaria-1/contactos') && init?.method === 'POST') return response({ id: 'contact-2' }, 201);
  return response({}, 204);
}));

async function reachReview(user: ReturnType<typeof userEvent.setup>) { await user.click(screen.getByRole('button', { name: 'Nueva notaría' })); await user.type(screen.getByLabelText('Denominación *'), 'Notaría Pública 18'); await user.type(screen.getByLabelText('Entidad federativa *'), 'Nayarit'); await user.click(screen.getByRole('button', { name: 'Siguiente' })); await user.type(screen.getByLabelText('Municipio *'), 'Tepic'); await user.click(screen.getByRole('button', { name: 'Siguiente' })); await user.click(screen.getByRole('button', { name: 'Siguiente' })); }

describe('Notarías', () => {
  beforeEach(() => vi.restoreAllMocks());
  it('renderiza KPIs reales, distribución por estado, tabla y cards móviles', async () => { mockApi(); render(<MemoryRouter initialEntries={['/notarias']}><App /></MemoryRouter>); expect(await screen.findByRole('heading', { name: 'Notarías' })).toBeInTheDocument(); expect(await screen.findByRole('table')).toBeInTheDocument(); expect(screen.getByText('Distribución por estado')).toBeInTheDocument(); expect(screen.getAllByText('Notaría 12').length).toBeGreaterThan(1); expect(screen.getAllByText(/4 expedientes activos/).length).toBeGreaterThan(0); });
  it('envía búsqueda, filtros, sort y paginación al servidor', async () => { mockApi(); const user = userEvent.setup(); render(<MemoryRouter initialEntries={['/notarias']}><App /></MemoryRouter>); await screen.findByRole('table'); await user.type(screen.getByPlaceholderText(/número, titular/), 'Ana'); await waitFor(() => expect(fetch).toHaveBeenCalledWith(expect.stringContaining('search=Ana'), expect.anything())); await user.selectOptions(screen.getByLabelText('Estado geográfico'), 'Nayarit'); await waitFor(() => expect(fetch).toHaveBeenCalledWith(expect.stringContaining('estado=Nayarit'), expect.anything())); await user.selectOptions(screen.getByLabelText('Ordenar notarías'), 'titular:asc'); await waitFor(() => expect(fetch).toHaveBeenCalledWith(expect.stringContaining('sort=titular%3Aasc'), expect.anything())); });
  it('respeta permisos de solo lectura', async () => { mockApi({ grants: ['notarias.read'] }); render(<MemoryRouter initialEntries={['/notarias']}><App /></MemoryRouter>); await screen.findByRole('table'); expect(screen.queryByRole('button', { name: 'Nueva notaría' })).not.toBeInTheDocument(); });
  it('crea notaría con flujo progresivo y deja la duplicidad al backend real', async () => { mockApi(); const user = userEvent.setup(); render(<MemoryRouter initialEntries={['/notarias']}><App /></MemoryRouter>); await screen.findByRole('table'); await reachReview(user); await user.click(screen.getByRole('button', { name: 'Guardar notaría' })); await waitFor(() => expect(vi.mocked(fetch).mock.calls.some(([url, init]) => String(url).endsWith('/notarias') && init?.method === 'POST')).toBe(true)); });
  it('muestra el conflicto de duplicidad sin exponer detalles técnicos', async () => { mockApi({ duplicate: true }); const user = userEvent.setup(); render(<MemoryRouter initialEntries={['/notarias']}><App /></MemoryRouter>); await screen.findByRole('table'); await reachReview(user); await user.click(screen.getByRole('button', { name: 'Guardar notaría' })); expect(await screen.findByText(/Ya existe la Notaría/)).toBeInTheDocument(); });
  it('abre detalle con tabs accesibles, contactos, expedientes, actividad y configuración reales', async () => { mockApi(); const user = userEvent.setup(); render(<MemoryRouter initialEntries={['/notarias/notaria-1']}><App /></MemoryRouter>); expect(await screen.findByRole('heading', { name: 'Notaría 12' })).toBeInTheDocument(); const summaryTab = screen.getByRole('tab', { name: 'Resumen' }); expect(summaryTab).toHaveAttribute('tabindex', '0'); summaryTab.focus(); await user.keyboard('{ArrowRight}'); expect(await screen.findByRole('tab', { name: 'Contactos', selected: true })).toBeInTheDocument(); expect((await screen.findAllByText('Recepción')).length).toBeGreaterThan(0); await user.click(screen.getByRole('tab', { name: 'Expedientes' })); expect(await screen.findByText('EXP-2026-0041')).toBeInTheDocument(); await user.click(screen.getByRole('tab', { name: 'Actividad' })); expect(await screen.findByText('Información actualizada')).toBeInTheDocument(); await user.click(screen.getByRole('tab', { name: 'Configuración' })); expect(await screen.findByText('2 días')).toBeInTheDocument(); });
  it('agrega contacto mediante endpoint autenticado', async () => { mockApi(); const user = userEvent.setup(); render(<MemoryRouter initialEntries={['/notarias/notaria-1']}><App /></MemoryRouter>); await screen.findByRole('heading', { name: 'Notaría 12' }); await user.click(screen.getByRole('button', { name: /Agregar contacto/ })); await user.type(screen.getByLabelText('Nombre *'), 'Proyectos'); await user.type(screen.getByLabelText('Cargo o rol *'), 'Proyectista'); const dialog = screen.getByRole('dialog', { name: 'Agregar contacto' }); await user.click(dialog.querySelector('footer button:last-child') as HTMLButtonElement); await waitFor(() => expect(vi.mocked(fetch).mock.calls.some(([url, init]) => String(url).endsWith('/contactos') && init?.method === 'POST')).toBe(true)); });
  it('muestra empty y error humanos', async () => { mockApi({ empty: true }); const first = render(<MemoryRouter initialEntries={['/notarias']}><App /></MemoryRouter>); expect(await screen.findByText('No hay notarías registradas.')).toBeInTheDocument(); first.unmount(); mockApi({ fail: true }); render(<MemoryRouter initialEntries={['/notarias']}><App /></MemoryRouter>); expect(await screen.findByText('No pudimos cargar las notarías.')).toBeInTheDocument(); });
  it('expone contexto IA distinto para lista y entidad real', () => { const listContext = resolveAssistantContext({ pathname: '/notarias', hash: '' }); const detailContext = resolveAssistantContext({ pathname: '/notarias/notaria-1', hash: '#contactos' }); expect(getAssistantActions(listContext).map((action) => action.label)).toContain('Buscar notaría'); expect(detailContext).toMatchObject({ module: 'notarias', entityType: 'notaria', entityId: 'notaria-1', subview: 'contactos' }); expect(getAssistantActions(detailContext).map((action) => action.label)).toContain('Próximas firmas'); });
});
