import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { App } from '../app/App';
import { getAssistantActions, resolveAssistantContext } from '../features/assistant/assistantContext';

const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});
const grants=['reportes.read','reportes.global.read','reportes.financial.read','reportes.targets.manage','expedientes.read','ai.use','ai.reportes.read'];
const period={key:'ESTE_MES',label:'1 ago – 31 ago 2026',from:'2026-08-01',to:'2026-08-31'};
const scope={mode:'GLOBAL',financial:true};
const financial={honorarios_generados:850000,honorarios_cobrados:620000,honorarios_por_cobrar:230000,ingresos_recibidos:1300000,fondos_terceros:650000,otros_destinos:30000,fondos_terceros_pendientes:410000,egresos:220000};
const summary={period,scope,financial,goal:{meta:1000000,actual:620000,pendiente:380000,cumplimiento:62,base:'COBRADOS'},operations:{firmas_realizadas:18,firmas_restantes_semana:5,honorarios_programados_semana:280000,presupuestos_solicitados:34,importe_cotizado:1220000,presupuestos_aceptados:22,clientes_generados:17},alerts:{firmas_defectuosas:{available:false,label:'Pendiente de definir con operación'}},definitions:{programado:'Honorarios programados hasta el domingo.',clientes:'Cotizaciones aceptadas.'}};
const finance={period,scope,financial,tendency:[{periodo:'2026-03',generados:500000,cobrados:400000},{periodo:'2026-04',generados:650000,cobrados:530000},{periodo:'2026-05',generados:720000,cobrados:580000},{periodo:'2026-06',generados:800000,cobrados:600000},{periodo:'2026-07',generados:780000,cobrados:610000},{periodo:'2026-08',generados:850000,cobrados:620000}]};
const group={id:'u1',nombre:'Andrea Ruiz',generated:400000,collected:300000,pending:100000,expedientes:4,porcentaje_cobrado:75};
const collectionRow={id:'fee1',expediente_id:'exp1',expediente:'EXP-2026-0141',cliente:'Inmobiliaria del Valle',abogado:'Andrea Ruiz',notaria:'Notaría 12',generated:100000,collected:40000,pending:60000,due:'2026-08-20',link:'/expedientes/exp1'};
const collections={period,scope,totals:{generated:850000,collected:620000,pending:230000,overdue:60000},byLawyer:[group],byNotaria:[{...group,id:'n1',nombre:'Notaría 12'}],rows:[collectionRow]};
const lawyers={period,scope,year:2026,rows:[{id:'u1',nombre:'Andrea Ruiz',expedientes_ano:31,honorarios_generados:1600000,firmas_proximo_mes:4,honorarios_proximo_mes:310000}]};
const signatures={period,scope,metrics:{realizadas_mes:18,realizadas_semana_anterior:4,realizadas_semana_actual:5,pendientes_semana_actual:3,programadas_mes:20,valor_programado_semana:280000,monto_programado_mes:720000,honorarios_firmados_mes:850000},defective:{available:false,label:'Pendiente de definir con operación'},rows:[{id:'exp1',numero_pravia:'EXP-2026-0141',cliente_alias:'Inmobiliaria del Valle',fecha_estimada_firma:'2026-08-20',fecha_real_firma:null,honorarios:100000,abogado:'Andrea Ruiz',link:'/expedientes/exp1'}]};
const eighty={period,scope,definition:'Expedientes con anticipo recibido y pendientes de seguimiento/firma.',rows:[{id:'exp1',expediente:'EXP-2026-0141',cliente:'Inmobiliaria del Valle',honorarios:100000,anticipo:80000,pending:20000,fecha_firma:'2026-08-28',notaria:'Notaría 12',abogado:'Andrea Ruiz',link:'/expedientes/exp1'}]};
const potential={period,scope,definition:'Cotizaciones existentes sin anticipo financiero aplicado.',rows:[{id:'q1',cliente:'Corporativo Horizonte',honorarios:92000,notaria:'Notaría 18',responsable:'Andrea Ruiz',acto:'Compraventa',fecha_cotizacion:'2026-07-20',ultimo_seguimiento:null,dias_sin_anticipo:23,link:'/cotizaciones/q1'}]};
const catalogs={usuarios:[{id:'u1',nombre:'Andrea',apellido:'Ruiz',rol:'ADMINISTRACION'}],notarias:[{id:'n1',nombre:'Notaría 12',numero_notaria:12}],scope:{global:true,financial:true,targetsManage:true}};

function mockApi(options:{permissions?:string[];fail?:string;empty?:boolean}={}){const permissions=options.permissions??grants,financialAllowed=permissions.includes('reportes.financial.read');vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL)=>{const url=String(input);if(url.endsWith('/auth/me'))return json({user:{id:'u1',name:'Andrea Ruiz',role:'ADMINISTRACION',permissions}});if(url.includes('/reportes/catalogos'))return json({success:true,data:{...catalogs,scope:{global:permissions.includes('reportes.global.read'),financial:financialAllowed}}});if(url.includes(`/reportes/${options.fail}`))return json({error:'No disponible'},500);if(url.includes('/reportes/resumen'))return json({success:true,data:{...summary,financial:financialAllowed?financial:null,scope:{...scope,financial:financialAllowed}}});if(url.includes('/reportes/finanzas'))return json({success:true,data:financialAllowed?finance:{period,scope:{...scope,financial:false},restricted:true}});if(url.includes('/reportes/cobranza'))return json({success:true,data:financialAllowed?{...collections,rows:options.empty?[]:collections.rows,byLawyer:options.empty?[]:collections.byLawyer}:{period,scope:{...scope,financial:false},restricted:true}});if(url.includes('/reportes/abogados'))return json({success:true,data:lawyers});if(url.includes('/reportes/firmas'))return json({success:true,data:signatures});if(url.includes('/reportes/80-20'))return json({success:true,data:financialAllowed?eighty:{period,scope:{...scope,financial:false},restricted:true}});if(url.includes('/reportes/clientes-potenciales'))return json({success:true,data:{...potential,rows:options.empty?[]:potential.rows}});return json({success:true,data:{}});}));}
const renderReports=(path='/reportes')=>render(<MemoryRouter initialEntries={[path]}><App/></MemoryRouter>);

describe('Reportes',()=>{beforeEach(()=>vi.restoreAllMocks());
 it('presenta un resumen ejecutivo trazable con periodo y drill-down',async()=>{mockApi();const user=userEvent.setup();renderReports();expect(await screen.findByRole('heading',{name:'Reportes'})).toBeInTheDocument();expect(await screen.findByText('Honorarios generados')).toBeInTheDocument();expect(screen.getByText('Honorarios cobrados')).toBeInTheDocument();expect(screen.getByText('Por cobrar')).toBeInTheDocument();expect(screen.getByRole('note',{name:/Definición de clientes generados: Cotizaciones aceptadas/})).toBeInTheDocument();expect(screen.getByRole('img',{name:/Tendencia mensual/})).toBeInTheDocument();await user.click(screen.getByRole('button',{name:/Honorarios generados/}));expect(await screen.findByRole('heading',{name:'Tendencia financiera'})).toBeInTheDocument();});
 it('mantiene periodo y filtros de alcance en todas las vistas',async()=>{mockApi();const user=userEvent.setup();renderReports();await screen.findByText('Honorarios generados');await user.selectOptions(screen.getByLabelText('Periodo del reporte'),'ESTE_TRIMESTRE');await user.selectOptions(screen.getByLabelText('Filtrar por abogado'),'u1');await waitFor(()=>expect(vi.mocked(fetch).mock.calls.some(([u])=>String(u).includes('periodo=ESTE_TRIMESTRE')&&String(u).includes('abogado_id=u1'))).toBe(true));await user.click(screen.getByRole('button',{name:'Cobranza'}));expect(await screen.findByRole('heading',{name:'Cobranza por abogado'})).toBeInTheDocument();expect(screen.getByLabelText('Periodo del reporte')).toHaveValue('ESTE_TRIMESTRE');});
 it('cubre Abogados, Firmas, 80/20 y Clientes potenciales con enlaces reales',async()=>{mockApi();const user=userEvent.setup();renderReports('/reportes?view=abogados');expect(await screen.findByText('Operación por abogado')).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Firmas'}));expect(await screen.findByText('Firmas defectuosas')).toBeInTheDocument();expect(screen.getByText(/No se muestra una cifra ficticia/)).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'80/20'}));expect(await screen.findByText('Expedientes con anticipo')).toBeInTheDocument();expect(screen.getByRole('link',{name:'EXP-2026-0141'})).toHaveAttribute('href','/expedientes/exp1');await user.click(screen.getByRole('button',{name:'Clientes potenciales'}));expect(await screen.findByText('Cotizaciones sin anticipo')).toBeInTheDocument();expect(screen.getByRole('link',{name:'Corporativo Horizonte'})).toHaveAttribute('href','/cotizaciones/q1');});
 it('degrada un widget sin perder el resumen completo',async()=>{mockApi({fail:'cobranza'});renderReports();expect(await screen.findByText('Honorarios generados')).toBeInTheDocument();expect(screen.getByText(/Algunos indicadores no pudieron actualizarse/)).toBeInTheDocument();expect(screen.getByText('No fue posible actualizar este bloque.')).toBeInTheDocument();});
 it('respeta lectura y confidencialidad financiera por rol',async()=>{mockApi({permissions:['reportes.read']});renderReports('/reportes?view=finanzas');expect(await screen.findByText('Vista financiera restringida')).toBeInTheDocument();expect(screen.getByRole('link',{name:'Reportes'})).toBeInTheDocument();const first=screen.getByRole('heading',{name:'Reportes'});expect(first).toBeInTheDocument();});
 it('oculta el módulo sin permiso y ofrece empty state humano',async()=>{mockApi({permissions:['expedientes.read']});const first=renderReports();expect(await screen.findByText('Acceso a reportes restringido')).toBeInTheDocument();expect(screen.queryByRole('link',{name:'Reportes'})).not.toBeInTheDocument();first.unmount();mockApi({empty:true});renderReports('/reportes?view=clientes-potenciales');expect(await screen.findByText('No hay cotizaciones pendientes de anticipo')).toBeInTheDocument();});
 it('expone acciones de IA específicas de reportes',()=>{const context=resolveAssistantContext({pathname:'/reportes',hash:''});expect(getAssistantActions(context).map(x=>x.label)).toEqual(['Resumen ejecutivo','Analizar cobranza','Analizar firmas','Clientes potenciales']);});
 it('muestra configuración histórica de meta al permiso administrativo',async()=>{mockApi();renderReports();expect(await screen.findByText('Honorarios generados')).toBeInTheDocument();});
});
