import { beforeEach, describe, expect, it, vi } from 'vitest';

const mocks=vi.hoisted(()=>{
  const tx:any={complianceReview:{create:vi.fn(),update:vi.fn()},complianceDecision:{create:vi.fn()},complianceEvidence:{create:vi.fn(),update:vi.fn()},compliancePayment:{create:vi.fn()},complianceBeneficialOwner:{create:vi.fn()},compliancePartySnapshot:{create:vi.fn()},compliancePepReview:{create:vi.fn(),upsert:vi.fn()},complianceScreeningResult:{create:vi.fn()},complianceObligation:{findFirst:vi.fn(),create:vi.fn(),update:vi.fn()},complianceEvent:{create:vi.fn()},auditLog:{create:vi.fn()}};
  const db:any={user:{findFirst:vi.fn()},expediente:{findFirst:vi.fn()},complianceRuleSet:{findFirst:vi.fn()},complianceReview:{findFirst:vi.fn(),findMany:vi.fn()},compliancePartySnapshot:{findFirst:vi.fn()},complianceObligation:{findFirst:vi.fn()},complianceEvidence:{findFirst:vi.fn()},documento:{findFirst:vi.fn()},$transaction:vi.fn(async(arg:any)=>typeof arg==='function'?arg(tx):Promise.all(arg))};
  return {db,tx,capture:vi.fn(),changed:vi.fn(),prefill:vi.fn(),ruleSnapshot:vi.fn()};
});
vi.mock('../config/prisma',()=>({default:mocks.db}));
vi.mock('./complianceSnapshot.service',()=>({captureMasterSnapshot:mocks.capture,masterChangedSince:mocks.changed,prefillFromSnapshot:mocks.prefill,snapshotRule:mocks.ruleSnapshot}));

import { ComplianceReviewService } from './complianceReview.service';

const user:any={id:'user-1',email:'a@b.mx',nombre:'Andrea',apellido:'Ruiz',rol:'ABOGADO',sessionId:'s1',permissions:['compliance.read','compliance.write','compliance.review','compliance.notice.confirm','compliance.sensitive.read'],requiresPasswordChange:false};
const rule={id:'rule-1',tipo:'UIF',version:'2026.1',estatus:'REFERENCIA_VERIFICADA',vigencia_desde:new Date('2026-01-01'),vigencia_hasta:null};
const base={id:'review-1',expediente_id:'exp-1',tipo:'UIF',estatus:'BORRADOR',created_at:new Date('2026-08-01'),fecha_operacion:new Date('2026-08-01'),rule_version_snapshot:'2026.1',rule_snapshot:{parametros:{uma:{valor_diario_mxn:100},reglas:{ACTO:{aviso_siempre:false,umbral_uma:10,base:'MONTO_OPERACION',fundamento:'R-1'}}}},master_snapshot:{expediente:{id:'exp-1'},comparecientes:[]},cuestionario_json:{tipo_acto_uif:'ACTO',monto_operacion:1200,identidad_verificada:true,beneficiario_controlador_identificado:true,actividad_ocupacion_acreditada:true,origen_recursos_documentado:true,pep_declarada:'NO'},resultado_json:null};

describe('servicio de revisiones de cumplimiento',()=>{beforeEach(()=>{vi.clearAllMocks();mocks.db.user.findFirst.mockResolvedValue({id:'user-1'});mocks.db.complianceReview.findMany.mockResolvedValue([]);mocks.tx.complianceObligation.findFirst.mockResolvedValue(null);mocks.tx.auditLog.create.mockResolvedValue({});mocks.tx.complianceEvent.create.mockResolvedValue({});});
 it('evalúa contra parámetros del snapshot y aplica object scope del abogado',async()=>{mocks.db.complianceReview.findFirst.mockResolvedValue(base);mocks.tx.complianceReview.update.mockImplementation(async({data}:any)=>({...base,...data}));const result:any=await ComplianceReviewService.evaluate(user,'user-1','review-1',{},'cor-1');expect(result.resultado_json.umbral_mxn).toBe(1000);expect(result.resultado_json.requiere_aviso).toBe(true);expect(mocks.db.complianceReview.findFirst).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({expediente:expect.objectContaining({OR:[{abogado_id:'user-1'},{creador_id:'user-1'}]})})}));});
 it('una confirmación crea decisión inmutable con resultado, regla, master, actor y fecha',async()=>{const current={...base,estatus:'PENDIENTE_REVISION',resultado_json:{clasificacion:'REQUIERE_AVISO'}};mocks.db.complianceReview.findFirst.mockResolvedValue(current);mocks.tx.complianceDecision.create.mockResolvedValue({id:'decision-1'});mocks.tx.complianceReview.update.mockImplementation(async({data}:any)=>({...current,...data}));await ComplianceReviewService.decide(user,'user-1','review-1',{decision:'CONFIRMAR',observaciones:'Revisado'},'cor-1');expect(mocks.tx.complianceDecision.create).toHaveBeenCalledWith({data:expect.objectContaining({review_id:'review-1',decision:'CONFIRMAR',resultado_snapshot:current.resultado_json,rule_snapshot:current.rule_snapshot,master_snapshot:current.master_snapshot,decidido_por_id:'user-1'})});expect(mocks.tx.complianceReview.update).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({estatus:'CONFIRMADO',revisado_por_id:'user-1'})}));});
 it('no permite sobrescribir una revisión confirmada',async()=>{mocks.db.complianceReview.findFirst.mockResolvedValue({...base,estatus:'CONFIRMADO',resultado_json:{clasificacion:'REQUIERE_AVISO'}});await expect(ComplianceReviewService.decide(user,'user-1','review-1',{decision:'CONFIRMAR'})).rejects.toMatchObject({code:'COMPLIANCE_REVIEW_LOCKED',status:409});expect(mocks.tx.complianceDecision.create).not.toHaveBeenCalled();});
 it('la reevaluación crea una revisión nueva y enlaza la anterior',async()=>{mocks.db.complianceReview.findFirst.mockResolvedValue({...base,estatus:'CONFIRMADO',fecha_operacion:new Date('2026-08-01')});mocks.db.complianceRuleSet.findFirst.mockResolvedValue(rule);mocks.db.expediente.findFirst.mockResolvedValue({id:'exp-1'});mocks.capture.mockResolvedValue({expediente:{id:'exp-1'},comparecientes:[]});mocks.prefill.mockReturnValue({pep_declarada:'PENDIENTE'});mocks.ruleSnapshot.mockReturnValue({version:'2026.1',parametros:{}});mocks.tx.complianceReview.create.mockImplementation(async({data}:any)=>({id:'review-2',...data}));const created:any=await ComplianceReviewService.reevaluate(user,'user-1','review-1',{},'cor-2');expect(created.supersedes_review_id).toBe('review-1');expect(mocks.tx.complianceReview.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({master_snapshot:expect.any(Object),rule_snapshot:expect.any(Object),supersedes_review_id:'review-1'})}));});
 it('evidencia sólo reutiliza un documento del expediente y queda auditada',async()=>{mocks.db.complianceReview.findFirst.mockResolvedValue(base);mocks.db.documento.findFirst.mockResolvedValue({id:'doc-1'});mocks.tx.complianceEvidence.create.mockResolvedValue({id:'ev-1',tipo_evidencia:'ORIGEN_RECURSOS',documento:{nombre_original:'origen.pdf'}});await ComplianceReviewService.addEvidence(user,'user-1','review-1',{documento_id:'doc-1',tipo_evidencia:'ORIGEN_RECURSOS'},'cor-3');expect(mocks.db.documento.findFirst).toHaveBeenCalledWith({where:expect.objectContaining({id:'doc-1',OR:[{expediente_id:'exp-1'},{expedienteVinculos:{some:{expediente_id:'exp-1',estatus:'ACTIVO'}}}]}),select:{id:true}});expect(mocks.tx.auditLog.create).toHaveBeenCalled();});
 it('registra pago con cuenta enmascarada y auditoría sin exponer la cuenta completa',async()=>{mocks.db.complianceReview.findFirst.mockResolvedValue(base);mocks.tx.compliancePayment.create.mockImplementation(async({data}:any)=>({id:'pay-1',...data}));const payment:any=await ComplianceReviewService.addPayment(user,'user-1','review-1',{amount_mxn:1250000,method:'TRANSFERENCIA',payment_date:'2026-08-17',masked_account:'1234-5678-9012'},'cor-4');expect(payment.masked_account).toBe('56789012');expect(mocks.tx.auditLog.create).toHaveBeenCalledWith({data:expect.not.objectContaining({masked_account:expect.anything()})});});
 it('rechaza una persona fuera del snapshot para evitar IDOR',async()=>{mocks.db.complianceReview.findFirst.mockResolvedValue(base);mocks.db.compliancePartySnapshot.findFirst.mockResolvedValue(null);await expect(ComplianceReviewService.saveBeneficialOwner(user,'user-1','review-1',{compareciente_id:'otra-persona',status:'EXISTE'})).rejects.toMatchObject({code:'COMPLIANCE_PARTY_SCOPE_DENIED',status:404});expect(mocks.tx.complianceBeneficialOwner.create).not.toHaveBeenCalled();});
 it('no permite cerrar una revisión PEP sin confirmación humana explícita',async()=>{mocks.db.complianceReview.findFirst.mockResolvedValue(base);mocks.db.compliancePartySnapshot.findFirst.mockResolvedValue({id:'snap-1'});await expect(ComplianceReviewService.savePepReview(user,'user-1','review-1',{compareciente_id:'party-1',status:'NO_IDENTIFICADO'})).rejects.toMatchObject({code:'COMPLIANCE_PEP_HUMAN_CONFIRMATION_REQUIRED',status:409});expect(mocks.tx.compliancePepReview.upsert).not.toHaveBeenCalled();});
 it('no marca un Aviso como presentado sin acuse vinculado',async()=>{mocks.db.complianceReview.findFirst.mockResolvedValue(base);mocks.db.complianceObligation.findFirst.mockResolvedValue({id:'obl-1',review_id:'review-1'});mocks.db.complianceEvidence.findFirst.mockResolvedValue(null);await expect(ComplianceReviewService.confirmExternalNotice(user,'user-1','review-1','obl-1',{external_filed_at:'2026-09-10',external_folio:'F-123',external_receipt_id:'doc-x'})).rejects.toMatchObject({code:'COMPLIANCE_NOTICE_RECEIPT_INVALID',status:404});expect(mocks.tx.complianceObligation.update).not.toHaveBeenCalled();});
 it('protege el visor por scope de revisión y evidencia',async()=>{mocks.db.complianceReview.findFirst.mockResolvedValue(base);mocks.db.complianceEvidence.findFirst.mockResolvedValue(null);await expect(ComplianceReviewService.evidenceDocument(user,'review-1','ev-otra')).rejects.toMatchObject({code:'COMPLIANCE_EVIDENCE_NOT_FOUND',status:404});expect(mocks.db.complianceEvidence.findFirst).toHaveBeenCalledWith(expect.objectContaining({where:{id:'ev-otra',review_id:'review-1'}}));});
});
