import { beforeEach, describe, expect, it, vi } from 'vitest';

const mocks=vi.hoisted(()=>{
  const tx:any={complianceReview:{create:vi.fn(),update:vi.fn()},complianceDecision:{create:vi.fn()},complianceEvidence:{create:vi.fn()},auditLog:{create:vi.fn()}};
  const db:any={user:{findFirst:vi.fn()},expediente:{findFirst:vi.fn()},complianceRuleSet:{findFirst:vi.fn()},complianceReview:{findFirst:vi.fn()},documento:{findFirst:vi.fn()},$transaction:vi.fn(async(arg:any)=>typeof arg==='function'?arg(tx):Promise.all(arg))};
  return {db,tx,capture:vi.fn(),changed:vi.fn(),prefill:vi.fn(),ruleSnapshot:vi.fn()};
});
vi.mock('../config/prisma',()=>({default:mocks.db}));
vi.mock('./complianceSnapshot.service',()=>({captureMasterSnapshot:mocks.capture,masterChangedSince:mocks.changed,prefillFromSnapshot:mocks.prefill,snapshotRule:mocks.ruleSnapshot}));

import { ComplianceReviewService } from './complianceReview.service';

const user:any={id:'user-1',email:'a@b.mx',nombre:'Andrea',apellido:'Ruiz',rol:'ABOGADO',sessionId:'s1',permissions:['cumplimiento.read','cumplimiento.write','cumplimiento.confirm'],requiresPasswordChange:false};
const rule={id:'rule-1',tipo:'UIF',version:'2026.1',estatus:'REFERENCIA_VERIFICADA',vigencia_desde:new Date('2026-01-01'),vigencia_hasta:null};
const base={id:'review-1',expediente_id:'exp-1',tipo:'UIF',estatus:'BORRADOR',rule_version_snapshot:'2026.1',rule_snapshot:{parametros:{uma:{valor_diario_mxn:100},reglas:{ACTO:{aviso_siempre:false,umbral_uma:10,base:'MONTO_OPERACION',fundamento:'R-1'}}}},master_snapshot:{expediente:{id:'exp-1'}},cuestionario_json:{tipo_acto_uif:'ACTO',monto_operacion:1200,identidad_verificada:true,beneficiario_controlador_identificado:true,actividad_ocupacion_acreditada:true,origen_recursos_documentado:true,pep_declarada:'NO'},resultado_json:null};

describe('servicio de revisiones de cumplimiento',()=>{beforeEach(()=>{vi.clearAllMocks();mocks.db.user.findFirst.mockResolvedValue({id:'user-1'});mocks.tx.auditLog.create.mockResolvedValue({});});
 it('evalúa contra parámetros del snapshot y aplica object scope del abogado',async()=>{mocks.db.complianceReview.findFirst.mockResolvedValue(base);mocks.tx.complianceReview.update.mockImplementation(async({data}:any)=>({...base,...data}));const result:any=await ComplianceReviewService.evaluate(user,'user-1','review-1',{},'cor-1');expect(result.resultado_json.umbral_mxn).toBe(1000);expect(result.resultado_json.requiere_aviso).toBe(true);expect(mocks.db.complianceReview.findFirst).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({expediente:expect.objectContaining({OR:[{abogado_id:'user-1'},{creado_por_id:'user-1'}]})})}));});
 it('una confirmación crea decisión inmutable con resultado, regla, master, actor y fecha',async()=>{const current={...base,estatus:'PENDIENTE_REVISION',resultado_json:{clasificacion:'REQUIERE_AVISO'}};mocks.db.complianceReview.findFirst.mockResolvedValue(current);mocks.tx.complianceDecision.create.mockResolvedValue({id:'decision-1'});mocks.tx.complianceReview.update.mockImplementation(async({data}:any)=>({...current,...data}));await ComplianceReviewService.decide(user,'user-1','review-1',{decision:'CONFIRMAR',observaciones:'Revisado'},'cor-1');expect(mocks.tx.complianceDecision.create).toHaveBeenCalledWith({data:expect.objectContaining({review_id:'review-1',decision:'CONFIRMAR',resultado_snapshot:current.resultado_json,rule_snapshot:current.rule_snapshot,master_snapshot:current.master_snapshot,decidido_por_id:'user-1'})});expect(mocks.tx.complianceReview.update).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({estatus:'CONFIRMADO',revisado_por_id:'user-1'})}));});
 it('no permite sobrescribir una revisión confirmada',async()=>{mocks.db.complianceReview.findFirst.mockResolvedValue({...base,estatus:'CONFIRMADO',resultado_json:{clasificacion:'REQUIERE_AVISO'}});await expect(ComplianceReviewService.decide(user,'user-1','review-1',{decision:'CONFIRMAR'})).rejects.toMatchObject({code:'COMPLIANCE_REVIEW_LOCKED',status:409});expect(mocks.tx.complianceDecision.create).not.toHaveBeenCalled();});
 it('la reevaluación crea una revisión nueva y enlaza la anterior',async()=>{mocks.db.complianceReview.findFirst.mockResolvedValue({...base,estatus:'CONFIRMADO',fecha_operacion:new Date('2026-08-01')});mocks.db.complianceRuleSet.findFirst.mockResolvedValue(rule);mocks.db.expediente.findFirst.mockResolvedValue({id:'exp-1'});mocks.capture.mockResolvedValue({expediente:{id:'exp-1'},comparecientes:[]});mocks.prefill.mockReturnValue({pep_declarada:'PENDIENTE'});mocks.ruleSnapshot.mockReturnValue({version:'2026.1',parametros:{}});mocks.tx.complianceReview.create.mockImplementation(async({data}:any)=>({id:'review-2',...data}));const created:any=await ComplianceReviewService.reevaluate(user,'user-1','review-1',{},'cor-2');expect(created.supersedes_review_id).toBe('review-1');expect(mocks.tx.complianceReview.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({master_snapshot:expect.any(Object),rule_snapshot:expect.any(Object),supersedes_review_id:'review-1'})}));});
 it('evidencia sólo reutiliza un documento del expediente y queda auditada',async()=>{mocks.db.complianceReview.findFirst.mockResolvedValue(base);mocks.db.documento.findFirst.mockResolvedValue({id:'doc-1'});mocks.tx.complianceEvidence.create.mockResolvedValue({id:'ev-1',tipo_evidencia:'ORIGEN_RECURSOS'});await ComplianceReviewService.addEvidence(user,'user-1','review-1',{documento_id:'doc-1',tipo_evidencia:'ORIGEN_RECURSOS'},'cor-3');expect(mocks.db.documento.findFirst).toHaveBeenCalledWith({where:expect.objectContaining({id:'doc-1',OR:[{expediente_id:'exp-1'},{expedienteVinculos:{some:{expediente_id:'exp-1',estatus:'ACTIVO'}}}]}),select:{id:true}});expect(mocks.tx.auditLog.create).toHaveBeenCalled();});
});
