import { Prisma } from '@prisma/client';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { ROLE_PERMISSIONS, roleHasPermission } from '../auth/permissions';

const mocks = vi.hoisted(() => ({
  downloadFile: vi.fn(async () => Buffer.from('documento controlado')),
  extract: vi.fn(async () => ({ proveedor: 'OpenAI', modelo: 'fixture-model', alertas: [], campos: [
    { campo: 'rfc', valor: 'AAAA800101AA1', confianza: 'LECTURA_CLARA', documento_id: 'doc-1', pagina: 2 },
    { campo: 'precio_enajenacion', valor: '2000000.00', confianza: 'LECTURA_DUDOSA', documento_id: 'doc-1', pagina: 8 },
  ] })),
}));
vi.mock('./supabase.service', () => ({ downloadFile: mocks.downloadFile }));
vi.mock('./openaiDocument.service', () => ({ extraerMultiplesDocumentos: mocks.extract, getOpenAIModelName: () => 'fixture-model' }));

import { ISRService, isrObjectWhere } from './isr.service';

const input = { operationType:'ENAJENACION_INMUEBLE',taxYear:2026,taxpayer:{fullName:'Persona Controlada',rfc:'AAAA800101AA1',personType:'FISICA',fiscalResidence:'MEXICO',confirmed:true},property:{description:'Inmueble controlado',landAndConstructionSameAcquisitionDate:true},acquisitionDate:'2016-01-01',saleDate:'2026-08-17',yearsElapsed:10,salePrice:'2000000.00',deductions:[{id:'d1',concept:'Costo actualizado',historicalAmount:'1000000.00',updatedAmount:'1200000.00',expenseDate:'2016-01-01',updateOrigin:'MANUAL_CONFIRMED',updateMethod:'Importe actualizado proporcionado por el usuario',treatment:'COSTO_ADQUISICION_ACTUALIZADO',included:true,confirmed:true,supportDocumentId:'doc-1',reason:'LISR 121-I y 124',confirmedBy:'user-1',confirmedAt:'2026-08-17T15:30:00.000Z'}],exemptionTreatment:'NO_APLICA_CONFIRMADO',ordinaryCaseConfirmed:true,specialCases:[] };
const user = (role='ABOGADO', permissions=ROLE_PERMISSIONS.ABOGADO) => ({ id:'user-1',email:'u@pravia.test',nombre:'Usuario',apellido:'Prueba',rol:role,sessionId:'session-1',permissions,requiresPasswordChange:false } as any);
const record = (patch:Record<string,unknown>={}) => ({ id:'calc-1',folio:'ISR-2026-TEST',tipo_operacion:'ENAJENACION_INMUEBLE',estado:'LISTO_PARA_CALCULAR',ejercicio:2026,expediente_id:'exp-1',compareciente_id:null,contribuyente_nombre:'Persona Controlada',contribuyente_rfc:'AAAA800101AA1',inmueble_descripcion:'Inmueble controlado',contribuyente_snapshot:null,input_data:input,ultima_version:0,datos_modificados:false,creado_por_id:'user-1',actualizado_por_id:'user-1',created_at:new Date(),updated_at:new Date(),archived_at:null,expediente:{id:'exp-1',numero_pravia:'EXP-1'},compareciente:null,versiones:[],documentos:[],propuestas:[],...patch});

function dbMock(current=record()) {
  const tx:any={ calculoISR:{create:vi.fn(async({data}:any)=>({...current,...data})),update:vi.fn(async({data}:any)=>({...current,...data}))},calculoISRVersion:{create:vi.fn(async({data}:any)=>({id:'version',...data}))},calculoISRPropuesta:{deleteMany:vi.fn(async()=>({count:0})),create:vi.fn(async({data}:any)=>data),findFirst:vi.fn(),update:vi.fn()},auditLog:{create:vi.fn(async({data}:any)=>data)} };
  const db:any={calculoISR:{findFirst:vi.fn(async()=>current),findMany:vi.fn(async()=>[current]),count:vi.fn().mockResolvedValueOnce(1).mockResolvedValueOnce(0).mockResolvedValueOnce(1)},expediente:{findFirst:vi.fn(async()=>({id:'exp-1',cliente_alias:'Persona Controlada',valor_operacion:null,datos_operacion:null}))},compareciente:{findFirst:vi.fn(async()=>({id:'party-1',tipo_persona:'FISICA',nombre_busqueda:'Persona Controlada',personaFisica:{nombre_completo_calculado:'Persona Controlada',rfc:'AAAA800101AA1',curp:'AAAA800101HNELPR01'},personaMoral:null}))},fiscalRuleSet:{findFirst:vi.fn(async()=>({id:'rules-1',clave:'ISR_ENAJENACION_INMUEBLE_PAGO_PROVISIONAL_MX_FED',version:'2026.1',ejercicio:2026,tipo_operacion:'ENAJENACION_INMUEBLE',jurisdiccion:'MX-FED',vigencia_desde:new Date('2026-01-01'),vigencia_hasta:new Date('2026-12-31'),fuente_normativa:'LISR 126; Anexo 8',fuente_url:'https://www.dof.gob.mx/',parametros:{years_cap:20},rate_tables:[{brackets:[{orden:1,limite_inferior:new Prisma.Decimal('.01'),limite_superior:null,cuota_fija:new Prisma.Decimal('0'),porcentaje:new Prisma.Decimal('1.92')}]}]}))},calculoISRPropuesta:tx.calculoISRPropuesta,auditLog:tx.auditLog,$transaction:vi.fn(async(arg:any)=>typeof arg==='function'?arg(tx):Promise.all(arg))};
  return {db,tx};
}

describe('ISRService, RBAC e inmutabilidad',()=>{
  beforeEach(()=>vi.clearAllMocks());
  it('asigna permisos mínimos por rol y excluye recepción/gestoría',()=>{
    expect(roleHasPermission('DIRECCION','isr.admin')).toBe(true);expect(roleHasPermission('ADMINISTRACION','isr.calculate')).toBe(true);expect(roleHasPermission('ABOGADO','isr.write')).toBe(true);expect(roleHasPermission('CONSULTA','isr.read')).toBe(true);expect(roleHasPermission('CONSULTA','isr.write')).toBe(false);expect(roleHasPermission('RECEPCION','isr.read')).toBe(false);expect(roleHasPermission('GESTORIA','isr.read')).toBe(false);
  });
  it('impone object scope a abogado e impide IDOR por lectura',async()=>{
    expect(isrObjectWhere(user())).toEqual({OR:[{creado_por_id:'user-1'},{expediente:{OR:[{abogado_id:'user-1'},{creador_id:'user-1'}]}}]});
    const {db}=dbMock(null as any);await expect(new ISRService(db).get(user(),'foreign-id')).rejects.toMatchObject({code:'ISR_NOT_FOUND'});
  });
  it('lista exclusivamente con el scope del actor',async()=>{const {db}=dbMock();await new ISRService(db).list(user(),{});expect(db.calculoISR.findMany.mock.calls[0][0].where.OR).toBeDefined();});
  it('crea borrador vinculado solo tras comprobar acceso y audita',async()=>{const {db,tx}=dbMock();const created=await new ISRService(db).create(user(),{ejercicio:2026,tipo_operacion:'ENAJENACION_INMUEBLE',expediente_id:'exp-1'});expect(db.expediente.findFirst).toHaveBeenCalled();expect(created.folio).toMatch(/^ISR-2026-/);expect(tx.auditLog.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({accion:'CREAR_CALCULO_ISR'})}));});
  it('copia un snapshot fiscal al seleccionar un compareciente autorizado',async()=>{const {db,tx}=dbMock();await new ISRService(db).create(user(),{ejercicio:2026,tipo_operacion:'ENAJENACION_INMUEBLE',compareciente_id:'party-1'});expect(db.compareciente.findFirst).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({id:'party-1'})}));expect(tx.calculoISR.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({compareciente_id:'party-1',contribuyente_snapshot:expect.objectContaining({rfc:'AAAA800101AA1'})})}));});
  it('impide vincular por IDOR un compareciente fuera del alcance',async()=>{const {db}=dbMock();db.compareciente.findFirst.mockResolvedValue(null);await expect(new ISRService(db).update(user(),'calc-1',{input_data:input,compareciente_id:'foreign-party'})).rejects.toMatchObject({code:'COMPARECIENTE_ACCESS_DENIED'});});
  it('calcula en backend y guarda snapshot + versión sin sobrescribir anteriores',async()=>{const {db,tx}=dbMock(record({ultima_version:1,versiones:[{version:1}]}));const version:any=await new ISRService(db).calculate(user(),'calc-1');expect(version.version).toBe(2);expect(tx.calculoISRVersion.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({version:2,input_snapshot:expect.any(Object),ruleset_snapshot:expect.any(Object),breakdown:expect.any(Array),result:expect.any(Object)})}));expect(tx.calculoISRVersion).not.toHaveProperty('update');expect(tx.auditLog.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({accion:'RECALCULAR_ISR'})}));});
  it('IA persiste propuestas y procedencia, pero nunca modifica el input fiscal',async()=>{const linked=record({documentos:[{documento_id:'doc-1',documento:{id:'doc-1',storage_key:'isr/doc.pdf',mime_type:'application/pdf',tipo:'ISR_SOPORTE',nombre_original:'Escritura.pdf'}}]});const {db,tx}=dbMock(linked);const result=await new ISRService(db).extract(user(),'calc-1');expect(result).toMatchObject({proposals:2,conflicts:[]});expect(tx.calculoISRPropuesta.create).toHaveBeenCalledTimes(2);expect(tx.calculoISR.update).not.toHaveBeenCalled();expect(tx.auditLog.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({accion:'EXTRAER_DATOS_ISR_IA'})}));});
  it('separa aceptación humana de la edición del snapshot',async()=>{const {db}=dbMock();db.calculoISRPropuesta.findFirst.mockResolvedValue({id:'p1',calculo_id:'calc-1',field_path:'rfc'});db.calculoISRPropuesta.update.mockResolvedValue({id:'p1',status:'ACEPTADA'});await new ISRService(db).reviewProposal(user(),'calc-1','p1','ACEPTADA');expect(db.calculoISRPropuesta.update).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({reviewed_by_id:'user-1'})}));expect(db.calculoISR.findFirst).toHaveBeenCalledTimes(1);});
});
