import { Prisma } from '@prisma/client';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { ROLE_PERMISSIONS, roleHasPermission } from '../auth/permissions';

const mocks = vi.hoisted(() => ({
  downloadFile: vi.fn(async () => Buffer.from('documento controlado')),
  uploadFile: vi.fn(async () => undefined),
  deleteFile: vi.fn(async () => undefined),
  extract: vi.fn(async () => ({ proveedor: 'OpenAI', modelo: 'fixture-model', alertas: [], campos: [
    { campo: 'rfc', valor: 'AAAA800101AA1', confianza: 'LECTURA_CLARA', documento_id: 'doc-1', pagina: 2 },
    { campo: 'precio_enajenacion', valor: '2000000.00', confianza: 'LECTURA_DUDOSA', documento_id: 'doc-1', pagina: 8 },
  ], usos: [{ modelo:'fixture-model',input_tokens:100,cached_input_tokens:10,output_tokens:20,reasoning_tokens:5,total_tokens:120,duracion_ms:50,documentos_enviados:1,costo_estimado_usd:0.001,precios_version:'test',escalamiento_utilizado:false }] })),
}));
vi.mock('./supabase.service', () => ({ downloadFile: mocks.downloadFile, uploadFile: mocks.uploadFile, deleteFile: mocks.deleteFile }));
vi.mock('./openaiDocument.service', () => ({ extraerMultiplesDocumentos: mocks.extract, getOpenAIModelName: () => 'fixture-model' }));

import { ISRService, isrObjectWhere } from './isr.service';

const input = { operationType:'ENAJENACION_INMUEBLE',taxYear:2026,taxpayer:{fullName:'Persona Controlada',rfc:'AAAA800101AA1',personType:'FISICA',fiscalResidence:'MEXICO',confirmed:true},property:{description:'Inmueble controlado',landAndConstructionSameAcquisitionDate:true},acquisitionDate:'2016-01-01',saleDate:'2026-08-17',yearsElapsed:10,salePrice:'2000000.00',deductions:[{id:'d1',concept:'Costo actualizado',historicalAmount:'1000000.00',updatedAmount:'1200000.00',expenseDate:'2016-01-01',updateOrigin:'MANUAL_CONFIRMED',updateMethod:'Importe actualizado proporcionado por el usuario',treatment:'COSTO_ADQUISICION_ACTUALIZADO',included:true,confirmed:true,supportDocumentId:'doc-1',reason:'LISR 121-I y 124',confirmedBy:'user-1',confirmedAt:'2026-08-17T15:30:00.000Z'}],exemptionTreatment:'NO_APLICA_CONFIRMADO',ordinaryCaseConfirmed:true,specialCases:[] };
const user = (role='ABOGADO', permissions=ROLE_PERMISSIONS.ABOGADO) => ({ id:'user-1',organizationId:'org-1',email:'u@pravia.test',nombre:'Usuario',apellido:'Prueba',rol:role,sessionId:'session-1',permissions,requiresPasswordChange:false } as any);
const record = (patch:Record<string,unknown>={}) => ({ id:'calc-1',folio:'ISR-2026-TEST',tipo_operacion:'ENAJENACION_INMUEBLE',estado:'LISTO_PARA_CALCULAR',ejercicio:2026,expediente_id:'exp-1',compareciente_id:null,contribuyente_nombre:'Persona Controlada',contribuyente_rfc:'AAAA800101AA1',inmueble_descripcion:'Inmueble controlado',contribuyente_snapshot:null,input_data:input,ultima_version:0,datos_modificados:false,creado_por_id:'user-1',actualizado_por_id:'user-1',created_at:new Date(),updated_at:new Date(),archived_at:null,expediente:{id:'exp-1',numero_pravia:'EXP-1'},compareciente:null,versiones:[],documentos:[],propuestas:[],...patch});

function dbMock(current=record()) {
  const expediente:any={id:'exp-1',numero_pravia:'EXP-0001-2026',version:1,cliente_alias:'Persona Controlada',valor_operacion:null,datos_operacion:null,fecha_escritura:null,numero_escritura:null,numero_notaria:null,notaria:null,actos:[],predios:[],comparecientes:[]};
  const rules={id:'rules-1',clave:'ISR_ENAJENACION_INMUEBLE_PAGO_PROVISIONAL_MX_FED',version:'2026.1',ejercicio:2026,tipo_operacion:'ENAJENACION_INMUEBLE',jurisdiccion:'MX-FED',vigencia_desde:new Date('2026-01-01'),vigencia_hasta:new Date('2026-12-31'),fuente_normativa:'LISR 126; Anexo 8',fuente_url:'https://www.dof.gob.mx/',parametros:{years_cap:20},rate_tables:[{brackets:[{orden:1,limite_inferior:new Prisma.Decimal('.01'),limite_superior:null,cuota_fija:new Prisma.Decimal('0'),porcentaje:new Prisma.Decimal('1.92')}]}]};
  const tx:any={
    $executeRaw:vi.fn(async()=>1),
    calculoISR:{
      findFirst:vi.fn(async({where,include}:any)=>include||where?.id===current?.id?current:null),
      create:vi.fn(async({data}:any)=>({...current,...data})),
      update:vi.fn(async({data}:any)=>({...current,...data})),
    },
    calculoISRVersion:{findFirst:vi.fn(async()=>null),create:vi.fn(async({data}:any)=>({id:'version',...data}))},
    calculoISRPropuesta:{deleteMany:vi.fn(async()=>({count:0})),create:vi.fn(async({data}:any)=>data),findFirst:vi.fn(),update:vi.fn()},
    aIUsageLog:{findFirst:vi.fn(async()=>null),upsert:vi.fn(async({create}:any)=>create),create:vi.fn(async({data}:any)=>data)},
    expediente:{findFirst:vi.fn(async()=>expediente)},
    fiscalRuleSet:{findFirst:vi.fn(async()=>rules)},
    fiscalReferenceRevision:{findMany:vi.fn(async()=>[])},
    expedienteActividad:{create:vi.fn(async({data}:any)=>data)},auditLog:{create:vi.fn(async({data}:any)=>data),
  }};
  const db:any={calculoISR:{findFirst:vi.fn(async()=>current),findMany:vi.fn(async()=>[current]),count:vi.fn().mockResolvedValueOnce(1).mockResolvedValueOnce(0).mockResolvedValueOnce(1)},expediente:{findFirst:vi.fn(async()=>expediente)},compareciente:{findFirst:vi.fn(async()=>({id:'party-1',tipo_persona:'FISICA',nombre_busqueda:'Persona Controlada',personaFisica:{nombre_completo_calculado:'Persona Controlada',rfc:'AAAA800101AA1',curp:'AAAA800101HNELPR01'},personaMoral:null}))},tipoActo:{findMany:vi.fn(async()=>[])},fiscalRuleSet:{findFirst:vi.fn(async()=>rules),findMany:vi.fn(async()=>[])},fiscalReferenceRevision:{findFirst:vi.fn(async()=>null),findMany:vi.fn(async()=>[])},fiscalExportProfile:{findFirst:vi.fn(async()=>null),findMany:vi.fn(async()=>[])},postalCodeCatalog:{findFirst:vi.fn(async()=>null),findMany:vi.fn(async()=>[])},catalogoArtefactoDestino:{findMany:vi.fn(async()=>[])},calculoISRPropuesta:tx.calculoISRPropuesta,aIUsageLog:tx.aIUsageLog,auditLog:tx.auditLog,$transaction:vi.fn(async(arg:any)=>typeof arg==='function'?arg(tx):Promise.all(arg))};
  return {db,tx,expediente};
}

describe('ISRService, RBAC e inmutabilidad',()=>{
  beforeEach(()=>vi.clearAllMocks());
  it('asigna permisos mínimos por rol y excluye recepción/gestoría',()=>{
    expect(roleHasPermission('DIRECCION','isr.admin')).toBe(true);expect(roleHasPermission('ADMINISTRACION','isr.calculate')).toBe(true);expect(roleHasPermission('ADMINISTRACION','isr.export')).toBe(true);expect(roleHasPermission('ABOGADO','isr.write')).toBe(true);expect(roleHasPermission('ABOGADO','isr.export')).toBe(true);expect(roleHasPermission('CONSULTA','isr.read')).toBe(true);expect(roleHasPermission('CONSULTA','isr.export')).toBe(false);expect(roleHasPermission('CONSULTA','isr.write')).toBe(false);expect(roleHasPermission('RECEPCION','isr.read')).toBe(false);expect(roleHasPermission('GESTORIA','isr.read')).toBe(false);
  });
  it('impone object scope a abogado e impide IDOR por lectura',async()=>{
    expect(isrObjectWhere(user())).toEqual({OR:[{creado_por_id:'user-1'},{expediente:{OR:[{abogado_id:'user-1'},{creador_id:'user-1'}]}}]});
    const {db}=dbMock(null as any);await expect(new ISRService(db).get(user(),'foreign-id')).rejects.toMatchObject({code:'ISR_NOT_FOUND'});
  });
  it('lista exclusivamente con el scope del actor',async()=>{const {db}=dbMock();await new ISRService(db).list(user(),{});expect(db.calculoISR.findMany.mock.calls[0][0].where.OR).toBeDefined();});
  it('publica sólo referencias y perfiles verificados vigentes para la fecha jurídica',async()=>{const {db}=dbMock();db.fiscalReferenceRevision.findMany.mockResolvedValue([{id:'ref-1',reference_type:'INPC',code:'INPC-2026-08',version:1,effective_from:new Date('2026-08-01T00:00:00Z'),effective_to:null,value:{factor:'1.0123'},source_title:'Fuente QA',source_url:'https://qa.local.invalid/inpc'}]);db.fiscalExportProfile.findMany.mockResolvedValue([{id:'profile-1',code:'SAT-QA',name:'Perfil SAT QA',target:'SAT',version:1,definition:{fields:[]},authority:'QA',valid_from:new Date('2026-01-01'),valid_to:new Date('2026-12-31'),serialization:{format:'JSON'},validation_rules:{},source_title:'Fuente QA',source_url:'https://qa.local.invalid/profile'}]);const result=await new ISRService(db).resources(user(),'2026-08-17');expect(db.fiscalReferenceRevision.findMany).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({organization_id:'org-1',verification_status:'VERIFICADA'})}));expect(db.fiscalExportProfile.findMany).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({organization_id:'org-1',active:true,verification_status:'VERIFICADA',valid_from:{lte:expect.any(Date)}})}));expect(result).toMatchObject({legal_date:'2026-08-17',references:[{id:'ref-1',type:'INPC',sourceTitle:'Fuente QA'}],export_profiles:[{id:'profile-1',target:'SAT',validFrom:'2026-01-01',validTo:'2026-12-31'}]});});
  it('prepara una salida fiscal determinista desde la versión inmutable y conserva perfil y checksum',async()=>{const latest={id:'v1',version:3,input_snapshot:input,result:{provisionalFederalISR:'123.45'},calculated_at:new Date()};const {db}=dbMock(record({ultima_version:3,versiones:[latest]}));db.fiscalExportProfile.findFirst.mockResolvedValue({id:'profile-1',code:'SAT-QA',name:'Perfil SAT QA',target:'SAT',version:2,definition:{fields:[{path:'input.taxpayer.rfc',outputPath:'contribuyente.rfc',required:true},{path:'calculation.provisionalFederalISR',outputPath:'resultado.isr',required:true}],catalogs:{}},authority:'QA',valid_from:new Date('2026-01-01'),valid_to:new Date('2026-12-31'),serialization:{format:'JSON'},source_title:'Fuente QA',source_url:'https://qa.local.invalid/profile'});const service=new ISRService(db);const first=await service.exportData(user(),'calc-1','profile-1');const second=await service.exportData(user(),'calc-1','profile-1');expect(first).toEqual(second);expect(first).toMatchObject({payload:{calculation:{id:'calc-1',version:3},data:{contribuyente:{rfc:'AAAA800101AA1'},resultado:{isr:'123.45'}},fictitiousValues:false},checksum_sha256:expect.stringMatching(/^[a-f0-9]{64}$/),mime_type:'application/json'});expect(db.auditLog.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({accion:'PREPARAR_EXPORTACION_FISCAL'})}));});
  it('calcula adquisición o IVA sólo desde una referencia verificada y audita',async()=>{const {db}=dbMock();db.fiscalReferenceRevision.findFirst.mockResolvedValue({id:'tax-ref',reference_type:'ADQUISICION',code:'ADQ-NAY-2026',version:1,effective_from:new Date('2026-01-01'),effective_to:null,value:{rate:'2'},source_title:'Fuente verificada',source_url:'https://example.test/adq'});const result=await new ISRService(db).additionalTax(user(),{reference_id:'tax-ref',taxable_base:'100000'});expect(result).toMatchObject({tax:'2000.00',type:'ADQUISICION'});expect(db.auditLog.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({accion:'CALCULAR_IMPUESTO_ADICIONAL_ISR',entidad_id:'tax-ref'})}));});
  it('busca CP, colonia, municipio o estado exclusivamente en la revisión SEPOMEX más reciente',async()=>{const {db}=dbMock();db.postalCodeCatalog.findFirst.mockResolvedValue({source_version:'SEPOMEX-2026-09-25',source_updated_at:new Date('2026-09-25T00:00:00Z'),source_url:'https://www.correosdemexico.gob.mx/'});db.postalCodeCatalog.findMany.mockResolvedValue([{id:'cp-1',postal_code:'63000',settlement:'Tepic Centro',settlement_type:'Colonia',municipality:'Tepic',state:'Nayarit',city:'Tepic',zone:'Urbano'}]);const result=await new ISRService(db).searchPostalCodes('Tepic');expect(db.postalCodeCatalog.findMany).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({source_version:'SEPOMEX-2026-09-25',OR:expect.any(Array)}),take:30}));expect(result).toMatchObject({source:{version:'SEPOMEX-2026-09-25',updated_at:'2026-09-25'},data:[{postal_code:'63000',settlement:'Tepic Centro'}]});});
  it('crea borrador vinculado solo tras comprobar acceso y audita',async()=>{const {db,tx}=dbMock();const created=await new ISRService(db).create(user(),{ejercicio:2026,tipo_operacion:'ENAJENACION_INMUEBLE',expediente_id:'exp-1'});expect(tx.expediente.findFirst).toHaveBeenCalled();expect(created.folio).toMatch(/^ISR-2026-/);expect(tx.expedienteActividad.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({organization_id:user().organizationId,expediente_id:'exp-1',titulo:'Cálculo ISR vinculado'})}));expect(tx.auditLog.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({accion:'CREAR_CALCULO_ISR'})}));});
  it('captura escritura, notaría y Predio como snapshot fiscal sin mutar maestros ni inventar ausentes',async()=>{const {db,tx,expediente}=dbMock();expediente.fecha_escritura=new Date('2026-08-17T12:00:00Z');expediente.numero_escritura='418';expediente.notaria={id:'notary-1',nombre:'Notaría 12',numero_notaria:'12',entidad_federativa:'Nayarit'};expediente.datos_operacion={tipo_instrumento:'ESCRITURA_PUBLICA',tipo_inmueble:'HOUSE',tipo_transmision:'ONEROSA'};expediente.actos=[{id:'act-1',tipo_acto_id:'type-1',tipo_acto:{id:'type-1',codigo_catalogo:'COMPRAVENTA',nombre:'Compraventa'}}];expediente.predios=[{id:'link-1',predio_id:'predio-1',actos:[{expediente_acto_id:'act-1'}],predio:{id:'predio-1',version:2,apodo:'Casa QA',descripcion:'Casa habitación',ubicacion_texto:'Domicilio QA',clave_catastral:'CAT-QA',cuenta_predial:'PRED-QA',folio_real:'FR-QA',datos_registrales:{partida:'418'},pais:'México',superficie_terreno_m2:new Prisma.Decimal('420'),superficie_construccion_m2:new Prisma.Decimal('238'),superficie_construccion_comercial_m2:null,valor_catastral:new Prisma.Decimal('100'),valor_avaluo:new Prisma.Decimal('200'),valor_operacion:new Prisma.Decimal('300'),colindancias:[{orden:1,referencia:'Norte',medida:new Prisma.Decimal('20'),unidad:'m',colindante:'Área común',descripcion:null}]}}];await new ISRService(db).create(user(),{expediente_id:'exp-1',idempotency_key:'snapshot-1'});expect(tx.calculoISR.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({input_data:expect.objectContaining({operation:expect.objectContaining({operationDate:'2026-08-17',operationTypeCode:'COMPRAVENTA',instrumentTypeCode:'ESCRITURA_PUBLICA',deedNumber:'418',notary:expect.objectContaining({name:'Notaría 12',number:'12'}),propertyTypeCode:'HOUSE',transmissionTypeCode:'ONEROSA',source:'EXPEDIENTE_SNAPSHOT',confirmed:false}),property:expect.objectContaining({sourcePredioId:'predio-1',realEstateFolio:'FR-QA',cadastralKey:'CAT-QA',propertyTaxAccount:'PRED-QA',registryData:{partida:'418'},boundaries:[expect.objectContaining({reference:'Norte',measurement:'20.00'})]})})})}));expect(tx.expediente.update).toBeUndefined();});
  it('copia un snapshot fiscal al seleccionar un compareciente autorizado',async()=>{const {db,tx}=dbMock();await new ISRService(db).create(user(),{ejercicio:2026,tipo_operacion:'ENAJENACION_INMUEBLE',compareciente_id:'party-1'});expect(db.compareciente.findFirst).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({id:'party-1'})}));expect(tx.calculoISR.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({compareciente_id:'party-1',contribuyente_snapshot:expect.objectContaining({rfc:'AAAA800101AA1'})})}));});
  it('impide vincular por IDOR un compareciente fuera del alcance',async()=>{const {db}=dbMock();db.compareciente.findFirst.mockResolvedValue(null);await expect(new ISRService(db).update(user(),'calc-1',{input_data:input,compareciente_id:'foreign-party'})).rejects.toMatchObject({code:'COMPARECIENTE_ACCESS_DENIED'});});
  it('calcula en backend y guarda snapshot + versión sin sobrescribir anteriores',async()=>{const {db,tx}=dbMock(record({ultima_version:1,versiones:[{version:1}],documentos:[{documento_id:'doc-1'}]}));const version:any=await new ISRService(db).calculate(user(),'calc-1');expect(version.version).toBe(2);expect(tx.calculoISRVersion.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({organization_id:'org-1',version:2,input_snapshot:expect.any(Object),ruleset_snapshot:expect.any(Object),breakdown:expect.any(Array),result:expect.any(Object)})}));expect(tx.calculoISRVersion).not.toHaveProperty('update');expect(tx.auditLog.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({accion:'RECALCULAR_ISR'})}));});
  it('ejecuta ISR v3 sólo con parámetros fiscales verificados y persiste el snapshot reproducible',async()=>{const v3={schemaVersion:3,taxYear:2026,operationDate:'2026-08-17',act:{id:'act-1',name:'Compraventa',fiscalClassification:'COMPRAVENTA'},property:{type:'CONSTRUCCION_COMERCIAL',sameAcquisitionDate:true},values:{operation:'1000000',appraisal:'1200000',cadastral:'800000',landSale:'400000',constructionSale:'600000'},calculateIVA:true,parties:[{id:'s1',role:'ENAJENANTE',name:'Vendedor',subjectType:'PF',nationalityCode:'MX',fiscalResidence:'MEXICO',percentage:'100',acquisitionLayers:[{id:'l1',percentage:'100',acquisitionAct:'ONEROSA',legalDate:'2016-01-01',fiscalDate:'2016-01-01',adjustedLandCost:'400000',adjustedConstructionCost:'0',source:'Escritura',verified:true}]},{id:'b1',role:'ADQUIRENTE',name:'Comprador',subjectType:'PF',nationalityCode:'MX',fiscalResidence:'MEXICO',percentage:'100'}],deductions:[]};const {db,tx}=dbMock(record({input_data:v3,documentos:[]}));tx.fiscalReferenceRevision.findMany.mockResolvedValue([{id:'a',reference_type:'RATE',code:'RLISR217_THRESHOLD_PERCENT',version:1,effective_from:new Date('2026-01-01'),effective_to:null,value:{value:'10'},source_title:'RLISR 217',source_url:'https://www.diputados.gob.mx/'},{id:'b',reference_type:'RATE',code:'RLISR217_ACQUISITION_RATE',version:1,effective_from:new Date('2026-01-01'),effective_to:null,value:{value:'20'},source_title:'LISR 130',source_url:'https://www.diputados.gob.mx/'},{id:'c',reference_type:'RATE',code:'LIVA_GENERAL_RATE',version:1,effective_from:new Date('2026-01-01'),effective_to:null,value:{value:'16'},source_title:'LIVA 1',source_url:'https://www.diputados.gob.mx/'}]);await new ISRService(db).calculate(user(),'calc-1');expect(tx.calculoISRVersion.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({input_snapshot:expect.objectContaining({schemaVersion:3}),ruleset_snapshot:expect.objectContaining({engineVersion:'ISR-V3.0'}),result:expect.objectContaining({schemaVersion:3,engineVersion:'ISR-V3.0',acquisitionISR:[expect.objectContaining({amount:'40000.00'})],iva:expect.objectContaining({amount:'96000.00'})})})}));expect(tx.auditLog.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({detalles:expect.objectContaining({engine:'ISR-V3.0'})})}));});
  it('calcula componentes sólo con criterio verificado cuyo contenido coincide',async()=>{const advanced={...input,deductions:[],components:[{id:'land',type:'TERRENO',saleValue:'2000000.00',acquisitions:[{id:'a1',date:'2016-01-01',historicalAmount:'900000.00',updatedAmount:'900000.00',adjustmentMethod:'MANUAL_CONFIRMED',source:'Escritura',confirmed:true}]}],criteria:{adjustmentMethod:'AUTO',resolvedAdjustmentMethod:'MANUAL_CONFIRMED',tariffSelection:'AUTO',landLossOffsetsConstructionGain:false,version:'1',effectiveFrom:'2026-01-01',source:'https://qa.local/criterion',referenceCode:'ISR-CRIT-1'}};const {db,tx}=dbMock(record({input_data:advanced,documentos:[]}));tx.fiscalReferenceRevision.findMany.mockResolvedValue([{id:'crit-1',reference_type:'CALCULATION_CRITERIA',code:'ISR-CRIT-1',version:1,effective_from:new Date('2026-01-01'),effective_to:new Date('2026-12-31'),value:{adjustmentMethod:'AUTO',resolvedAdjustmentMethod:'MANUAL_CONFIRMED',tariffSelection:'AUTO',landLossOffsetsConstructionGain:false},source_title:'Criterio QA',source_url:'https://qa.local/criterion'}]);await new ISRService(db).calculate(user(),'calc-1');expect(tx.calculoISRVersion.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({input_snapshot:expect.objectContaining({criteria:expect.objectContaining({referenceCode:'ISR-CRIT-1'})}),result:expect.objectContaining({advanced:expect.objectContaining({criteria:expect.objectContaining({version:'1'})})})})}));});
  it('rechaza una política capturada distinta a la revisión fiscal verificada',async()=>{const advanced={...input,deductions:[],components:[{id:'land',type:'TERRENO',saleValue:'2000000.00',acquisitions:[{id:'a1',date:'2016-01-01',historicalAmount:'900000.00',updatedAmount:'900000.00',adjustmentMethod:'MANUAL_CONFIRMED',source:'Escritura',confirmed:true}]}],criteria:{adjustmentMethod:'AUTO',resolvedAdjustmentMethod:'MANUAL_CONFIRMED',tariffSelection:'AUTO',landLossOffsetsConstructionGain:true,version:'1',effectiveFrom:'2026-01-01',source:'https://qa.local/criterion',referenceCode:'ISR-CRIT-1'}};const {db,tx}=dbMock(record({input_data:advanced,documentos:[]}));tx.fiscalReferenceRevision.findMany.mockResolvedValue([{id:'crit-1',reference_type:'CALCULATION_CRITERIA',code:'ISR-CRIT-1',version:1,effective_from:new Date('2026-01-01'),effective_to:new Date('2026-12-31'),value:{adjustmentMethod:'AUTO',resolvedAdjustmentMethod:'MANUAL_CONFIRMED',tariffSelection:'AUTO',landLossOffsetsConstructionGain:false},source_title:'Criterio QA',source_url:'https://qa.local/criterion'}]);await expect(new ISRService(db).calculate(user(),'calc-1')).rejects.toMatchObject({code:'CALCULATION_CRITERIA_POLICY_MISMATCH'});});
  it('impide tarifa manual a un rol no autorizado antes de calcular',async()=>{const manual={...input,criteria:{adjustmentMethod:'AUTO',resolvedAdjustmentMethod:'MANUAL_CONFIRMED',tariffSelection:'MANUAL_AUTHORIZED',landLossOffsetsConstructionGain:false,version:'1',effectiveFrom:'2026-01-01',source:'https://qa.local/manual',referenceCode:'ISR-MANUAL-1',tariffRuleSetId:'rules-1',reason:'Corrección autorizada'}};const {db}=dbMock(record({input_data:manual}));await expect(new ISRService(db).calculate(user('ABOGADO'),'calc-1')).rejects.toMatchObject({code:'MANUAL_TARIFF_PERMISSION_DENIED',status:403});});
  it('autoriza tarifa manual sólo en backend y conserva actor, fecha, motivo y ruleset',async()=>{const manual={...input,criteria:{adjustmentMethod:'AUTO',resolvedAdjustmentMethod:'MANUAL_CONFIRMED',tariffSelection:'MANUAL_AUTHORIZED',landLossOffsetsConstructionGain:false,version:'1',effectiveFrom:'2026-01-01',source:'https://qa.local/manual',referenceCode:'ISR-MANUAL-1',tariffRuleSetId:'rules-1',reason:'Operación histórica revisada'}};const {db,tx}=dbMock(record({input_data:manual,documentos:[{documento_id:'doc-1'}]}));tx.fiscalReferenceRevision.findMany.mockResolvedValue([{id:'manual-1',reference_type:'CALCULATION_CRITERIA',code:'ISR-MANUAL-1',version:1,effective_from:new Date('2026-01-01'),effective_to:new Date('2026-12-31'),value:{adjustmentMethod:'AUTO',resolvedAdjustmentMethod:'MANUAL_CONFIRMED',tariffSelection:'MANUAL_AUTHORIZED',landLossOffsetsConstructionGain:false},source_title:'Criterio manual QA',source_url:'https://qa.local/manual'}]);await new ISRService(db).calculate(user('ADMINISTRACION',ROLE_PERMISSIONS.ADMINISTRACION),'calc-1');expect(tx.fiscalRuleSet.findFirst).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({id:'rules-1'})}));expect(tx.calculoISRVersion.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({input_snapshot:expect.objectContaining({criteria:expect.objectContaining({authorizedBy:'user-1',authorizedAt:expect.any(String),reason:'Operación histórica revisada'})})})}));expect(tx.auditLog.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({detalles:expect.objectContaining({criteria_reference:'ISR-MANUAL-1',tariff_selection:'MANUAL_AUTHORIZED',tariff_authorized_by:'user-1'})})}));});
  it('IA envía cada documento una sola vez, registra uso canónico y nunca modifica el input fiscal',async()=>{const linked=record({documentos:[{documento_id:'doc-1',documento:{id:'doc-1',storage_key:'isr/doc.pdf',mime_type:'application/pdf',tipo:'ISR_SOPORTE',nombre_original:'Escritura.pdf'}}]});const {db,tx}=dbMock(linked);const result=await new ISRService(db).extract(user(),'calc-1',{requestKey:'extract-1'});expect(result).toMatchObject({proposals:2,conflicts:[],idempotent:false});expect(mocks.extract).toHaveBeenCalledWith([expect.objectContaining({documentoId:'doc-1'})]);expect(tx.calculoISRPropuesta.create).toHaveBeenCalledTimes(2);expect(tx.aIUsageLog.upsert).toHaveBeenCalledWith(expect.objectContaining({where:{operation_id:'isr-extraction:org-1:calc-1:extract-1:0'},create:expect.objectContaining({organization_id:'org-1',usuario_id:'user-1',expediente_id:'exp-1',operacion:'ISR_DOCUMENT_EXTRACTION',documentos_enviados:1})}));expect(tx.calculoISR.update).not.toHaveBeenCalled();expect(tx.auditLog.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({accion:'EXTRAER_DATOS_ISR_IA'})}));});
  it('reintentar la misma extracción no vuelve a invocar proveedor ni duplica auditoría',async()=>{const linked=record({propuestas:[{id:'p1',field_path:'rfc',status:'PENDIENTE'}]});const {db,tx}=dbMock(linked);db.aIUsageLog.findFirst.mockResolvedValue({provider:'OPENAI',modelo:'fixture-model',estatus:'COMPLETADO'});const result=await new ISRService(db).extract(user(),'calc-1',{requestKey:'same-extract'});expect(result).toMatchObject({proposals:1,idempotent:true});expect(mocks.extract).not.toHaveBeenCalled();expect(tx.auditLog.create).not.toHaveBeenCalled();});
  it('un borrador cambiado después de calcular deja de fingir estado final',async()=>{const current=record({ultima_version:1,estado:'CALCULADO'});const {db,tx}=dbMock(current);await new ISRService(db).update(user(),'calc-1',{input_data:{...input,salePrice:'2100000.00'},expected_updated_at:current.updated_at.toISOString()});expect(tx.calculoISR.update).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({estado:'LISTO_PARA_CALCULAR',datos_modificados:true})}));});
  it('separa aceptación humana de la edición del snapshot',async()=>{const {db}=dbMock();db.calculoISRPropuesta.findFirst.mockResolvedValue({id:'p1',calculo_id:'calc-1',field_path:'rfc'});db.calculoISRPropuesta.update.mockResolvedValue({id:'p1',status:'ACEPTADA'});await new ISRService(db).reviewProposal(user(),'calc-1','p1','ACEPTADA');expect(db.calculoISRPropuesta.update).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({reviewed_by_id:'user-1'})}));expect(db.calculoISR.findFirst).toHaveBeenCalledTimes(1);});
  it('abre siempre el mismo cálculo ya vinculado y no crea un duplicado',async()=>{const {db,tx}=dbMock();tx.calculoISR.findFirst.mockResolvedValue(record());const result=await new ISRService(db).openForExpediente(user(),'exp-1','same-request');expect(result).toMatchObject({created:false,idempotent:true,data:{id:'calc-1'}});expect(tx.calculoISR.create).not.toHaveBeenCalled();});
  it('el backend bloquea abrir un expediente de otro tenant aunque el ID sea válido',async()=>{const {db,tx}=dbMock();tx.expediente.findFirst.mockResolvedValue(null);await expect(new ISRService(db).openForExpediente(user(),'tenant-b-exp')).rejects.toMatchObject({code:'EXPEDIENT_ACCESS_DENIED',status:403});expect(tx.calculoISR.create).not.toHaveBeenCalled();});
  it('exige Reemplazar o Cancelar cuando el expediente está ocupado',async()=>{const current=record({expediente_id:null,expediente:null});const {db,tx}=dbMock(current);tx.calculoISR.findFirst.mockImplementation(async({where}:any)=>where.id==='calc-1'?current:{id:'occupied',folio:'ISR-OCUPADO'});await expect(new ISRService(db).update(user(),'calc-1',{input_data:input,expediente_id:'exp-1'})).rejects.toMatchObject({code:'ISR_EXPEDIENT_OCCUPIED',status:409});expect(tx.calculoISR.update).not.toHaveBeenCalled();});
  it('reemplaza sólo el vínculo y preserva el cálculo anterior',async()=>{const current=record({expediente_id:null,expediente:null});const {db,tx}=dbMock(current);tx.calculoISR.findFirst.mockImplementation(async({where}:any)=>where.id==='calc-1'?current:{id:'occupied',folio:'ISR-OCUPADO'});await new ISRService(db).update(user(),'calc-1',{input_data:input,expediente_id:'exp-1',replace_existing:true});expect(tx.calculoISR.update).toHaveBeenNthCalledWith(1,{where:{id:'occupied'},data:{expediente_id:null,actualizado_por_id:'user-1'}});expect(tx.calculoISR.update).toHaveBeenNthCalledWith(2,expect.objectContaining({where:{id:'calc-1'},data:expect.objectContaining({expediente_id:'exp-1'})}));});
  it('desvincular conserva el cálculo, versiones y documentos',async()=>{const {db,tx}=dbMock(record());const result=await new ISRService(db).unlinkFromExpediente(user(),'calc-1');expect(result.idempotent).toBe(false);expect(tx.calculoISR.update).toHaveBeenCalledWith(expect.objectContaining({where:{id:'calc-1'},data:expect.objectContaining({expediente_id:null})}));expect((tx.calculoISR as any).delete).toBeUndefined();});
  it('rechaza deducciones cuyo soporte no pertenece al cálculo',async()=>{const {db}=dbMock(record({documentos:[]}));await expect(new ISRService(db).calculate(user(),'calc-1')).rejects.toMatchObject({code:'ISR_SUPPORT_DOCUMENT_INVALID'});});
  it('no genera PDF sin una versión vigente y un formato ISR configurado',async()=>{const current=record({ultima_version:1,versiones:[{id:'v1',version:1,input_snapshot:input,result:{},calculated_at:new Date()}],datos_modificados:false});const {db}=dbMock(current);await expect(new ISRService(db).generatePdf(user(),'calc-1',{expectedVersion:1,idempotencyKey:'pdf-1'})).rejects.toMatchObject({code:'ISR_PDF_FORMAT_REQUIRED',status:409});expect(mocks.uploadFile).not.toHaveBeenCalled();});
});
