import type { PrismaClient } from '@prisma/client';
import type { Request } from 'express';
import { expedienteAccessWhere } from '../middleware/auth.middleware';
import { reportFinancialTotals, mondayWeek, resolveReportingPeriod, targetProgress, type ReportingPeriod } from '../domain/reportingCore';
import type { CanonicalMovement, EconomicNature } from '../domain/financeCore';

type AuthUser=NonNullable<Request['user']>;
type ReportQuery={periodo?:string;fecha_desde?:string;fecha_hasta?:string;abogado_id?:string;notaria_id?:string};
type TargetInput={alcance?:string;usuario_id?:string;periodo_inicio?:string;periodo_fin?:string;importe?:number|string;base?:string;moneda?:string};
const applied=['APLICADO','RECIBIDO','VALIDADO'];
const n=(value:unknown)=>Number(value||0);
const person=(user?:{nombre:string;apellido:string}|null)=>user?`${user.nombre} ${user.apellido}`.trim():'Sin responsable';
const feeRows=(value:{monto:unknown}|Array<{monto:unknown}>|null|undefined)=>value?(Array.isArray(value)?value:[value]):[];

export class ReportingService{
 constructor(private db:PrismaClient){}
 context(user:AuthUser,query:ReportQuery){
  const period=resolveReportingPeriod(query);
  const global=user.permissions.includes('reportes.global.read');
  const financial=user.permissions.includes('reportes.financial.read');
  const lawyerId=global&&query.abogado_id&&query.abogado_id!=='TODOS'?query.abogado_id:user.rol==='ABOGADO'?user.id:undefined;
  const notariaId=query.notaria_id&&query.notaria_id!=='TODOS'?query.notaria_id:undefined;
  return {period,scope:{mode:global?'GLOBAL':user.rol==='ABOGADO'?'PROPIO':'OPERATIVO',lawyerId,notariaId,financial}};
 }
 private feeWhere(ctx:ReturnType<ReportingService['context']>,range?:{from?:Date;to?:Date}){return {estado:{not:'CANCELADO' as const},...(ctx.scope.lawyerId?{responsable_id:ctx.scope.lawyerId}:{}),...(ctx.scope.notariaId?{notaria_id:ctx.scope.notariaId}:{}),...(range?.from||range?.to?{fecha_reconocimiento:{...(range.from?{gte:range.from}:{}),...(range.to?{lte:range.to}:{})}}:{})};}
 private movementWhere(ctx:ReturnType<ReportingService['context']>,range=ctx.period){return {estatus:{in:applied as any},fecha_movimiento:{gte:range.from,lte:range.to},...(ctx.scope.lawyerId?{responsable_id:ctx.scope.lawyerId}:{}),...(ctx.scope.notariaId?{notaria_id:ctx.scope.notariaId}:{})};}
 private expedienteWhere(user:AuthUser,ctx:ReturnType<ReportingService['context']>){return {archived_at:null,...expedienteAccessWhere(user),...(ctx.scope.lawyerId?{abogado_id:ctx.scope.lawyerId}:{}),...(ctx.scope.notariaId?{notaria_id:ctx.scope.notariaId}:{})};}
 async canonicalFinancials(ctx:ReturnType<ReportingService['context']>){
  if(!ctx.scope.financial)return null;
  const [fees,movements]=await Promise.all([
   this.db.honorarioGenerado.findMany({where:this.feeWhere(ctx,{from:ctx.period.from,to:ctx.period.to}),select:{monto:true}}),
   this.db.movimientoFinanciero.findMany({where:this.movementWhere(ctx),select:{naturaleza:true,monto:true,estatus:true,distribuciones:{select:{monto:true,categoria:{select:{naturaleza:true}}}}}}),
  ]);
  return reportFinancialTotals(fees.map(x=>n(x.monto)),movements.map((x):CanonicalMovement=>({nature:x.naturaleza,amount:n(x.monto),status:x.estatus,allocations:x.distribuciones.map(d=>({nature:d.categoria.naturaleza as EconomicNature,amount:n(d.monto)}))})));
 }
 async catalogs(user:AuthUser){const global=user.permissions.includes('reportes.global.read');const [users,notarias]=await Promise.all([this.db.user.findMany({where:{activo:true,...(!global?{id:user.id}:{})},select:{id:true,nombre:true,apellido:true,rol:true},orderBy:{nombre:'asc'}}),this.db.notaria.findMany({where:{activa:true,archived_at:null},select:{id:true,nombre:true,numero_notaria:true},orderBy:{nombre:'asc'}})]);return{usuarios:users,notarias,scope:{global,financial:user.permissions.includes('reportes.financial.read'),targetsManage:user.permissions.includes('reportes.targets.manage')}};}
 async createTarget(user:AuthUser,input:TargetInput){
  if(!user.permissions.includes('reportes.targets.manage'))throw new Error('No tienes autorización para configurar metas.');
  const alcance=input.alcance==='ABOGADO'?'ABOGADO':'DESPACHO',usuarioId=alcance==='ABOGADO'?String(input.usuario_id||''):null,from=new Date(`${input.periodo_inicio||''}T00:00:00`),to=new Date(`${input.periodo_fin||''}T23:59:59.999`),amount=n(input.importe),base=input.base==='COBRADOS'?'COBRADOS':'GENERADOS';
  if(Number.isNaN(from.getTime())||Number.isNaN(to.getTime())||from>to)throw new Error('La vigencia de la meta no es válida.');
  if(amount<=0)throw new Error('La meta debe ser mayor que cero.');
  if(alcance==='ABOGADO'&&!usuarioId)throw new Error('Selecciona el abogado de la meta.');
  return this.db.metaHonorario.create({data:{alcance,usuario_id:usuarioId,periodo_inicio:from,periodo_fin:to,importe:amount,moneda:String(input.moneda||'MXN').slice(0,3),base,creada_por_id:user.id},include:{usuario:{select:{id:true,nombre:true,apellido:true}}}});
 }
 private ensureTargetManager(user:AuthUser){if(!user.permissions.includes('reportes.targets.manage'))throw new Error('No tienes autorización para configurar metas.');}
 async updateTarget(user:AuthUser,id:string,input:TargetInput){
  this.ensureTargetManager(user);const current=await this.db.metaHonorario.findUnique({where:{id}});if(!current)throw new Error('La meta no existe.');if(!current.activa)throw new Error('Una meta histórica cerrada no puede modificarse.');
  const from=input.periodo_inicio?new Date(`${input.periodo_inicio}T00:00:00`):current.periodo_inicio,to=input.periodo_fin?new Date(`${input.periodo_fin}T23:59:59.999`):current.periodo_fin,amount=input.importe===undefined?n(current.importe):n(input.importe),alcance=input.alcance==='ABOGADO'?'ABOGADO':input.alcance==='DESPACHO'?'DESPACHO':current.alcance,usuarioId=alcance==='ABOGADO'?String(input.usuario_id||current.usuario_id||''):null,base=input.base==='COBRADOS'?'COBRADOS':input.base==='GENERADOS'?'GENERADOS':current.base;
  if(Number.isNaN(from.getTime())||Number.isNaN(to.getTime())||from>to)throw new Error('La vigencia de la meta no es válida.');if(amount<=0)throw new Error('La meta debe ser mayor que cero.');if(alcance==='ABOGADO'&&!usuarioId)throw new Error('Selecciona el abogado de la meta.');
  return this.db.metaHonorario.update({where:{id},data:{alcance,usuario_id:usuarioId,periodo_inicio:from,periodo_fin:to,importe:amount,moneda:String(input.moneda||current.moneda).slice(0,3),base},include:{usuario:{select:{id:true,nombre:true,apellido:true}}}});
 }
 async closeTarget(user:AuthUser,id:string){this.ensureTargetManager(user);const current=await this.db.metaHonorario.findUnique({where:{id}});if(!current)throw new Error('La meta no existe.');if(!current.activa)return current;return this.db.metaHonorario.update({where:{id},data:{activa:false}});}
 async summary(user:AuthUser,query:ReportQuery){
  const ctx=this.context(user,query),expWhere=this.expedienteWhere(user,ctx),week=mondayWeek();
  const [financial,target,signatures,remaining,quotes,clients]=await Promise.all([
   this.canonicalFinancials(ctx),
   ctx.scope.financial?this.db.metaHonorario.findFirst({where:{activa:true,periodo_inicio:{lte:ctx.period.to},periodo_fin:{gte:ctx.period.from},...(ctx.scope.lawyerId?{alcance:'ABOGADO',usuario_id:ctx.scope.lawyerId}:{alcance:'DESPACHO'})},orderBy:{periodo_inicio:'desc'}}):null,
   this.db.expediente.count({where:{...expWhere,fecha_real_firma:{gte:ctx.period.from,lte:ctx.period.to}}}),
   this.db.expediente.findMany({where:{...expWhere,fecha_real_firma:null,fecha_estimada_firma:{gte:new Date(),lte:week.to}},select:{id:true,numero_pravia:true,fecha_estimada_firma:true,honorariosGenerados:{where:{estado:{not:'CANCELADO'}},select:{monto:true}}}}),
   this.db.cotizacion.findMany({where:{created_at:{gte:ctx.period.from,lte:ctx.period.to},...(ctx.scope.lawyerId?{user_id:ctx.scope.lawyerId}:{}),...(ctx.scope.notariaId?{notaria_id:ctx.scope.notariaId}:{})},select:{id:true,total_cliente:true,fecha_aceptacion_cliente:true}}),
   this.db.prospecto.count({where:{archived_at:null,cotizacion:{is:{fecha_aceptacion_cliente:{gte:ctx.period.from,lte:ctx.period.to},...(ctx.scope.lawyerId?{user_id:ctx.scope.lawyerId}:{}),...(ctx.scope.notariaId?{notaria_id:ctx.scope.notariaId}:{})}}}}),
  ]);
  const goal=financial&&target?targetProgress({amount:n(target.importe),base:target.base},financial):null;
  return{period:ctx.period,scope:ctx.scope,financial,goal,operations:{firmas_realizadas:signatures,firmas_restantes_semana:remaining.length,honorarios_programados_semana:remaining.reduce((s,x)=>s+x.honorariosGenerados.reduce((a,h)=>a+n(h.monto),0),0),presupuestos_solicitados:quotes.length,importe_cotizado:quotes.reduce((s,x)=>s+n(x.total_cliente),0),presupuestos_aceptados:quotes.filter(x=>x.fecha_aceptacion_cliente).length,clientes_generados:clients},alerts:{firmas_defectuosas:{available:false,label:'Pendiente de definir con operación'}},definitions:{programado:'Honorarios de firmas pendientes desde hoy hasta el domingo.',clientes:'Prospectos con cotización aceptada en el periodo.'}};
 }
 async finance(user:AuthUser,query:ReportQuery){const ctx=this.context(user,query);if(!ctx.scope.financial)return{period:ctx.period,scope:ctx.scope,restricted:true};const financial=await this.canonicalFinancials(ctx);const months:Array<{periodo:string;generados:number;cobrados:number}>=[];for(let i=5;i>=0;i--){const from=new Date(ctx.period.to.getFullYear(),ctx.period.to.getMonth()-i,1),to=new Date(ctx.period.to.getFullYear(),ctx.period.to.getMonth()-i+1,0,23,59,59,999);const sub={...ctx,period:{...ctx.period,from,to}};const totals=await this.canonicalFinancials(sub);months.push({periodo:`${from.getFullYear()}-${String(from.getMonth()+1).padStart(2,'0')}`,generados:totals?.honorarios_generados||0,cobrados:totals?.honorarios_cobrados||0});}return{period:ctx.period,scope:ctx.scope,financial,tendency:months};}
 private async receivableRows(user:AuthUser,ctx:ReturnType<ReportingService['context']>){const records=await this.db.honorarioGenerado.findMany({where:this.feeWhere(ctx,{to:ctx.period.to}),select:{id:true,monto:true,fecha_reconocimiento:true,fecha_vencimiento:true,expediente:{select:{id:true,numero_pravia:true,cliente_alias:true,abogado:{select:{id:true,nombre:true,apellido:true}},notaria:{select:{id:true,nombre:true}}}},cotizacion:{select:{numero_cotizacion:true,prospecto:{select:{nombre:true}}}},responsable:{select:{id:true,nombre:true,apellido:true}},notaria:{select:{id:true,nombre:true}},distribuciones:{where:{movimiento:{estatus:{in:applied as any},naturaleza:'INGRESO',fecha_movimiento:{lte:ctx.period.to}}},select:{monto:true}}},orderBy:{fecha_reconocimiento:'desc'}});return records.map(x=>{const generated=n(x.monto),collected=x.distribuciones.reduce((s,d)=>s+n(d.monto),0);return{id:x.id,expediente_id:x.expediente?.id,expediente:x.expediente?.numero_pravia||x.cotizacion.numero_cotizacion||'Cotización',cliente:x.expediente?.cliente_alias||x.cotizacion.prospecto?.nombre||'Sin cliente',abogado_id:x.responsable?.id||x.expediente?.abogado.id||'SIN_RESPONSABLE',abogado:person(x.responsable||x.expediente?.abogado),notaria_id:x.notaria?.id||x.expediente?.notaria?.id||'SIN_NOTARIA',notaria:x.notaria?.nombre||x.expediente?.notaria?.nombre||'Sin notaría',generated,collected,pending:Math.max(0,generated-collected),due:x.fecha_vencimiento,link:x.expediente?`/expedientes/${x.expediente.id}`:`/cotizaciones`};}).filter(x=>x.pending>0);}
 async collections(user:AuthUser,query:ReportQuery){const ctx=this.context(user,query);if(!ctx.scope.financial)return{period:ctx.period,scope:ctx.scope,restricted:true};const rows=await this.receivableRows(user,ctx),group=(key:'abogado'|'notaria',idKey:'abogado_id'|'notaria_id')=>[...rows.reduce((m,x)=>{const id=x[idKey],old=m.get(id)||{id,nombre:x[key],generated:0,collected:0,pending:0,expedientes:0};old.generated+=x.generated;old.collected+=x.collected;old.pending+=x.pending;old.expedientes++;m.set(id,old);return m;},new Map<string,any>()).values()].map(x=>({...x,porcentaje_cobrado:x.generated?Math.round(x.collected/x.generated*1000)/10:0})).sort((a,b)=>b.pending-a.pending);return{period:ctx.period,scope:ctx.scope,totals:{generated:rows.reduce((s,x)=>s+x.generated,0),collected:rows.reduce((s,x)=>s+x.collected,0),pending:rows.reduce((s,x)=>s+x.pending,0),overdue:rows.filter(x=>x.due&&new Date(x.due)<ctx.period.to).reduce((s,x)=>s+x.pending,0)},byLawyer:group('abogado','abogado_id'),byNotaria:group('notaria','notaria_id'),rows};}
 async lawyers(user:AuthUser,query:ReportQuery){const ctx=this.context(user,query),year=ctx.period.to.getFullYear(),nextFrom=new Date(ctx.period.to.getFullYear(),ctx.period.to.getMonth()+1,1),nextTo=new Date(ctx.period.to.getFullYear(),ctx.period.to.getMonth()+2,0,23,59,59,999);const exps=await this.db.expediente.findMany({where:{...this.expedienteWhere(user,ctx),fecha_apertura:{gte:new Date(year,0,1),lte:new Date(year,11,31,23,59,59,999)}},select:{id:true,numero_pravia:true,fecha_estimada_firma:true,abogado:{select:{id:true,nombre:true,apellido:true}},honorariosGenerados:{where:{estado:{not:'CANCELADO'}},select:{monto:true}}}});const map=new Map<string,any>();for(const x of exps){const current=map.get(x.abogado.id)||{id:x.abogado.id,nombre:person(x.abogado),expedientes_ano:0,honorarios_generados:0,firmas_proximo_mes:0,honorarios_proximo_mes:0};const fees=x.honorariosGenerados.reduce((s,h)=>s+n(h.monto),0);current.expedientes_ano++;current.honorarios_generados+=fees;if(x.fecha_estimada_firma&&x.fecha_estimada_firma>=nextFrom&&x.fecha_estimada_firma<=nextTo){current.firmas_proximo_mes++;current.honorarios_proximo_mes+=fees;}map.set(x.abogado.id,current);}return{period:ctx.period,scope:ctx.scope,year,rows:[...map.values()].sort((a,b)=>b.honorarios_generados-a.honorarios_generados)};}
 async signatures(user:AuthUser,query:ReportQuery){const ctx=this.context(user,query),where=this.expedienteWhere(user,ctx),week=mondayWeek(ctx.period.to),previous={from:new Date(week.from.getTime()-7*86400000),to:new Date(week.to.getTime()-7*86400000)},rows=await this.db.expediente.findMany({where:{...where,OR:[{fecha_estimada_firma:{gte:new Date(Math.min(previous.from.getTime(),ctx.period.from.getTime())),lte:new Date(Math.max(week.to.getTime(),ctx.period.to.getTime()))}},{fecha_real_firma:{gte:new Date(Math.min(previous.from.getTime(),ctx.period.from.getTime())),lte:new Date(Math.max(week.to.getTime(),ctx.period.to.getTime()))}}]},select:{id:true,numero_pravia:true,cliente_alias:true,fecha_estimada_firma:true,fecha_real_firma:true,abogado:{select:{id:true,nombre:true,apellido:true}},honorariosGenerados:{where:{estado:{not:'CANCELADO'}},select:{monto:true}}}});const inRange=(d:Date|null,a:Date,b:Date)=>Boolean(d&&d>=a&&d<=b),fees=(x:any)=>x.honorariosGenerados.reduce((s:number,h:any)=>s+n(h.monto),0);return{period:ctx.period,scope:ctx.scope,metrics:{realizadas_mes:rows.filter(x=>inRange(x.fecha_real_firma,ctx.period.from,ctx.period.to)).length,realizadas_semana_anterior:rows.filter(x=>inRange(x.fecha_real_firma,previous.from,previous.to)).length,realizadas_semana_actual:rows.filter(x=>inRange(x.fecha_real_firma,week.from,week.to)).length,pendientes_semana_actual:rows.filter(x=>!x.fecha_real_firma&&inRange(x.fecha_estimada_firma,week.from,week.to)).length,programadas_mes:rows.filter(x=>!x.fecha_real_firma&&inRange(x.fecha_estimada_firma,ctx.period.from,ctx.period.to)).length,valor_programado_semana:rows.filter(x=>!x.fecha_real_firma&&inRange(x.fecha_estimada_firma,week.from,week.to)).reduce((s,x)=>s+fees(x),0),monto_programado_mes:rows.filter(x=>!x.fecha_real_firma&&inRange(x.fecha_estimada_firma,ctx.period.from,ctx.period.to)).reduce((s,x)=>s+fees(x),0),honorarios_firmados_mes:rows.filter(x=>inRange(x.fecha_real_firma,ctx.period.from,ctx.period.to)).reduce((s,x)=>s+fees(x),0)},defective:{available:false,label:'Pendiente de definir con operación'},rows:rows.map(x=>({...x,honorarios:fees(x),abogado:person(x.abogado),link:`/expedientes/${x.id}`}))};}
 async eightyTwenty(user:AuthUser,query:ReportQuery){const ctx=this.context(user,query);if(!ctx.scope.financial)return{period:ctx.period,scope:ctx.scope,restricted:true};const movements=await this.db.movimientoFinanciero.findMany({where:{...this.movementWhere(ctx),tipo_movimiento:'ANTICIPO',OR:[{expediente_id:{not:null}},{cotizacion_id:{not:null}}]},select:{monto:true,fecha_movimiento:true,expediente:{select:{id:true,numero_pravia:true,cliente_alias:true,fecha_estimada_firma:true,abogado:{select:{nombre:true,apellido:true}},notaria:{select:{nombre:true}},honorariosGenerados:{where:{estado:{not:'CANCELADO'}},select:{monto:true}}}},cotizacion:{select:{id:true,numero_cotizacion:true,prospecto:{select:{nombre:true}},honorariosGenerados:{select:{monto:true}},expediente:{select:{id:true,numero_pravia:true,fecha_estimada_firma:true,abogado:{select:{nombre:true,apellido:true}},notaria:{select:{nombre:true}}}}}}},orderBy:{fecha_movimiento:'desc'}});const map=new Map<string,any>();for(const m of movements){const exp=m.expediente||m.cotizacion?.expediente,key=exp?.id||m.cotizacion?.id;if(!key)continue;const fees=feeRows(m.expediente?.honorariosGenerados||m.cotizacion?.honorariosGenerados).reduce((s,h)=>s+n(h.monto),0),old=map.get(key)||{id:key,expediente:exp?.numero_pravia||m.cotizacion?.numero_cotizacion,cliente:m.expediente?.cliente_alias||m.cotizacion?.prospecto?.nombre||'Sin cliente',honorarios:fees,anticipo:0,fecha_firma:exp?.fecha_estimada_firma,notaria:exp?.notaria?.nombre||'Sin notaría',abogado:person(exp?.abogado),link:exp?`/expedientes/${exp.id}`:`/cotizaciones/${m.cotizacion?.id}`};old.anticipo+=n(m.monto);old.pending=Math.max(0,old.honorarios-old.anticipo);map.set(key,old);}return{period:ctx.period,scope:ctx.scope,definition:'Expedientes con anticipo recibido y pendientes de seguimiento/firma.',rows:[...map.values()].sort((a,b)=>b.honorarios-a.honorarios)};}
 async potentialClients(user:AuthUser,query:ReportQuery){const ctx=this.context(user,query),quotes=await this.db.cotizacion.findMany({where:{created_at:{lte:ctx.period.to},estado:{notIn:['RECHAZADA','VENCIDA']},...(ctx.scope.lawyerId?{user_id:ctx.scope.lawyerId}:{}),...(ctx.scope.notariaId?{notaria_id:ctx.scope.notariaId}:{})},select:{id:true,numero_cotizacion:true,created_at:true,honorarios_pravia:true,prospecto:{select:{id:true,nombre:true,tipo_acto:true}},creada_por:{select:{nombre:true,apellido:true}},notaria:{select:{nombre:true}},expediente:{select:{id:true,movimientosFinancieros:{where:{tipo_movimiento:'ANTICIPO',estatus:{in:applied as any}},select:{id:true},take:1}}},movimientosFinancieros:{where:{tipo_movimiento:'ANTICIPO',estatus:{in:applied as any}},select:{id:true},take:1},seguimientos:{orderBy:{created_at:'desc'},select:{created_at:true},take:1}},orderBy:{created_at:'desc'}});return{period:ctx.period,scope:ctx.scope,definition:'Cotizaciones existentes sin anticipo financiero aplicado.',rows:quotes.filter(x=>!x.movimientosFinancieros.length&&!x.expediente?.movimientosFinancieros.length).map(x=>({id:x.id,cliente:x.prospecto?.nombre||'Sin cliente',honorarios:n(x.honorarios_pravia),notaria:x.notaria?.nombre||'Sin notaría',responsable:person(x.creada_por),acto:x.prospecto?.tipo_acto||'Sin acto',fecha_cotizacion:x.created_at,ultimo_seguimiento:x.seguimientos[0]?.created_at||null,dias_sin_anticipo:Math.max(0,Math.floor((ctx.period.to.getTime()-x.created_at.getTime())/86400000)),link:`/cotizaciones/${x.id}`}))};}
}
