import { describe, expect, it, vi } from 'vitest';
import { ReportingService } from './reporting.service';

const user=(role='DIRECCION',permissions=['reportes.read','reportes.global.read','reportes.financial.read'])=>({id:'user-1',rol:role,permissions,sessionId:'s1',email:'test@pravia.mx',nombre:'Ana',apellido:'Prueba',requiresPasswordChange:false} as any);
const database=()=>({
  honorarioGenerado:{findMany:vi.fn().mockResolvedValue([])},movimientoFinanciero:{findMany:vi.fn().mockResolvedValue([])},metaHonorario:{findFirst:vi.fn().mockResolvedValue(null),findUnique:vi.fn().mockResolvedValue(null),create:vi.fn().mockResolvedValue({id:'meta-1'}),update:vi.fn().mockResolvedValue({id:'meta-1',activa:false})},expediente:{count:vi.fn().mockResolvedValue(0),findMany:vi.fn().mockResolvedValue([])},cotizacion:{findMany:vi.fn().mockResolvedValue([])},prospecto:{count:vi.fn().mockResolvedValue(0)},user:{findMany:vi.fn().mockResolvedValue([])},notaria:{findMany:vi.fn().mockResolvedValue([])},
} as any);

describe('ReportingService',()=>{
 it('impone scope propio al abogado y no acepta ampliar abogado_id',()=>{const service=new ReportingService(database());const ctx=service.context(user('ABOGADO',['reportes.read','reportes.financial.read']),{abogado_id:'otro'});expect(ctx.scope).toMatchObject({mode:'PROPIO',lawyerId:'user-1',financial:true});});
 it('mantiene al usuario operativo sin importes si no tiene permiso financiero',async()=>{const db=database(),service=new ReportingService(db);const result=await service.finance(user('CONSULTA',['reportes.read']),{});expect(result).toMatchObject({restricted:true,scope:{mode:'OPERATIVO',financial:false}});expect(db.honorarioGenerado.findMany).not.toHaveBeenCalled();});
 it('construye cartera por abogado y notaría sin contar dos veces un reconocimiento',async()=>{const db=database();db.honorarioGenerado.findMany.mockResolvedValue([
   {id:'h1',monto:100000,fecha_reconocimiento:new Date(),fecha_vencimiento:new Date('2026-01-01'),expediente:{id:'e1',numero_pravia:'EXP-1',cliente_alias:'Cliente A',abogado:{id:'u1',nombre:'Ana',apellido:'Ruiz'},notaria:{id:'n1',nombre:'Notaría 1'}},cotizacion:{numero_cotizacion:'COT-1',prospecto:{nombre:'Cliente A'}},responsable:{id:'u1',nombre:'Ana',apellido:'Ruiz'},notaria:{id:'n1',nombre:'Notaría 1'},distribuciones:[{monto:40000}]},
   {id:'h2',monto:50000,fecha_reconocimiento:new Date(),fecha_vencimiento:null,expediente:{id:'e2',numero_pravia:'EXP-2',cliente_alias:'Cliente B',abogado:{id:'u1',nombre:'Ana',apellido:'Ruiz'},notaria:{id:'n1',nombre:'Notaría 1'}},cotizacion:{numero_cotizacion:'COT-2',prospecto:{nombre:'Cliente B'}},responsable:{id:'u1',nombre:'Ana',apellido:'Ruiz'},notaria:{id:'n1',nombre:'Notaría 1'},distribuciones:[]},
  ]);const result=await new ReportingService(db).collections(user(),{periodo:'ESTE_ANO'});expect(result.totals).toMatchObject({generated:150000,collected:40000,pending:110000});expect(result.byLawyer).toEqual([expect.objectContaining({nombre:'Ana Ruiz',expedientes:2,generated:150000,pending:110000})]);expect(result.byNotaria).toEqual([expect.objectContaining({nombre:'Notaría 1',expedientes:2,pending:110000})]);});
 it('reporta expedientes abiertos del año y usa honorarios, no valor de operación',async()=>{const db=database();db.expediente.findMany.mockResolvedValue([{id:'e1',numero_pravia:'EXP-1',fecha_estimada_firma:new Date(new Date().getFullYear(),new Date().getMonth()+1,10),abogado:{id:'u1',nombre:'Ana',apellido:'Ruiz'},honorariosGenerados:[{monto:90000}]}]);const result=await new ReportingService(db).lawyers(user(),{});expect(result.rows[0]).toMatchObject({expedientes_ano:1,honorarios_generados:90000,firmas_proximo_mes:1,honorarios_proximo_mes:90000});expect(db.expediente.findMany).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({fecha_apertura:expect.any(Object)})}));});
 it('separa firmas reales de pendientes programadas y sus honorarios',async()=>{const db=database(),now=new Date(),real=new Date(now.getFullYear(),now.getMonth(),Math.max(1,now.getDate()-1));db.expediente.findMany.mockResolvedValue([{id:'e1',numero_pravia:'EXP-1',cliente_alias:'A',fecha_estimada_firma:real,fecha_real_firma:real,abogado:{id:'u1',nombre:'Ana',apellido:'Ruiz'},honorariosGenerados:[{monto:100000}]},{id:'e2',numero_pravia:'EXP-2',cliente_alias:'B',fecha_estimada_firma:now,fecha_real_firma:null,abogado:{id:'u1',nombre:'Ana',apellido:'Ruiz'},honorariosGenerados:[{monto:50000}]}]);const result=await new ReportingService(db).signatures(user(),{});expect(result.metrics.realizadas_mes).toBe(1);expect(result.metrics.programadas_mes).toBe(1);expect(result.metrics.honorarios_firmados_mes).toBe(100000);expect(result.defective).toMatchObject({available:false});});
 it('80/20 exige anticipo aplicado y ordena por honorarios descendentes',async()=>{const db=database();db.movimientoFinanciero.findMany.mockResolvedValue([{monto:40000,fecha_movimiento:new Date(),expediente:{id:'e1',numero_pravia:'EXP-1',cliente_alias:'A',fecha_estimada_firma:null,abogado:{nombre:'Ana',apellido:'Ruiz'},notaria:{nombre:'Notaría 1'},honorariosGenerados:[{monto:120000}]},cotizacion:null},{monto:20000,fecha_movimiento:new Date(),expediente:{id:'e2',numero_pravia:'EXP-2',cliente_alias:'B',fecha_estimada_firma:null,abogado:{nombre:'Luis',apellido:'Paz'},notaria:{nombre:'Notaría 2'},honorariosGenerados:[{monto:80000}]},cotizacion:null}]);const result=await new ReportingService(db).eightyTwenty(user(),{});expect(result.rows?.map(x=>x.expediente)).toEqual(['EXP-1','EXP-2']);expect(result.rows?.[0]).toMatchObject({honorarios:120000,anticipo:40000,pending:80000});expect(db.movimientoFinanciero.findMany).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({tipo_movimiento:'ANTICIPO'})}));});
 it('clientes potenciales excluye cotizaciones con anticipo aplicado',async()=>{const db=database();db.cotizacion.findMany.mockResolvedValue([{id:'q1',numero_cotizacion:'COT-1',created_at:new Date('2026-08-01'),honorarios_pravia:75000,prospecto:{id:'p1',nombre:'Cliente pendiente',tipo_acto:'Compraventa'},creada_por:{nombre:'Ana',apellido:'Ruiz'},notaria:{nombre:'Notaría 1'},expediente:null,movimientosFinancieros:[],seguimientos:[]},{id:'q2',numero_cotizacion:'COT-2',created_at:new Date('2026-08-01'),honorarios_pravia:50000,prospecto:{id:'p2',nombre:'Cliente con anticipo',tipo_acto:'Poder'},creada_por:{nombre:'Ana',apellido:'Ruiz'},notaria:{nombre:'Notaría 1'},expediente:null,movimientosFinancieros:[{id:'m1'}],seguimientos:[]}]);const result=await new ReportingService(db).potentialClients(user(),{periodo:'PERSONALIZADO',fecha_desde:'2026-08-01',fecha_hasta:'2026-08-31'});expect(result.rows).toHaveLength(1);expect(result.rows[0]).toMatchObject({cliente:'Cliente pendiente',honorarios:75000});});
 it('crea metas históricas sólo con permiso administrativo y base explícita',async()=>{const db=database(),service=new ReportingService(db);await expect(service.createTarget(user('ABOGADO',['reportes.read']),{periodo_inicio:'2026-08-01',periodo_fin:'2026-08-31',importe:100000})).rejects.toThrow('autorización');const result=await service.createTarget(user('DIRECCION',['reportes.read','reportes.targets.manage']),{alcance:'ABOGADO',usuario_id:'u1',periodo_inicio:'2026-08-01',periodo_fin:'2026-08-31',importe:100000,base:'COBRADOS'});expect(result).toMatchObject({id:'meta-1'});expect(db.metaHonorario.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({alcance:'ABOGADO',usuario_id:'u1',importe:100000,base:'COBRADOS',creada_por_id:'user-1'})}));});
 it('revalida permiso al modificar y cerrar metas sin reescribir metas históricas cerradas',async()=>{const db=database(),service=new ReportingService(db),manager=user('DIRECCION',['reportes.read','reportes.targets.manage']);await expect(service.updateTarget(user('CONSULTA',['reportes.read']),'meta-1',{importe:2})).rejects.toThrow('autorización');await expect(service.closeTarget(user('CONSULTA',['reportes.read']),'meta-1')).rejects.toThrow('autorización');const active={id:'meta-1',activa:true,alcance:'DESPACHO',usuario_id:null,periodo_inicio:new Date('2026-08-01'),periodo_fin:new Date('2026-08-31'),importe:100000,moneda:'MXN',base:'GENERADOS'};db.metaHonorario.findUnique.mockResolvedValue(active);await service.updateTarget(manager,'meta-1',{importe:120000});expect(db.metaHonorario.update).toHaveBeenCalledWith(expect.objectContaining({where:{id:'meta-1'},data:expect.objectContaining({importe:120000})}));await service.closeTarget(manager,'meta-1');expect(db.metaHonorario.update).toHaveBeenLastCalledWith({where:{id:'meta-1'},data:{activa:false}});db.metaHonorario.findUnique.mockResolvedValue({...active,activa:false});await expect(service.updateTarget(manager,'meta-1',{importe:130000})).rejects.toThrow('histórica cerrada');});
});
