import { Plus, Power, TrendingUp } from 'lucide-react';
import { useState } from 'react';
import type { FinanceSummary, RecurringExpense } from '../finance.types';
import { financeDate, money } from '../finance.utils';
import { financeService } from '../finance.service';
import styles from '../Finance.module.css';

export function FinanceProjectionView({summary,expenses,canWrite,onChanged}:{summary:FinanceSummary;expenses:RecurringExpense[];canWrite:boolean;onChanged:()=>void}) {
  const [open,setOpen]=useState(false); const [error,setError]=useState(''); const [saving,setSaving]=useState(false);
  const [draft,setDraft]=useState({concepto:'',monto:'',fecha_inicio:new Date().toISOString().slice(0,10),fecha_fin:''});
  const max=Math.max(...summary.projection.months.flatMap(row=>[row.fees,row.otherIncome,row.expenses]),1);
  const submit=async()=>{setSaving(true);setError('');try{await financeService.createRecurringExpense({...draft,monto:Number(draft.monto),periodicidad:'MENSUAL'});setOpen(false);setDraft({...draft,concepto:'',monto:'',fecha_fin:''});onChanged();}catch(e){setError(e instanceof Error?e.message:'No pudimos guardar.');}finally{setSaving(false);}};
  return <div className={styles.projectionLayout}><section className={styles.projectionCard}><header><div><h2>Proyección financiera</h2><p>Honorarios pendientes por firma, otros ingresos y egresos previstos.</p></div><TrendingUp size={20}/></header>{summary.projection.months.length?<div className={styles.projectionRows}>{summary.projection.months.map(row=><div key={row.period}><strong>{new Intl.DateTimeFormat('es-MX',{month:'long',year:'numeric'}).format(new Date(`${row.period}-02T12:00:00`))}</strong><span><i data-series="fees" style={{width:`${row.fees/max*100}%`}}/><b>Honorarios {money(row.fees)}</b></span><span><i data-series="income" style={{width:`${row.otherIncome/max*100}%`}}/><b>Otros ingresos {money(row.otherIncome)}</b></span><span><i data-series="expense" style={{width:`${row.expenses/max*100}%`}}/><b>Egresos {money(row.expenses)}</b></span></div>)}</div>:<div className={styles.compactEmpty}>NO HAY MOVIMIENTOS PARA ESTE PERIODO</div>}<footer><span>Honorarios sin fecha de firma</span><b>{money(summary.projection.noDate.fees)}</b></footer></section><section className={styles.recurringCard}><header><div><h2>Gastos fijos y recurrentes</h2><p>Sólo los activos alimentan la proyección.</p></div>{canWrite&&<button type="button" onClick={()=>setOpen(value=>!value)}><Plus size={15}/>Agregar</button>}</header>{open&&<div className={styles.recurringForm}><label>Concepto<input value={draft.concepto} onChange={e=>setDraft({...draft,concepto:e.target.value})}/></label><label>Importe mensual<input type="number" min="0.01" step="0.01" value={draft.monto} onChange={e=>setDraft({...draft,monto:e.target.value})}/></label><label>Desde<input type="date" value={draft.fecha_inicio} onChange={e=>setDraft({...draft,fecha_inicio:e.target.value})}/></label><label>Hasta (opcional)<input type="date" value={draft.fecha_fin} onChange={e=>setDraft({...draft,fecha_fin:e.target.value})}/></label>{error&&<p role="alert">{error}</p>}<button type="button" disabled={saving||!draft.concepto||!draft.monto} onClick={submit}>{saving?'Guardando…':'Guardar gasto recurrente'}</button></div>}<div className={styles.recurringList}>{expenses.map(item=><article key={item.id}><span data-active={item.activo}><Power size={14}/></span><p><strong>{item.concepto}</strong><small>{item.periodicidad.toLocaleLowerCase('es-MX')} · desde {financeDate(item.fecha_inicio)}{item.fecha_fin?` hasta ${financeDate(item.fecha_fin)}`:''}</small></p><b>{money(item.monto)}</b>{canWrite&&<button type="button" onClick={async()=>{await financeService.updateRecurringExpense(item.id,{activo:!item.activo});onChanged();}}>{item.activo?'Desactivar':'Activar'}</button>}</article>)}</div>{!expenses.length&&!open&&<div className={styles.compactEmpty}>No hay gastos recurrentes configurados.</div>}</section></div>;
}
