import { AlertTriangle, ArrowLeft, ArrowRight, Check, LoaderCircle, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { notariasService } from '../notarias.service';
import type { NotariaDetail, NotariaDraft } from '../notarias.types';
import styles from '../Notarias.module.css';

const empty: NotariaDraft = { numero_notaria:'',nombre:'',notario_titular:'',entidad_federativa:'',municipio:'',ciudad:'',demarcacion:'',direccion:'',codigo_postal:'',telefono:'',whatsapp:'',correo_general:'',correo_proyectos:'',activa:true };
const fromDetail = (item?: NotariaDetail): NotariaDraft => item ? { numero_notaria:item.numero_notaria||'',nombre:item.nombre,notario_titular:item.titular||'',entidad_federativa:item.entidad_federativa||'',municipio:item.municipio||'',ciudad:item.ciudad||'',demarcacion:item.demarcacion||'',direccion:item.direccion||'',codigo_postal:item.codigo_postal||'',telefono:item.telefono||'',whatsapp:item.whatsapp||'',correo_general:item.correo_general||'',correo_proyectos:item.correo_proyectos||'',activa:item.activa } : empty;
const steps = ['Identificación','Ubicación','Contacto','Revisión'];

export function NewNotariaFlow({ initial, onClose, onSaved }: { initial?: NotariaDetail; onClose():void; onSaved(id:string):void }) {
  const [step,setStep]=useState(0); const [draft,setDraft]=useState<NotariaDraft>(()=>fromDetail(initial)); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const title=initial?'Editar notaría':'Nueva notaría'; const set=(field:keyof NotariaDraft,value:string|boolean)=>setDraft((current)=>({...current,[field]:value}));
  const valid=useMemo(()=>step===0?Boolean(draft.nombre.trim()&&draft.entidad_federativa.trim()):step===1?Boolean(draft.municipio.trim()):true,[draft,step]);
  const save=async()=>{setBusy(true);setError('');try{const result=initial?await notariasService.update(initial.id,draft):await notariasService.create(draft);onSaved(result.id);}catch(err){setError(err instanceof Error?err.message:'No pudimos guardar la notaría.');setBusy(false);}};
  return <div className={styles.drawerBackdrop} role="presentation"><section className={styles.drawer} role="dialog" aria-modal="true" aria-labelledby="notaria-flow-title"><header className={styles.drawerHeader}><div><span>{initial?'Actualización de directorio':'Registro de notaría'}</span><h2 id="notaria-flow-title">{title}</h2><p>Captura únicamente información confirmada de la oficina notarial.</p></div><button type="button" aria-label="Cerrar" onClick={onClose}><X/></button></header><div className={styles.drawerBody}><ol className={styles.stepper}>{steps.map((label,index)=><li key={label} className={index===step?styles.stepCurrent:index<step?styles.stepDone:''}><span>{index<step?<Check size={14}/>:index+1}</span><b>{label}</b></li>)}</ol>{error&&<div className={styles.formError} role="alert"><AlertTriangle size={16}/>{error}</div>}
    {step===0&&<fieldset className={styles.flowStep}><legend>Identificación</legend><p>El número se valida junto con la entidad federativa y la demarcación.</p><div className={styles.formGrid}><label className={styles.formField}><span>Número de notaría</span><input value={draft.numero_notaria} onChange={(e)=>set('numero_notaria',e.target.value)} placeholder="Ej. 12" /></label><label className={styles.formField}><span>Denominación *</span><input required value={draft.nombre} onChange={(e)=>set('nombre',e.target.value)} placeholder="Nombre registrado de la notaría" /></label><label className={`${styles.formField} ${styles.fieldWide}`}><span>Titular</span><input value={draft.notario_titular} onChange={(e)=>set('notario_titular',e.target.value)} placeholder="Nombre completo, sin inventar tratamiento" /></label><label className={styles.formField}><span>Entidad federativa *</span><input required value={draft.entidad_federativa} onChange={(e)=>set('entidad_federativa',e.target.value)} placeholder="Ej. Nayarit" /></label><label className={styles.formField}><span>Demarcación o distrito</span><input value={draft.demarcacion} onChange={(e)=>set('demarcacion',e.target.value)} /></label></div></fieldset>}
    {step===1&&<fieldset className={styles.flowStep}><legend>Ubicación</legend><p>Usa la ciudad o municipio que conste en el directorio de la notaría.</p><div className={styles.formGrid}><label className={styles.formField}><span>Municipio *</span><input required value={draft.municipio} onChange={(e)=>set('municipio',e.target.value)} /></label><label className={styles.formField}><span>Ciudad</span><input value={draft.ciudad} onChange={(e)=>set('ciudad',e.target.value)} /></label><label className={`${styles.formField} ${styles.fieldWide}`}><span>Domicilio</span><input value={draft.direccion} onChange={(e)=>set('direccion',e.target.value)} placeholder="Calle, número y colonia" /></label><label className={styles.formField}><span>Código postal</span><input value={draft.codigo_postal} onChange={(e)=>set('codigo_postal',e.target.value)} inputMode="numeric" /></label></div></fieldset>}
    {step===2&&<fieldset className={styles.flowStep}><legend>Contacto</legend><p>Estos canales se mostrarán como contacto general de la notaría.</p><div className={styles.formGrid}><label className={styles.formField}><span>Teléfono</span><input value={draft.telefono} onChange={(e)=>set('telefono',e.target.value)} inputMode="tel" /></label><label className={styles.formField}><span>WhatsApp</span><input value={draft.whatsapp} onChange={(e)=>set('whatsapp',e.target.value)} inputMode="tel" /></label><label className={styles.formField}><span>Correo general</span><input value={draft.correo_general} onChange={(e)=>set('correo_general',e.target.value)} type="email" /></label><label className={styles.formField}><span>Correo de proyectos</span><input value={draft.correo_proyectos} onChange={(e)=>set('correo_proyectos',e.target.value)} type="email" /></label></div></fieldset>}
    {step===3&&<fieldset className={styles.flowStep}><legend>Revisión</legend><p>Confirma la identidad, ubicación y estado operativo antes de guardar.</p><dl className={styles.reviewList}><div><dt>Notaría</dt><dd>{draft.numero_notaria?`Notaría ${draft.numero_notaria}`:draft.nombre}</dd></div><div><dt>Denominación</dt><dd>{draft.nombre}</dd></div><div><dt>Titular</dt><dd>{draft.notario_titular||'Sin titular registrado'}</dd></div><div><dt>Ubicación</dt><dd>{[draft.ciudad||draft.municipio,draft.entidad_federativa].filter(Boolean).join(', ')}</dd></div><div><dt>Contacto</dt><dd>{draft.correo_general||draft.telefono||'Sin contacto general'}</dd></div></dl><label className={styles.statusToggle}><input type="checkbox" checked={draft.activa} onChange={(e)=>set('activa',e.target.checked)}/><span><strong>Notaría activa</strong><small>Disponible para nuevas operaciones</small></span></label></fieldset>}
  </div><footer className={styles.drawerFooter}>{step>0&&<button type="button" className={styles.secondaryButton} onClick={()=>setStep((value)=>value-1)}><ArrowLeft size={16}/>Anterior</button>}<span/>{step<steps.length-1?<button type="button" className={styles.primaryButton} disabled={!valid} onClick={()=>setStep((value)=>value+1)}>Siguiente<ArrowRight size={16}/></button>:<button type="button" className={styles.primaryButton} disabled={busy} onClick={()=>void save()}>{busy?<LoaderCircle className={styles.spin} size={16}/>:<Check size={16}/>}Guardar notaría</button>}</footer></section></div>;
}
