import { Router } from 'express';
import { ComplianceController } from '../controllers/compliance.controller';
import { requireExpedienteAccess, requirePermission } from '../middleware/auth.middleware';

const router = Router();
router.get('/catalogos', ComplianceController.catalogs);
router.get('/revisiones', ComplianceController.list);
router.get('/revisiones/:id', ComplianceController.detail);
router.post('/revisiones', requirePermission('compliance.write'), requireExpedienteAccess, ComplianceController.create);
router.post('/revisiones/:id/evaluar', requirePermission('compliance.write'), ComplianceController.evaluate);
router.post('/revisiones/:id/revisar', requirePermission('compliance.review'), ComplianceController.review);
router.post('/revisiones/:id/reevaluar', requirePermission('compliance.write'), ComplianceController.reevaluate);
router.post('/revisiones/:id/evidencias', requirePermission('compliance.write'), ComplianceController.addEvidence);
router.get('/revisiones/:id/evidencias/:evidenceId/archivo', requirePermission('compliance.sensitive.read'), ComplianceController.viewEvidence);
router.post('/revisiones/:id/evidencias/:evidenceId/retirar', requirePermission('compliance.write'), ComplianceController.retireEvidence);
router.post('/revisiones/:id/pagos', requirePermission('compliance.write'), ComplianceController.addPayment);
router.post('/revisiones/:id/beneficiarios-controladores', requirePermission('compliance.write'), requirePermission('compliance.sensitive.read'), ComplianceController.saveBeneficialOwner);
router.post('/revisiones/:id/pep', requirePermission('compliance.review'), requirePermission('compliance.sensitive.read'), ComplianceController.savePepReview);
router.post('/revisiones/:id/obligaciones/:obligationId/presentacion-externa', requirePermission('compliance.notice.confirm'), ComplianceController.confirmExternalNotice);
export default router;
