import { Router } from 'express';
import multer from 'multer';
import { ComplianceController } from '../controllers/compliance.controller';
import { requireExpedienteAccess, requirePermission } from '../middleware/auth.middleware';

const router = Router();
const signedUpload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 25 * 1024 * 1024, files: 1 } });
router.get('/expedientes/:expedienteId/documental', ComplianceController.documentStructure);
router.post('/expedientes/:expedienteId/documental/requisitos/:requirementId/evidencias', requirePermission('compliance.write'), requirePermission('documentos.read'), ComplianceController.linkDocumentEvidence);
router.post('/expedientes/:expedienteId/documental/requisitos/:requirementId/cargar-firmado', requirePermission('compliance.write'), requirePermission('documentos.write'), signedUpload.single('file'), ComplianceController.uploadSignedEvidence);
router.post('/expedientes/:expedienteId/documental/evidencias/:evidenceId/validar', requirePermission('compliance.review'), ComplianceController.validateDocumentEvidence);
router.get('/expedientes/:expedienteId/documental/exportar', requirePermission('documentos.read'), requirePermission('compliance.sensitive.read'), ComplianceController.exportDocumentPackage);
router.post('/configuracion/anticipacion-alertas', requirePermission('compliance.rules.manage'), ComplianceController.publishAlertLead);
router.post('/reglas-legales', requirePermission('compliance.rules.manage'), ComplianceController.createLegalRule);
router.post('/reglas-legales/:ruleId/revisiones', requirePermission('compliance.rules.manage'), ComplianceController.createLegalRuleRevision);
router.post('/reglas-legales/:ruleId/revisiones/:revisionId/verificar', requirePermission('compliance.rules.manage'), ComplianceController.verifyLegalRuleRevision);
router.post('/reglas-legales/:ruleId/revisiones/:revisionId/activar', requirePermission('compliance.rules.manage'), ComplianceController.activateLegalRuleRevision);
router.post('/expedientes/:expedienteId/evaluaciones-legales', requirePermission('compliance.write'), ComplianceController.evaluateLegalCase);
router.get('/expedientes/:expedienteId/estado', ComplianceController.legalCaseState);
router.get('/catalogos', ComplianceController.catalogs);
router.get('/revisiones', ComplianceController.list);
router.get('/revisiones/:id', ComplianceController.detail);
router.post('/revisiones', requirePermission('compliance.write'), requireExpedienteAccess, ComplianceController.create);
router.post('/revisiones/:id/evaluar', requirePermission('compliance.write'), ComplianceController.evaluate);
router.post('/revisiones/:id/revisar', requirePermission('compliance.review'), ComplianceController.review);
router.post('/revisiones/:id/reevaluar', requirePermission('compliance.write'), ComplianceController.reevaluate);
router.post('/revisiones/:id/evidencias', requirePermission('compliance.write'), ComplianceController.addEvidence);
router.get('/revisiones/:id/evidencias/:evidenceId/archivo', requirePermission('compliance.sensitive.read'), ComplianceController.viewEvidence);
router.post('/revisiones/:id/evidencias/:evidenceId/retirar', requirePermission('compliance.write'), ComplianceController.retireEvidence);
router.post('/revisiones/:id/pagos', requirePermission('compliance.write'), ComplianceController.addPayment);
router.post('/revisiones/:id/beneficiarios-controladores', requirePermission('compliance.write'), requirePermission('compliance.sensitive.read'), ComplianceController.saveBeneficialOwner);
router.post('/revisiones/:id/pep', requirePermission('compliance.review'), requirePermission('compliance.sensitive.read'), ComplianceController.savePepReview);
router.post('/revisiones/:id/obligaciones/:obligationId/presentacion-externa', requirePermission('compliance.notice.confirm'), ComplianceController.confirmExternalNotice);
export default router;
