import { AlertTriangle, CalendarClock, ChevronLeft, ChevronRight, CircleAlert, ClipboardCheck, Grid2X2, List, Plus, RefreshCw, Search, ShieldCheck, ShieldX } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useLocation, useNavigate, useSearchParams } from 'react-router-dom';
import { PageContainer } from '../../components/layout/PageContainer';
import { useAuth } from '../auth/AuthProvider';
import { settingsService } from '../settings/settings.service';
import { fixtureComplianceDirectory } from './compliance.fixtures';
import { complianceService } from './compliance.service';
import type { ComplianceCatalogs, ComplianceList, ComplianceReview } from './compliance.types';
import { NewReviewDialog } from './components/NewReviewDialog';
import styles from './Compliance.module.css';

const emptyList: ComplianceList = { revisiones: [], meta: { page: 1, pageSize: 12, total: 0, totalPages: 1 }, metrics: { expedientes_evaluados: 0, requieren_revision: 0, avisos_por_presentar: 0, obligaciones_vencidas: 0 } };
const emptyCatalogs: ComplianceCatalogs = { reglas: [], expedientes: [], usuarios: [], documentos: [] };
export const activityLabels: Record<string, string> = { TRANSMISION_DERECHOS_REALES_INMUEBLES: 'Derechos reales sobre inmuebles', PODER_IRREVOCABLE_ADMINISTRACION_DOMINIO: 'Poder irrevocable', CONSTITUCION_MODIFICACION_PERSONA_MORAL: 'Operación societaria', FIDEICOMISO_TRASLATIVO_GARANTIA: 'Fideicomiso traslativo o de garantía', MUTUO_CREDITO_NO_FINANCIERO: 'Mutuo o crédito' };
export const evaluationLabels: Record<string, string> = { SIN_EVALUAR: 'Sin evaluar', EN_REVISION: 'En revisión', INFORMACION_INCOMPLETA: 'Información incompleta', EVALUADO: 'Evaluado', REQUIERE_REVISION: 'Requiere revisión' };
export const noticeLabels: Record<string, string> = { NO_APLICA: 'No aplica', POR_DETERMINAR: 'Por determinar', REQUIERE_AVISO: 'Requiere Aviso', EN_PREPARACION: 'En preparación', PRESENTADO_EXTERNAMENTE: 'Presentado externamente', VENCIDO: 'Vencido' };

export function CompliancePage() {
  const { user } = useAuth(); const location = useLocation(); const navigate = useNavigate(); const [params, setParams] = useSearchParams();
  const fixture = import.meta.env.DEV && new URLSearchParams(location.search).get('fixture') === 'directory'; const localVisual = fixture && new URLSearchParams(location.search).get('visual') === '1';
  const [data, setData] = useState<ComplianceList>(fixture ? fixtureComplianceDirectory : emptyList); const [catalogs, setCatalogs] = useState<ComplianceCatalogs>(emptyCatalogs); const [status, setStatus] = useState<'loading'|'ready'|'error'>(fixture ? 'ready' : 'loading'); const [open, setOpen] = useState(false); const [view, setView] = useState<'cards'|'list'>('cards');
  const canRead = localVisual || Boolean(user?.permissions?.some((permission) => ['compliance.read', 'cumplimiento.read'].includes(permission))); const canWrite = localVisual || Boolean(user?.permissions?.some((permission) => ['compliance.write', 'cumplimiento.write'].includes(permission)));
  const filters = { search: params.get('search') || '', nivel: params.get('nivel') || '', actividad: params.get('actividad') || '', estado_aviso: params.get('estado_aviso') || '', notaria_id: params.get('notaria_id') || '', responsable_id: params.get('responsable_id') || '', desde: params.get('desde') || '', hasta: params.get('hasta') || '', page: params.get('page') || '1' };
  const load = useCallback(async (signal?: AbortSignal) => { if (!canRead || fixture) return; setStatus('loading'); try { const [list, cats] = await Promise.all([complianceService.list({ ...filters, page: Number(filters.page), tipo: 'UIF' }, signal), complianceService.catalogs(signal)]); setData(list); setCatalogs(cats); setStatus('ready'); } catch (error) { if (!(error instanceof DOMException && error.name === 'AbortError')) setStatus('error'); } }, [canRead, fixture, params.toString()]);
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort(); }, [load]);
  useEffect(() => { if (fixture) return; settingsService.preferences().then((payload) => setView(payload.preferences.default_view === 'LIST' ? 'list' : 'cards')).catch(() => undefined); }, [fixture]);
  const change = (key: string, value: string) => { const next = new URLSearchParams(params); value ? next.set(key, value) : next.delete(key); if (key !== 'page') next.delete('page'); setParams(next, { replace: true }); };
  const changeView = (next: 'cards'|'list') => { setView(next); if (!fixture && import.meta.env.VITE_DISABLE_PREFERENCE_WRITES !== 'true') void settingsService.updatePreferences({ default_view: next === 'list' ? 'LIST' : 'CARDS' }).catch(() => undefined); };
  const notaries = useMemo(() => Array.from(new Map(catalogs.expedientes.filter((item: any) => item.notaria?.id).map((item: any) => [item.notaria.id, item.notaria])).values()) as any[], [catalogs.expedientes]);
  if (!canRead) return <PageContainer title="Riesgos / UIF" subtitle="Control de cumplimiento, actividades vulnerables y obligaciones de aviso."><section className={styles.restricted}><ShieldX/><h2>Acceso restringido</h2><p>Tu rol no incluye permiso para consultar evaluaciones de cumplimiento.</p></section></PageContainer>;
  return <PageContainer title="Riesgos / UIF" subtitle="Control de cumplimiento, actividades vulnerables y obligaciones de aviso." action={canWrite ? <button className={styles.headerAction} type="button" onClick={() => setOpen(true)}><Plus/>Nueva evaluación</button> : undefined}>
    {status === 'loading' && <ComplianceLoading/>}{status === 'error' && <section className={styles.error} role="alert"><AlertTriangle/><h2>No pudimos cargar Riesgos / UIF.</h2><p>La información no está disponible en este momento.</p><button type="button" onClick={() => void load()}><RefreshCw/>Reintentar</button></section>}
    {status === 'ready' && <><section className={styles.metrics} aria-label="Indicadores de Riesgos y UIF"><Metric icon={ShieldCheck} label="Expedientes evaluados" value={data.metrics.expedientes_evaluados} detail="Dentro de tu alcance" tone="blue"/><Metric icon={CircleAlert} label="Requieren revisión" value={data.metrics.requieren_revision} detail="Información o decisión pendiente" tone="gold"/><Metric icon={ClipboardCheck} label="Avisos por presentar" value={data.metrics.avisos_por_presentar} detail="Obligaciones abiertas" tone="green"/><Metric icon={CalendarClock} label="Obligaciones vencidas" value={data.metrics.obligaciones_vencidas} detail="Atención prioritaria" tone="red"/></section>
      <section className={styles.directoryPanel}><div className={styles.directoryFilters} aria-label="Filtros de Riesgos y UIF"><label className={styles.search}><span className="sr-only">Buscar evaluación</span><Search/><input value={filters.search} onChange={(event) => change('search', event.target.value)} placeholder="Buscar expediente, cliente o folio…"/></label><label><span>Nivel de revisión</span><select value={filters.nivel} onChange={(event) => change('nivel', event.target.value)}><option value="">Todos</option>{Object.entries(evaluationLabels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label><span>Actividad vulnerable</span><select value={filters.actividad} onChange={(event) => change('actividad', event.target.value)}><option value="">Todas</option>{Object.entries(activityLabels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label><span>Estado de Aviso</span><select value={filters.estado_aviso} onChange={(event) => change('estado_aviso', event.target.value)}><option value="">Todos</option>{Object.entries(noticeLabels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label><span>Notaría</span><select value={filters.notaria_id} onChange={(event) => change('notaria_id', event.target.value)}><option value="">Todas</option>{notaries.map((notaria: any) => <option key={notaria.id} value={notaria.id}>Notaría {notaria.numero_notaria}</option>)}</select></label><label><span>Responsable</span><select value={filters.responsable_id} onChange={(event) => change('responsable_id', event.target.value)}><option value="">Todos</option>{catalogs.usuarios.map((item: any) => <option key={item.id} value={item.id}>{item.nombre} {item.apellido}</option>)}</select></label><label><span>Desde</span><input type="date" value={filters.desde} onChange={(event) => change('desde', event.target.value)}/></label><label><span>Hasta</span><input type="date" value={filters.hasta} onChange={(event) => change('hasta', event.target.value)}/></label></div>
        <div className={styles.resultsToolbar}><p><strong>{data.meta.total}</strong> evaluaciones dentro de tu alcance</p><div className={styles.viewSwitch} role="group" aria-label="Vista de evaluaciones"><button type="button" aria-pressed={view === 'cards'} onClick={() => changeView('cards')}><Grid2X2/>Tarjetas</button><button type="button" aria-pressed={view === 'list'} onClick={() => changeView('list')}><List/>Lista</button></div></div>
        {!data.revisiones.length ? <div className={styles.empty}><ShieldCheck/><h2>No hay evaluaciones con estos filtros</h2><p>Ajusta los filtros o crea una evaluación desde un expediente accesible.</p></div> : view === 'cards' ? <div className={styles.complianceCards}>{data.revisiones.map((item) => <ComplianceDirectoryCard key={item.id} item={item} onOpen={() => navigate(`/riesgos/revisiones/${item.id}${fixture ? '?fixture=workspace&visual=1' : ''}`)}/>)}</div> : <ComplianceDirectoryTable items={data.revisiones} onOpen={(item) => navigate(`/riesgos/revisiones/${item.id}${fixture ? '?fixture=workspace&visual=1' : ''}`)}/>}<nav className={styles.pagination} aria-label="Paginación"><span>Página {data.meta.page} de {data.meta.totalPages}</span><div><button type="button" aria-label="Página anterior" disabled={data.meta.page <= 1} onClick={() => change('page', String(data.meta.page - 1))}><ChevronLeft/></button><button type="button" aria-label="Página siguiente" disabled={data.meta.page >= data.meta.totalPages} onClick={() => change('page', String(data.meta.page + 1))}><ChevronRight/></button></div></nav>
      </section></>}
    {open && <NewReviewDialog
      catalogs={catalogs}
      onClose={() => setOpen(false)}
      onCreated={(id) => { setOpen(false); navigate(`/riesgos/revisiones/${id}`); }}
    />}
  </PageContainer>;
}

function Metric({ icon: Icon, label, value, detail, tone }: any) { return <article data-tone={tone}><span><Icon/></span><div><small>{label}</small><strong>{value}</strong><p>{detail}</p></div></article>; }
function levelFor(item: ComplianceReview) { return item.resultado_json?.estado_evaluacion || (item.estatus === 'CONFIRMADO' ? 'EVALUADO' : item.estatus === 'BORRADOR' ? 'SIN_EVALUAR' : 'EN_REVISION'); }
function ComplianceDirectoryCard({ item, onOpen }: { item: ComplianceReview; onOpen: () => void }) { const result: any = item.resultado_json || {}; const level = levelFor(item); return <button type="button" className={styles.complianceDirectoryCard} onClick={onOpen}><header><span>{item.expediente.numero_pravia}</span><b data-tone={level}>{evaluationLabels[level] || level}</b></header><h2>{item.expediente.cliente_alias || 'Cliente pendiente'}</h2><p>{activityLabels[result.acto] || item.expediente.tipo_acto?.nombre || 'Actividad por determinar'}</p><dl><div><dt>Aviso</dt><dd>{noticeLabels[result.estado_aviso] || 'Por determinar'}</dd></div><div><dt>Notaría</dt><dd>{item.expediente.notaria?.numero_notaria ? `Notaría ${item.expediente.notaria.numero_notaria}` : 'Sin asignar'}</dd></div><div><dt>Responsable</dt><dd>{item.expediente.abogado ? `${item.expediente.abogado.nombre} ${item.expediente.abogado.apellido}` : 'Sin asignar'}</dd></div><div><dt>Última evaluación</dt><dd>{new Date(item.updated_at).toLocaleDateString('es-MX')}</dd></div></dl><footer><span>{result.faltantes?.length || 0} pendientes</span><strong>Abrir evaluación</strong></footer></button>; }
function ComplianceDirectoryTable({ items, onOpen }: { items: ComplianceReview[]; onOpen: (item: ComplianceReview) => void }) { return <div className={styles.directoryTable}><table><thead><tr><th>Expediente / cliente</th><th>Actividad vulnerable</th><th>Evaluación</th><th>Aviso</th><th>Notaría</th><th>Responsable</th><th>Actualización</th></tr></thead><tbody>{items.map((item) => { const result: any = item.resultado_json || {}; const level = levelFor(item); return <tr key={item.id} tabIndex={0} onClick={() => onOpen(item)} onKeyDown={(event) => { if (event.key === 'Enter') onOpen(item); }}><td><strong>{item.expediente.numero_pravia}</strong><small>{item.expediente.cliente_alias}</small></td><td>{activityLabels[result.acto] || item.expediente.tipo_acto?.nombre || 'Por determinar'}</td><td><b data-tone={level}>{evaluationLabels[level] || level}</b></td><td>{noticeLabels[result.estado_aviso] || 'Por determinar'}</td><td>{item.expediente.notaria?.numero_notaria || '—'}</td><td>{item.expediente.abogado ? `${item.expediente.abogado.nombre} ${item.expediente.abogado.apellido}` : '—'}</td><td>{new Date(item.updated_at).toLocaleDateString('es-MX')}</td></tr>; })}</tbody></table></div>; }
export function ComplianceLoading() { return <div className={styles.loading} aria-label="Cargando evaluaciones"><div>{[1,2,3,4].map((item) => <span key={item}/>)}</div><section><i/><i/><i/><i/></section></div>; }
