import {
  AlertTriangle, ArrowLeft, Bot, CalendarClock, ChevronRight, CircleDollarSign, ExternalLink,
  FileCheck2, FileSearch, Fingerprint, History, Landmark, Link2, RefreshCw, Scale,
  ShieldAlert, ShieldCheck, Sparkles, UserCheck, UsersRound, WalletCards,
} from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { DocumentViewer } from '../../components/documents/DocumentViewer';
import { useAssistant } from '../assistant/AssistantProvider';
import { useAuth } from '../auth/AuthProvider';
import { fixtureComplianceDetail } from './compliance.fixtures';
import { activityLabels, evaluationLabels, noticeLabels } from './CompliancePage';
import { complianceService } from './compliance.service';
import type { ComplianceDetail } from './compliance.types';
import styles from './Compliance.module.css';

const sections = [
  ['operacion', '01', 'Operación'], ['actividad', '02', 'Actividad vulnerable'], ['personas', '03', 'Personas'],
  ['beneficiario', '04', 'Beneficiario controlador'], ['pep', '05', 'PEP y listas'], ['pagos', '06', 'Pago y efectivo'],
  ['riesgo', '07', 'Riesgo interno'], ['obligaciones', '08', 'Obligaciones y Avisos'], ['evidencia', '09', 'Evidencia'],
  ['historial', '10', 'Historial'],
] as const;
const money = (value: unknown) => Number(value || 0).toLocaleString('es-MX', { style: 'currency', currency: 'MXN' });
const date = (value: unknown) => value ? new Date(String(value)).toLocaleDateString('es-MX', { year: 'numeric', month: 'short', day: 'numeric' }) : 'Por determinar';
const text = (value: unknown, fallback = 'Por determinar') => value == null || value === '' ? fallback : String(value).replaceAll('_', ' ').toLocaleLowerCase('es-MX');

export function ComplianceReviewPage() {
  const { id = '' } = useParams(); const location = useLocation(); const navigate = useNavigate(); const { user } = useAuth(); const assistant = useAssistant();
  const fixture = import.meta.env.DEV && new URLSearchParams(location.search).get('fixture') === 'workspace';
  const localVisual = fixture && new URLSearchParams(location.search).get('visual') === '1';
  const [data, setData] = useState<ComplianceDetail | null>(fixture ? fixtureComplianceDetail : null);
  const [status, setStatus] = useState<'loading' | 'ready' | 'error'>(fixture ? 'ready' : 'loading'); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  const [viewer, setViewer] = useState<{ open: boolean; name: string; mime?: string; url?: string; loading?: boolean; error?: string }>({ open: false, name: '' });
  const canWrite = localVisual || Boolean(user?.permissions?.some((permission) => ['compliance.write', 'cumplimiento.write'].includes(permission)));
  const canReview = localVisual || Boolean(user?.permissions?.some((permission) => ['compliance.review', 'cumplimiento.confirm'].includes(permission)));
  const load = useCallback(async (signal?: AbortSignal) => { if (fixture) return; setStatus('loading'); try { setData(await complianceService.detail(id, signal)); setStatus('ready'); } catch (error) { if (!(error instanceof DOMException && error.name === 'AbortError')) setStatus('error'); } }, [fixture, id]);
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort(); }, [load]);
  useEffect(() => () => { if (viewer.url) URL.revokeObjectURL(viewer.url); }, [viewer.url]);
  const reevaluate = async () => { setSaving(true); setMessage(''); try { const created = await complianceService.reevaluate(id); navigate(`/riesgos/revisiones/${created.id}`); } catch { setMessage('No fue posible crear la reevaluación.'); } finally { setSaving(false); } };
  const openEvidence = async (evidence: any) => { const document = evidence.documento || {}; setViewer({ open: true, name: document.nombre_original || 'Evidencia', mime: document.mime_type, loading: !fixture }); if (fixture) return; try { const blob = await complianceService.evidenceBlob(id, evidence.id); setViewer((current) => ({ ...current, loading: false, url: URL.createObjectURL(blob) })); } catch { setViewer((current) => ({ ...current, loading: false, error: 'No fue posible mostrar este documento.' })); } };
  if (status === 'loading') return <main className={styles.workspacePage}><div className={styles.reviewSkeleton}><span/><span/><section/><section/></div></main>;
  if (status === 'error' || !data) return <main className={styles.workspacePage}><section className={styles.error}><AlertTriangle/><h2>No pudimos cargar esta evaluación.</h2><p>La información no está disponible en este momento.</p><button type="button" onClick={() => void load()}><RefreshCw/>Reintentar</button></section></main>;
  const review = data.revision; const workspace = data.workspace || { parties: [], beneficialOwners: [], pepReviews: [], screenings: [], payments: [], obligations: [], events: [], aiProposals: [], sensitiveRedacted: false }; const result: any = review.resultado_json || {}; const questionnaire = review.cuestionario_json || {};
  const operationValue = result.monto_base_mxn ?? questionnaire.precio_pactado ?? review.expediente.valor_operacion; const paymentTotal = workspace.payments.reduce((sum: number, payment: any) => sum + Number(payment.amount_mxn || 0), 0); const evaluation = result.estado_evaluacion || (review.estatus === 'CONFIRMADO' ? 'EVALUADO' : 'SIN_EVALUAR');
  return <main className={styles.workspacePage}>
    <header className={styles.workspaceHeader}><button type="button" className={styles.backLink} onClick={() => navigate('/riesgos')}><ArrowLeft/>Riesgos / UIF</button><div className={styles.workspaceTitle}><div><span>Evaluación UIF · versión {review.rule_version_snapshot}</span><h1>{review.expediente.numero_pravia}</h1><p>{review.expediente.cliente_alias || 'Cliente por confirmar'} · {review.expediente.tipo_acto?.nombre || 'Acto por determinar'}</p></div><div className={styles.workspaceActions}><b data-tone={evaluation}>{evaluationLabels[evaluation] || text(evaluation)}</b>{canWrite && <button type="button" disabled={saving} onClick={() => void reevaluate()}><RefreshCw/>Reevaluar</button>}</div></div><div className={styles.workspaceMeta}><span><Landmark/>Notaría {review.expediente.notaria?.numero_notaria || 'sin asignar'}</span><span><UserCheck/>{review.expediente.abogado ? `${review.expediente.abogado.nombre} ${review.expediente.abogado.apellido}` : 'Sin responsable'}</span><span><CalendarClock/>Operación: {date(review.fecha_operacion)}</span><span><History/>Snapshot: {date(review.snapshot_captured_at)}</span></div>{review.master_data_changed && <p className={styles.snapshotWarning}><AlertTriangle/>Los datos maestros cambiaron después del snapshot. Reevalúa para incorporarlos sin alterar esta versión.</p>}</header>
    <nav className={styles.sectionNav} aria-label="Secciones de la evaluación">{sections.map(([key, number, label]) => <a key={key} href={`#${key}`}><span>{number}</span>{label}</a>)}</nav>{message && <p className={styles.inlineNotice} role="status">{message}</p>}
    <div className={styles.workspaceLayout}><div className={styles.workspaceSections}>
      <WorkspaceSection id="operacion" number="01" icon={FileCheck2} title="Operación y snapshot" subtitle="Datos jurídicos congelados para esta evaluación."><KeyGrid items={[["Expediente", review.expediente.numero_pravia], ["Acto", review.expediente.tipo_acto?.nombre], ["Valor de operación", money(operationValue)], ["Fecha jurídica", date(review.fecha_operacion)], ["Versión del expediente", review.master_snapshot?.expediente?.version ? `v${review.master_snapshot.expediente.version}` : 'Snapshot registrado'], ["Regla aplicable", review.rule_version_snapshot]]}/></WorkspaceSection>
      <WorkspaceSection id="actividad" number="02" icon={Scale} title="Actividad vulnerable" subtitle="Determinación por supuesto legal, fecha y UMA aplicable."><div className={styles.legalDecision}><span data-state={result.actividad_vulnerable}>{result.actividad_vulnerable === 'SI' ? 'Actividad vulnerable identificada' : result.actividad_vulnerable === 'NO' ? 'No identificada' : 'Información insuficiente'}</span><h3>{activityLabels[result.acto] || 'Supuesto pendiente de determinar'}</h3><p>{result.fundamento || 'La evaluación aún no cuenta con fundamento persistido.'}</p></div><KeyGrid items={[["Identificación", text(result.identificacion_requerida)], ["Aviso", noticeLabels[result.estado_aviso] || 'Por determinar'], ["Monto individual", money(result.monto_base_mxn)], ["Acumulado 6 meses", money(result.acumulado_seis_meses_mxn)], ["Umbral de Aviso", result.umbral_uma ? `${Number(result.umbral_uma).toLocaleString('es-MX')} UMA · ${money(result.umbral_mxn)}` : 'Aviso en todos los casos'], ["UMA aplicable", result.uma ? `${money(result.uma.dailyValueMxn)} diarios · ${result.uma.year}` : 'Por determinar']]}/><SourceNote result={result}/></WorkspaceSection>
      <WorkspaceSection id="personas" number="03" icon={UsersRound} title="Personas y comparecientes" subtitle="Snapshot de intervinientes; los cambios maestros no reescriben esta versión.">{workspace.sensitiveRedacted ? <Restricted/> : <div className={styles.partyGrid}>{workspace.parties.map((party: any) => { const snap = party.snapshot || {}; return <article key={party.id}><Fingerprint/><div><strong>{snap.nombre || snap.razon_social || 'Persona registrada'}</strong><p>{text(snap.tipo_persona)} · {snap.rfc || 'RFC pendiente'}</p><small>{text(party.role)} · snapshot v{party.snapshot_version}</small></div></article>; })}</div>}</WorkspaceSection>
      <WorkspaceSection id="beneficiario" number="04" icon={UserCheck} title="Beneficiario controlador" subtitle="Declaraciones y evidencia separadas de cualquier propuesta automatizada.">{workspace.sensitiveRedacted ? <Restricted/> : <div className={styles.recordList}>{workspace.beneficialOwners.length ? workspace.beneficialOwners.map((owner: any) => <article key={owner.id}><div><strong>{text(owner.status)}</strong><p>{owner.declaration || 'Sin declaración documentada.'}</p></div><span>{owner.confirmed_at ? 'Confirmado por persona autorizada' : 'Pendiente de confirmación humana'}</span></article>) : <EmptyLine text="No se ha documentado la determinación del beneficiario controlador."/>}</div>}</WorkspaceSection>
      <WorkspaceSection id="pep" number="05" icon={ShieldAlert} title="PEP y listas" subtitle="Una coincidencia potencial nunca equivale a una determinación de ilicitud.">{workspace.sensitiveRedacted ? <Restricted/> : <><div className={styles.integrationStatus}><AlertTriangle/><div><strong>Consulta oficial PEP no configurada</strong><p>No se simulan resultados ni se infieren coincidencias. La declaración y revisión humana permanecen auditables.</p></div></div><div className={styles.recordList}>{workspace.pepReviews.map((pep: any) => <article key={pep.id}><div><strong>{text(pep.status)}</strong><p>{pep.notes || 'Revisión sin observaciones.'}</p></div><span>{pep.human_reviewed_at ? `Revisado ${date(pep.human_reviewed_at)}` : 'Revisión pendiente'}</span></article>)}</div></>}</WorkspaceSection>
      <WorkspaceSection id="pagos" number="06" icon={WalletCards} title="Formas de pago y restricción de efectivo" subtitle="La obligación de Aviso y la restricción de efectivo se evalúan por separado."><div className={styles.paymentSummary}><div><small>Valor de operación</small><strong>{money(operationValue)}</strong></div><div><small>Pagos documentados</small><strong>{money(paymentTotal)}</strong></div><div><small>Diferencia</small><strong>{money(Number(operationValue || 0) - paymentTotal)}</strong></div></div><div className={styles.recordList}>{workspace.payments.map((payment: any) => <article key={payment.id}><div><strong>{money(payment.amount_mxn)}</strong><p>{text(payment.method)} · {date(payment.payment_date)}</p></div><span>{payment.masked_account || payment.reference || 'Sin referencia visible'}</span></article>)}</div><div className={styles.cashRule} data-state={result.restriccion_efectivo?.status}><CircleDollarSign/><div><strong>{result.restriccion_efectivo?.status === 'CUMPLE' ? 'Sin restricción detectada con los datos registrados' : 'Requiere revisión de forma de pago'}</strong><p>Umbral independiente: 8,025 UMA ({money(result.restriccion_efectivo?.thresholdMxn)}). {result.restriccion_efectivo?.legalBasis}</p></div></div></WorkspaceSection>
      <WorkspaceSection id="riesgo" number="07" icon={ShieldCheck} title="Evaluación interna de riesgo" subtitle="Metodología interna explicable; no constituye una probabilidad de ilicitud."><div className={styles.riskScore}><span data-level={result.evaluacion_riesgo?.level}>{text(result.evaluacion_riesgo?.level)}</span><div><strong>{result.evaluacion_riesgo?.score ?? 0} puntos internos</strong><p>{result.evaluacion_riesgo?.methodology || 'Metodología no registrada'}</p></div></div><ul className={styles.factorList}>{(result.evaluacion_riesgo?.factors || []).map((factor: any) => <li key={factor.key}><strong>+{factor.points}</strong><span>{text(factor.key)}<small>{factor.evidence}</small></span></li>)}</ul><p className={styles.normativePending}>Estado normativo: {text(result.evaluacion_riesgo?.normativeStatus)}. {result.evaluacion_riesgo?.disclaimer}</p></WorkspaceSection>
      <WorkspaceSection id="obligaciones" number="08" icon={CalendarClock} title="Obligaciones y Avisos" subtitle="PRAVIA prepara y controla; la presentación externa solo se marca con confirmación humana y acuse."><div className={styles.obligationGrid}>{workspace.obligations.map((obligation: any) => <article key={obligation.id}><header><span>{noticeLabels[obligation.status] || text(obligation.status)}</span><b>{obligation.type === 'AVISO_24H' ? '24 horas' : `Límite ${date(obligation.due_at)}`}</b></header><h3>{obligation.type === 'AVISO_24H' ? 'Aviso prioritario condicionado' : 'Aviso ordinario'}</h3><p>{obligation.legal_basis}</p><dl><div><dt>Canal</dt><dd>{obligation.channel}</dd></div><div><dt>Versión</dt><dd>{obligation.rule_version}</dd></div><div><dt>Presentación</dt><dd>{obligation.external_folio ? `Folio ${obligation.external_folio}` : 'No confirmada externamente'}</dd></div></dl>{canReview && !obligation.external_folio && <button type="button" disabled title="Requiere fecha, folio y acuse vinculados">Registrar presentación externa</button>}</article>)}</div><p className={styles.humanGate}><ShieldAlert/>La coincidencia textual no genera por sí sola un Aviso de 24 horas. Requiere supuesto vigente, evidencia y confirmación humana.</p></WorkspaceSection>
      <WorkspaceSection id="evidencia" number="09" icon={FileSearch} title="Evidencia y conservación" subtitle="Documentos protegidos, vinculados al expediente y conservados al menos diez años."><div className={styles.evidenceGrid}>{review.evidencias.map((evidence: any) => <button type="button" key={evidence.id} onClick={() => void openEvidence(evidence)}><FileSearch/><span><strong>{evidence.documento.nombre_original}</strong><small>{text(evidence.tipo_evidencia)} · conserva hasta {date(evidence.retention_until)}</small></span><ChevronRight/></button>)}</div>{!review.evidencias.length && <EmptyLine text="No hay evidencia vinculada a esta evaluación."/>}</WorkspaceSection>
      <WorkspaceSection id="historial" number="10" icon={History} title="Historial, versiones e integraciones" subtitle="Registro append-only de hechos, actores, decisiones y fuentes."><div className={styles.timeline}>{workspace.events.map((event: any) => <article key={event.id}><span/><div><strong>{text(event.event_type)}</strong><p>{event.summary}</p><small>{date(event.created_at)}</small></div></article>)}</div><h3 className={styles.subsectionTitle}>Versiones anteriores</h3><div className={styles.versionGrid}>{data.historial.map((item: any) => <article key={item.id}><strong>{item.rule_version_snapshot}</strong><p>{evaluationLabels[item.resultado_json?.estado_evaluacion] || text(item.estatus)}</p><small>{date(item.created_at)} · solo lectura</small></article>)}</div></WorkspaceSection>
    </div><aside className={styles.workspaceAside}><section className={styles.assistantCard}><header><Sparkles/><span>PRAVIA IA</span><b>Contextual</b></header><h2>Apoyo para esta evaluación</h2><p>Consulta faltantes, alertas y fuentes de esta versión. PRAVIA IA no confirma personas, no presenta Avisos y no emite dictámenes.</p><button type="button" onClick={() => assistant.openAssistant({ prefill: 'Resume esta evaluación UIF, sus faltantes y fuentes, sin emitir un dictamen legal.' })}><Bot/>Abrir con contexto</button></section>{workspace.aiProposals.map((proposal: any) => <section className={styles.aiProposal} key={proposal.id}><small>Propuesta automatizada</small><strong>PROPUESTA — REQUIERE CONFIRMACIÓN HUMANA.</strong><p>{proposal.content?.message || 'Información extraída pendiente de revisión.'}</p><dl><div><dt>Documento</dt><dd>{proposal.source_document_id || 'Fuente registrada'}</dd></div><div><dt>Página</dt><dd>{proposal.source_page || '—'}</dd></div><div><dt>Modelo</dt><dd>{proposal.model}</dd></div><div><dt>Versión</dt><dd>{proposal.prompt_version}</dd></div></dl></section>)}<section className={styles.disclaimerCard}><ShieldCheck/><div><strong>Apoyo operativo, no dictamen</strong><p>{result.disclaimer || 'La decisión requiere revisión humana autorizada.'}</p></div></section></aside></div>
    <DocumentViewer open={viewer.open} name={viewer.name} mimeType={viewer.mime} url={viewer.url} loading={viewer.loading} error={viewer.error} onClose={() => setViewer({ open: false, name: '' })}/>
  </main>;
}

function WorkspaceSection({ id, number, icon: Icon, title, subtitle, children }: any) { return <section className={styles.workspaceSection} id={id}><header><span>{number}</span><Icon/><div><h2>{title}</h2><p>{subtitle}</p></div></header><div className={styles.sectionBody}>{children}</div></section>; }
function KeyGrid({ items }: { items: Array<[string, unknown]> }) { return <dl className={styles.keyGrid}>{items.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value == null || value === '' ? 'Por determinar' : String(value)}</dd></div>)}</dl>; }
function SourceNote({ result }: any) { return <div className={styles.sourceNote}><Link2/><div><strong>Fuente normativa verificada</strong><p>{result.version_normativa || 'Versión por determinar'} · consultada el 17 de agosto de 2026.</p><a href={result.uma?.sourceUrl || 'https://www.diputados.gob.mx/LeyesBiblio/pdf/LFPIORPI.pdf'} target="_blank" rel="noreferrer">Abrir fuente oficial <ExternalLink/></a></div></div>; }
function Restricted() { return <div className={styles.restrictedInline}><ShieldAlert/><p>Tu permiso permite ver la evaluación, pero no estos datos sensibles.</p></div>; }
function EmptyLine({ text: label }: { text: string }) { return <div className={styles.emptyLine}><FileCheck2/><p>{label}</p></div>; }
