import { AlertTriangle, CheckCircle2, ClipboardCheck, FileText, History, ListChecks, RefreshCw, ShieldAlert } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useAuth } from '../auth/AuthProvider';
import { AlertExplanation, AlertPanel } from './components/AlertPanel';
import { EvidencePanel } from './components/EvidencePanel';
import { ReviewChecklist } from './components/ReviewChecklist';
import { ReviewHeader } from './components/ReviewHeader';
import { ReviewHistory } from './components/ReviewHistory';
import { RuleResult } from './components/RuleResult';
import { complianceService } from './compliance.service';
import type { ComplianceAlert, ComplianceCatalogs, ComplianceDetail } from './compliance.types';
import styles from './Compliance.module.css';

const tabs=[['resumen','Resumen',ClipboardCheck],['checklist','Checklist',ListChecks],['alertas','Alertas',ShieldAlert],['evidencia','Evidencia',FileText],['historial','Historial',History]] as const;
export function ComplianceReviewPage(){const {id=''}=useParams();const navigate=useNavigate();const {user}=useAuth();const [data,setData]=useState<ComplianceDetail|null>(null),[catalogs,setCatalogs]=useState<ComplianceCatalogs|null>(null),[status,setStatus]=useState<'loading'|'ready'|'error'>('loading'),[active,setActive]=useState<(typeof tabs)[number][0]>('resumen'),[draft,setDraft]=useState<Record<string,any>>({}),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notes,setNotes]=useState(''),[selectedAlert,setSelectedAlert]=useState<ComplianceAlert|null>(null);const canWrite=Boolean(user?.permissions?.includes('cumplimiento.write')),canConfirm=Boolean(user?.permissions?.includes('cumplimiento.confirm'));
 const load=useCallback(async(signal?:AbortSignal)=>{setStatus('loading');try{const [detail,cats]=await Promise.all([complianceService.detail(id,signal),complianceService.catalogs(signal)]);setData(detail);setCatalogs(cats);setDraft(detail.revision.cuestionario_json||{});setStatus('ready');}catch(err){if(!(err instanceof DOMException&&err.name==='AbortError'))setStatus('error');}},[id]);useEffect(()=>{const controller=new AbortController();void load(controller.signal);return()=>controller.abort();},[load]);
 const run=async(fn:()=>Promise<any>,after?:(value:any)=>void)=>{setSaving(true);setError('');try{const value=await fn();after?.(value);await load();}catch(err){setError(err instanceof Error?err.message:'No fue posible completar la acción.');}finally{setSaving(false);}};
 if(status==='loading')return <main className={styles.reviewPage}><div className={styles.reviewSkeleton}><span/><span/><section/><section/></div></main>;if(status==='error'||!data||!catalogs)return <main className={styles.reviewPage}><section className={styles.error}><AlertTriangle/><h2>No pudimos cargar la revisión.</h2><p>La información no está disponible en este momento.</p><button onClick={()=>load()}><RefreshCw/>Reintentar</button></section></main>;
 const review=data.revision;const readOnly=review.estatus==='CONFIRMADO'||!canWrite;const evaluate=()=>run(()=>complianceService.evaluate(id,draft));const decide=(decision:'CONFIRMAR'|'REQUIERE_AJUSTES')=>run(()=>complianceService.decide(id,decision,notes));const reevaluate=()=>run(()=>complianceService.reevaluate(id),created=>navigate(`/riesgos/revisiones/${created.id}`));const addEvidence=(body:any)=>run(()=>complianceService.addEvidence(id,body));
 return <main className={styles.reviewPage}><ReviewHeader review={review} canWrite={canWrite} onReevaluate={reevaluate}/><nav className={styles.reviewTabs} aria-label="Secciones de la revisión">{tabs.map(([key,label,Icon])=><button key={key} aria-current={active===key?'page':undefined} onClick={()=>setActive(key)}><Icon/>{label}</button>)}</nav>{error&&<p className={styles.inlineError} role="alert">{error}</p>}
  {active==='resumen'&&<div className={styles.reviewGrid}><div><RuleResult review={review}/><ReviewChecklist review={review} draft={draft} onChange={(key,value)=>setDraft(current=>({...current,[key]:value}))} readOnly={readOnly}/></div><aside><AlertPanel alerts={review.resultado_json?.alertas||[]} onSelect={setSelectedAlert}/><EvidencePanel review={review} documents={catalogs.documentos} canWrite={canWrite} onAdd={addEvidence}/><DecisionPanel review={review} canWrite={canWrite} canConfirm={canConfirm} notes={notes} setNotes={setNotes} saving={saving} onEvaluate={evaluate} onDecide={decide}/></aside></div>}
  {active==='checklist'&&<ReviewChecklist review={review} draft={draft} onChange={(key,value)=>setDraft(current=>({...current,[key]:value}))} readOnly={readOnly}/>} {active==='alertas'&&<div className={styles.singlePanel}><AlertPanel alerts={review.resultado_json?.alertas||[]} onSelect={setSelectedAlert}/><RuleResult review={review}/></div>} {active==='evidencia'&&<div className={styles.singlePanel}><EvidencePanel review={review} documents={catalogs.documentos} canWrite={canWrite} onAdd={addEvidence}/></div>} {active==='historial'&&<div className={styles.singlePanel}><ReviewHistory current={review} history={data.historial}/></div>}
  {selectedAlert&&<AlertExplanation alert={selectedAlert} onClose={()=>setSelectedAlert(null)}/>}</main>}

function DecisionPanel({review,canWrite,canConfirm,notes,setNotes,saving,onEvaluate,onDecide}:any){if(review.estatus==='CONFIRMADO')return <section className={styles.decisionDone}><CheckCircle2/><div><h2>Confirmación humana registrada</h2><p>{review.revisado_por?`${review.revisado_por.nombre} ${review.revisado_por.apellido}`:'Usuario autorizado'} · {new Date(review.revisado_at).toLocaleString('es-MX')}</p></div></section>;return <section className={styles.decision}><small>Acción humana</small><h2>Evaluar y confirmar</h2><p>Las reglas producen un resultado explicable. La decisión final queda vinculada a actor, fecha, regla y snapshots.</p>{canConfirm&&<textarea aria-label="Observaciones de la decisión" rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Observaciones para el historial…"/>}<div>{canWrite&&<button disabled={saving} onClick={onEvaluate}><RefreshCw/>{saving?'Procesando…':'Ejecutar evaluación'}</button>}{canConfirm&&review.resultado_json&&<><button disabled={saving} onClick={()=>onDecide('REQUIERE_AJUSTES')}>Solicitar ajustes</button><button className={styles.primary} disabled={saving} onClick={()=>onDecide('CONFIRMAR')}><CheckCircle2/>Confirmar revisión</button></>}</div></section>}
