import { CheckCircle2, LoaderCircle, PackageCheck } from 'lucide-react';
import { useMemo, useState } from 'react';
import { dateTime } from '../expedienteFormatters';
import { expedientesService } from '../expedientes.service';
import type { ExpedienteDetail } from '../expedientes.types';
import styles from '../Expedientes.module.css';

export function DeliveryPanel({ expediente, onChanged }: { expediente: ExpedienteDetail; onChanged(): void }) {
  const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const [receiver, setReceiver] = useState(''); const [character, setCharacter] = useState(''); const [date, setDate] = useState(''); const [medium, setMedium] = useState('Presencial'); const [itemId, setItemId] = useState(''); const [itemType, setItemType] = useState('DOCUMENTO'); const [quantity, setQuantity] = useState(1); const [evidenceId, setEvidenceId] = useState(''); const [notes, setNotes] = useState('');
  const documents = useMemo(() => (expediente.expedienteDocumentos || []).map((link: any) => link.documento || link).filter((document: any) => document?.id), [expediente.expedienteDocumentos]);
  if (expediente.entrega) return <section className={styles.deliveryComplete}><span><CheckCircle2 size={20} /></span><div><small>Entrega registrada</small><strong>{expediente.entrega.receptor_nombre}</strong><p>{expediente.entrega.receptor_caracter} · {expediente.entrega.medio} · {dateTime(expediente.entrega.fecha_efectiva)}</p></div></section>;
  if (expediente.estatus !== 'LISTO_ENTREGA') return null;
  const submit = async () => { setSaving(true); setError(''); try { await expedientesService.deliver(expediente.id, { expected_version: expediente.version, receptor_nombre: receiver, receptor_caracter: character, fecha_efectiva: date, medio: medium, items: [{ documento_id: itemId, tipo: itemType, cantidad: quantity }], evidencia_documento_id: evidenceId, ...(notes.trim() ? { observaciones: notes.trim() } : {}) }); setOpen(false); onChanged(); } catch { setError('No pudimos registrar la entrega. Verifica la fecha efectiva, los documentos y la evidencia.'); } finally { setSaving(false); } };
  return <section className={styles.deliveryReady}><span><PackageCheck size={21} /></span><div><small>Readiness de entrega</small><strong>El expediente está listo para su entrega final</strong><p>Registra receptor, documentos y evidencia. El backend volverá a validar todo antes de cerrar.</p></div>{expediente.capabilities.canDeliver && <button type="button" className={styles.primaryButton} onClick={() => setOpen(true)}>Registrar entrega</button>}{open && <div className={styles.dialogBackdrop}><section className={styles.dialog} role="dialog" aria-modal="true" aria-label="Registrar entrega final"><header><div><h2>Registrar entrega final</h2><p>La fecha efectiva y la evidencia son obligatorias.</p></div></header>{error && <div className={styles.inlineError} role="alert">{error}</div>}<div className={styles.dialogBody}><label>Receptor<input value={receiver} onChange={(event) => setReceiver(event.target.value)} /></label><label>Carácter<input value={character} onChange={(event) => setCharacter(event.target.value)} placeholder="Titular, representante…" /></label><label>Fecha y hora efectiva<input type="datetime-local" value={date} onChange={(event) => setDate(event.target.value)} /></label><label>Medio<select value={medium} onChange={(event) => setMedium(event.target.value)}><option>Presencial</option><option>Mensajería</option><option>Otro</option></select></label><label>Documento entregado<select value={itemId} onChange={(event) => setItemId(event.target.value)}><option value="">Selecciona un documento</option>{documents.map((document: any) => <option key={document.id} value={document.id}>{document.nombre_original || document.nombre}</option>)}</select></label><div className={styles.inlineFields}><label>Tipo<select value={itemType} onChange={(event) => setItemType(event.target.value)}><option value="DOCUMENTO">Documento</option><option value="TESTIMONIO">Testimonio</option><option value="COPIA">Copia</option></select></label><label>Cantidad<input type="number" min="1" value={quantity} onChange={(event) => setQuantity(Number(event.target.value))} /></label></div><label>Acuse o evidencia<select value={evidenceId} onChange={(event) => setEvidenceId(event.target.value)}><option value="">Selecciona una evidencia</option>{documents.map((document: any) => <option key={document.id} value={document.id}>{document.nombre_original || document.nombre}</option>)}</select></label><label>Observaciones<textarea value={notes} onChange={(event) => setNotes(event.target.value)} rows={3} /></label></div><footer><button type="button" className={styles.secondaryButton} onClick={() => setOpen(false)}>Cancelar</button><button type="button" className={styles.primaryButton} disabled={saving || !receiver.trim() || !character.trim() || !date || !medium || !itemId || !evidenceId || quantity < 1} onClick={() => void submit()}>{saving && <LoaderCircle className={styles.spin} size={15} />}Confirmar entrega</button></footer></section></div>}</section>;
}
