import { Check, ChevronLeft, ChevronRight, LoaderCircle, Search, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { useAuth } from '../../auth/AuthProvider';
import { expedientesService } from '../expedientes.service';
import { fullName, partyOptionName } from '../expedienteFormatters';
import type { ActTypeOption, ExpedienteDetail, NotaryOption, PartyOption, PersonOption } from '../expedientes.types';
import styles from '../Expedientes.module.css';

const steps = ['Tipo de acto', 'Cliente', 'Notaría', 'Responsable', 'Revisión'];
export function NewExpedienteFlow({ onClose, onCreated }: { onClose(): void; onCreated(expediente: ExpedienteDetail): void }) {
  const { user } = useAuth(); const [step, setStep] = useState(0); const [types, setTypes] = useState<ActTypeOption[]>([]); const [users, setUsers] = useState<PersonOption[]>([]);
  const [notaries, setNotaries] = useState<NotaryOption[]>([]); const [parties, setParties] = useState<PartyOption[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const [typeId, setTypeId] = useState(''); const [partyId, setPartyId] = useState(''); const [notaryId, setNotaryId] = useState(''); const [responsibleId, setResponsibleId] = useState(''); const [partySearch, setPartySearch] = useState(''); const [notarySearch, setNotarySearch] = useState('');
  useEffect(() => { const controller = new AbortController(); setError(''); Promise.all([expedientesService.types(controller.signal), expedientesService.users(controller.signal), expedientesService.notaries('', controller.signal)]).then(([typeItems, userItems, notaryItems]) => { setTypes(typeItems); setUsers(userItems); setNotaries(notaryItems); const own = userItems.find((item) => item.id === user?.id); if (user?.role === 'ABOGADO' && own) setResponsibleId(own.id); }).catch((cause) => { if (!(cause instanceof DOMException && cause.name === 'AbortError')) setError('No pudimos preparar el nuevo expediente.'); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [user?.id, user?.role]);
  useEffect(() => { if (step !== 1) return; if (partySearch.trim().length < 2) { setParties([]); return; } const controller = new AbortController(); const timer = window.setTimeout(() => { expedientesService.parties(partySearch, controller.signal).then(setParties).catch(() => setParties([])); }, 220); return () => { window.clearTimeout(timer); controller.abort(); }; }, [partySearch, step]);
  useEffect(() => { if (step !== 2) return; const controller = new AbortController(); const timer = window.setTimeout(() => { expedientesService.notaries(notarySearch, controller.signal).then(setNotaries).catch(() => setNotaries([])); }, 220); return () => { window.clearTimeout(timer); controller.abort(); }; }, [notarySearch, step]);
  const selectedType = types.find((item) => item.id === typeId); const selectedParty = parties.find((item) => item.id === partyId); const selectedNotary = notaries.find((item) => item.id === notaryId); const selectedResponsible = users.find((item) => item.id === responsibleId);
  const canNext = [Boolean(typeId), Boolean(partyId && selectedParty), true, Boolean(responsibleId), true][step];
  const submit = async () => { if (!selectedType || !selectedParty || !selectedResponsible) return; setSaving(true); setError(''); try { const expediente = await expedientesService.create({ tipo_acto_id: selectedType.id, abogado_id: selectedResponsible.id, cliente_alias: partyOptionName(selectedParty), compareciente_id: selectedParty.id, ...(notaryId ? { notaria_id: notaryId } : {}), ...(selectedType.tipoActoCaracteresCompareciente?.[0]?.caracter_id ? { caracter_id: selectedType.tipoActoCaracteresCompareciente[0].caracter_id } : {}) }); onCreated(expediente); } catch { setError('No pudimos crear el expediente. Revisa la información e inténtalo nuevamente.'); } finally { setSaving(false); } };
  const choices = useMemo(() => ({ type: selectedType?.nombre || 'Sin seleccionar', party: selectedParty ? partyOptionName(selectedParty) : 'Sin seleccionar', notary: selectedNotary ? `${selectedNotary.numero_notaria ? `Notaría ${selectedNotary.numero_notaria} · ` : ''}${selectedNotary.nombre}` : 'Sin notaría', responsible: selectedResponsible ? fullName(selectedResponsible) : 'Sin seleccionar' }), [selectedNotary, selectedParty, selectedResponsible, selectedType]);
  return <div className={styles.drawerBackdrop} role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className={styles.drawer} role="dialog" aria-modal="true" aria-labelledby="new-expediente-title"><header className={styles.drawerHeader}><div><span>Nuevo expediente</span><h2 id="new-expediente-title">Abrir una operación notarial</h2><p>Captura únicamente los datos necesarios para iniciar.</p></div><button type="button" aria-label="Cerrar" onClick={onClose}><X size={20} /></button></header>
    <div className={styles.drawerBody}>{loading ? <div className={styles.formState}><LoaderCircle className={styles.spin} />Preparando catálogos…</div> : <><ol className={styles.stepper}>{steps.map((label, index) => <li key={label} className={index === step ? styles.stepCurrent : index < step ? styles.stepDone : ''}><span>{index < step ? <Check size={14} /> : index + 1}</span><b>{label}</b></li>)}</ol>{error && <div className={styles.formError} role="alert">{error}</div>}
      {step === 0 && <fieldset className={styles.flowStep}><legend>Selecciona el tipo de acto</legend><p>Se utilizará su configuración vigente al abrir el expediente.</p><div className={styles.choiceGrid}>{types.map((item) => <button type="button" key={item.id} className={typeId === item.id ? styles.choiceSelected : ''} onClick={() => setTypeId(item.id)}><strong>{item.nombre}</strong><span>{item.descripcion || 'Operación notarial configurada'}</span>{typeId === item.id && <Check size={17} />}</button>)}</div></fieldset>}
      {step === 1 && <fieldset className={styles.flowStep}><legend>Busca el cliente o compareciente principal</legend><p>Selecciona un registro existente para evitar duplicados.</p><label className={styles.flowSearch}><Search size={17} /><input autoFocus value={partySearch} onChange={(event) => { setPartySearch(event.target.value); setPartyId(''); }} placeholder="Nombre, razón social, RFC o CURP" /></label><div className={styles.choiceList}>{partySearch.trim().length < 2 ? <div className={styles.inlineState}>Escribe al menos dos caracteres.</div> : parties.length ? parties.map((item) => <button type="button" key={item.id} className={partyId === item.id ? styles.choiceSelected : ''} onClick={() => setPartyId(item.id)}><span><strong>{partyOptionName(item)}</strong><small>{item.tipo_persona === 'MORAL' ? 'Persona moral' : 'Persona física'} · {item.personaFisica?.rfc || item.personaMoral?.rfc || 'RFC no registrado'}</small></span>{partyId === item.id && <Check size={17} />}</button>) : <div className={styles.inlineState}>No encontramos coincidencias. El alta completa de comparecientes se realiza desde su módulo.</div>}</div></fieldset>}
      {step === 2 && <fieldset className={styles.flowStep}><legend>Selecciona la notaría</legend><p>Este dato es opcional al abrir y puede completarse después.</p><label className={styles.flowSearch}><Search size={17} /><input value={notarySearch} onChange={(event) => setNotarySearch(event.target.value)} placeholder="Número, titular, ciudad o nombre" /></label><div className={styles.choiceList}><button type="button" className={!notaryId ? styles.choiceSelected : ''} onClick={() => setNotaryId('')}><span><strong>Sin notaría por ahora</strong><small>Podrás asignarla dentro del expediente.</small></span>{!notaryId && <Check size={17} />}</button>{notaries.map((item) => <button type="button" key={item.id} className={notaryId === item.id ? styles.choiceSelected : ''} onClick={() => setNotaryId(item.id)}><span><strong>{item.numero_notaria ? `Notaría ${item.numero_notaria}` : item.nombre}</strong><small>{item.nombre} · {item.municipio || 'Ubicación no registrada'}</small></span>{notaryId === item.id && <Check size={17} />}</button>)}</div></fieldset>}
      {step === 3 && <fieldset className={styles.flowStep}><legend>Asigna a una persona responsable</legend><p>Solo se muestran usuarios activos con un rol autorizado.</p><div className={styles.choiceList}>{users.map((item) => <button type="button" key={item.id} className={responsibleId === item.id ? styles.choiceSelected : ''} onClick={() => user?.role !== 'ABOGADO' && setResponsibleId(item.id)}><span><strong>{fullName(item)}</strong><small>{item.rol === 'ABOGADO' ? 'Abogado' : item.rol === 'DIRECCION' ? 'Dirección' : 'Administración'}</small></span>{responsibleId === item.id && <Check size={17} />}</button>)}</div></fieldset>}
      {step === 4 && <fieldset className={styles.flowStep}><legend>Revisa antes de crear</legend><p>El folio, flujo, primera etapa y requisitos se generarán al confirmar.</p><dl className={styles.reviewList}><div><dt>Tipo de acto</dt><dd>{choices.type}</dd></div><div><dt>Cliente</dt><dd>{choices.party}</dd></div><div><dt>Notaría</dt><dd>{choices.notary}</dd></div><div><dt>Responsable</dt><dd>{choices.responsible}</dd></div></dl></fieldset>}</>}</div>
    <footer className={styles.drawerFooter}><button type="button" className={styles.secondaryButton} onClick={step ? () => setStep(step - 1) : onClose}>{step ? <><ChevronLeft size={17} />Anterior</> : 'Cancelar'}</button><span />{step < steps.length - 1 ? <button type="button" className={styles.primaryButton} disabled={!canNext || loading} onClick={() => setStep(step + 1)}>Continuar<ChevronRight size={17} /></button> : <button type="button" className={styles.primaryButton} disabled={saving} onClick={submit}>{saving ? <><LoaderCircle className={styles.spin} size={17} />Creando…</> : 'Crear expediente'}</button>}</footer>
  </section></div>;
}
