import { Building2, CheckCircle2, CircleAlert, LoaderCircle, Plus } from 'lucide-react';
import { useState } from 'react';
import { dateTime } from '../expedienteFormatters';
import { expedientesService } from '../expedientes.service';
import type { ExpedienteDetail } from '../expedientes.types';
import styles from '../Expedientes.module.css';

const taskTypeLabels: Record<string, string> = { CATASTRO: 'Catastro', REGISTRO_PUBLICO: 'Registro Público', BANCO: 'Banco', NOTARIA: 'Notaría', OTRA_GESTION: 'Otra gestión' };

export function PostfirmaPanel({ expediente, onChanged }: { expediente: ExpedienteDetail; onChanged(): void }) {
  const tasks = expediente.tareas_postfirma || expediente.tareas_externas || [];
  const editable = expediente.capabilities.canManagePostfirma && ['FIRMADO', 'POST_FIRMA'].includes(expediente.estatus);
  const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const [type, setType] = useState('REGISTRO_PUBLICO'); const [description, setDescription] = useState(''); const [institution, setInstitution] = useState(''); const [due, setDue] = useState('');
  const create = async () => { setSaving(true); setError(''); try { await expedientesService.createPostfirmaTask(expediente.id, { tipo: type, descripcion: description, institucion: institution, ...(due ? { fecha_limite: due } : {}) }); setOpen(false); setDescription(''); setInstitution(''); setDue(''); onChanged(); } catch { setError('No pudimos registrar el trámite. Revisa los datos e inténtalo de nuevo.'); } finally { setSaving(false); } };
  const start = async (task: any) => { setSaving(true); setError(''); try { await expedientesService.updatePostfirmaTask(expediente.id, task.id, { estatus: 'EN_PROCESO' }); onChanged(); } catch { setError('No pudimos actualizar el trámite.'); } finally { setSaving(false); } };
  if (!tasks.length && !editable) return null;
  return <section className={styles.sectionCard}><header><div><h2>Trámites de postfirma</h2><p>Gestiones externas reales vinculadas con el expediente.</p></div>{editable && <button type="button" className={styles.secondaryButton} onClick={() => setOpen(true)}><Plus size={16} />Nuevo trámite</button>}</header>{error && <div className={styles.inlineError} role="alert">{error}</div>}{tasks.length ? <div className={styles.postfirmaList}>{tasks.map((task: any) => <article key={task.id}><span className={task.estatus === 'COMPLETADA' ? styles.taskDone : task.estatus === 'BLOQUEADA' ? styles.taskBlocked : ''}>{task.estatus === 'COMPLETADA' ? <CheckCircle2 size={18} /> : task.estatus === 'BLOQUEADA' ? <CircleAlert size={18} /> : <Building2 size={18} />}</span><div><strong>{task.descripcion}</strong><small>{taskTypeLabels[task.tipo] || task.tipo} · {task.institucion}</small></div><div><b>{String(task.estatus || 'PENDIENTE').replaceAll('_', ' ').toLocaleLowerCase('es-MX')}</b><time>{task.fecha_limite ? `Límite ${dateTime(task.fecha_limite)}` : 'Sin fecha límite'}</time></div>{editable && task.estatus === 'PENDIENTE' && <button type="button" disabled={saving} onClick={() => void start(task)}>{saving ? <LoaderCircle className={styles.spin} size={15} /> : 'Iniciar'}</button>}</article>)}</div> : <p className={styles.sectionEmpty}>No hay trámites externos registrados.</p>}{open && <div className={styles.dialogBackdrop}><section className={styles.dialog} role="dialog" aria-modal="true" aria-label="Nuevo trámite de postfirma"><header><div><h2>Nuevo trámite de postfirma</h2><p>Registra únicamente una gestión externa que exista en la operación.</p></div></header><div className={styles.dialogBody}><label>Tipo<select value={type} onChange={(event) => setType(event.target.value)}>{Object.entries(taskTypeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Descripción<input value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Ej. Inscripción de escritura" /></label><label>Institución<input value={institution} onChange={(event) => setInstitution(event.target.value)} placeholder="Nombre de la institución" /></label><label>Fecha límite<input type="date" value={due} onChange={(event) => setDue(event.target.value)} /></label></div><footer><button type="button" className={styles.secondaryButton} onClick={() => setOpen(false)}>Cancelar</button><button type="button" className={styles.primaryButton} disabled={saving || !description.trim() || !institution.trim()} onClick={() => void create()}>{saving && <LoaderCircle className={styles.spin} size={15} />}Registrar trámite</button></footer></section></div>}</section>;
}
