import { Download, FileText, Upload } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import type { ComparecienteDetail } from '../comparecientes.types';
import { comparecientesService } from '../comparecientes.service';
import { StatusBadge } from '../components/ComparecienteTable';
import { Empty, SectionCard } from './SectionCard';
import styles from '../Comparecientes.module.css';

export function DocumentsTab({ item, onChanged, uploadSignal = 0 }: { item: ComparecienteDetail; onChanged(): void; uploadSignal?: number }) { const input = useRef<HTMLInputElement>(null); const [category, setCategory] = useState('OTROS'); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); useEffect(() => { if (uploadSignal) input.current?.click(); }, [uploadSignal]); const upload = async (file?: File) => { if (!file) return; setBusy(true); setMessage(''); try { await comparecientesService.uploadDocument(item.id, file, category); setMessage('Documento agregado correctamente.'); onChanged(); } catch { setMessage('No pudimos agregar el documento.'); } finally { setBusy(false); if (input.current) input.current.value = ''; } }; return <SectionCard title="Archivo documental" subtitle="Carga y descarga autenticadas; no se exponen rutas internas." action={<div className={styles.documentActions}><select value={category} onChange={(event) => setCategory(event.target.value)} aria-label="Categoría documental"><option value="IDENTIFICACION">Identificación</option><option value="FISCAL">Fiscal</option><option value="DOMICILIO">Domicilio</option><option value="PODERES">Poderes</option><option value="OTROS">Otros</option></select><button type="button" className={styles.secondaryButton} onClick={() => input.current?.click()} disabled={busy}><Upload size={15} />{busy ? 'Cargando…' : 'Agregar'}</button><input ref={input} hidden type="file" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx" onChange={(event) => void upload(event.target.files?.[0])} /></div>}>{message && <p className={styles.inlineMessage} role="status">{message}</p>}{item.documentos.length ? <div className={styles.documentTable}><div className={styles.documentHead}><span>Nombre</span><span>Tipo</span><span>Estado</span><span>Fecha</span><span>Acción</span></div>{item.documentos.map((link: any) => <article key={link.id}><div><FileText size={18} /><span><strong>{link.documento.nombre_original}</strong><small>{link.documento.mime_type} · {Math.max(1, Math.round(link.documento.size_bytes / 1024))} KB</small></span></div><span>{link.categoria}</span><StatusBadge state={['VENCIDO','RECHAZADO'].includes(link.documento.estatus) ? 'OBSERVACION' : link.fecha_validacion ? 'COMPLETO' : 'PENDIENTE'} /><time>{new Intl.DateTimeFormat('es-MX').format(new Date(link.documento.fecha_carga))}</time><button type="button" aria-label={`Descargar ${link.documento.nombre_original}`} onClick={() => void comparecientesService.downloadDocument(item.id, link.documento.id, link.documento.nombre_original)}><Download size={17} /></button></article>)}</div> : <Empty>No hay documentos vinculados. No existe un denominador global de requeridos para esta persona.</Empty>}</SectionCard>; }
