import { FolderPlus, Search, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { comparecientesService } from '../comparecientes.service';
import styles from '../Comparecientes.module.css';

type CaseOption = { id: string; numero_pravia: string; cliente_principal?: string; tipo_acto?: { nombre: string } };

export function LinkCaseDialog({ partyId, linkedIds, onClose, onLinked }: { partyId: string; linkedIds: string[]; onClose(): void; onLinked(): void }) {
  const [search, setSearch] = useState(''); const [cases, setCases] = useState<CaseOption[]>([]); const [characters, setCharacters] = useState<Array<{ id: string; nombre: string }>>([]); const [caseId, setCaseId] = useState(''); const [characterId, setCharacterId] = useState(''); const [notes, setNotes] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { const controller = new AbortController(); void Promise.all([comparecientesService.searchCases(search, controller.signal), comparecientesService.catalogs(controller.signal)]).then(([items, catalog]) => { setCases(items); setCharacters(catalog.caracteresCompareciente); if (!characterId) setCharacterId(catalog.caracteresCompareciente[0]?.id || ''); }).catch(() => setError('No pudimos cargar los expedientes disponibles.')); return () => controller.abort(); }, [search]);
  const submit = async () => { if (!caseId || !characterId) { setError('Selecciona un expediente y el carácter del compareciente.'); return; } setBusy(true); setError(''); try { await comparecientesService.linkCase(partyId, { expediente_id: caseId, caracter_id: characterId, observaciones: notes.trim() || undefined }); onLinked(); } catch { setError('No pudimos vincular el expediente. Revisa tu alcance e intenta nuevamente.'); } finally { setBusy(false); } };
  return <div className={styles.dialogBackdrop} role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className={`${styles.dialog} ${styles.linkDialog}`} role="dialog" aria-modal="true" aria-labelledby="link-case-title"><header><span className={styles.dialogIcon}><FolderPlus /></span><div><h2 id="link-case-title">Vincular expediente</h2><p>Busca un expediente dentro de tu alcance. Los ya vinculados permanecen identificados.</p></div><button type="button" className={styles.iconButton} aria-label="Cerrar" onClick={onClose}><X /></button></header><div className={styles.linkDialogBody}><label className={styles.formField}><span>Buscar expediente</span><div className={styles.caseSearch}><Search /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Número, acto o cliente…" /></div></label><div className={styles.caseOptions} role="radiogroup" aria-label="Expedientes disponibles">{cases.map((item) => { const linked = linkedIds.includes(item.id); return <label key={item.id} className={linked ? styles.caseLinked : ''}><input type="radio" name="expediente" value={item.id} disabled={linked} checked={caseId === item.id} onChange={() => setCaseId(item.id)} /><span><strong>{item.numero_pravia}</strong><small>{item.tipo_acto?.nombre || 'Acto sin clasificar'} · {item.cliente_principal || 'Sin cliente principal'}</small></span>{linked && <b>Ya vinculado</b>}</label>; })}{!cases.length && <p className={styles.sectionEmpty}>No encontramos expedientes accesibles.</p>}</div><label className={styles.formField}><span>Carácter en el expediente</span><select value={characterId} onChange={(event) => setCharacterId(event.target.value)}>{characters.map((item) => <option key={item.id} value={item.id}>{item.nombre}</option>)}</select></label><label className={styles.formField}><span>Observaciones opcionales</span><textarea value={notes} onChange={(event) => setNotes(event.target.value)} rows={3} /></label>{error && <p className={styles.formError} role="alert">{error}</p>}</div><footer><button type="button" className={styles.secondaryButton} onClick={onClose}>Cancelar</button><button type="button" className={styles.primaryButton} disabled={busy} onClick={() => void submit()}>{busy ? 'Vinculando…' : 'Vincular expediente'}</button></footer></section></div>;
}
