import { AlertTriangle, ArrowLeft, ArrowRight, Bot, Building2, Check, FileUp, LoaderCircle, UserRound, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { comparecientesService } from '../comparecientes.service';
import type { DuplicateCandidate, NewComparecienteDraft, PersonType } from '../comparecientes.types';
import { DuplicateCandidateDialog } from './DuplicateCandidateDialog';
import styles from '../Comparecientes.module.css';

const steps = ['Tipo', 'Identificación', 'Fiscal', 'Domicilio', 'Documentos', 'Revisión'];
const initial: NewComparecienteDraft = { tipo_persona: 'FISICA', nombre: '', apellido_paterno: '', apellido_materno: '', razon_social: '', rfc: '', curp: '', nacionalidad: 'Mexicana', pep_estado: 'PENDIENTE', correo: '', telefono: '', pais: 'México' };

function Field({ label, name, value, onChange, type = 'text', required, placeholder }: { label: string; name: string; value?: string; onChange(name: string, value: string): void; type?: string; required?: boolean; placeholder?: string }) { return <label className={styles.formField}><span>{label}{required && ' *'}</span><input name={name} type={type} value={value || ''} onChange={(event) => onChange(name, event.target.value)} required={required} placeholder={placeholder} /></label>; }

export function NewComparecienteFlow({ onClose, onCreated }: { onClose(): void; onCreated(id: string): void }) {
  const [step, setStep] = useState(0); const [draft, setDraft] = useState(initial); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [duplicates, setDuplicates] = useState<DuplicateCandidate[]>([]); const [override, setOverride] = useState(false); const [sessionId, setSessionId] = useState(''); const [docs, setDocs] = useState<Array<{ id: string; name: string }>>([]); const [aiProposal, setAiProposal] = useState<Record<string, any> | null>(null);
  const title = draft.tipo_persona === 'FISICA' ? [draft.nombre, draft.apellido_paterno, draft.apellido_materno].filter(Boolean).join(' ') : draft.razon_social;
  const canNext = useMemo(() => step === 0 || step === 1 ? draft.tipo_persona === 'FISICA' ? Boolean(draft.nombre.trim()) : Boolean(draft.razon_social.trim()) : true, [step, draft]);
  const change = (name: string, value: string) => { setDraft((current) => ({ ...current, [name]: value })); setOverride(false); };
  const selectType = (type: PersonType) => { setDraft({ ...initial, tipo_persona: type }); setStep(1); };

  const addDocuments = async (files: FileList | null) => { if (!files?.length) return; setBusy(true); setError(''); try { let active = sessionId; if (!active) { active = (await comparecientesService.startAssisted(draft.tipo_persona)).session.id; setSessionId(active); } const uploaded: Array<{ id: string; name: string }> = []; for (const file of Array.from(files)) { const response = await comparecientesService.uploadAssisted(active, file); uploaded.push({ id: response.documento.id, name: response.documento.nombre_original }); } setDocs((current) => [...current, ...uploaded]); } catch { setError('No pudimos cargar los documentos. Intenta nuevamente.'); } finally { setBusy(false); } };
  const extract = async () => { if (!sessionId || !docs.length) return; setBusy(true); setError(''); try { const response = await comparecientesService.extractAssisted(sessionId, docs.map((item) => item.id)); const proposal = response.borrador_actualizado || {}; setAiProposal(proposal._ia_propuesta || {}); setDraft((current) => ({ ...current, ...Object.fromEntries(Object.entries(proposal).filter(([, value]) => typeof value === 'string')), tipo_persona: current.tipo_persona })); } catch { setError('La extracción no pudo completarse. Tus datos permanecen sin cambios.'); } finally { setBusy(false); } };

  const submit = async (force = false) => { setBusy(true); setError(''); try { if (!override && !force) { const matches = await comparecientesService.duplicates(draft); if (matches.length) { setDuplicates(matches); setBusy(false); return; } } const response = sessionId ? await comparecientesService.confirmAssisted(sessionId, draft, docs.map((item) => item.id)) : await comparecientesService.create(draft).then((item) => ({ compareciente: item.data.compareciente })); onCreated(response.compareciente.id); } catch (err) { setError(err instanceof Error ? err.message : 'No pudimos crear el compareciente.'); setBusy(false); } };
  const continueOverride = () => { setDuplicates([]); setOverride(true); void submit(true); };

  return <><div className={styles.drawerBackdrop} role="presentation"><section className={styles.drawer} role="dialog" aria-modal="true" aria-labelledby="new-party-title"><header className={styles.drawerHeader}><div><span>Nuevo compareciente</span><h2 id="new-party-title">Nuevo compareciente</h2><p>Puedes crear el registro mínimo y completar su ficha después.</p></div><button type="button" aria-label="Cerrar" onClick={onClose}><X /></button></header><div className={styles.drawerBody}><ol className={styles.stepper}>{steps.map((label, index) => <li key={label} className={index === step ? styles.stepCurrent : index < step ? styles.stepDone : ''}><span>{index < step ? <Check size={14} /> : index + 1}</span><b>{label}</b></li>)}</ol>{error && <div className={styles.formError} role="alert"><AlertTriangle size={16} />{error}</div>}
      {step === 0 && <fieldset className={styles.flowStep}><legend>¿Qué tipo de persona vas a registrar?</legend><p>El formulario se adapta al modelo jurídico disponible.</p><div className={styles.personTypeGrid}><button type="button" onClick={() => selectType('FISICA')}><UserRound /><strong>Persona física</strong><span>Nombre, CURP, RFC e identificación.</span></button><button type="button" onClick={() => selectType('MORAL')}><Building2 /><strong>Persona moral</strong><span>Razón social, RFC y datos registrales.</span></button></div></fieldset>}
      {step === 1 && <fieldset className={styles.flowStep}><legend>Identificación principal</legend><p>Registra lo mínimo para localizar inequívocamente a la persona.</p><div className={styles.formGrid}>{draft.tipo_persona === 'FISICA' ? <><Field label="Nombre" name="nombre" value={draft.nombre} onChange={change} required /><Field label="Apellido paterno" name="apellido_paterno" value={draft.apellido_paterno} onChange={change} /><Field label="Apellido materno" name="apellido_materno" value={draft.apellido_materno} onChange={change} /><Field label="Fecha de nacimiento" name="fecha_nacimiento" type="date" value={draft.fecha_nacimiento} onChange={change} /></> : <><Field label="Razón social" name="razon_social" value={draft.razon_social} onChange={change} required /><Field label="Nombre comercial" name="nombre_comercial" value={draft.nombre_comercial} onChange={change} /><Field label="Tipo societario" name="tipo_societario" value={draft.tipo_societario} onChange={change} placeholder="S.A. de C.V." /><Field label="Fecha de constitución" name="fecha_constitucion" type="date" value={draft.fecha_constitucion} onChange={change} /></>}</div></fieldset>}
      {step === 2 && <fieldset className={styles.flowStep}><legend>Información fiscal y contacto</legend><p>RFC y CURP exactos bloquean duplicados; correo y teléfono generan advertencias.</p><div className={styles.formGrid}><Field label="RFC" name="rfc" value={draft.rfc} onChange={change} />{draft.tipo_persona === 'FISICA' && <Field label="CURP" name="curp" value={draft.curp} onChange={change} />} {draft.tipo_persona === 'MORAL' && <Field label="Folio mercantil" name="folio_mercantil" value={draft.folio_mercantil} onChange={change} />}<Field label="Correo" name="correo" type="email" value={draft.correo} onChange={change} /><Field label="Teléfono" name="telefono" type="tel" value={draft.telefono} onChange={change} /><Field label="Nacionalidad" name="nacionalidad" value={draft.nacionalidad} onChange={change} /></div></fieldset>}
      {step === 3 && <fieldset className={styles.flowStep}><legend>Domicilio principal</legend><p>Esta sección es opcional para el alta rápida.</p><div className={styles.formGrid}><Field label="Calle" name="calle" value={draft.calle} onChange={change} /><Field label="Número exterior" name="exterior" value={draft.exterior} onChange={change} /><Field label="Número interior" name="interior" value={draft.interior} onChange={change} /><Field label="Colonia" name="colonia" value={draft.colonia} onChange={change} /><Field label="Municipio" name="municipio" value={draft.municipio} onChange={change} /><Field label="Estado" name="estado" value={draft.estado} onChange={change} /><Field label="Código postal" name="codigo_postal" value={draft.codigo_postal} onChange={change} /><Field label="País" name="pais" value={draft.pais} onChange={change} /></div></fieldset>}
      {step === 4 && <fieldset className={styles.flowStep}><legend>Documentos y extracción asistida</legend><p>La IA solo propone datos. Nada jurídico se confirma sin tu revisión.</p><label className={styles.uploadZone}><FileUp /><strong>{busy ? 'Procesando…' : 'Seleccionar documentos'}</strong><span>PDF, JPG o PNG · máximo 25 MB por archivo</span><input type="file" multiple accept=".pdf,.jpg,.jpeg,.png" disabled={busy} onChange={(event) => void addDocuments(event.target.files)} /></label>{docs.length > 0 && <div className={styles.uploadedDocs}>{docs.map((doc) => <span key={doc.id}><FileUp size={14} />{doc.name}</span>)}<button type="button" onClick={() => void extract()} disabled={busy}><Bot size={16} />Extraer datos con IA</button></div>}{aiProposal && <section className={styles.aiReview}><header><Bot size={18} /><div><strong>Datos propuestos</strong><span>Revisados por una persona antes de confirmar</span></div></header>{Object.entries(aiProposal).slice(0, 8).map(([key, proposal]: [string, any]) => <article key={key} className={proposal?.estado === 'EN_CONFLICTO' ? styles.conflict : ''}><div><small>{key.replaceAll('_', ' ')}</small><strong>{proposal?.valor || 'Sin valor único'}</strong></div><span>{proposal?.estado === 'EN_CONFLICTO' ? 'Conflicto · revisar' : proposal?.fuente || 'Documento cargado'}</span></article>)}</section>}</fieldset>}
      {step === 5 && <fieldset className={styles.flowStep}><legend>Revisión humana</legend><p>Confirma que los datos corresponden a la persona correcta.</p><dl className={styles.reviewList}><div><dt>Tipo</dt><dd>{draft.tipo_persona === 'FISICA' ? 'Persona física' : 'Persona moral'}</dd></div><div><dt>Nombre</dt><dd>{title}</dd></div><div><dt>RFC</dt><dd>{draft.rfc || 'Pendiente'}</dd></div>{draft.tipo_persona === 'FISICA' && <div><dt>CURP</dt><dd>{draft.curp || 'Pendiente'}</dd></div>}<div><dt>Documentos</dt><dd>{docs.length ? `${docs.length} para integrar` : 'Sin documentos; completar después'}</dd></div><div><dt>Confirmación</dt><dd>{aiProposal ? 'Propuestas de IA revisadas por usuario' : 'Captura manual'}</dd></div></dl></fieldset>}
    </div><footer className={styles.drawerFooter}>{step > 0 ? <button type="button" className={styles.secondaryButton} onClick={() => setStep((value) => value - 1)} disabled={busy}><ArrowLeft size={16} />Anterior</button> : <span /> }<span />{step < steps.length - 1 ? <button type="button" className={styles.primaryButton} onClick={() => setStep((value) => value + 1)} disabled={!canNext || busy}>Siguiente<ArrowRight size={16} /></button> : <button type="button" className={styles.primaryButton} onClick={() => void submit()} disabled={busy}>{busy ? <LoaderCircle className={styles.spin} size={16} /> : <Check size={16} />}Crear compareciente</button>}</footer></section></div>{duplicates.length > 0 && <DuplicateCandidateDialog items={duplicates} onCancel={() => setDuplicates([])} onContinue={continueOverride} />}</>;
}
