import { AlertTriangle, Check, ChevronDown, GitBranch, Link2, LoaderCircle, Network, Plus, Save, Search, Sparkles, Trash2, UserPlus, X } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import {
  comparecientesService, type ControlFact, type OwnershipAiProposal, type OwnershipEdge,
  type OwnershipReconciliationPreview, type OwnershipGraph, type OwnershipLinkPreview, type OwnershipNode, type OwnershipStructure,
} from '../comparecientes.service';
import styles from './OwnershipStructureEditor.module.css';

const uuid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const empty=(comparecienteId:string,name:string):OwnershipStructure=>{const root=uuid();return {configured:false,root_node_id:root,revision:0,fingerprint:null,incomplete_markers:['EMPTY_STRUCTURE'],reconciliations:[],nodes:[{id:root,party_kind:'PM',identity_mode:'LINKED',linked_compareciente_id:comparecienteId,canonical_label:name,metadata:{}}],edges:[],controls:[]}};
const nodeName=(node:OwnershipNode,index:number)=>String(node.canonical_label||node.display_name||(node.metadata?.label as string)||`${node.party_kind==='PF'?'Persona física':'Persona moral'} ${index+1}`);
const graphOf=(value:OwnershipStructure|OwnershipGraph):OwnershipGraph=>({root_node_id:value.root_node_id,nodes:value.nodes,edges:value.edges,controls:value.controls,incomplete_markers:value.incomplete_markers});

const controlLabels:Record<ControlFact['kind'],string>={VOTE:'Voto',APPOINTMENT:'Designación',MANAGEMENT:'Dirección',AGREEMENT:'Acuerdo',OTHER:'Otro'};
/** A read projection shared by confirmation and diagram; never an editable second graph. */
function GraphReview({graph,before,title,documents}:{graph:OwnershipGraph;before?:OwnershipGraph;title:string;documents:Array<{id:string;name:string}>}){
  const names=new Map(graph.nodes.map((node,index)=>[node.id,nodeName(node,index)]));
  const priorNames=new Map((before?.nodes||[]).map((node,index)=>[node.id,nodeName(node,index)]));
  const changes=<T extends {id:string}>(next:T[],prior:T[]=[])=>[
    ...next.map(item=>({item,operation:!before?'':!prior.some(old=>old.id===item.id)?'Agregar':JSON.stringify(prior.find(old=>old.id===item.id))===JSON.stringify(item)?'Sin cambios':'Actualizar'})),
    ...prior.filter(item=>!next.some(row=>row.id===item.id)).map(item=>({item,operation:'Eliminar'})),
  ];
  const evidence=(item:OwnershipEdge|ControlFact)=>item.evidence_document_id
    ? `Fuente: ${documents.find(doc=>doc.id===item.evidence_document_id)?.name||item.evidence_document_id} · versión: ${item.evidence_document_version||'se verificará al guardar'} · huella: ${item.evidence_document_checksum||'se verificará al guardar'}`
    : 'Sin documento de soporte';
  return <section className={styles.graphReview} aria-label={title}><h4>{title}</h4>
    {changes(graph.nodes,before?.nodes).map(({item,operation},index)=><article key={item.id}><strong>{operation&&`${operation}: `}{nodeName(item,index)}</strong><small>{item.party_kind==='PF'?'Persona física':'Persona moral'} · {item.identity_mode==='LINKED'?'Ficha canónica vinculada':'Identidad estructurada'}</small>{item.linked_compareciente_id&&<a href={`/comparecientes/${encodeURIComponent(item.linked_compareciente_id)}`}>Abrir ficha de {nodeName(item,index)}</a>}{item.incomplete&&<small>Identidad incompleta</small>}{Object.keys(item.metadata||{}).length>0&&<dl>{Object.entries(item.metadata!).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{typeof value==='object'?JSON.stringify(value):String(value)}</dd></div>)}</dl>}</article>)}
    <ul>{changes(graph.edges,before?.edges).map(({item,operation})=><li key={item.id}><strong>{operation&&`${operation}: `}{names.get(item.owner_node_id)||priorNames.get(item.owner_node_id)} → {names.get(item.owned_node_id)||priorNames.get(item.owned_node_id)} · {item.percentage===null||item.percentage===undefined?'Porcentaje desconocido':`${item.percentage}%`}</strong><small>{evidence(item)}</small></li>)}
    {changes(graph.controls,before?.controls).map(({item,operation})=><li key={item.id}><strong>{operation&&`${operation}: `}{names.get(item.subject_node_id)||priorNames.get(item.subject_node_id)} · {controlLabels[item.kind]}</strong><p>{item.description||'Descripción pendiente'}</p><small>{item.human_confirmed?'Confirmación humana registrada':'Sin confirmación humana'} · {evidence(item)}</small></li>)}</ul>
    {(graph.incomplete_markers||[]).length>0&&<p role="note">Estructura incompleta: {(graph.incomplete_markers||[]).length} señales de ramas desconocidas, ciclos o hechos pendientes; requieren revisión en la ficha canónica.</p>}
  </section>;
}

type SearchOption={id:string;nombre:string;rfc?:string|null;curp?:string|null;tipo_persona:'FISICA'|'MORAL'};
function LinkedPartySelector({node,disabled,onSelect}:{node:OwnershipNode;disabled:boolean;onSelect:(option:SearchOption)=>void}){
  const [query,setQuery]=useState(node.canonical_label||'');const [options,setOptions]=useState<SearchOption[]>([]);const [loading,setLoading]=useState(false);
  useEffect(()=>{if(disabled||query.trim().length<2||query===node.canonical_label){setOptions([]);return}const controller=new AbortController();const timer=window.setTimeout(()=>{setLoading(true);void comparecientesService.searchMaster(query,controller.signal).then(result=>setOptions(result.filter(option=>(node.party_kind==='PF'?option.tipo_persona==='FISICA':option.tipo_persona==='MORAL')))).catch(()=>setOptions([])).finally(()=>setLoading(false))},180);return()=>{controller.abort();window.clearTimeout(timer)}},[disabled,node.canonical_label,node.party_kind,query]);
  return <div className={styles.partySearch}><label><span>Compareciente canónico</span><div><Search/><input aria-label="Buscar compareciente canónico" value={query} disabled={disabled} placeholder="Buscar por nombre, RFC o CURP" onChange={event=>setQuery(event.target.value)}/>{loading&&<LoaderCircle className={styles.spin}/>}</div></label>{options.length>0&&<div className={styles.searchResults} role="listbox" aria-label="Comparecientes disponibles">{options.map(option=><button type="button" role="option" aria-selected={node.linked_compareciente_id===option.id} key={option.id} onClick={()=>{onSelect(option);setQuery(option.nombre);setOptions([])}}><strong>{option.nombre}</strong><small>{option.rfc||option.curp||'Identificador pendiente'} · {option.tipo_persona==='FISICA'?'Persona física':'Persona moral'}</small></button>)}</div>} {!disabled&&<a className={styles.createLink} href="/comparecientes/nuevo" target="_blank" rel="noreferrer"><UserPlus/>Crear compareciente en una nueva pestaña</a>}</div>;
}

export function OwnershipStructureEditor({comparecienteId,name,canWrite,canUseAi=false,documents}:{comparecienteId:string;name:string;canWrite:boolean;canUseAi?:boolean;documents:Array<{id:string;name:string}>}){
  const [value,setValue]=useState<OwnershipStructure|null>(null);const [status,setStatus]=useState<'loading'|'ready'|'error'>('loading');const [busy,setBusy]=useState('');const [message,setMessage]=useState('');const [previews,setPreviews]=useState<OwnershipLinkPreview[]>([]);const [aiDocument,setAiDocument]=useState('');const [aiProposal,setAiProposal]=useState<OwnershipAiProposal|null>(null);const [aiReviewed,setAiReviewed]=useState(false);const [reconciliationPreviews,setReconciliationPreviews]=useState<Record<string,OwnershipReconciliationPreview>>({});
  const load=useCallback(async(signal?:AbortSignal)=>{try{const result=await comparecientesService.ownershipStructure(comparecienteId,signal);setValue(result.configured?result:empty(comparecienteId,name));setStatus('ready')}catch(error){if(!(error instanceof DOMException&&error.name==='AbortError'))setStatus('error')}},[comparecienteId,name]);
  useEffect(()=>{const controller=new AbortController();void load(controller.signal);return()=>controller.abort()},[load]);
  const updateNode=(id:string,patch:Partial<OwnershipNode>)=>setValue(current=>current?{...current,nodes:current.nodes.map(node=>node.id===id?{...node,...patch}:node)}:current);
  const removeNode=(id:string)=>setValue(current=>current?{...current,nodes:current.nodes.filter(node=>node.id!==id),edges:current.edges.filter(edge=>edge.owner_node_id!==id&&edge.owned_node_id!==id),controls:current.controls.filter(fact=>fact.subject_node_id!==id)}:current);
  const updateEdge=(id:string,patch:Partial<OwnershipEdge>)=>setValue(current=>current?{...current,edges:current.edges.map(edge=>edge.id===id?{...edge,...patch}:edge)}:current);
  const updateControl=(id:string,patch:Partial<ControlFact>)=>setValue(current=>current?{...current,controls:current.controls.map(fact=>fact.id===id?{...fact,...patch}:fact)}:current);
  const persist=async(identityConfirmations:Record<string,string>={})=>{if(!value)return;setBusy('save');setMessage('');try{const result=await comparecientesService.saveOwnershipStructure(comparecienteId,{...graphOf(value),expected_revision:value.revision,idempotency_key:uuid(),identity_confirmations:identityConfirmations});setValue({...result,configured:true});setPreviews([]);setMessage('Estructura guardada. Las conclusiones jurídicas requieren una evaluación explícita.')}catch(error){setMessage(error instanceof Error?error.message:'No fue posible guardar la estructura.')}finally{setBusy('')}};
  const prepareSave=async()=>{if(!value)return;setBusy('preview');setMessage('');try{const result=await comparecientesService.previewOwnershipLinks(comparecienteId,graphOf(value));if(result.length){setPreviews(result);setBusy('')}else await persist()}catch(error){setMessage(error instanceof Error?error.message:'No fue posible validar los vínculos.');setBusy('')}};
  const previewReconciliation=async(proposalId:string)=>{setBusy(proposalId);setMessage('');try{const preview=await comparecientesService.previewOwnershipReconciliation(comparecienteId,proposalId);setReconciliationPreviews(current=>({...current,[proposalId]:preview}))}catch(error){setMessage(error instanceof Error?error.message:'No fue posible revisar la conciliación.')}finally{setBusy('')}};
  const decideReconciliation=async(proposalId:string,decision:'ACCEPTED'|'REJECTED')=>{if(!value)return;const preview=reconciliationPreviews[proposalId];if(decision==='ACCEPTED'&&!preview)return;setBusy(proposalId);setMessage('');try{await comparecientesService.decideOwnershipReconciliation(comparecienteId,proposalId,{decision,graph:decision==='ACCEPTED'?preview.proposed:undefined,...(decision==='ACCEPTED'?{review_token:preview.review_token}:{})});await load();setReconciliationPreviews({});setMessage(decision==='ACCEPTED'?'Los cambios revisados se incorporaron a la estructura canónica vinculada.':'La propuesta de conciliación fue descartada.')}catch(error){setReconciliationPreviews({});setMessage(error instanceof Error?error.message:'No fue posible registrar la decisión.')}finally{setBusy('')}};
  const prepareAi=async()=>{if(!aiDocument)return;setBusy('ai');setMessage('');try{const proposal=await comparecientesService.proposeOwnershipAi(comparecienteId,aiDocument);setAiProposal(proposal);setAiReviewed(false);setMessage('La IA preparó una propuesta. No se ha modificado la estructura.')}catch(error){setMessage(error instanceof Error?error.message:'No fue posible preparar la propuesta.')}finally{setBusy('')}};
  const decideAi=async(decision:'CONFIRMED'|'REJECTED')=>{if(!aiProposal||(decision==='CONFIRMED'&&!aiReviewed))return;setBusy('ai-decision');setMessage('');try{await comparecientesService.decideOwnershipAi(comparecienteId,aiProposal.id,{decision,graph:decision==='CONFIRMED'?aiProposal.proposed_changes.graph:undefined,...(decision==='CONFIRMED'?{review_token:aiProposal.review_token}:{})});setAiProposal(null);if(decision==='CONFIRMED')await load();setMessage(decision==='CONFIRMED'?'Propuesta confirmada por una persona y guardada.':'Propuesta rechazada sin modificar la estructura.')}catch(error){setMessage(error instanceof Error?error.message:'No fue posible registrar la decisión.')}finally{setBusy('')}};
  if(status==='loading')return <section className={styles.card} aria-label="Estructura de propiedad y control"><p className={styles.state}><LoaderCircle className={styles.spin}/>Cargando estructura…</p></section>;
  if(status==='error'||!value)return <section className={styles.card} aria-label="Estructura de propiedad y control"><p className={styles.state} role="alert"><AlertTriangle/>No pudimos consultar la estructura dentro de tus permisos.</p></section>;
  const root=value.nodes.find(node=>node.id===value.root_node_id);
  const pendingReconciliations=value.reconciliations.filter(item=>item.status==='PENDING');
  return <section className={styles.card} aria-labelledby="ownership-title">
    <header><div><span>CUM-BC-001</span><h2 id="ownership-title">Estructura de propiedad y control</h2><p>Registra hechos corporativos actuales. Esto no determina por sí solo al beneficiario controlador.</p></div>{canWrite&&<button type="button" onClick={()=>void prepareSave()} disabled={Boolean(busy)}><Save/>{busy==='preview'||busy==='save'?'Validando…':'Guardar estructura'}</button>}</header>
    {!canWrite&&<p className={styles.readOnly}>Vista de solo lectura. La estructura y sus fuentes no pueden modificarse con tus permisos actuales.</p>}
    {message&&<p className={styles.message} role="status">{message}</p>}
    {value.incomplete_markers.length>0&&<div className={styles.notice}><AlertTriangle/><span><strong>Estructura incompleta</strong><small>Puede guardarse para revisión; no se emitirá una conclusión automática. {value.incomplete_markers.length} señal{value.incomplete_markers.length===1?'':'es'} pendiente{value.incomplete_markers.length===1?'':'s'}.</small></span></div>}
    {previews.length>0&&<section className={styles.confirmPanel} aria-labelledby="identity-confirmation-title"><div><h3 id="identity-confirmation-title">Confirma las identidades canónicas</h3><p>El vínculo usará la ficha maestra seleccionada y su estructura vigente.</p></div><ul>{previews.map(preview=><li key={preview.node_id}><Check/><span><strong>Identidad canónica: {preview.canonical_identity.nombre}</strong><small>Identidad local anterior: {preview.before?nodeName(preview.before,0):'Sin identidad previa'}</small><small>{preview.canonical_identity.tipo_persona==='FISICA'?'Persona física':'Persona moral'} · revisión vinculada {preview.target_structure_revision}</small></span></li>)}</ul><div><button type="button" onClick={()=>setPreviews([])}><X/>Cancelar</button><button type="button" onClick={()=>void persist(Object.fromEntries(previews.map(preview=>[preview.node_id,preview.confirmation])))} disabled={busy==='save'}><Check/>Confirmar y guardar</button></div></section>}
    <div className={styles.block}><div className={styles.blockTitle}><div><GitBranch/><span><strong>Personas y entidades</strong><small>{value.nodes.length} nodos · raíz explícita</small></span></div>{canWrite&&<button type="button" onClick={()=>setValue(current=>current?{...current,nodes:[...current.nodes,{id:uuid(),party_kind:'PF',identity_mode:'STRUCTURED_ONLY',display_name:'',incomplete:true,metadata:{}}]}:current)}><Plus/>Agregar</button>}</div>
      <div className={styles.nodes}>{value.nodes.map((node,index)=><article key={node.id} className={node.id===value.root_node_id?styles.root:''}><div className={styles.nodeHead}><span>{node.id===value.root_node_id?'Entidad analizada':node.party_kind==='PF'?'Persona física':'Persona moral'}</span>{canWrite&&node.id!==value.root_node_id&&<button type="button" aria-label={`Eliminar ${nodeName(node,index)}`} onClick={()=>removeNode(node.id)}><Trash2/></button>}</div>{node.id===value.root_node_id?<strong>{nodeName(node,index)}</strong>:node.identity_mode==='LINKED'?<LinkedPartySelector node={node} disabled={!canWrite} onSelect={option=>updateNode(node.id,{linked_compareciente_id:option.id,canonical_label:option.nombre,party_kind:option.tipo_persona==='FISICA'?'PF':'PM',display_name:null,incomplete:false})}/>:<label className={styles.textField}><span>Nombre o razón social</span><input aria-label={`Nombre del nodo ${index+1}`} value={node.display_name||''} placeholder="Dato estructurado sin ficha maestra" readOnly={!canWrite} onChange={event=>updateNode(node.id,{display_name:event.target.value,incomplete:!event.target.value.trim()})}/></label>}<div className={styles.nodeOptions}><label>Tipo<select value={node.party_kind} disabled={!canWrite||node.id===value.root_node_id} onChange={event=>updateNode(node.id,{party_kind:event.target.value as 'PF'|'PM',linked_compareciente_id:null,canonical_label:null})}><option value="PF">Persona física</option><option value="PM">Persona moral</option></select></label><label>Identidad<select value={node.identity_mode} disabled={!canWrite||node.id===value.root_node_id} onChange={event=>updateNode(node.id,{identity_mode:event.target.value as 'LINKED'|'STRUCTURED_ONLY',linked_compareciente_id:null,canonical_label:null,display_name:event.target.value==='STRUCTURED_ONLY'?(node.display_name||''):null,incomplete:true})}><option value="STRUCTURED_ONLY">Dato estructurado</option><option value="LINKED">Compareciente vinculado</option></select></label></div></article>)}</div>
    </div>
    <div className={styles.block}><div className={styles.blockTitle}><div><Link2/><span><strong>Propiedad</strong><small>Dirección: propietario → entidad poseída</small></span></div>{canWrite&&value.nodes.length>1&&root&&<button type="button" onClick={()=>setValue(current=>current?{...current,edges:[...current.edges,{id:uuid(),owner_node_id:current.nodes.find(node=>node.id!==current.root_node_id)!.id,owned_node_id:current.root_node_id,percentage:null}]}:current)}><Plus/>Relación</button>}</div>
      {value.edges.length===0?<p className={styles.empty}>No hay relaciones de propiedad registradas.</p>:<div className={styles.rows}>{value.edges.map(edge=><div key={edge.id}><select aria-label="Propietario" value={edge.owner_node_id} disabled={!canWrite} onChange={event=>updateEdge(edge.id,{owner_node_id:event.target.value})}>{value.nodes.map((node,index)=><option key={node.id} value={node.id}>{nodeName(node,index)}</option>)}</select><span>posee a</span><select aria-label="Entidad poseída" value={edge.owned_node_id} disabled={!canWrite} onChange={event=>updateEdge(edge.id,{owned_node_id:event.target.value})}>{value.nodes.map((node,index)=><option key={node.id} value={node.id}>{nodeName(node,index)}</option>)}</select><label><input aria-label="Porcentaje de propiedad" type="number" min="0" max="100" step="0.000001" value={edge.percentage??''} placeholder="Desconocido" readOnly={!canWrite} onChange={event=>updateEdge(edge.id,{percentage:event.target.value||null})}/><span>%</span></label><select aria-label="Documento de evidencia de propiedad" value={edge.evidence_document_id||''} disabled={!canWrite} onChange={event=>updateEdge(edge.id,{evidence_document_id:event.target.value||null})}><option value="">Sin evidencia</option>{documents.map(document=><option key={document.id} value={document.id}>{document.name}</option>)}</select>{canWrite&&<button type="button" aria-label="Eliminar relación" onClick={()=>setValue(current=>current?{...current,edges:current.edges.filter(item=>item.id!==edge.id)}:current)}><Trash2/></button>}</div>)}</div>}
    </div>
    <div className={styles.block}><div className={styles.blockTitle}><div><Network/><span><strong>Hechos de control</strong><small>Separados de los porcentajes de propiedad</small></span></div>{canWrite&&value.nodes.length>0&&<button type="button" onClick={()=>setValue(current=>current?{...current,controls:[...current.controls,{id:uuid(),subject_node_id:current.nodes[0].id,kind:'OTHER',description:'',human_confirmed:false}]}:current)}><Plus/>Hecho</button>}</div>
      {value.controls.length===0?<p className={styles.empty}>No hay hechos de control registrados.</p>:<div className={styles.controls}>{value.controls.map(fact=><div key={fact.id}><select aria-label="Persona con control" value={fact.subject_node_id} disabled={!canWrite} onChange={event=>updateControl(fact.id,{subject_node_id:event.target.value})}>{value.nodes.map((node,index)=><option key={node.id} value={node.id}>{nodeName(node,index)}</option>)}</select><select aria-label="Tipo de control" value={fact.kind} disabled={!canWrite} onChange={event=>updateControl(fact.id,{kind:event.target.value as ControlFact['kind']})}><option value="VOTE">Voto</option><option value="APPOINTMENT">Designación</option><option value="MANAGEMENT">Dirección</option><option value="AGREEMENT">Acuerdo</option><option value="OTHER">Otro</option></select><input aria-label="Descripción del control" value={fact.description||''} placeholder="Describe el hecho verificable" readOnly={!canWrite} onChange={event=>updateControl(fact.id,{description:event.target.value})}/><select aria-label="Documento de evidencia del control" value={fact.evidence_document_id||''} disabled={!canWrite} onChange={event=>updateControl(fact.id,{evidence_document_id:event.target.value||null,human_confirmed:Boolean(event.target.value)})}><option value="">Sin evidencia</option>{documents.map(document=><option key={document.id} value={document.id}>{document.name}</option>)}</select>{fact.kind==='OTHER'&&<label className={styles.confirmCheck}><input type="checkbox" checked={Boolean(fact.human_confirmed)} disabled={!canWrite||!fact.evidence_document_id} onChange={event=>updateControl(fact.id,{human_confirmed:event.target.checked})}/>Confirmado por una persona</label>}{canWrite&&<button type="button" aria-label="Eliminar hecho de control" onClick={()=>setValue(current=>current?{...current,controls:current.controls.filter(item=>item.id!==fact.id)}:current)}><Trash2/></button>}</div>)}</div>}
    </div>
    {pendingReconciliations.length>0&&<section className={styles.block} aria-labelledby="reconciliation-title"><div className={styles.blockTitle}><div><GitBranch/><span><h3 id="reconciliation-title">Conciliaciones pendientes</h3><small>La estructura canónica vinculada prevalece hasta una decisión humana.</small></span></div></div><div className={styles.reconciliations}>{pendingReconciliations.map(item=><article key={item.id}><div><strong>Rama local por revisar</strong><small>Propuesta basada en la revisión canónica {item.target_revision}</small></div>{canWrite&&<div><button type="button" onClick={()=>void decideReconciliation(item.id,'REJECTED')} disabled={busy===item.id}>Descartar</button><button type="button" onClick={()=>void previewReconciliation(item.id)} disabled={Boolean(busy)}>Revisar cambios</button><button type="button" onClick={()=>void decideReconciliation(item.id,'ACCEPTED')} disabled={Boolean(busy)||!reconciliationPreviews[item.id]}>Confirmar cambios e incorporar</button></div>}{reconciliationPreviews[item.id]&&<div className={styles.reviewStack}><GraphReview title="Rama local de origen" graph={reconciliationPreviews[item.id].local} documents={documents}/><GraphReview title="Destino canónico actual" graph={reconciliationPreviews[item.id].current} documents={documents}/><GraphReview title="Cambios propuestos para confirmar" graph={reconciliationPreviews[item.id].proposed} before={reconciliationPreviews[item.id].current} documents={documents}/></div>}</article>)}</div></section>}
    {canWrite&&canUseAi&&documents.length>0&&<section className={styles.block} aria-labelledby="ai-proposal-title"><div className={styles.blockTitle}><div><Sparkles/><span><h3 id="ai-proposal-title">Propuesta asistida desde documento</h3><small>La IA sólo prepara hechos para revisión; nunca modifica la estructura sin confirmación.</small></span></div></div><div className={styles.aiBar}><select aria-label="Documento fuente para propuesta IA" value={aiDocument} onChange={event=>setAiDocument(event.target.value)}><option value="">Selecciona un documento autorizado</option>{documents.map(document=><option key={document.id} value={document.id}>{document.name}</option>)}</select><button type="button" disabled={!aiDocument||Boolean(busy)} onClick={()=>void prepareAi()}><Sparkles/>{busy==='ai'?'Preparando…':'Preparar propuesta'}</button></div>{aiProposal&&<div className={styles.aiReview}><div><strong>Propuesta pendiente de revisión humana</strong><small>{aiProposal.proposed_changes.graph.nodes.length} nodos · {aiProposal.proposed_changes.graph.edges.length} relaciones · páginas fuente: {aiProposal.source_pages.join(', ')||'sin referencia verificable'}</small></div><GraphReview title="Hechos propuestos por IA" graph={aiProposal.proposed_changes.graph} before={graphOf(value)} documents={documents}/><label className={styles.confirmCheck}><input type="checkbox" checked={aiReviewed} onChange={event=>setAiReviewed(event.target.checked)}/>He revisado identidades, porcentajes, control, fuentes y cambios</label><div><button type="button" onClick={()=>{setValue(current=>current?{...current,...aiProposal.proposed_changes.graph,expanded:undefined}:current);setAiProposal(null);setPreviews([]);setMessage('Propuesta cargada en el editor. Corrige los hechos y usa Guardar estructura para revisar y confirmar. No se ha guardado ningún cambio.')}} disabled={Boolean(busy)}>Corregir en editor</button><button type="button" onClick={()=>void decideAi('REJECTED')} disabled={busy==='ai-decision'}>Rechazar</button><button type="button" onClick={()=>void decideAi('CONFIRMED')} disabled={Boolean(busy)||!aiReviewed||!aiProposal.review_token}><Check/>Confirmar propuesta</button></div></div>}</section>}
    <details className={styles.diagram}><summary><span><Network/>Vista derivada de la estructura</span><ChevronDown/></summary><div><p>Proyección de la estructura canónica guardada y sus ramas vinculadas. Los cambios locales se reflejarán al guardar; esta vista no se edita ni se guarda por separado.</p><GraphReview title="Expansión canónica" graph={value.expanded||value} documents={documents}/></div></details>
    <footer><span>Revisión {value.revision}</span><span>{value.fingerprint?`Huella ${value.fingerprint.slice(0,12)}…`:'Aún no guardada'}</span><span>{value.expanded_fingerprint?'Expansión canónica disponible':'Sin expansión canónica adicional'}</span></footer>
  </section>;
}
