import { ArrowLeft, Bot, Building2, ExternalLink, FilePlus2, GripVertical, LoaderCircle, Plus, Save, Trash2, X } from 'lucide-react';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom';
import { useAuth } from '../auth/AuthProvider';
import { resolveExpedienteCreationContext, resolveExpedienteReturn } from '../cases/expedienteNavigation';
import { propertiesService } from './properties.service';
import type { PropertyAIReview, PropertyBoundary, PropertyForm, PropertyRecord } from './properties.types';
import styles from './PropertyWorkspace.module.css';

const blank: PropertyForm = { apodo: '', clave_catastral: '', cuenta_predial: '', folio_real: '', datos_registrales_texto: '', ubicacion_texto: '', calle: '', numero_exterior: '', numero_interior: '', colonia: '', localidad: '', municipio: '', estado: '', codigo_postal: '', pais: 'México', superficie_terreno_m2: '', superficie_construccion_m2: '', superficie_construccion_comercial_m2: '', valor_catastral: '', valor_avaluo: '', valor_operacion: '', regimen: '', descripcion: '', colindancias: [] };
const fieldLabels: Record<string, string> = { apodo: 'Apodo', clave_catastral: 'Clave catastral', cuenta_predial: 'Cuenta predial', folio_real: 'Folio real', datos_registrales: 'Datos registrales', ubicacion_texto: 'Ubicación', calle: 'Calle', numero_exterior: 'Número exterior', numero_interior: 'Número interior', colonia: 'Colonia', localidad: 'Localidad', municipio: 'Municipio', estado: 'Estado', codigo_postal: 'Código postal', pais: 'País', superficie_terreno_m2: 'Superficie de terreno', superficie_construccion_m2: 'Superficie de construcción', superficie_construccion_comercial_m2: 'Componente comercial', valor_catastral: 'Valor fiscal / catastral', valor_avaluo: 'Avalúo', valor_operacion: 'Valor de operación', regimen: 'Régimen', descripcion: 'Descripción', colindancias: 'Medidas y colindancias' };

const toForm = (record: PropertyRecord): PropertyForm => ({ ...record, datos_registrales_texto: record.datos_registrales ? JSON.stringify(record.datos_registrales, null, 2) : '', colindancias: record.colindancias || [], expected_version: record.version });
const displayValue = (value?: string | null) => value || 'Sin dato registrado';

export function PropertyWorkspace() {
  const { id } = useParams(); const isNew = !id || id === 'nuevo'; const location = useLocation(); const navigate = useNavigate(); const { user } = useAuth();
  const creationContext = resolveExpedienteCreationContext(location.search); const returnPath = resolveExpedienteReturn(location.search) || '/expedientes';
  const [record, setRecord] = useState<PropertyRecord | null>(null); const [form, setForm] = useState<PropertyForm>(blank);
  const [status, setStatus] = useState<'loading' | 'ready' | 'error'>(isNew ? 'ready' : 'loading'); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  const [documentFile, setDocumentFile] = useState<File | null>(null); const [documentType, setDocumentType] = useState('TÍTULO / ESCRITURA'); const [uploading, setUploading] = useState(false);
  const [sourceDocumentId, setSourceDocumentId] = useState(''); const [analyzing, setAnalyzing] = useState(false); const [review, setReview] = useState<PropertyAIReview | null>(null); const [decisions, setDecisions] = useState<Record<string, 'ACCEPT' | 'KEEP'>>({});
  const firstField = useRef<HTMLInputElement | null>(null); const canWrite = Boolean(user?.permissions?.includes('expedientes.write'));

  useEffect(() => { if (isNew) { firstField.current?.focus(); return; } const controller = new AbortController(); propertiesService.get(id!, controller.signal).then((data) => { setRecord(data); setForm(toForm(data)); setStatus('ready'); }).catch(() => setStatus('error')); return () => controller.abort(); }, [id, isNew]);
  const update = (field: keyof PropertyForm, value: unknown) => setForm((current) => ({ ...current, [field]: value }));
  const addBoundary = () => update('colindancias', [...(form.colindancias || []), { referencia: '', medida: '', unidad: 'm', colindante: '', descripcion: '' }]);
  const updateBoundary = (index: number, field: keyof PropertyBoundary, value: string) => update('colindancias', (form.colindancias || []).map((item, position) => position === index ? { ...item, [field]: value } : item));
  const removeBoundary = (index: number) => update('colindancias', (form.colindancias || []).filter((_, position) => position !== index));
  const moveBoundary = (index: number, direction: -1 | 1) => { const next = [...(form.colindancias || [])]; const target = index + direction; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; update('colindancias', next); };
  const payload = useMemo(() => ({ ...form, datos_registrales: form.datos_registrales_texto?.trim() || null, colindancias: form.colindancias || [], expected_version: record?.version }), [form, record?.version]);

  const save = async () => {
    setSaving(true); setMessage('');
    try {
      const saved = isNew ? await propertiesService.create(payload) : await propertiesService.update(id!, payload);
      setRecord(saved); setForm(toForm(saved));
      if (isNew && creationContext) navigate(creationContext.returnPath, { replace: true, state: { prd001NewPredioId: saved.id } });
      else if (isNew) navigate(`/predios/${saved.id}`, { replace: true });
      else setMessage('Ficha maestra guardada.');
    } catch (error) { setMessage(error instanceof Error ? error.message : 'No fue posible guardar la ficha.'); }
    finally { setSaving(false); }
  };
  const upload = async () => { if (!record || !documentFile) return; setUploading(true); setMessage(''); try { const updated = await propertiesService.uploadDocument(record.id, documentFile, documentType); setRecord(updated); setForm(toForm(updated)); setDocumentFile(null); setMessage('Documento vinculado al inmueble.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'No fue posible cargar el documento.'); } finally { setUploading(false); } };
  const viewDocument = async (documentId: string) => { if (!record) return; try { const { url } = await propertiesService.documentUrl(record.id, documentId); window.open(url, '_blank', 'noopener,noreferrer'); } catch { setMessage('No fue posible abrir el documento.'); } };
  const analyze = async () => { if (!record || !sourceDocumentId) return; setAnalyzing(true); setMessage(''); try { const result = await propertiesService.propose(record.id, sourceDocumentId); setReview(result); setDecisions(Object.fromEntries(result.propuestas.map((item) => [item.campo, 'KEEP']))); } catch (error) { setMessage(error instanceof Error ? error.message : 'No fue posible analizar el documento.'); } finally { setAnalyzing(false); } };
  const applyReview = async () => { if (!record || !review) return; setSaving(true); try { const updated = await propertiesService.applyProposal(record.id, review.extraccion_id, record.version, decisions); setRecord(updated); setForm(toForm(updated)); setReview(null); setMessage('Decisiones aplicadas con trazabilidad.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'La propuesta cambió o no pudo aplicarse.'); } finally { setSaving(false); } };

  if (status === 'loading') return <div className={styles.state}><LoaderCircle className={styles.spin} />Preparando ficha maestra…</div>;
  if (status === 'error') return <section className={styles.state} role="alert"><h1>No pudimos abrir este inmueble.</h1><Link to={returnPath}>Volver</Link></section>;
  return <div className={styles.page}>
    <Link className={styles.back} to={returnPath}><ArrowLeft size={17} />{creationContext ? 'Volver al expediente' : 'Volver'}</Link>
    <header className={styles.header}><div><span className={styles.eyebrow}><Building2 size={16} />Ficha maestra reutilizable</span><h1>{isNew ? 'Nuevo predio / inmueble' : form.apodo || 'Predio / inmueble'}</h1><p>La identidad vive una sola vez en la organización. Los expedientes, actos e ISR sólo consumen relaciones o copias operativas.</p></div>{canWrite && <button type="button" className={styles.primary} disabled={saving} onClick={() => void save()}><Save size={17} />{saving ? 'Guardando…' : 'Guardar ficha'}</button>}</header>
    {message && <div className={styles.notice} role="status">{message}</div>}
    <section className={styles.card}><div className={styles.sectionTitle}><div><h2>Datos generales</h2><p>Identificación práctica y ubicación sin geocodificación obligatoria.</p></div></div><div className={styles.grid}>
      <label><span>Apodo / nombre corto</span><input ref={firstField} value={String(form.apodo || '')} onChange={(event) => update('apodo', event.target.value)} placeholder="Ej. Casa Bucerías" /></label>
      <label className={styles.wide}><span>Ubicación descriptiva</span><input value={String(form.ubicacion_texto || '')} onChange={(event) => update('ubicacion_texto', event.target.value)} /></label>
      <label className={styles.wide}><span>Calle</span><input value={String(form.calle || '')} onChange={(event) => update('calle', event.target.value)} /></label><label><span>Número exterior</span><input value={String(form.numero_exterior || '')} onChange={(event) => update('numero_exterior', event.target.value)} /></label><label><span>Número interior</span><input value={String(form.numero_interior || '')} onChange={(event) => update('numero_interior', event.target.value)} /></label>
      <label><span>Colonia</span><input value={String(form.colonia || '')} onChange={(event) => update('colonia', event.target.value)} /></label><label><span>Localidad</span><input value={String(form.localidad || '')} onChange={(event) => update('localidad', event.target.value)} /></label><label><span>Municipio</span><input value={String(form.municipio || '')} onChange={(event) => update('municipio', event.target.value)} /></label><label><span>Estado</span><input value={String(form.estado || '')} onChange={(event) => update('estado', event.target.value)} /></label><label><span>Código postal</span><input inputMode="numeric" value={String(form.codigo_postal || '')} onChange={(event) => update('codigo_postal', event.target.value)} /></label><label><span>País</span><input value={String(form.pais || '')} onChange={(event) => update('pais', event.target.value)} /></label>
    </div></section>
    <section className={styles.card}><div className={styles.sectionTitle}><div><h2>Registro y catastro</h2><p>Clave catastral, cuenta predial y folio real se conservan como conceptos distintos.</p></div></div><div className={styles.grid}><label><span>Clave catastral</span><input value={String(form.clave_catastral || '')} onChange={(event) => update('clave_catastral', event.target.value)} /></label><label><span>Cuenta predial</span><input value={String(form.cuenta_predial || '')} onChange={(event) => update('cuenta_predial', event.target.value)} /></label><label><span>Folio real</span><input value={String(form.folio_real || '')} onChange={(event) => update('folio_real', event.target.value)} /></label><label><span>Régimen</span><input value={String(form.regimen || '')} onChange={(event) => update('regimen', event.target.value)} /></label><label className={styles.full}><span>Datos registrales flexibles</span><textarea rows={3} value={String(form.datos_registrales_texto || '')} onChange={(event) => update('datos_registrales_texto', event.target.value)} placeholder="Libro, tomo, partida, sección u otra referencia aplicable" /></label><label className={styles.full}><span>Descripción</span><textarea rows={3} value={String(form.descripcion || '')} onChange={(event) => update('descripcion', event.target.value)} /></label></div></section>
    <section className={styles.card}><div className={styles.sectionTitle}><div><h2>Superficies y valores</h2><p>Importes y superficies separados; esta ficha no ejecuta cálculos ISR.</p></div></div><div className={styles.grid}>
      <label><span>Terreno (m²)</span><input type="number" min="0" step="0.0001" value={String(form.superficie_terreno_m2 || '')} onChange={(event) => update('superficie_terreno_m2', event.target.value)} /></label><label><span>Construcción (m²)</span><input type="number" min="0" step="0.0001" value={String(form.superficie_construccion_m2 || '')} onChange={(event) => update('superficie_construccion_m2', event.target.value)} /></label><label><span>Componente comercial (m²)</span><input type="number" min="0" step="0.0001" value={String(form.superficie_construccion_comercial_m2 || '')} onChange={(event) => update('superficie_construccion_comercial_m2', event.target.value)} /></label>
      <label><span>Valor fiscal / catastral</span><input type="number" min="0" step="0.01" value={String(form.valor_catastral || '')} onChange={(event) => update('valor_catastral', event.target.value)} /></label><label><span>Avalúo</span><input type="number" min="0" step="0.01" value={String(form.valor_avaluo || '')} onChange={(event) => update('valor_avaluo', event.target.value)} /></label><label><span>Valor de operación</span><input type="number" min="0" step="0.01" value={String(form.valor_operacion || '')} onChange={(event) => update('valor_operacion', event.target.value)} /></label>
    </div><div className={styles.snapshotNote}><strong>Separación ISR</strong><span>Un cálculo posterior recibirá una copia operativa. Editar o eliminar ese cálculo nunca modifica ni elimina este maestro.</span></div></section>
    <section className={styles.card}><div className={styles.sectionTitle}><div><h2>Medidas y colindancias</h2><p>Agrega tantos segmentos como requiera el inmueble; la referencia no está limitada a puntos cardinales.</p></div><button type="button" className={styles.secondary} onClick={addBoundary}><Plus size={16} />Agregar colindancia</button></div><div className={styles.boundaries}>{(form.colindancias || []).map((item, index) => <fieldset key={item.id || index} className={styles.boundary}><legend>Segmento {index + 1}</legend><div className={styles.boundaryTools}><GripVertical aria-hidden="true" /><button type="button" aria-label={`Mover segmento ${index + 1} arriba`} onClick={() => moveBoundary(index, -1)}>↑</button><button type="button" aria-label={`Mover segmento ${index + 1} abajo`} onClick={() => moveBoundary(index, 1)}>↓</button><button type="button" aria-label={`Eliminar segmento ${index + 1}`} onClick={() => removeBoundary(index)}><Trash2 size={16} /></button></div><label><span>Orientación / referencia</span><input value={String(item.referencia || '')} onChange={(event) => updateBoundary(index, 'referencia', event.target.value)} placeholder="Ej. Del vértice 1 al 2" /></label><label><span>Medida</span><input type="number" min="0" step="0.0001" value={String(item.medida || '')} onChange={(event) => updateBoundary(index, 'medida', event.target.value)} /></label><label><span>Unidad</span><input value={String(item.unidad || '')} onChange={(event) => updateBoundary(index, 'unidad', event.target.value)} /></label><label><span>Colindante</span><input value={String(item.colindante || '')} onChange={(event) => updateBoundary(index, 'colindante', event.target.value)} placeholder="Ej. Lote 4" /></label><label className={styles.full}><span>Descripción</span><textarea rows={2} value={String(item.descripcion || '')} onChange={(event) => updateBoundary(index, 'descripcion', event.target.value)} /></label></fieldset>)}{!(form.colindancias || []).length && <p className={styles.empty}>Sin colindancias registradas. No se inventan cuatro lados por defecto.</p>}</div></section>
    {!isNew && record && <section className={styles.card}><div className={styles.sectionTitle}><div><h2>Documentos</h2><p>Archivos privados vinculados al maestro documental canónico.</p></div></div><div className={styles.documents}>{record.documentos.map((link) => <article key={link.id}><div><strong>{link.documento.nombre_original}</strong><span>{link.tipo_vinculo}</span></div><button type="button" className={styles.icon} aria-label={`Abrir ${link.documento.nombre_original}`} onClick={() => void viewDocument(link.documento_id)}><ExternalLink size={17} /></button></article>)}{!record.documentos.length && <p className={styles.empty}>No hay documentos vinculados.</p>}</div>{canWrite && <div className={styles.upload}><label><span>Tipo de documento</span><input value={documentType} onChange={(event) => setDocumentType(event.target.value)} /></label><label><span>Archivo</span><input type="file" accept=".pdf,.png,.jpg,.jpeg,.docx" onChange={(event) => setDocumentFile(event.target.files?.[0] || null)} /></label><button type="button" className={styles.secondary} disabled={!documentFile || uploading} onClick={() => void upload()}><FilePlus2 size={16} />{uploading ? 'Cargando…' : 'Vincular documento'}</button></div>}<div className={styles.aiBox}><div><Bot size={20} /><div><strong>Extracción asistida</strong><span>Selecciona explícitamente una sola fuente. El análisis produce una propuesta y no cambia la ficha.</span></div></div><div className={styles.aiActions}><label><span>Documento fuente</span><select aria-label="Documento fuente para extracción" value={sourceDocumentId} onChange={(event) => setSourceDocumentId(event.target.value)}><option value="">Seleccionar documento…</option>{record.documentos.map((link) => <option key={link.id} value={link.documento_id}>{link.documento.nombre_original}</option>)}</select></label><button type="button" className={styles.secondary} disabled={!sourceDocumentId || analyzing} onClick={() => void analyze()}>{analyzing ? 'Analizando…' : 'Analizar documento seleccionado'}</button></div></div></section>}
    {review && <div className={styles.backdrop}><section className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby="property-ai-title"><header><div><h2 id="property-ai-title">Propuesta desde {review.documento.nombre}</h2><p>Compara cada dato. Conservar nunca sobrescribe el valor actual.</p></div><button type="button" className={styles.icon} aria-label="Cerrar propuesta" onClick={() => setReview(null)}><X /></button></header><div className={styles.proposalList}>{review.propuestas.map((proposal) => <article key={proposal.campo}><div className={styles.proposalHeader}><strong>{fieldLabels[proposal.campo] || proposal.campo}</strong><span>{proposal.confianza?.replaceAll('_', ' ').toLowerCase()}</span></div><div className={styles.compare}><div><small>Actual</small><p>{displayValue(proposal.valor_actual)}</p></div><div><small>Propuesto</small><p>{displayValue(proposal.valor_propuesto)}</p></div></div>{proposal.fragmento_fuente && <blockquote>{proposal.fragmento_fuente}</blockquote>}<fieldset><legend>Decisión</legend><label><input type="radio" name={`decision-${proposal.campo}`} checked={decisions[proposal.campo] === 'KEEP'} onChange={() => setDecisions((current) => ({ ...current, [proposal.campo]: 'KEEP' }))} />Conservar actual</label><label><input type="radio" name={`decision-${proposal.campo}`} checked={decisions[proposal.campo] === 'ACCEPT'} onChange={() => setDecisions((current) => ({ ...current, [proposal.campo]: 'ACCEPT' }))} />Aceptar propuesto</label></fieldset></article>)}</div><footer><button type="button" className={styles.secondary} onClick={() => setReview(null)}>Cancelar</button><button type="button" className={styles.primary} disabled={saving} onClick={() => void applyReview()}>Aplicar decisiones</button></footer></section></div>}
  </div>;
}
