import { randomUUID } from 'node:crypto';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { PrismaClient } from '@prisma/client';
import { BeneficialControllerService } from '../services/beneficialController.service';
import { ComplianceBcScreeningAdapter } from '../services/complianceBcScreening.service';
import { comparecienteObjectWhere } from '../services/objectAccess.service';
import { bcGraphFingerprint, bcResultExecutions } from '../domain/beneficialController';

function isolatedDatabaseUrl() {
  if (process.env.NODE_ENV !== 'test' || process.env.H4_PG_TEST_CONFIRMATION !== 'RUN_ISOLATED_H4_POSTGRESQL') throw new Error('H4 isolated PostgreSQL confirmation is required.');
  const direct = new URL(process.env.H4_TEST_DIRECT_URL || '');
  if (process.env.DATABASE_URL !== process.env.DIRECT_URL || process.env.DIRECT_URL !== direct.toString()) throw new Error('DATABASE_URL and DIRECT_URL must equal the explicit H4 target.');
  if (!['127.0.0.1', 'localhost', '[::1]'].includes(direct.hostname) || !direct.pathname.slice(1).startsWith('pravia_h4_')) throw new Error('H4 tests accept only an explicit localhost pravia_h4_* database.');
  console.info({host:direct.hostname,port:direct.port,database:direct.pathname.slice(1)});
  direct.searchParams.set('schema', 'pravia_os'); return direct.toString();
}

const id=()=>randomUUID();
const ids={org:id(),otherOrg:id(),user:id(),otherUser:id(),membership:id(),otherMembership:id(),pmParty:id(),pfParty:id(),otherParty:id(),pm:id(),otherPm:id(),exp:id(),review:id(),structure:id(),root:id(),owner:id(),edge:id(),snapshot:id(),evaluation:id(),legacy:id(),doc:id(),society:id()};
const prisma=new PrismaClient({datasources:{db:{url:isolatedDatabaseUrl()}}});
const execute=(sql:string)=>prisma.$executeRawUnsafe(sql);
const fp='a'.repeat(64), checksum='b'.repeat(64);

describe('H4 PostgreSQL physical invariants',()=>{
  beforeAll(async()=>{
    const statements=[
      `INSERT INTO pravia_os.organizations (id,name,status,created_at,updated_at) VALUES ('${ids.org}','H4 synthetic','ACTIVE',now(),now()),('${ids.otherOrg}','H4 other','ACTIVE',now(),now())`,
      `INSERT INTO pravia_os.users (id,email,password_hash,nombre,apellido,rol,activo,created_at,updated_at,requires_password_change) VALUES ('${ids.user}','${ids.user}@example.invalid','x','H4','User','ADMINISTRACION',true,now(),now(),false),('${ids.otherUser}','${ids.otherUser}@example.invalid','x','H4','Other','ADMINISTRACION',true,now(),now(),false)`,
      `INSERT INTO pravia_os.organization_memberships (id,organization_id,user_id,rol,status,created_at,updated_at) VALUES ('${ids.membership}','${ids.org}','${ids.user}','ADMINISTRACION','ACTIVE',now(),now()),('${ids.otherMembership}','${ids.otherOrg}','${ids.otherUser}','ADMINISTRACION','ACTIVE',now(),now())`,
      `INSERT INTO pravia_os.comparecientes (id,organization_id,tipo_persona,nombre_busqueda,estatus,creado_por_id,created_at,updated_at,version) VALUES ('${ids.pmParty}','${ids.org}','MORAL','H4 PM','ACTIVO','${ids.user}',now(),now(),1),('${ids.pfParty}','${ids.org}','FISICA','H4 PF','ACTIVO','${ids.user}',now(),now(),1),('${ids.otherParty}','${ids.otherOrg}','MORAL','H4 OTHER PM','ACTIVO','${ids.otherUser}',now(),now(),1)`,
      `INSERT INTO pravia_os.personas_morales (id,organization_id,compareciente_id,razon_social,estatus_societario,created_at,updated_at) VALUES ('${ids.pm}','${ids.org}','${ids.pmParty}','H4 PM','EN_CONSTITUCION',now(),now()),('${ids.otherPm}','${ids.otherOrg}','${ids.otherParty}','H4 OTHER PM','ACTIVA',now(),now())`,
      `INSERT INTO pravia_os.expedientes (id,organization_id,numero_pravia,abogado_id,creador_id,fecha_apertura,estatus,avance_documental,avance_financiero,avance_general,avance_operativo,created_at,updated_at,version) VALUES ('${ids.exp}','${ids.org}','EXP-H4-${ids.exp.slice(0,8)}','${ids.user}','${ids.user}',now(),'ABIERTO',0,0,0,0,now(),now(),1)`,
      `INSERT INTO pravia_os.compliance_reviews (id,organization_id,expediente_id,tipo,estatus,rule_version_snapshot,cuestionario_json,rule_snapshot,master_snapshot,snapshot_captured_at,creado_por_id,created_at,updated_at,engine_version,idempotency_key,is_canonical_legal_engine) VALUES ('${ids.review}','${ids.org}','${ids.exp}','LEGAL_H1','EVALUACION_DETERMINISTA','synthetic','{}','{}','{}',now(),'${ids.user}',now(),now(),'h4-test','${ids.review}',true)`,
      `INSERT INTO pravia_os.persona_moral_ownership_structures (id,organization_id,persona_moral_id,root_node_id,revision,fingerprint,incomplete_markers,created_by_id,updated_by_id) VALUES ('${ids.structure}','${ids.org}','${ids.pm}','${ids.root}',1,'${fp}','[]','${ids.user}','${ids.user}')`,
      `INSERT INTO pravia_os.persona_moral_ownership_nodes (id,organization_id,structure_id,party_kind,identity_mode,linked_compareciente_id,incomplete,metadata) VALUES ('${ids.root}','${ids.org}','${ids.structure}','PM','LINKED','${ids.pmParty}',false,'{"root":true}'),('${ids.owner}','${ids.org}','${ids.structure}','PF','LINKED','${ids.pfParty}',false,'{}')`,
      `INSERT INTO pravia_os.persona_moral_ownership_edges (id,organization_id,structure_id,owner_node_id,owned_node_id,percentage) VALUES ('${ids.edge}','${ids.org}','${ids.structure}','${ids.owner}','${ids.root}',40)`,
      `INSERT INTO pravia_os.documentos (id,organization_id,nombre_original,nombre_interno,tipo,categoria,storage_key,mime_type,size_bytes,checksum_sha256,fecha_carga,estatus,subido_por_id) VALUES ('${ids.doc}','${ids.org}','evidence.pdf','${ids.doc}-evidence.pdf','H4_EVIDENCE','OTROS','synthetic/${ids.doc}.pdf','application/pdf',10,'${checksum}',now(),'VIGENTE','${ids.user}')`,
      `INSERT INTO pravia_os.compliance_beneficial_owners (id,organization_id,review_id,status,snapshot,created_at) VALUES ('${ids.legacy}','${ids.org}','${ids.review}','PENDIENTE_DE_CONFIRMAR','{}',now())`,
    ];
    await prisma.$transaction(async tx => {
      for (const statement of statements) await tx.$executeRawUnsafe(statement);
    });
  });
  afterAll(async()=>{await prisma.$disconnect()});

  it('blocks a valid linked compareciente from another tenant',async()=>{await expect(execute(`INSERT INTO pravia_os.persona_moral_ownership_nodes (organization_id,structure_id,party_kind,identity_mode,linked_compareciente_id,incomplete,metadata) VALUES ('${ids.org}','${ids.structure}','PM','LINKED','${ids.otherParty}',false,'{}')`)).rejects.toThrow()});
  it('blocks linked PF/PM type mismatch',async()=>{await expect(execute(`INSERT INTO pravia_os.persona_moral_ownership_nodes (organization_id,structure_id,party_kind,identity_mode,linked_compareciente_id,incomplete,metadata) VALUES ('${ids.org}','${ids.structure}','PM','LINKED','${ids.pfParty}',false,'{}')`)).rejects.toThrow(/H4_LINKED_NODE_KIND_MISMATCH/)});
  it('blocks XOR and self ownership while allowing unknown percentages and cycles',async()=>{await expect(execute(`INSERT INTO pravia_os.persona_moral_ownership_nodes (organization_id,structure_id,party_kind,identity_mode,display_name,linked_compareciente_id,incomplete,metadata) VALUES ('${ids.org}','${ids.structure}','PF','STRUCTURED_ONLY','Bad','${ids.pfParty}',false,'{}')`)).rejects.toThrow();await expect(execute(`INSERT INTO pravia_os.persona_moral_ownership_edges (organization_id,structure_id,owner_node_id,owned_node_id,percentage) VALUES ('${ids.org}','${ids.structure}','${ids.root}','${ids.root}',20)`)).rejects.toThrow();await execute(`INSERT INTO pravia_os.persona_moral_ownership_edges (organization_id,structure_id,owner_node_id,owned_node_id,percentage) VALUES ('${ids.org}','${ids.structure}','${ids.root}','${ids.owner}',NULL)`)});
  it('freezes an exact case/review/tenant snapshot',async()=>{const graph=JSON.stringify({root_node_id:ids.root,nodes:[{id:ids.root,identity_mode:'LINKED',linked_compareciente_id:ids.pmParty},{id:ids.owner,identity_mode:'LINKED',linked_compareciente_id:ids.pfParty}],edges:[],controls:[],incomplete_markers:[]}).replaceAll("'","''");await execute(`INSERT INTO pravia_os.compliance_bc_structure_snapshots (id,organization_id,review_id,expediente_id,target_persona_moral_id,structure_id,structure_revision,structure_fingerprint,graph_snapshot,incomplete_markers,captured_by_id) VALUES ('${ids.snapshot}','${ids.org}','${ids.review}','${ids.exp}','${ids.pm}','${ids.structure}',1,'${fp}','${graph}','[]','${ids.user}')`);await expect(execute(`UPDATE pravia_os.compliance_bc_structure_snapshots SET structure_revision=2 WHERE id='${ids.snapshot}'`)).rejects.toThrow(/H4_IMMUTABLE_RECORD/)});
  it('blocks a snapshot whose review does not match its tenant/case',async()=>{const graph=JSON.stringify({root_node_id:ids.root,nodes:[],edges:[],controls:[],incomplete_markers:[]}).replaceAll("'","''");await expect(execute(`INSERT INTO pravia_os.compliance_bc_structure_snapshots (organization_id,review_id,expediente_id,target_persona_moral_id,structure_id,structure_revision,structure_fingerprint,graph_snapshot,incomplete_markers,captured_by_id) VALUES ('${ids.otherOrg}','${ids.review}','${ids.exp}','${ids.otherPm}','${ids.structure}',1,'${fp}','${graph}','[]','${ids.otherUser}')`)).rejects.toThrow()});
  it('records NOT_CONFIGURED separately and physically forbids a false result',async()=>{await execute(`INSERT INTO pravia_os.compliance_bc_evaluations (id,organization_id,review_id,expediente_id,target_persona_moral_id,snapshot_id,regime,status,logical_hash,engine_version,input_snapshot,result_snapshot,created_by_id) VALUES ('${ids.evaluation}','${ids.org}','${ids.review}','${ids.exp}','${ids.pm}','${ids.snapshot}','LFPIORPI','NOT_CONFIGURED','${checksum}','H4-TEST','{}','{"subject_executions":[]}','${ids.user}')`);await expect(execute(`INSERT INTO pravia_os.compliance_bc_results (organization_id,evaluation_id,subject_compareciente_id,determination,facts_snapshot,result_snapshot) VALUES ('${ids.org}','${ids.evaluation}','${ids.pfParty}','BENEFICIAL_CONTROLLER','[]','{}')`)).rejects.toThrow(/H4_RESULT_REQUIRES_VERIFIED_EVALUATION/)});
  it('keeps evaluation history immutable',async()=>{await expect(execute(`DELETE FROM pravia_os.compliance_bc_evaluations WHERE id='${ids.evaluation}'`)).rejects.toThrow(/H4_IMMUTABLE_RECORD/)});
  it('keeps legacy beneficiary rows physically separate with zero H4 promotion',async()=>{const rows:any[]=await prisma.$queryRawUnsafe(`SELECT (SELECT count(*)::int FROM pravia_os.compliance_beneficial_owners WHERE id='${ids.legacy}') legacy,(SELECT count(*)::int FROM pravia_os.compliance_bc_results WHERE organization_id='${ids.org}') h4`);expect(rows[0]).toEqual({legacy:1,h4:0})});
  it('enforces one current structure per tenant/person',async()=>{await expect(execute(`INSERT INTO pravia_os.persona_moral_ownership_structures (organization_id,persona_moral_id,root_node_id,revision,fingerprint,incomplete_markers,created_by_id,updated_by_id) VALUES ('${ids.org}','${ids.pm}','${ids.root}',1,'${checksum}','[]','${ids.user}','${ids.user}')`)).rejects.toThrow()});
  it('allows explicit society linkage without automatically changing the persona moral',async()=>{await execute(`INSERT INTO pravia_os.expediente_society_targets (id,organization_id,expediente_id,persona_moral_id,target_intent_key,created_by_id) VALUES ('${ids.society}','${ids.org}','${ids.exp}','${ids.pm}','h4:${ids.exp}:${ids.pm}','${ids.user}')`);const rows:any[]=await prisma.$queryRawUnsafe(`SELECT estatus_societario FROM pravia_os.personas_morales WHERE id='${ids.pm}'`);expect(rows[0].estatus_societario).toBe('EN_CONSTITUCION')});
});

const actor:any={id:ids.user,organizationId:ids.org,rol:'ADMINISTRACION',permissions:['comparecientes.read','comparecientes.write','compliance.read','compliance.write','documentos.read']};
let actId:string;const revisions:any[]=[];
async function materializationInput(multiple:boolean){
 const review=await prisma.complianceReview.create({data:{organization_id:ids.org,expediente_id:ids.exp,tipo:'LEGAL_H1',estatus:'EVALUACION_DETERMINISTA',rule_version_snapshot:'SYNTHETIC',cuestionario_json:{},rule_snapshot:{},master_snapshot:{},snapshot_captured_at:new Date(),creado_por_id:ids.user,engine_version:'SYNTHETIC',idempotency_key:id(),is_canonical_legal_engine:true}});
 const current=await prisma.expedienteComplianceState.findFirst({where:{organization_id:ids.org,expediente_id:ids.exp}});
 const state=current?await prisma.expedienteComplianceState.update({where:{id:current.id},data:{current_review_id:review.id}}):await prisma.expedienteComplianceState.create({data:{organization_id:ids.org,expediente_id:ids.exp,current_review_id:review.id,updated_by_id:ids.user}});
 const structure=await prisma.personaMoralOwnershipStructure.findUniqueOrThrow({where:{id:ids.structure}});
 const p2=id(),p3=id();const graph:any={root_node_id:ids.root,nodes:[{id:ids.root,party_kind:'PM',identity_mode:'LINKED',linked_compareciente_id:ids.pmParty},{id:ids.owner,party_kind:'PF',identity_mode:'LINKED',linked_compareciente_id:ids.pfParty,metadata:{positive:true}},...(multiple?[{id:p2,party_kind:'PF',identity_mode:'STRUCTURED_ONLY',display_name:'SYNTHETIC P2',metadata:{positive:true}},{id:p3,party_kind:'PF',identity_mode:'STRUCTURED_ONLY',display_name:'SYNTHETIC NEGATIVE',metadata:{positive:false}}]:[])],edges:[{id:id(),owner_node_id:ids.owner,owned_node_id:ids.root,percentage:multiple?'25':'100'},...(multiple?[{id:id(),owner_node_id:p2,owned_node_id:ids.root,percentage:'35'},{id:id(),owner_node_id:p3,owned_node_id:ids.root,percentage:'40'}]:[])],controls:[],incomplete_markers:[]};
 return {organizationId:ids.org,expedienteId:ids.exp,reviewId:review.id,stateId:state.id,actorUserId:ids.user,actor,plan:{targets:[{personaMoralId:ids.pm,actId,structure,graph,fingerprint:bcGraphFingerprint(graph)}],identity:[]},revisions,legalDate:new Date('2026-01-01'),requestHash:'e'.repeat(64),context:{enabled:true,actos:[{id:actId}]},previousReviewId:null};
}
const materialize=(input:any)=>prisma.$transaction(tx=>BeneficialControllerService.materializeForReviewTx(tx,input),{timeout:30000});
async function reconciliationFixture(){
 const service=new BeneficialControllerService(prisma);
 const createPm=async(name:string)=>{const party=await prisma.compareciente.create({data:{organization_id:ids.org,tipo_persona:'MORAL',nombre_busqueda:name,creado_por_id:ids.user}});const pm=await prisma.personaMoral.create({data:{organization_id:ids.org,compareciente_id:party.id,razon_social:name,estatus_societario:'ACTIVA'}});return {party,pm};};
 const source=await createPm('SYNTHETIC SOURCE'),target=await createPm('SYNTHETIC TARGET');
 const root=id(),branch=id(),localOwner=id(),targetRoot=id(),targetOwner=id();
 const targetGraph:any={root_node_id:targetRoot,nodes:[{id:targetRoot,party_kind:'PM',identity_mode:'LINKED',linked_compareciente_id:target.party.id},{id:targetOwner,party_kind:'PF',identity_mode:'STRUCTURED_ONLY',display_name:'SYNTHETIC CURRENT OWNER'}],edges:[{id:id(),owner_node_id:targetOwner,owned_node_id:targetRoot,percentage:'100'}],controls:[]};
 const sourceGraph:any={root_node_id:root,nodes:[{id:root,party_kind:'PM',identity_mode:'LINKED',linked_compareciente_id:source.party.id},{id:branch,party_kind:'PM',identity_mode:'STRUCTURED_ONLY',display_name:'SYNTHETIC LOCAL BRANCH'},{id:localOwner,party_kind:'PF',identity_mode:'STRUCTURED_ONLY',display_name:'SYNTHETIC PROPOSED OWNER'}],edges:[{id:id(),owner_node_id:branch,owned_node_id:root,percentage:'100'},{id:id(),owner_node_id:localOwner,owned_node_id:branch,percentage:'100'}],controls:[]};
 await service.save(actor,target.party.id,{...targetGraph,expected_revision:0,idempotency_key:id()});
 await service.save(actor,source.party.id,{...sourceGraph,expected_revision:0,idempotency_key:id()});
 const linked={...sourceGraph,nodes:sourceGraph.nodes.map((node:any)=>node.id===branch?{...node,identity_mode:'LINKED',linked_compareciente_id:target.party.id,display_name:null}:node)};
 const links=await service.previewLinks(actor,source.party.id,linked);
 const saved=await service.save(actor,source.party.id,{...linked,expected_revision:1,idempotency_key:id(),identity_confirmations:Object.fromEntries(links.map(link=>[link.node_id,link.confirmation]))});
 const proposal=saved.reconciliations.find(row=>row.status==='PENDING')!;
 expect(proposal).toBeTruthy();return {service,source,target,proposal,targetGraph};
}
let multiInput:any,multiEvaluation:any,multiResults:any[];
describe('H4 targeted real service / PostgreSQL remediation',()=>{
 beforeAll(async()=>{
  const type=await prisma.tipoActo.create({data:{organization_id:ids.org,nombre:'SYNTHETIC H4 TARGETED'}});
  const act=await prisma.expedienteActo.create({data:{organization_id:ids.org,expediente_id:ids.exp,tipo_acto_id:type.id,origen:'ADICIONAL',created_by:ids.user}});actId=act.id;
  for(const purpose of ['APPLICABILITY','DETERMINATION']){
   const rule=await prisma.complianceLegalRule.create({data:{organization_id:ids.org,stable_key:'SYNTHETIC_TARGETED_'+purpose,family:'CUM_MAT_002',name:'SYNTHETIC TEST ONLY',created_by_id:ids.user}});
   const revision=await prisma.complianceLegalRuleRevision.create({data:{organization_id:ids.org,rule_id:rule.id,version:1,status:'ACTIVE',effective_from:new Date('2026-01-01'),conditions:{op:'equals',path:purpose==='APPLICABILITY'?'enabled':'subject.metadata.positive',value:true},outcome:{bc:{regime:'LFPIORPI',purpose},when_true:{applicability:'APLICA_SIN_AVISO',vulnerable_activity:true}},legal_basis:'SYNTHETIC TEST ONLY',source_name:'Synthetic fixture',source_url:'https://example.invalid/test',source_published_at:new Date('2026-01-01'),source_checksum:'f'.repeat(64),verified_by_id:ids.user,verified_at:new Date('2026-01-01'),activated_by_id:ids.user,activated_at:new Date('2026-01-01'),checksum:'c'.repeat(64),created_by_id:ids.user}});
   revisions.push({...revision,stable_key:rule.stable_key,family:rule.family});
  }
 });
 afterAll(async()=>prisma.$disconnect());
 it('F001 persists one positive through the actual materializer, with ordered array facts',async()=>{const input=await materializationInput(false);await materialize(input);const results=await prisma.complianceBcResult.findMany({where:{evaluation:{review_id:input.reviewId}},include:{evaluation:true}});expect(results).toHaveLength(1);expect(Array.isArray(results[0].facts_snapshot)).toBe(true);expect(bcResultExecutions(results[0],results[0].evaluation.result_snapshot)).toHaveLength(1);});
 it('F002 persists P1/P2 positives and P3 negative under one H1 rule/context identity',async()=>{multiInput=await materializationInput(true);await materialize(multiInput);multiEvaluation=await prisma.complianceBcEvaluation.findFirstOrThrow({where:{review_id:multiInput.reviewId,regime:'LFPIORPI'},include:{snapshot:true}});multiResults=await prisma.complianceBcResult.findMany({where:{evaluation_id:multiEvaluation.id}});expect(multiResults).toHaveLength(2);expect(multiEvaluation.result_snapshot.subject_executions).toHaveLength(4);expect(multiEvaluation.result_snapshot.subject_executions.filter((e:any)=>e.truth==='FALSE')).toHaveLength(1);expect(await prisma.complianceRuleResult.count({where:{review_id:multiInput.reviewId}})).toBe(2);expect(multiResults.every(row=>bcResultExecutions(row,multiEvaluation.result_snapshot).length===1)).toBe(true);});
 it('F002 retries without duplicate rule, subject or current evaluation',async()=>{await materialize(multiInput);expect(await prisma.complianceRuleResult.count({where:{review_id:multiInput.reviewId}})).toBe(2);expect(await prisma.complianceBcEvaluation.count({where:{review_id:multiInput.reviewId}})).toBe(2);expect(await prisma.complianceBcResult.count({where:{evaluation_id:multiEvaluation.id}})).toBe(2);});
 it.each([0,1])('F003 physically rejects linked/structured subject swap direction %i',async index=>{const source=multiResults[index],other=multiResults[1-index];const {id:oldId,created_at,...data}=source;await expect(prisma.complianceBcResult.create({data:{...data,id:id(),subject_compareciente_id:other.subject_compareciente_id,subject_snapshot_node_id:other.subject_snapshot_node_id}})).rejects.toThrow(/H4_RESULT_EXECUTION_SUBJECT_MISMATCH/);});
 it('F003 rejects wrong snapshot member and false execution as a result',async()=>{const {id:oldId,created_at,...data}=multiResults[0];await expect(prisma.complianceBcResult.create({data:{...data,id:id(),subject_compareciente_id:null,subject_snapshot_node_id:id()}})).rejects.toThrow(/H4_RESULT_SUBJECT_SNAPSHOT_MISMATCH/);const negative=multiEvaluation.result_snapshot.subject_executions.find((e:any)=>e.truth==='FALSE');await expect(prisma.complianceBcResult.create({data:{...data,id:id(),subject_compareciente_id:null,subject_snapshot_node_id:negative.bc_subject_node_id,result_snapshot:{...data.result_snapshot,execution_ids:[negative.execution_id]}}})).rejects.toThrow(/H4_RESULT_EXECUTION_SUBJECT_MISMATCH/);});
 it('F003 independently blocks wrong-subject H3 dispatch before creating screening requests',async()=>{const structured=multiResults.find(row=>row.subject_snapshot_node_id);const count=await prisma.complianceScreeningResult.count({where:{organization_id:ids.org}});await expect(prisma.$transaction(tx=>ComplianceBcScreeningAdapter.ensureForIdentifiedBcTx(tx,{actor,organizationId:ids.org,expedienteId:ids.exp,reviewId:multiInput.reviewId,expedienteActoId:actId,targetPersonaMoralId:ids.pm,evaluationId:multiEvaluation.id,resultId:structured.id,comparecienteId:ids.pfParty,actorUserId:ids.user}))).rejects.toThrow(/H4_BC_SCREENING_LINEAGE_MISMATCH/);expect(await prisma.complianceScreeningResult.count({where:{organization_id:ids.org}})).toBe(count);});
 it('F003 accepts legitimate linked lineage through real H3 MASTER/snapshot authorities',async()=>{const linked=multiResults.find(row=>row.subject_compareciente_id);const result=await prisma.$transaction(tx=>ComplianceBcScreeningAdapter.ensureForIdentifiedBcTx(tx,{actor,organizationId:ids.org,expedienteId:ids.exp,reviewId:multiInput.reviewId,expedienteActoId:actId,targetPersonaMoralId:ids.pm,evaluationId:multiEvaluation.id,resultId:linked.id,comparecienteId:ids.pfParty,actorUserId:ids.user}),{timeout:30000});expect(result.eligible).toBe(true);expect(await prisma.complianceScreeningResult.count({where:{organization_id:ids.org,compareciente_id:ids.pfParty,query_kind:'MASTER'}})).toBe(1);});
 it('F001-F003 rolls back all partial inserts on a later invalid tenant actor',async()=>{const input=await materializationInput(false);input.actorUserId=ids.otherUser;input.actor={...actor,id:ids.otherUser};await expect(materialize(input)).rejects.toThrow();expect(await prisma.complianceRuleResult.count({where:{review_id:input.reviewId}})).toBe(0);expect(await prisma.complianceBcStructureSnapshot.count({where:{review_id:input.reviewId}})).toBe(0);});
 it('F004 enforces actual same-tenant object authorization on current, expanded and historical reads',async()=>{await prisma.organizationMembership.create({data:{organization_id:ids.org,user_id:ids.otherUser,rol:'ABOGADO',status:'ACTIVE'}});await prisma.compareciente.update({where:{id:ids.pmParty},data:{creado_por_id:ids.otherUser}});await prisma.expediente.update({where:{id:ids.exp},data:{abogado_id:ids.otherUser}});const limited={...actor,id:ids.otherUser,rol:'ABOGADO'};expect(await prisma.compareciente.findFirst({where:{AND:[{id:ids.pfParty,organization_id:ids.org},comparecienteObjectWhere(limited)]}})).toBeNull();await expect(new BeneficialControllerService(prisma).current(limited,ids.pmParty)).rejects.toMatchObject({code:'BC_LINKED_PARTY_NOT_FOUND'});await expect(new BeneficialControllerService(prisma).caseSummary(limited,ids.exp)).rejects.toMatchObject({code:'BC_LINKED_PARTY_NOT_FOUND'});const visible:any=await new BeneficialControllerService(prisma).current(actor,ids.pmParty);expect(visible.nodes.find((n:any)=>n.linked_compareciente_id===ids.pfParty).canonical_label).toBe('H4 PF');await expect(new BeneficialControllerService(prisma).current(actor,ids.otherParty)).rejects.toMatchObject({code:'BC_PERSONA_MORAL_NOT_FOUND'});});
 it('F006 accepts only the reviewed replacement and applies it through canonical authority atomically',async()=>{const {service,source,target,proposal}=await reconciliationFixture();const preview=await service.previewReconciliation(actor,source.party.id,proposal.id);expect(preview.local.nodes.some(node=>node.display_name==='SYNTHETIC PROPOSED OWNER')).toBe(true);expect(preview.current.nodes.some(node=>node.display_name==='SYNTHETIC CURRENT OWNER')).toBe(true);await expect(service.decideReconciliation(actor,source.party.id,proposal.id,{decision:'ACCEPTED',graph:preview.current,review_token:preview.review_token})).rejects.toMatchObject({code:'BC_RECONCILIATION_REVIEW_REQUIRED'});expect((await prisma.personaMoralStructureReconciliation.findUniqueOrThrow({where:{id:proposal.id}})).status).toBe('PENDING');await service.decideReconciliation(actor,source.party.id,proposal.id,{decision:'ACCEPTED',graph:preview.proposed,review_token:preview.review_token});const current:any=await service.current(actor,target.party.id);const owner=current.nodes.find((node:any)=>node.display_name==='SYNTHETIC PROPOSED OWNER');expect(current.edges.some((edge:any)=>edge.owner_node_id===owner.id&&edge.owned_node_id===current.root_node_id)).toBe(true);expect(current.revision).toBe(2);expect((await prisma.personaMoralStructureReconciliation.findUniqueOrThrow({where:{id:proposal.id}})).status).toBe('ACCEPTED');const origin:any=await service.current(actor,source.party.id);expect(origin.nodes.some((node:any)=>node.display_name==='SYNTHETIC PROPOSED OWNER')).toBe(false);expect(origin.expanded.nodes.some((node:any)=>node.display_name==='SYNTHETIC PROPOSED OWNER')).toBe(true);});
 it('F006 rejects without changing the target and keeps canonical PM as sole authority',async()=>{const {service,source,target,proposal}=await reconciliationFixture();const before:any=await service.current(actor,target.party.id);await service.decideReconciliation(actor,source.party.id,proposal.id,{decision:'REJECTED'});const after:any=await service.current(actor,target.party.id);expect(after.fingerprint).toBe(before.fingerprint);expect(after.revision).toBe(before.revision);expect((await prisma.personaMoralStructureReconciliation.findUniqueOrThrow({where:{id:proposal.id}})).status).toBe('REJECTED');});
});
