import { AlertTriangle, Building2, ChevronLeft, ChevronRight, Plus } from 'lucide-react';
import { useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { PageContainer } from '../../components/layout/PageContainer';
import { useAuth } from '../auth/AuthProvider';
import { NewNotariaFlow } from './components/NewNotariaFlow';
import { NotariaDistribution } from './components/NotariaDistribution';
import { NotariaFilters } from './components/NotariaFilters';
import { NotariaMetrics } from './components/NotariaMetrics';
import { NotariaMobileCard } from './components/NotariaMobileCard';
import { NotariaTable } from './components/NotariaTable';
import { useNotarias } from './useNotarias';
import styles from './Notarias.module.css';

const fields=['search','state','city','status','sort'] as const;
export function NotariasPage(){const{user}=useAuth();const[params,setParams]=useSearchParams();const[open,setOpen]=useState(params.get('new')==='1');const[toast,setToast]=useState('');const values=Object.fromEntries(fields.map((field)=>[field,params.get(field)||(field==='sort'?'numero:asc':'')])) as Record<string,string>;const activeCases=params.get('activeCases')==='true';const page=Math.max(1,Number.parseInt(params.get('page')||'1',10)||1);const{result,status,reload}=useNotarias({...values,state:values.state,city:values.city,status:values.status,activeCases,page,pageSize:20});const canWrite=user?.permissions?.includes('notarias.write')||false;const change=(field:string,value:string)=>{const next=new URLSearchParams(params);if(field==='activeCases'){value?next.set(field,'true'):next.delete(field);}else if(value&&!(field==='sort'&&value==='numero:asc'))next.set(field,value);else next.delete(field);if(field!=='page')next.delete('page');next.delete('new');setParams(next,{replace:true});};const clear=()=>setParams(new URLSearchParams(),{replace:true});const metricSelect=(key:string)=>{if(key==='WITH_CASES'){change('activeCases',activeCases?'':'true');return;}const next=params.get('status')===key?'':key;change('status',next);};const hasFilters=Boolean(values.search||values.state||values.city||values.status||activeCases);
return <PageContainer title="Notarías" subtitle="Directorio y operación de notarías vinculadas." action={canWrite&&<button type="button" className={styles.primaryButton} onClick={()=>setOpen(true)}><Plus size={18}/>Nueva notaría</button>}>
{status==='loading'&&<div className={styles.loading} aria-label="Cargando notarías"><div className={styles.loadingTop}><div className={styles.loadingMetrics}>{[1,2,3,4].map((item)=><span key={item}/>)}</div><span className={styles.loadingChart}/></div><span className={styles.loadingFilters}/><span className={styles.loadingTable}/></div>}
{status==='error'&&<section className={styles.pageState} role="alert"><span><AlertTriangle/></span><h2>No pudimos cargar las notarías.</h2><p>El directorio no está disponible en este momento.</p><button type="button" className={styles.secondaryButton} onClick={reload}>Reintentar</button></section>}
{status==='ready'&&result&&<><div className={styles.overview}><NotariaMetrics metrics={result.metrics} active={activeCases?'WITH_CASES':values.status} onSelect={metricSelect}/><NotariaDistribution distribution={result.distribution}/></div><NotariaFilters values={values} facets={result.facets} onChange={change} onClear={clear}/>{!result.data.length&&!hasFilters?<section className={styles.pageState}><span><Building2/></span><h2>No hay notarías registradas.</h2><p>Cuando registres una oficina notarial aparecerá aquí.</p>{canWrite&&<button type="button" className={styles.primaryButton} onClick={()=>setOpen(true)}><Plus size={18}/>Registrar primera notaría</button>}</section>:<section className={styles.listCard} aria-label="Directorio de notarías">{result.data.length?<><NotariaTable items={result.data}/><div className={styles.mobileList}>{result.data.map((item)=><NotariaMobileCard key={item.id} item={item}/>)}</div></>:<div className={styles.filteredEmpty}><strong>No encontramos notarías con estos filtros.</strong><button type="button" onClick={clear}>Limpiar filtros</button></div>}<nav className={styles.pagination} aria-label="Paginación de notarías"><span>Mostrando {result.data.length?(page-1)*result.meta.pageSize+1:0} a {Math.min(page*result.meta.pageSize,result.meta.total)} de {result.meta.total}</span><div><button type="button" aria-label="Página anterior" disabled={!result.meta.hasPreviousPage} onClick={()=>change('page',String(page-1))}><ChevronLeft size={17}/></button><b>{page}</b><button type="button" aria-label="Página siguiente" disabled={!result.meta.hasNextPage} onClick={()=>change('page',String(page+1))}><ChevronRight size={17}/></button></div></nav></section>}</>}
{open&&<NewNotariaFlow onClose={()=>setOpen(false)} onSaved={()=>{setOpen(false);setToast('Notaría guardada correctamente.');void reload();window.setTimeout(()=>setToast(''),2500);}}/>}<div className={`${styles.toast} ${toast?styles.toastVisible:''}`} role="status">{toast}</div></PageContainer>}
