import { ArrowRight, CalendarCheck2, CircleDollarSign, FileCheck2, Scale, Sparkles, UsersRound, WalletCards } from 'lucide-react';
import { Link } from 'react-router-dom';
import styles from './Reports.module.css';
import type { CollectionsReport, EightyTwentyReport, FinanceReport, LawyersReport, PotentialClientsReport, SignaturesReport, SummaryReport } from './reporting.types';

const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0});
const number=new Intl.NumberFormat('es-MX');
const date=(value?:string|null)=>value?new Intl.DateTimeFormat('es-MX',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(value)):'Por definir';
const pct=(value:number)=>`${value.toFixed(1)}%`;
type MetricProps={label:string;value:string;helper?:string;icon?:React.ReactNode;tone?:string;definition?:string;onClick?:()=>void};
export function Metric({label,value,helper,icon,tone='gold',definition,onClick}:MetricProps){const body=<><span className={styles.metricTop}><span className={styles.metricIcon} data-tone={tone}>{icon}</span>{definition&&<span className={styles.info} title={definition} aria-label={`Definición de ${label}`}>i</span>}</span><strong>{value}</strong><span className={styles.metricLabel}>{label}</span>{helper&&<small>{helper}</small>}</>;return onClick?<button type="button" className={`${styles.metric} ${styles.metricButton}`} onClick={onClick}>{body}</button>:<article className={styles.metric}>{body}</article>}
export function Restricted(){return <section className={styles.restricted}><Scale/><h2>Vista financiera restringida</h2><p>Puedes consultar indicadores operativos, pero tu rol no tiene acceso a importes financieros.</p></section>}
export function Empty({title='Sin datos para este periodo',detail='Ajusta los filtros o selecciona otro periodo para consultar información.'}:{title?:string;detail?:string}){return <section className={styles.empty}><FileCheck2/><h3>{title}</h3><p>{detail}</p></section>}

function TrendChart({data=[]}:{data?:Array<{periodo:string;generados:number;cobrados:number}>}){
  if(!data.length)return <Empty/>;const max=Math.max(1,...data.flatMap(x=>[x.generados,x.cobrados]));const points=(key:'generados'|'cobrados')=>data.map((x,i)=>`${22+i*(420/Math.max(1,data.length-1))},${142-(x[key]/max)*112}`).join(' ');
  return <div className={styles.chart} role="img" aria-label="Tendencia mensual de honorarios generados y cobrados"><svg viewBox="0 0 470 175" preserveAspectRatio="none"><title>Tendencia de honorarios generados y cobrados</title>{[30,67,104,142].map(y=><line key={y} x1="20" y1={y} x2="450" y2={y} className={styles.gridLine}/>)}<polyline points={points('generados')} className={styles.generatedLine}/><polyline points={points('cobrados')} className={styles.collectedLine}/>{data.map((x,i)=><g key={x.periodo}><circle cx={22+i*(420/Math.max(1,data.length-1))} cy={142-(x.generados/max)*112} r="4" className={styles.generatedPoint}><title>{`${x.periodo}: ${money.format(x.generados)} generados`}</title></circle><circle cx={22+i*(420/Math.max(1,data.length-1))} cy={142-(x.cobrados/max)*112} r="4" className={styles.collectedPoint}><title>{`${x.periodo}: ${money.format(x.cobrados)} cobrados`}</title></circle><text x={22+i*(420/Math.max(1,data.length-1))} y="166" textAnchor="middle">{x.periodo.slice(5)}</text></g>)}</svg><div className={styles.legend}><span><i data-series="generated"/>Generados</span><span><i data-series="collected"/>Cobrados</span></div></div>
}

export function SummaryView({summary,finance,collections,signatures,errors,onOpen}:{summary:SummaryReport;finance?:FinanceReport;collections?:CollectionsReport;signatures?:SignaturesReport;errors:Set<string>;onOpen:(view:string)=>void}){
 const f=summary.financial;return <div className={styles.reportStack}>
  {errors.size>0&&<div className={styles.partialError} role="status">Algunos indicadores no pudieron actualizarse. El resto del reporte sigue disponible.</div>}
  <section className={styles.metrics} aria-label="Indicadores principales">
   {f&&<><Metric label="Honorarios generados" value={money.format(f.honorarios_generados)} helper="Reconocidos en el periodo" icon={<WalletCards/>} definition="Honorarios canónicos reconocidos, sin movimientos cancelados." onClick={()=>onOpen('finanzas')}/><Metric label="Honorarios cobrados" value={money.format(f.honorarios_cobrados)} helper="Aplicados a honorarios" icon={<CircleDollarSign/>} tone="green" definition="Ingresos aplicados mediante distribución canónica a honorarios." onClick={()=>onOpen('finanzas')}/><Metric label="Por cobrar" value={money.format(f.honorarios_por_cobrar)} helper="Generados menos cobrados" icon={<Scale/>} tone="blue" definition="Honorarios generados menos honorarios cobrados; nunca usa el total bruto recibido." onClick={()=>onOpen('cobranza')}/></>}
   <Metric label="Firmas realizadas" value={number.format(summary.operations.firmas_realizadas)} helper="En el periodo seleccionado" icon={<CalendarCheck2/>} tone="purple" onClick={()=>onOpen('firmas')}/>
  </section>
  <div className={styles.summaryGrid}>
   <section className={styles.panel}><header><div><span className={styles.eyebrow}>Tendencia</span><h2>Generado vs. cobrado</h2></div><button onClick={()=>onOpen('finanzas')}>Ver finanzas <ArrowRight/></button></header>{errors.has('finance')?<WidgetError/>:<TrendChart data={finance?.tendency}/>}</section>
   <section className={styles.panel}><header><div><span className={styles.eyebrow}>Objetivo</span><h2>Meta de honorarios</h2></div></header>{summary.goal?<div className={styles.goal}><div className={styles.goalCircle} style={{'--progress':`${Math.min(summary.goal.cumplimiento,100)*3.6}deg`} as React.CSSProperties}><span><strong>{pct(summary.goal.cumplimiento)}</strong><small>{summary.goal.base==='COBRADOS'?'Cobrados':'Generados'}</small></span></div><div><strong>{money.format(summary.goal.actual)}</strong><p>de {money.format(summary.goal.meta)}</p><small>Faltan {money.format(summary.goal.pendiente)} para la meta.</small></div></div>:<Empty title="Meta no configurada" detail="Los indicadores siguen disponibles; configura una meta histórica para medir avance."/>}</section>
   <section className={styles.panel}><header><div><span className={styles.eyebrow}>Operación</span><h2>Firmas y presupuestos</h2></div><button onClick={()=>onOpen('firmas')}>Ver firmas <ArrowRight/></button></header><div className={styles.miniStats}><div><strong>{summary.operations.firmas_restantes_semana}</strong><span>Firmas restantes esta semana</span><small>{money.format(summary.operations.honorarios_programados_semana)} programados</small></div><div><strong>{summary.operations.presupuestos_aceptados}/{summary.operations.presupuestos_solicitados}</strong><span>Presupuestos aceptados</span><small>{money.format(summary.operations.importe_cotizado)} cotizados</small></div><div><strong>{summary.operations.clientes_generados}</strong><span className={styles.definedLabel}>Clientes generados <i className={styles.info} tabIndex={0} role="note" title={summary.definitions.clientes} aria-label={`Definición de clientes generados: ${summary.definitions.clientes}`}>i</i></span><small>Cotización aceptada</small></div></div></section>
   <section className={styles.panel}><header><div><span className={styles.eyebrow}>Cobranza</span><h2>Cartera pendiente</h2></div><button onClick={()=>onOpen('cobranza')}>Ver cobranza <ArrowRight/></button></header>{errors.has('collections')?<WidgetError/>:collections?.restricted?<Restricted/>:<div className={styles.collectionHighlight}><div><small>Pendiente</small><strong>{money.format(collections?.totals?.pending||0)}</strong></div><div><small>Vencido</small><strong className={styles.danger}>{money.format(collections?.totals?.overdue||0)}</strong></div><div className={styles.progress}><span style={{width:`${collections?.totals?.generated?Math.min(100,(collections.totals.collected/collections.totals.generated)*100):0}%`}}/><small>{collections?.totals?.generated?pct((collections.totals.collected/collections.totals.generated)*100):'0%'} cobrado</small></div></div>}</section>
  </div>
 </div>;
}
function WidgetError(){return <div className={styles.widgetError}>No fue posible actualizar este bloque.</div>}

export function FinanceView({data}:{data:FinanceReport}){if(data.restricted||!data.financial)return <Restricted/>;const f=data.financial;return <div className={styles.reportStack}><section className={styles.metrics}><Metric label="Honorarios generados" value={money.format(f.honorarios_generados)} icon={<WalletCards/>}/><Metric label="Honorarios cobrados" value={money.format(f.honorarios_cobrados)} icon={<CircleDollarSign/>} tone="green"/><Metric label="Por cobrar" value={money.format(f.honorarios_por_cobrar)} icon={<Scale/>} tone="blue"/><Metric label="Ingresos totales recibidos" value={money.format(f.ingresos_recibidos)} icon={<FileCheck2/>} tone="purple"/></section><div className={styles.twoCols}><section className={styles.panel}><header><div><span className={styles.eyebrow}>Últimos seis meses</span><h2>Tendencia financiera</h2></div></header><TrendChart data={data.tendency}/></section><section className={styles.panel}><header><div><span className={styles.eyebrow}>Distribución</span><h2>Destino de recursos</h2></div></header><div className={styles.distribution}><Distribution label="Del despacho" value={f.honorarios_cobrados} total={f.ingresos_recibidos}/><Distribution label="Terceros" value={f.fondos_terceros} total={f.ingresos_recibidos}/><Distribution label="Otros destinos" value={f.otros_destinos} total={f.ingresos_recibidos}/></div></section></div></div>}
function Distribution({label,value,total}:{label:string;value:number;total:number}){const valuePct=total?value/total*100:0;return <div><span><b>{label}</b><strong>{money.format(value)}</strong></span><i><em style={{width:`${Math.min(100,valuePct)}%`}}/></i><small>{pct(valuePct)} del total recibido</small></div>}

export function CollectionsView({data}:{data:CollectionsReport}){if(data.restricted||!data.totals)return <Restricted/>;return <div className={styles.reportStack}><section className={styles.metrics}><Metric label="Cartera reconocida" value={money.format(data.totals.generated)} icon={<WalletCards/>}/><Metric label="Aplicado" value={money.format(data.totals.collected)} icon={<CircleDollarSign/>} tone="green"/><Metric label="Pendiente" value={money.format(data.totals.pending)} icon={<Scale/>} tone="blue"/><Metric label="Vencido" value={money.format(data.totals.overdue)} icon={<FileCheck2/>} tone="red"/></section><div className={styles.collectionGroups}><section className={styles.panel}><header><div><span className={styles.eyebrow}>Responsables</span><h2>Cobranza por abogado</h2></div></header>{data.byLawyer?.length?<GroupTable rows={data.byLawyer} label="Abogado"/>:<Empty/>}</section><section className={styles.panel}><header><div><span className={styles.eyebrow}>Procedencia</span><h2>Cobranza por notaría</h2></div></header>{data.byNotaria?.length?<GroupTable rows={data.byNotaria} label="Notaría"/>:<Empty/>}</section></div><section className={styles.panel}><header><div><span className={styles.eyebrow}>Detalle</span><h2>Honorarios pendientes</h2></div></header>{data.rows?.length?<div className={styles.tableWrap}><table><thead><tr><th>Expediente</th><th>Cliente</th><th>Responsable</th><th>Notaría</th><th>Vencimiento</th><th className={styles.numeric}>Pendiente</th></tr></thead><tbody>{data.rows.map(x=><tr key={x.id}><td data-label="Expediente"><Link to={x.link}>{x.expediente}</Link></td><td data-label="Cliente">{x.cliente}</td><td data-label="Responsable">{x.abogado}</td><td data-label="Notaría">{x.notaria}</td><td data-label="Vencimiento">{date(x.due)}</td><td data-label="Pendiente" className={styles.numeric}>{money.format(x.pending)}</td></tr>)}</tbody></table></div>:<Empty/>}</section></div>}
function GroupTable({rows,label}:{rows:NonNullable<CollectionsReport['byLawyer']>;label:'Abogado'|'Notaría'}){return <div className={styles.tableWrap}><table><thead><tr><th>{label}</th><th>Expedientes</th><th className={styles.numeric}>Generado</th><th className={styles.numeric}>Cobrado</th><th className={styles.numeric}>Pendiente</th><th>Avance</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td data-label={label}><strong>{x.nombre}</strong></td><td data-label="Expedientes">{x.expedientes}</td><td data-label="Generado" className={styles.numeric}>{money.format(x.generated)}</td><td data-label="Cobrado" className={styles.numeric}>{money.format(x.collected)}</td><td data-label="Pendiente" className={styles.numeric}>{money.format(x.pending)}</td><td data-label="Avance"><span className={styles.status}>{pct(x.porcentaje_cobrado)}</span></td></tr>)}</tbody></table></div>}

export function LawyersView({data}:{data:LawyersReport}){return <section className={styles.panel}><header><div><span className={styles.eyebrow}>Desempeño {data.year}</span><h2>Operación por abogado</h2></div></header>{data.rows.length?<div className={styles.tableWrap}><table><thead><tr><th>Abogado</th><th>Expedientes del año</th><th className={styles.numeric}>Honorarios generados</th><th>Firmas próximo mes</th><th className={styles.numeric}>Honorarios próximos</th></tr></thead><tbody>{data.rows.map(x=><tr key={x.id}><td data-label="Abogado"><strong>{x.nombre}</strong></td><td data-label="Expedientes del año">{x.expedientes_ano}</td><td data-label="Honorarios generados" className={styles.numeric}>{money.format(x.honorarios_generados)}</td><td data-label="Firmas próximo mes">{x.firmas_proximo_mes}</td><td data-label="Honorarios próximos" className={styles.numeric}>{money.format(x.honorarios_proximo_mes)}</td></tr>)}</tbody></table></div>:<Empty/>}</section>}

export function SignaturesView({data}:{data:SignaturesReport}){const m=data.metrics;return <div className={styles.reportStack}><section className={styles.metrics}><Metric label="Realizadas este mes" value={number.format(m.realizadas_mes||0)} icon={<CalendarCheck2/>}/><Metric label="Semana actual" value={number.format(m.realizadas_semana_actual||0)} icon={<FileCheck2/>} tone="green"/><Metric label="Pendientes esta semana" value={number.format(m.pendientes_semana_actual||0)} icon={<Scale/>} tone="blue"/><Metric label="Honorarios firmados" value={money.format(m.honorarios_firmados_mes||0)} icon={<CircleDollarSign/>} tone="purple"/></section><div className={styles.notice}><Sparkles/><div><strong>Firmas defectuosas</strong><p>{data.defective.label}. No se muestra una cifra ficticia hasta contar con una definición operativa trazable.</p></div></div><section className={styles.panel}><header><div><span className={styles.eyebrow}>Calendario operativo</span><h2>Detalle de firmas</h2></div></header>{data.rows.length?<div className={styles.tableWrap}><table><thead><tr><th>Expediente</th><th>Cliente</th><th>Abogado</th><th>Firma estimada</th><th>Firma real</th><th className={styles.numeric}>Honorarios</th></tr></thead><tbody>{data.rows.map(x=><tr key={x.id}><td data-label="Expediente"><Link to={x.link}>{x.numero_pravia}</Link></td><td data-label="Cliente">{x.cliente_alias||'Sin cliente'}</td><td data-label="Abogado">{x.abogado}</td><td data-label="Firma estimada">{date(x.fecha_estimada_firma)}</td><td data-label="Firma real">{date(x.fecha_real_firma)}</td><td data-label="Honorarios" className={styles.numeric}>{money.format(x.honorarios)}</td></tr>)}</tbody></table></div>:<Empty/>}</section></div>}

export function EightyTwentyView({data}:{data:EightyTwentyReport}){if(data.restricted)return <Restricted/>;const rows=data.rows||[],totals=rows.reduce((a,x)=>({fees:a.fees+x.honorarios,deposit:a.deposit+x.anticipo,pending:a.pending+x.pending}),{fees:0,deposit:0,pending:0});return <div className={styles.reportStack}><div className={styles.definition}><strong>80/20 operativo</strong><span>{data.definition}</span></div><section className={styles.metrics}><Metric label="Honorarios vinculados" value={money.format(totals.fees)} icon={<WalletCards/>}/><Metric label="Anticipos recibidos" value={money.format(totals.deposit)} icon={<CircleDollarSign/>} tone="green"/><Metric label="Saldo pendiente" value={money.format(totals.pending)} icon={<Scale/>} tone="blue"/><Metric label="Operaciones" value={number.format(rows.length)} icon={<FileCheck2/>} tone="purple"/></section><section className={styles.panel}><header><div><span className={styles.eyebrow}>Seguimiento</span><h2>Expedientes con anticipo</h2></div></header>{rows.length?<div className={styles.tableWrap}><table><thead><tr><th>Expediente</th><th>Cliente</th><th>Abogado</th><th>Fecha de firma</th><th className={styles.numeric}>Honorarios</th><th className={styles.numeric}>Anticipo</th><th className={styles.numeric}>Pendiente</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td data-label="Expediente"><Link to={x.link}>{x.expediente}</Link></td><td data-label="Cliente">{x.cliente}</td><td data-label="Abogado">{x.abogado}</td><td data-label="Fecha de firma">{date(x.fecha_firma)}</td><td data-label="Honorarios" className={styles.numeric}>{money.format(x.honorarios)}</td><td data-label="Anticipo" className={styles.numeric}>{money.format(x.anticipo)}</td><td data-label="Pendiente" className={styles.numeric}>{money.format(x.pending)}</td></tr>)}</tbody></table></div>:<Empty title="Sin anticipos en el periodo"/>}</section></div>}

export function PotentialClientsView({data}:{data:PotentialClientsReport}){const total=data.rows.reduce((s,x)=>s+x.honorarios,0),stale=data.rows.filter(x=>x.dias_sin_anticipo>14).length;return <div className={styles.reportStack}><div className={styles.definition}><strong>Oportunidad de seguimiento</strong><span>{data.definition}</span></div><section className={styles.metrics}><Metric label="Clientes potenciales" value={number.format(data.rows.length)} icon={<UsersRound/>}/><Metric label="Honorarios potenciales" value={money.format(total)} icon={<CircleDollarSign/>} tone="green"/><Metric label="Más de 14 días" value={number.format(stale)} icon={<Scale/>} tone="red"/></section><section className={styles.panel}><header><div><span className={styles.eyebrow}>Conversión</span><h2>Cotizaciones sin anticipo</h2></div></header>{data.rows.length?<div className={styles.tableWrap}><table><thead><tr><th>Cliente</th><th>Acto</th><th>Responsable</th><th>Notaría</th><th>Fecha cotización</th><th>Días sin anticipo</th><th className={styles.numeric}>Honorarios</th></tr></thead><tbody>{data.rows.map(x=><tr key={x.id}><td data-label="Cliente"><Link to={x.link}>{x.cliente}</Link></td><td data-label="Acto">{x.acto}</td><td data-label="Responsable">{x.responsable}</td><td data-label="Notaría">{x.notaria}</td><td data-label="Fecha cotización">{date(x.fecha_cotizacion)}</td><td data-label="Días sin anticipo"><span className={x.dias_sin_anticipo>14?styles.risk:styles.status}>{x.dias_sin_anticipo} días</span></td><td data-label="Honorarios" className={styles.numeric}>{money.format(x.honorarios)}</td></tr>)}</tbody></table></div>:<Empty title="No hay cotizaciones pendientes de anticipo" detail="Todas las cotizaciones vigentes cuentan con anticipo aplicado."/>}</section></div>}
