import { X } from 'lucide-react';
import { useState } from 'react';
import styles from './Reports.module.css';
import { reportingService } from './reporting.service';
import type { ReportingCatalogs } from './reporting.types';

const local=(date:Date)=>new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,10);
export function TargetDialog({catalogs,onClose,onSaved}:{catalogs:ReportingCatalogs;onClose:()=>void;onSaved:()=>void}){
 const now=new Date();const [draft,setDraft]=useState({alcance:'DESPACHO',usuario_id:'',periodo_inicio:local(new Date(now.getFullYear(),now.getMonth(),1)),periodo_fin:local(new Date(now.getFullYear(),now.getMonth()+1,0)),importe:'',base:'GENERADOS'}),[error,setError]=useState(''),[saving,setSaving]=useState(false);const change=(key:string,value:string)=>setDraft(x=>({...x,[key]:value}));
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{await reportingService.createTarget(draft);onSaved();}catch(ex){setError(ex instanceof Error?ex.message:'No fue posible configurar la meta.');}finally{setSaving(false);}};
 return <div className={styles.dialogBackdrop} role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section role="dialog" aria-modal="true" aria-labelledby="target-title" className={styles.dialog}><header><div><span className={styles.eyebrow}>Objetivo histórico</span><h2 id="target-title">Configurar meta de honorarios</h2></div><button type="button" aria-label="Cerrar" onClick={onClose}><X/></button></header><form onSubmit={submit}><label><span>Alcance</span><select value={draft.alcance} onChange={e=>change('alcance',e.target.value)}><option value="DESPACHO">Despacho</option><option value="ABOGADO">Abogado</option></select></label>{draft.alcance==='ABOGADO'&&<label><span>Abogado</span><select required value={draft.usuario_id} onChange={e=>change('usuario_id',e.target.value)}><option value="">Selecciona</option>{catalogs.usuarios.map(x=><option key={x.id} value={x.id}>{x.nombre} {x.apellido}</option>)}</select></label>}<div className={styles.formPair}><label><span>Inicio</span><input required type="date" value={draft.periodo_inicio} onChange={e=>change('periodo_inicio',e.target.value)}/></label><label><span>Fin</span><input required type="date" value={draft.periodo_fin} onChange={e=>change('periodo_fin',e.target.value)}/></label></div><label><span>Importe objetivo (MXN)</span><input required type="number" min="0.01" step="0.01" value={draft.importe} onChange={e=>change('importe',e.target.value)}/></label><label><span>Base de cumplimiento</span><select value={draft.base} onChange={e=>change('base',e.target.value)}><option value="GENERADOS">Honorarios generados</option><option value="COBRADOS">Honorarios cobrados</option></select></label><p className={styles.formHint}>La base queda guardada en la historia y no se infiere después.</p>{error&&<p className={styles.formError} role="alert">{error}</p>}<footer><button type="button" onClick={onClose}>Cancelar</button><button type="submit" disabled={saving}>{saving?'Guardando…':'Guardar meta'}</button></footer></form></section></div>;
}
